mrbgems/mruby-bin-debugger/tools/mrdb/apibreak.c, mrbgems/mruby-bin-debugger/tools/mrdb/apilist.c, mrbgems/mruby-bin-debugger/tools/mrdb/cmdmisc.c
`mrb_malloc()` causes an exception when memory was empty.
=> Remove redundant NULL checks for mrb_malloc().

Rakefile
When cross-compiling a custom gem containing a binary I ran into a bug: the resulting executable
was placed into the host's output directory, rather than the one for the cross-build target. This bug does not appear for gems that come with mruby itself but only for gems outside `MRUBY_ROOT`, in which case `relative_from_root`  will give a double period path ('../') that points to the wrong directory.
I don't know if this is a decent fix, but it seems to work.
=> Set correct build dir for bins

test/assert.rb
Currently the test report looks like this:
```
Total: 835
OK: 835
KO: 0
Crash: 0
Time: 0.07538899999999 seconds
```
This change rounds just the test time to a more readable point:
```
Total: 835
OK: 835
KO: 0
Crash: 0
Time: 0.08 seconds
```
=> Round execution time

mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c
When [`mrb_open()` is called again](https://github.com/cubicdaiya/mruby/blob/error-handling-mrb-open/mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c#L710), it is not checked.
=> fixed error-handling for mrb_open().

minirake
Currently, directory tasks are not working, which is annoying if you need them. This is a basic and simple functional implementation, albeit with limitations (directory tasks have zero timestamps)
=> Properly implement directory tasks

mrbgems/mruby-struct/mrblib/struct.rb, mrbgems/mruby-struct/src/struct.c
Before:
```
$ ./bin/mirb 
> foo = Struct.new("Foo",:a,:b).new(1,2)
=> #<struct Struct::Foo a=1, b=2>
> foo.b = foo
Segmentation fault: 11
```
After:
```
$ ./bin/mirb
> foo = Struct.new("Foo",:a,:b).new(1,2)
=> #<struct Struct::Foo a=1, b=2>
> foo.b = foo
=> #<struct Struct::Foo:...>
```
=> fix Segmentation fault on Struct#inspect due to recursive Struct object

mrblib/string.rb
Before:
```
$ ./bin/mirb 
> "abc".match("b")
/Users/maki/tmp/mruby/mrblib/string.rb:149: stack level too deep. (limit=(0x40000 - 128)) (SystemStackError)
```
After (with `conf.gem github: 'iij/mruby-regexp-pcre'`):
```
$ ./bin/mirb 
> "abc".match("b")
=> #<MatchData "b">
```
After (without any regexp gems):
```
$ ./bin/mirb 
> "abc".match("b")
/Users/maki/tmp/mruby/mrblib/string.rb:154: String#match needs Regexp class (NotImplementedError)
```
cf. ISO (draft) 15.2.10.5.27 (and JIS X 03071:2011):
> if *regexp* (argument of `String#match`) is an instance of the class `String`, create a direct instance of
> the class `Regexp` by invoking the method `new` on the class …
=> fix infinite loop in String#match(arg) when arg is String

mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c
How to reproduce:
```
$ cat a.rb
Proc.new { 1 }.call
$ echo step | mrdb a.rb
```
=> mrdb: fix crash when stepping into Proc.call

tasks/mruby_build_gem.rake
Some of my *mrbgems* have pretty complicated build logic.
I usually use a singleton method on the spec objects and call it in the block one can pass to the
`gem` method. I ran into a bug, however: in one of these blocks I dynamically add other gems to the build, i.e. I call `gem` from within a block passed to another `gem` call. Now, because of the way these blocks are evaluated, `Build.current` is not set to the right build object and the spec is possibly assigned a different, wrong build object (e.g. a cross build object created later).
This seems to fix that.
=> Don't use Build.current if possible

src/vm.c, test/t/ensure.rb
How to reproduce:
class A
def x
yield
ensure
y
end
def y
end
end
A.new.x do
end
A.new.x do
break
end
lambda do
A.new.x do
return
end
end.call
`self` in ensure is broken when yield and break/return are used.
=> Fix ensure with yield context on break and return

src/backtrace.c
When invoking a method implemented as a `CFUNC` directly from C thought `mrb_funcall_argv`, `@lastpc` on the exception is not set. This is fine without boxing but, with `MRB_WORD_BOXING`, `mrb_exc_backtrace` causes a segfault. This is because of the [`mrb_cptr` with a `nil` value](https://github.com/mruby/mruby/blob/4957c852696c9559bfbea988325fd9bf94fc34bc/src/backtrace.c#L136).
---
I used the following program to test it
```c
#include "mruby.h"
#include "mruby/error.h"
int main(int argc, char *argv[]) {
mrb_state *mrb = mrb_open();
mrb_value s = mrb_str_new_cstr(mrb, "this will not end well");
mrb_value count = mrb_fixnum_value(-4);
mrb_funcall_argv(mrb, s, mrb_intern_lit(mrb, "*"), 1, &count);
mrb_p(mrb, mrb_inspect(mrb, mrb_exc_backtrace(mrb, mrb_obj_value(mrb->exc))));
return 0;
}
```
=> Fix possible segfault when accessing backtrace with MRB_WORD_BOXING.

tasks/mruby_build.rake
We can use `#define`-ed macros in GDB with `-g3` flag.
We can run code step by step in GDB with `-O0` flag.
See also about `-g3`: http://www.clear-code.com/blog/2013/5/8.html (in Japanese)
=> Add more debug flags for GCC based compilers

src/backtrace.c
#2156 disabled `Exception#backtrace` when compiling with `DISABLE_STDIO` by making it systematically returning an empty array. This was due to the fact that `get_backtrace_i` relied on `vsnprintf` to format stack locations.
This PR restores `Exception#backtrace` by getting rid of `vsnprintf` in favour of the string manipulation functions already in mruby. Other approaches are
* embedding an implementation of `snprintf` in mruby, as proposed in #2140. This seemed overkill since the formatting was pretty simple (only a few strings and one integer per stack location). However, it would have the advantage of hitting two birds with one stone and fixing the issue of `mrb_float_to_str` (#2140) at the same time.
* implementing a method similar to `Exception#backtrace_locations` in MRI. This would …
=> Make backtraces work again under DISABLE_STDIO

include/mruby/numeric.h, include/mruby/value.h, src/dump.c, src/fmt_fp.c, src/numeric.c
The new implementation is backwards incompatible, but I couldn't find any usage outside mruby and I also couldn't think of a different and good name.
All ISO C99 printf conversion specifiers for floating point numbers and an optional precision are supported.
It is largely based on code from the MIT licensed musl libc (http://www.musl-libc.org/) and its floating point printing is exact (unlike the current code behind `Float#to_s`).
--
Related issues: #2140, #1947 and #1906.
These points require further discussion:
- backwards incompatible (if this is really a problem, what's a good name?)
- increases the size by a few KB (~4 KB on x86 SSE2), but it still supports hexadecimal floating point numbers (can be made optional) and flags
- 3 of 4 format strings, especially the both used in …
=> re-implement mrb_float_to_str()

src/vm.c
In src/vm.c: mrb_funcall_with_block
stack_extend may realloc mrb->c->stbase, if argv points on mruby's stack,
then it points invalid address after stack_extend.
e.g. src/class.c: mrb_instance_new
This code:
```ruby
class A
def initialize(a0,a1,a2,a3,a4)
a0.is_a? Array
end
end
def f(a0,a1,a2,a3,a4)
A.new(a0,a1,a2,a3,a4)
f(a0,a1,a2,a3,a4)
end
f(0,1,2,3,4)
```
is expected to get exception
```
stack level too deep. (limit=(0x40000 - 128)) (SystemStackError)
```
but get segfault.
Signed-off-by: Go Saito <gos@iij.ad.jp>
=> fix pointer dereference after realloc

src/codegen.c, test/t/syntax.rb
Here is a script that reproduce this problem:
x = if true
1
else
case 2
when 3
end
4
end
p x # => nil # 1 is expected
=> Fix a bug that if and no return value case can't return true clause value

src/codegen.c, test/t/syntax.rb
Here is a script that reproduces this problem:
x = case
when true; 1
end
p x # => main # 1 is expected
=> Fix a bug that no expression case doesn't return valid value

src/vm.c
The following program reproduces this problem:
static mrb_value
recursive(mrb_state *mrb, mrb_value self)
{
mrb_int n;
mrb_get_args(mrb, "i", &n);
if (n == 0) {
mrb_raise(mrb, E_RUNTIME_ERROR, "XXX");
} else {
mrb_funcall(mrb, self, "recursive", 1, mrb_fixnum_value(n - 1));
}
return self;
}
int
main(void)
{
mrb_state *mrb;
mrb = mrb_open();
mrb_define_method(mrb, mrb->kernel_module, "recursive", recursive,
MRB_ARGS_REQ(1));
mrb_funcall(mrb, mrb_top_self(mrb), "recursive", 1, mrb_fixnum_value(30));
mrb_close(mrb);
}
Recursive method call isn't required. It's just for expanding call info
stack.
If mrb_realloc() is called in cipush(), cibase address is changed. So,
we shouldn't compare ci before mrb_realloc() and cibase after
mrb_realloc(). It accesses unknown address and …
=> Fix a crash bug on raising after realloc

src/vm.c
3df32161797aa9c6e9df259e8d8571b454cb2333 says so but there is no warning
with GCC 4.9 on my Debian GNU/Linux environment.
=> Use ptrdiff_t to suppress signedness warning

src/vm.c
In #2739, recursive send causes memory corruption.
Because mrb_f_send doesn't extend mruby stack.
After this fix,
```
% cat tmp.rb
class A
def f a0
self.send(:f, a0 + 1)
end
end
A.new.send(:f, 0)
% valgrind --tool=memcheck bin/mruby tmp.rb
==31101== Memcheck, a memory error detector
==31101== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==31101== Using Valgrind-3.9.0 and LibVEX; rerun with -h for copyright info
==31101== Command: bin/mruby tmp.rb
==31101==
tmp.rb:3: stack level too deep. (limit=(0x40000 - 128)) (SystemStackError)
==31101==
==31101== HEAP SUMMARY:
==31101==     in use at exit: 0 bytes in 0 blocks
==31101==   total heap usage: 6,055 allocs, 6,055 frees, 4,317,196,048 bytes allocated
==31101==
==31101== All heap blocks were freed -- no leaks are possible …
```
=> Fix #2739 stack_extend in mrb_f_send

src/fmt_fp.c
cygwinでmakeすると、下記のようなエラーがでるので、
----------------------------------------------------------------------------------------------
C:\git\github\mruby\src\fmt_fp.c: 関数 ‘fmt_fp’ 内:
C:\git\github\mruby\src\fmt_fp.c:125:3: エラー: 関数 ‘frexpl’ の暗黙的な宣言です [-Werror=implicit-function-declaration]
y = frexpl(y, &e2) * 2;
^
C:\git\github\mruby\src\fmt_fp.c:125:7: 警告: 組み込み関数 ‘frexpl’ の互換性がない暗黙的な宣言です
y = frexpl(y, &e2) * 2;
...
----------------------------------------------------------------------------------------------
fmt_fp.cに、frexp()をラップしたfrexpl()を追加しました。
=> I modified the undefined frexpl in cygwin of make

tasks/toolchains/visualcpp.rake
Exception handling is broken for visualcpp toolchain, if using C++ source files.
The issue is the the `/EHsc` cxx flag. From [MSDN /EH docs](https://msdn.microsoft.com/en-us/library/1deeycx5.aspx), this <i>'tells the compiler to assume that functions declared as extern "C" never throw a C++ exception.'</i>
The problem with that is that all of the functions in vm.c *are* extern "C". See this block from `mrb_funcall_with_block`
```C
MRB_TRY(&c_jmp) {
mrb->jmp = &c_jmp;
/* recursive call */
val = mrb_funcall_with_block(mrb, self, mid, argc, argv, blk);
mrb->jmp = 0;
}
MRB_CATCH(&c_jmp) { /* error */
while (old_ci != mrb->c->ci) {
mrb->c->stack = mrb->c->ci->stackent;
cipop(mrb);
}
mrb->jmp = 0;
val = mrb_obj_value(mrb->exc);
}
MRB_END_EXC(&c_jmp);
```
`cl.exe` (Microsoft C/C++ Version …
=> Fix exceptions for visualcpp

src/dump.c
No need to write the same assertion in each case (except the default one). Instead we can assert after the switch statement.
=> refactor write_pool_block()

mrbgems/mruby-time/src/time.c
`gettimeofday()` is an obsolescent POSIX function which may be removed in a future version. POSIX recommends using `clock_gettime()` (also POSIX) instead, but it isn't available on OS X or Windows (at least with MSVC and older MinGW versions).
Whereas `timespec_get()` is part of ISO C11 and mruby uses some small other C11 features too. It isn't universally available yet either, but it might be in the future. And Visual C++ 2015 implements it! I think it's a reasonable choice, since mruby strives for plain ISO C compatibility, .
`TIME_UTC` is used instead of `__STDC_VERSION__`, because if `TIME_UTC` is defined, then most likely `timespec_get()` is too. This isn't true in case of ` __STDC_VERSION__` (see MSVC).
=> mruby-time: call ISO C11's timespec_get() if available

include/mruby/value.h
Apparently the C compiler of Visual Studio 2015 CTP6 finally implements inline as `inline` and not only as `_inline` and `__inline`.
=> MSVC 2015 implements inline keyword

include/mruby/value.h
The format specifier macros were needed to portably print a `mrb_int`, because `mrb_raisef()` originally called `vsnprintf()`. It doesn't anymore since 18b2683b97ae54d4f2f15c19076f33aa29eaf2b7 and the `mrb_int` format specifier macros are already gone (couldn't find the commit).
=> remove unnecessary <inttypes.h> inclusion

mrbgems/mruby-bin-debugger/tools/mrdb/apibreak.c
This is a bug fixes for problems mrdb to access outside the range of breakpoints.
=> fix maximum value of the index when access breakpoints.

mrbgems/mruby-bin-debugger/tools/mrdb/cmdbreak.c, mrbgems/mruby-bin-mruby/tools/mruby/mruby.c, mrbgems/mruby-string-ext/src/string.c, src/fmt_fp.c, tasks/toolchains/gcc.rake
Here are suppressed warnings:
src/fmt_fp.c: In function 'fmt_fp':
src/fmt_fp.c:124:16: warning: initialization discards 'const' qualifier from pointer target type
char *ss = (t&32)?"inf":"INF";
^
src/fmt_fp.c:125:17: warning: assignment discards 'const' qualifier from pointer target type
if (y!=y) ss=(t&32)?"nan":"NAN";
^
mrbgems/mruby-string-ext/src/string.c: In function 'mrb_str_succ_bang':
mrbgems/mruby-string-ext/src/string.c:302:27: warning: assignment discards 'const' qualifier from pointer target type
if (e == b) prepend = "1";
^
mrbgems/mruby-string-ext/src/string.c:305:27: warning: assignment discards 'const' qualifier from pointer target type
if (e == b) prepend = "a";
^
mrbgems/mruby-string-ext/src/string.c:308:27: warning: assignment discards 'const' qualifier from pointer …
=> Suppress warnings generated by -Wwrite-strings

src/load.c
It isn't a complete fix (as there need to be more checks), but it's better than the current situation.
=> src/load.c: fix size error macros

src/fmt_fp.c
On MIPS/linaro, libm.so lacks frexpl() as CygWin does.
=> Defining static version of frexpl also fro MIPS platforms.

src/parse.y
The `YYDEBUG` macro enables parser debugging which unnecessarily increases the executable size (9 to 10 KB). Now it only will be defined when `PARSER_DEBUG` is too.
=> define YYDEBUG macro conditionally

include/mruby/boxing_nan.h, include/mruby/boxing_word.h
Looking at the assembly output, I found that the compiler produces an unnecessary store and, in consequence, an unneeded reload. Since this code gets executed quite frequently I changed things
so that the compiler (only tested with Clang) generates a single load.
The NaN-boxing case is rather obvious. For word-boxing, integers and symbols always occupy all bits
of the word (right?), so  clearing to zero beforehand is useless.
It did a quick `make test` with the appropriate boxing macros set and things should be fine.
=> Avoid unnecessary stores and reloads

src/dump.c
#2156 disabled `mrb_iseq_dump` under `DISABLE_STDIO` because it was relying on `mrb_float_to_string` as discussed in #2140. Now that `mrb_float_to_string` has been reimplemented not to rely on `snprintf` (#2723), we can reenable `mrb_dump_irep`.
=> Reenable mrb_dump_irep under DISABLE_STDIO.

MITL, README.md, include/mruby.h
Not sure what todo with ``doc/debugger/README.md`` as it claims the copyright belongs to the "mruby-forum" instead of "mruby developers"
=> Update Coopyright Information to year 2015

include/mruby/class.h, src/class.c, src/vm.c
It isn't needed as it's very similar to `mrb_define_method_raw()` and also there's only one place where `mrb_proc_ptr()` actually has to be called.
=> remove mrb_define_method_vm() function

src/dump.c
Some C compilers may allow other characters in identifiers such as `$`. They may also implement C99's extended identifiers (`\u30EB\u30D3\u30FC`, `ルビー`).
https://gcc.gnu.org/onlinedocs/gcc/Dollar-Signs.html
https://gcc.gnu.org/wiki/FAQ#What_is_the_status_of_adding_the_UTF-8_support_for_identifier_names_in_GCC.3F
http://llvm.org/releases/3.3/tools/clang/docs/ReleaseNotes.html#extended-identifiers-unicode-support-and-universal-character-names
=> let the C compiler validate the identifier

test/driver.c
=> Use `mrb_funcall` instead of `mrb_load_string` in test driver.

include/mruby/boxing_nan.h, include/mruby/boxing_no.h, include/mruby/boxing_word.h
It isn't used anymore since the #2791 merge. It's also unlikely to be needed again as it wasn't before (its usage was unnecessary).
=> remove SET_PROC_VALUE() macro

include/mruby.h, src/error.c
`mrb_str_new()` takes `size_t`, so should `mrb_exc_new()`.
=> fix type of mrb_exc_new()'s len parameter

mrbgems/mruby-bin-mirb/mrbgem.rake, src/fmt_fp.c
There are 2 compilation issues on NetBSD.
1. NetBSD 6.1.5 (latest release) does not have fexpl(3).
2. NetBSD does not have libreadline but readline(3) is in libedit.
The patch attached fixes them.
=> Fix build mruby for NetBSD

src/string.c
#2797 accidentally includes the useless (always true) conditional.  Sorry.
=> remove an always-true conditional.

src/proc.c
Related to AFL testing from #2769. This should prevent crashes caused by code like this:
```
l = !Kernel.lambda do
true
end
m = Kernel.lambda(&l)
```
=> Verify that proc_lambda is passed a proc

src/parse.y
I believe this will fix #2779 and also the following that causes a crash:
```
j do
def !a.test
end
c = 1
end
```
=> Add locals null checks

src/parse.y
This should fix another class of issues from the test cases in #2769, specifically certain special characters in heredocs combined with unterminated blocks. Here is an example, the ^@ here is actually a special character:
```
begin
<<o
^@
do
end
```
=> Add null check on lex_strterm in heredoc block

include/mruby.h, mrbgems/mruby-string-ext/src/string.c, mrbgems/mruby-string-utf8/src/string.c, mrbgems/mruby-struct/src/struct.c, src/class.c, src/dump.c, src/string.c, src/symbol.c, src/variable.c
- smaller file size (between 1 and 2 KB with dynamically linked C standard library)
- the macros don't require including `<ctype.h>` anymore
=> mruby.h: simplify ctype-like macros

src/parse.y
`atoi()` is used to convert the index to an int but the behavior is undefined if the value can't be represented.
```
> $9999999999
00007 NODE_SCOPE:
00007   NODE_BEGIN:
00007     NODE_NTH_REF: $2147483647
irep 00630580 nregs=2 nlocals=1 pools=0 syms=1 reps=0
file: (mirb)
7 000 OP_GETGLOBAL  R1      :$2147483647
7 001 OP_STOP
```
Call `strtoul()` instead as its behavior in such cases is defined and add a simple range check.
Alternatively `NODE_NTH_REF`'s cdr could be changed from `int` to `mrb_sym` (like `NODE_GVAR`). Then there would be no limitation but who needs that many capture groups anyway?
=> fix capture group index bug

src/codegen.c
It's just a copy of the code in the previous case (`NODE_CALL`).
=> codegen: remove unreachable code

src/class.c, test/t/class.rb, test/t/module.rb
For modules this check didn't exist yet. Also call `#inspect`.
This fixes [id:000379,sig:11,src:014265,op:arith8,pos:8,val:+26](https://github.com/tongson/afl-fuzz-findings/blob/1e8a1fb7210d756174ecd0f7e171534a805cbbb5/mruby-1.1.0/crashes/id:000379%2Csig:11%2Csrc:014265%2Cop:arith8%2Cpos:8%2Cval:%2B26) (ref #2769).
=> check if outer is a class or module

src/codegen.c, test/t/syntax.rb
The rest lhs variable has to be an empty array if rhs is an array with less elements than pre + post lhs variables. The codegen generated OP_ARRAY with an invalid length (such as 127 for `*a, b = []`) because rn was negative.
=> fix masgn nosplat array rhs bug

src/codegen.c
This fixes a crash for code like `"#{@a;1}"`. Unlike CRuby globals are excluded too since mruby doesn't implement hooking. That's okay, isn't it?
=> only generate gets of non-local vars in VAL mode

src/array.c, src/etc.c
I think `!mrb_array_p(ary2)` and `mrb_type(obj) != MRB_TT_DATA` are sufficient or am I missing something?
=> remove unnecessary mrb_immediate_p()

src/fmt_fp.c
MIPS of Linux platform is supported frexpl(3).
This fixes to use the frexpl that are provided with gcc if user wants to build
on MIPS of Linux platform.
Signe-doff-by: Nobuhiro Iwamatsu <iwamatsu@nigauri.org>
=> Fix build on MIPS of linux

mrblib/string.rb, test/t/string.rb
This implementation is compatible with CRuby's String#gsub/sub
except \1 ... \9 and \+.  They are useless without Regexp library.
=> gsub/sub supports back references in substitutes.  fixes #2816.

Rakefile, mrbgems/mruby-bin-mirb/mrbgem.rake
Detect if ncurses' backend is terminfo or termcap. fixes #2662
Borrowed from @mattn's code at:
https://github.com/mruby/mruby/issues/2662#issuecomment-65535705
Signed-off-by: Huei-Horng Yo <hiroshi@ghostsinthelab.org>
=> Detect if ncurses' backend is terminfo or termcap.

mrbgems/mruby-bin-mirb/mrbgem.rake
The detection code is unused even on OpenBSD 5.7,
because of the standard installation is libtermcap be installed, not libterminfo.
This fixes #2829
Tested on Arch Linux (x86_64) & OpenBSD 5.7 (amd64).
Signed-off-by: Huei-Horng Yo <hiroshi@ghostsinthelab.org>
=> Remove the unused libterminfo detection code.

mrbgems/mruby-bin-mruby/tools/mruby/mruby.c, src/print.c
`mrb_inspect()` also calls `mrb_obj_as_string()` after `#inspect` to ensure the `mrb_value` is a string.
=> refactor code to call mrb_inspect() instead

src/proc.c, test/t/proc.rb
From [the CRuby 2.2.2 Proc#arity documentation](https://github.com/ruby/ruby/blob/v2_2_2/proc.c#L790-L793):
>If the block has optional arguments, returns -n-1, where n is the number of mandatory arguments, with the exception for blocks that are not lambdas and have only a finite number of optional arguments; in this latter case, returns n.
=> fix arity of lambdas with optional arguments

mrbgems/default.gembox, mrbgems/mruby-bin-mirb/mrbgem.rake, mrbgems/mruby-bin-mruby/mrbgem.rake
cross compilesWhen trying to build `mruby-bin-mruby` or `mruby-bin-mirb` for cross compilation from Linux to OSX, I ran into the following error:
```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture x86_64:
"_mrb_load_file_cxt", referenced from:
_main in mruby.o
"_mrb_load_string_cxt", referenced from:
_main in mruby.o
"_mrbc_context_free", referenced from:
_main in mruby.o
"_mrbc_context_new", referenced from:
_main in mruby.o
"_mrbc_filename", referenced from:
_main in mruby.o
ld: symbol(s) not found for architecture x86_64
```
Adding `mruby-compiler` fixes it. If this is needed for cross compiles, we should just add it as a build dependency.
/cc @zzak
=> Need mruby-compiler to build mruby-bin-mruby and mruby-bin-mirb for

tasks/mruby_build.rake
Sometimes a mrbgem pulls in a native extension that needs to be built. There's currently no way to provide information to autoconf or build scripts how to build the native extension for the `MRuby::CrossBuild` target. Instead gems are forced to [skip building them](https://github.com/mattn/mruby-onig-regexp/commit/c2a82f6bcd8698b86bcffa0e79ba42dcebd5fe81) when detecting a `MRuby::CrossBuild`. This is a proposal for a `MRuby::CrossBuild` to provide this information so a [mrbgem can take advantage of it](https://github.com/hone/mruby-onig-regexp/commit/d3c8875713e938840a2dd8fcff6adefc9cdad580). The naming is based off the [flags for autoconf](https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Specifying-Target-Triplets.html).
Would love your throughts @take-cheeze.
/cc …
=> provide targets for building native extensions during CrossBuild

include/mruby.h, include/mruby/deprecated.h
This PR introduces code to properly handle deprecation. For now, it moves the deprecated `ARGS_` macros into a separate file. Unfortunately, it is not possible to deprecate macros via a compiler directive.
Are there currently any other deprecated functions or structures ?
=> Move deprecated macros and functions to dedicated header file

include/mruby/compile.h, include/mruby/opcode.h, mrbgems/mruby-compiler/core/parse.y, mrbgems/mruby-hash-ext/mrblib/hash.rb, mrbgems/mruby-sprintf/src/sprintf.c, mrbgems/mruby-struct/src/struct.c, mrblib/array.rb, src/class.c, src/numeric.c, src/object.c, src/string.c, src/variable.c
Dr Markus Kuhn published in 1999 an article [1] explaining in details
why we shouldn't use the ASCII grave accent (0x60) as a left quotation.
Backticks have been used most notably to produce nice-looking LaTeX
documents but it doesn't seem to be an issue on modern platforms and
for the oldest ones, there are workarounds as mentioned by Dr Kuhn.
[1]: https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html
=> Remove unnecessary backticks

tasks/mrbgem_spec.rake
```
rake aborted!
undefined local variable or method `root' for #<MRuby::Gem::List:0x002b4f6123c3b0>
```
=> add_dependency doesn't work

tasks/mruby_build_gem.rake
In some mrbgems is usual to add some dependencies libraries as dependencies, like:
https://github.com/luisbebop/mruby-polarssl
https://github.com/sadasant/mruby-qrcode
Is interesting that mrbgem, configured as git, have all submodules automatic initialized and updated:
```
MRuby::Build.new do |conf|
conf.gem :git => 'git@github.com:luisbebop/mruby-polarssl.git'
end
```
=> Add —-recursive option to automatically update submodules from git mgems

mrbgems/default.gembox, mrbgems/mruby-array-ext/mrbgem.rake, mrbgems/mruby-enum-ext/mrbgem.rake, mrbgems/mruby-hash-ext/mrbgem.rake, mrbgems/mruby-kernel-ext/mrbgem.rake, mrbgems/mruby-numeric-ext/mrbgem.rake, mrbgems/mruby-object-ext/mrbgem.rake, mrbgems/mruby-proc-ext/mrbgem.rake, mrbgems/mruby-range-ext/mrbgem.rake, mrbgems/mruby-string-ext/mrbgem.rake, mrbgems/mruby-symbol-ext/mrbgem.rake, mrbgems/mruby-toplevel-ext/mrbgem.rake
Adjective of `extension`(noun) is not `extensional` but `extended`
extenstional means 外延的 in Japanese.
refer:
http://ejje.weblio.jp/content/extensional
=> Fix typo; Replace extensional with extended

mrbgems/mruby-compiler/core/codegen.c
Mruby crashes with SIGSEGV on the input:
```ruby
begin
break
rescue
end
```
After this patch the output is:
```
codegen error:test.rb:2: unexpected break
```
=> Fix segfault found using afl-fuzz

src/proc.c
mrb_proc_new_cfunc_with_env() allocates RProc with RProc::env as NULL
then allocates REnv and sets it to RProc::env of the allocated RProc. If
incremental GC is ran before "allocates REnv and sets it to RProc::env
of the allocated RProc", the allocated RProc's GC status is
"marked" (Black) and the allocated REnv's GC status is
"unmarked" (White). The next incremental GC sweeps the allocated REnv
without re-marking the allocated RProc. Because the RProc is Black and
the REnv is White.
We need to implement write barrier for the case.
We can force to cause the above situation by the following patch:
diff --git a/src/proc.c b/src/proc.c
index f98998f..4f4e25c 100644
--- a/src/proc.c
+++ b/src/proc.c
@@ -92,6 +92,7 @@ mrb_proc_new_cfunc_with_env(mrb_state *mrb, mrb_func_t func, mrb_int argc, …
=> Fix a crash bug when GC is ran while creating a proc with env

src/numeric.c
`flo_round` is producing the following warning under both Darwin and Linux x86_64
```
mruby/src/numeric.c:454:7: warning: absolute value function 'abs' given an argument of type 'mrb_int' (aka 'long long') but has parameter of type 'int' which may
cause truncation of value [-Wabsolute-value]
i = abs(ndigits);
```
An alternative would be to not rely on `MRB_INT64` and have a check such as
```c
if (sizeof(num) == sizeof(long long)) {
return llabs(num);
} else {
return abs(num);
}
```
=> Avoid a narrowing cast in flo_round under MRB_INT64.

mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c
As detected in a Coverity scan. https://scan8.coverity.com/reports.htm#v26153/p11375/fileInstanceId=6844472&defectInstanceId=2516000&mergedDefectId=75866
=> Fix incorrect memory allocation of mrdb_state_new.

src/string.c
CID 75872 (#3-2 of 3): Pointer to local outside scope (RETURN_LOCAL)
38. use_invalid: Using p, which points to an out-of-scope variable buf.
It could be fixed in a different way but that seems to be the simplest one.
=> Coverity: fix dangling pointer

mrbgems/mruby-time/src/time.c
if you want, I'll make block this part with `#ifdef _WIN32`.
=> implement llround. some platform (ex: mingw32) doesn't have llround.

src/array.c
Fixes #2882
This is hardly a "bug," I know. I only noticed it because I'm implementing an mrbgem for some CRuby stdlib features, and when I got to the output field separator `$,`, which defaults to `nil`, I noticed that `Array#join` wouldn't actually take it. Obviously this isn't a huge blocker, but if compatibility with CRuby is desired, hopefully this PR can take care of that. 
Old behavior
```
[jared:~/projects/mruby-bindings/mrbgems/mruby-apr] ./mirb 
> [1, 2, 3].join(nil)
(mirb):2: expected String (TypeError)
```
New behavior
```
[jared:~/projects/mruby-bindings/mruby] ./bin/mirb 
> [1, 2, 3].join
=> "123"
> [1, 2, 3].join(nil)
=> "123"
> [1, 2, 3].join ' '
=> "1 2 3"
> [1, 2, 3].join(3)
(mirb):3: …
```
=> Patching array join

doc/api/mruby.h.md
Adding @matz's recent `!` implementation notes to mruby.h.md.
Tried running `rake doc`, but it didn't seem to catch the updates, so I applied them manually.
I didn't realize these format specifiers applied the implicit conversions until I read comments from 02474da, so I added a note about that as well.
=> Doc bang modifier

mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.c, mrbgems/mruby-bin-mruby/tools/mruby/mruby.c, src/dump.c
Passing a null pointer to `free()` is fine. So there's no need to optimize for speed in these cases since a program only exits once and errors are rare. Also the mruby source code doesn't have these kind of checks elsewhere.
The ones in `{Time,Random}#initialize` are kept because there it actually might matter. I didn't measure it though.
=> delete mrb_free()-related non-NULL checks

src/class.c, src/error.c, src/range.c, src/variable.c
`mrb_any_to_s()`, `mrb_obj_as_string()` and `mrb_inspect()` always return a string which means `mrb_str_cat_str()` can be directly called instead of indirectly by `mrb_str_append()`.
=> use mrb_str_cat_str() instead of mrb_str_append()

src/fmt_fp.c
64bit Cygwin doesn't have frexpl(3) as well as 32bit Cygwin, so I couldn't build mruby on 64bit Cygwin.
I tested this on 64bit Cygwin, 32bit Cygwin and Mac OS X.
=> 64bit Cygwin also doesn't have frexpl(3)

mrblib/string.rb
`String#sub` throws if the pattern to substitute is not in the string. The issue being that `pre, post = split(args[0], 2)` returns `[ORIGINAL_STRING, nil]`, that nil goes on to cause problems.
Before
```
C:\projects\mruby-bindings\mruby>bin\mirb.exe
> 'a'.sub 'b', 'c'
(mirb):1: expected String (TypeError)
```
After
```
C:\projects\mruby-bindings\mruby>bin\mirb.exe
> 'a'.sub 'b', 'c'
=> "a"
> 'a'.sub 'a', 'b'
=> "b"
> 'a'.sub 'a' do |c| 'b' end
=> "b"
> 'a'.sub 'b' do |c| 'd' end
=> "a"
```
=> Don't crash if pattern not found for sub

tasks/toolchains/androideabi.rake
Was trying to build for android and found out I had newer compiler versions.
Rather than just updating it I added the option to set it with `ENV` variables.
Just getting used to the project, so let me know if there's anything to fix :stuck_out_tongue:
=> Add ability to change compiler versions for androideabi

tasks/mrbgem_spec.rake, tasks/mruby_build_commands.rake
I think it should be recompile mrbgem when its *mrbgem.rake* has been modified !
the reason list below :
* compiler and linker options maybe change
* the mrbgem information maybe change, such as version.
=> mrbgem compile should be depend on mrbgem.rake

mrbgems/mruby-compiler/core/parse.y
See ruby/ruby@dfec9d978804fbd53df9e6b93e5801985b2b3130. It fixes a regression which affects mruby too because of 2fe556d9c039839c20965a2c90dff703f04e40ec.
=> pop cmdarg in lambda body; fix [ruby-bug#11380]

tasks/mruby_build_gem.rake
Allow people in `build_config.rb` to override a github repo or mgem with a local working copy, so you don't need to push to github to see the changes. This would like this:
```ruby
conf.gem :path => '/path/to/gem_fork`
```
=> be able to source with :path for mrbgems

.travis.yml
This PR adds a second job in a build matrix running on Trusty (Ubuntu 14.04 LTS), and a third, running on OS X.
For Trusty, `apt-get update` is necessary; without it, the current image cannot find `gperf`.
`language: c` has been added for tracking metrics correctly.
The multi-os feature has been turned on for `mruby/mruby`, so this PR should on the Mac image as well.
You can see an example build at https://travis-ci.org/BanzaiMan/mruby/builds/73983119.
=> Add build on Trusty and OS X

mrblib/error.rb
It overwrote the original definition in [src/error.c, line 446](https://github.com/mruby/mruby/blob/a1731254bee12c831ea1d509bf43520db1d0d9af/src/error.c#L446).
=> delete duplicate definition of Exception.exception

src/dump.c
IEC 60559 single format has 6 to 9 significant decimal digits precision.
However the printf conversion specifier e (and E, of course) already writes 1 digit - the one before the decimal point - and precision specifies the number of digits to write after the decimal point.
=> irep dump: fix format string for MRB_USE_FLOAT

test/bintest.rb
Currently, when running bintests mruby only checks for tests 1 level deep of the `bintest/` dir. So `bintest/foo.rb` will run, but `bintest/bar/baz.rb` will not. This allows the latter to be detected and run so people can organize their bintests however they want as long as they're in the `bintest/` dir.
=> run bintests within subfolders of bintest/

Rakefile, build_config.rb, mrbgems/mruby-test/mrbgem.rake, tasks/mruby_build.rake, travis_config.rb
Add build_mrbtest after config block is evaluated
This allows us to add `enable_test` anywhere in a build target,
without having to worry about the order in which they are included.
Previously, there was a bug that occured when adding 'mruby-test' gem
to dependencies before additional gems.
Instead of adding the 'mruby-test' gem dependency manually to a test build,
we now only need to call `enable_test` in the target. This also allows us to
call `test_enabled?` downstream when compiling mruby ourselves.
=> Add build_mrbtest after config block is evaluated

include/mruby.h, include/mruby/class.h, include/mruby/object.h, src/class.c, src/gc.c, src/kernel.c, src/object.c, test/t/module.rb
Hi, we requested Module#prepend, so about a year later we figured what the heck and went ahead and implemented it.
We've gone and ported over the original ruby commits by ko1 and nobu over to mruby, all tests currently pass. RClass struct size is now bigger, because we needed to add `origin`, but that seems unavoidable.
/cc @matz @cremno @zzak
Closes #2082.
=> Module#prepend

src/hash.c
As discussed in #2945, `Hash#keys` returns unfrozen key objects that are actually being used by the underlying hash table.  And unexpected behaviors happen if they get modified by the caller.
Thank to 1a45447, we can fix the issue as is done by MRI by freezing the key string when they are registered to the hash table.
Disclaimer: I am totally new to mruby and there might be issues overlooked within this PR.
=> freeze the hash keys (fixes #2945)

Rakefile
Previously, minirake installed several commands (e.g., mrbc) in
repository locally under bin directory.  But there was no knob for
users to change this directory.  It effectively made `make distcheck`
fail if mruby was embedded into project managed by autotools.
This change adds a way for the user to change installation directory
by setting INSTALL_DIR environment variable.
=> Customize installation directory using INSTALL_DIR environment variable

include/mruby.h, mrbgems/mruby-bin-mirb/tools/mirb/mirb.c, mrbgems/mruby-bin-mruby/tools/mruby/mruby.c, mrbgems/mruby-print/src/print.c, src/string.c
Add mrb_cstr_from_locale/mrb_cstr_to_locale. ARGV should be utf8 strings converted from locale strings. And __printstr__ should print locale strings.
=> Add mrb_utf8_from_locale, mrb_utf8_free, mrb_locale_from_utf8, mrb_locale_free

src/state.c
Sometimes it is very useful just return from mrb_close if NULL is
passed as mrb.  This is the same spirit of free(3), which just does
nothing if NULL is passed.
=> Don't crash if NULL is passed to mrb_close

mrbgems/mruby-hash-ext/mrblib/hash.rb, mrbgems/mruby-hash-ext/test/hash.rb
A block of Hash#fetch should have block variable, which is the same value of `key`.
=> fix block variable in Hash#fetch

include/mrbconf.h, include/mruby.h, include/mruby/array.h, include/mruby/class.h, include/mruby/common.h, include/mruby/compile.h, include/mruby/data.h, include/mruby/debug.h, include/mruby/dump.h, include/mruby/error.h, include/mruby/gc.h, include/mruby/hash.h, include/mruby/irep.h, include/mruby/khash.h, include/mruby/numeric.h, include/mruby/proc.h, include/mruby/range.h, include/mruby/string.h, include/mruby/value.h, include/mruby/variable.h, include/mruby/version.h
I started to work on documenting MRuby's C API.
While working on a gem project, I started to get locked quite often on "whats the function that does x?" moments so I started to document the methods I found on the process.
I noticed there are some methods already documented at [doc/api](https://github.com/mruby/mruby/tree/master/doc/api) but I believe it's better to have the API documented on the headers, so I've been taking those docs, and merging them into the headers as well.
I'm leaving this pull request to get some feedback before putting more effort into it.
Some of the things I've experimented with related with documenting MRuby's C API are:
* Generate a simple API website: the generated site is available right now at http://sagmor.com/mruby-c-api/ and its source at …
=> C API documentation

src/string.c
cf. #2963 
```
$ ./bin/mirb 
> a = "あ"
=> "あ"
> a.inspect
=> "\"あ\""
> b = "あい"
=> "あい"
> b.inspect
=> "\"あい\""
```
=> fix String#inspect with MRB_UTF8_STRING

include/mruby.h
dd925578c604a608f83172f85d8e5bfc3bb99c6a changed the order of arguments,
but it doesn't seem intentional.
Some mrbgems are broken by this change.
https://github.com/search?l=c&q=mrb_class_new_instance&type=Code&utf8=%E2%9C%93
=> fix signature of mrb_class_new_instance()

mrbgems/mruby-compiler/core/codegen.c, mrbgems/mruby-compiler/core/parse.y
This patch allows encoding option for Regexp literal.
```ruby
/foo/n #-> Regexp.compile("foo", nil, "n")
/bar/iu #-> Regexp.compile("bar", Regexp::IGNORECASE, "u")
```
(Note: This spec is not in ISO Ruby (Regexp.compile has only 2 arguments in ISO Ruby), but it's compatible with CRuby.)
=> support Regexp literal option: //n and //u

tasks/mrbgem_spec.rake
Since `LinkerConfig` does not set the fifth param to `[]`, `spec.linker.flags_after_libraries` will be `nil` inside `mrbgem.rake` where as all the other attributes are set to `[]`.
=> LinkerConfig is a struct with five params

tasks/mrbgem_spec.rake
Added a `add_test_dependency` method to gems specs.
All it does is call `add_dependency` if `test_enabled?` is true.
Not sure if it's the best approach but seems to be working :smile:
=> Add gem test dependencies

doc/api/gc-arena-howto.md
This adds documentation of mrb_gc_arena_save()/mrb_gc_arena_restore() functions.
As the documentation says, this is basically the English translation of Matz's blog post in Japanese back in 2013.  So first we have to ask @matz the permission to translate his post.
As far as I know, there is no official documentation about these functions in this repository.
Also I think that Matz's blog post is very well written.  I understand what these functions really do and their purpose.
It has 2 problems though.  First one is that it is written in Japanese, never get into official doc.  Second problem is that it is now outdated.  I read the post and learned that the size of stack is limited to 100, but the reality is it is now unlimited (true?).
Some say that they are really thin, and no overhead, …
=> Add how to use  mrb_gc_arena_save()/mrb_gc_arena_restore() doc

tasks/mruby_build.rake
Here's a proposed implementation of part of the mechanism I explained in #2972.
I't basically adds an optional params argument to the `toolchain` method on `Build` objects.
That additional param is then passed to the Toolchain to be handled at will.
For example:
```ruby
MRuby::CrossBuild.new('device') do |conf|
toolchain :xcode, platform: 'iPhoneOS'
end
MRuby::CrossBuild.new('simulator') do |conf|
toolchain :xcode, platform: 'iPhoneSimulator'
end
MRuby::Toolchain.new(:xcode) do |conf,params|
toolchain :clang
platform = params.fetch(:platform)
end
```
I'm actually working on a couple toolchains using these structure, but I wanted to leave this here first.
=> Add optional params to toolchain configuration

Rakefile
`doc/language/generator.rb` has been removed, so use `mrbdoc`
=> fix `rake doc` error

tasks/toolchains/androidndk.rake
Following the merge of #2978 I wanted to better approach Android cross-compilation.
This PR let's you configure android builds in the following way:
```ruby
MRuby::CrossBuild.new("build-name") do |conf|
toolchain :androidndk, arch: 'x86'
end
```
The main advantage is that it let's you build multiple architectures at once.
For example you could cross-compile to every Android architecture with something like:
```ruby
MRuby::Toolchain::AndroidNDK::ARCHITECTURES.each do |arch|
MRuby::CrossBuild.new("android-#{arch}") do |conf|
toolchain :androidndk, arch: arch
end
end
```
The available options are:
* `:arch`: Target architecture (defaults to 'armeabi')
* `:toolchain`: The underlying toolchain can be `:gcc` or `:clang` (defaults to `:gcc`)
* `:toolchain_version`: Toolchain version. …
=> WIP - New Android NDK toolchain

tasks/toolchains/androidndk.rake
To support 64bit architectures (arm64, mips64 and x86_64), androidndk.rake have to be modified.
We can build libmruby.a for 64bit architecture like below:
```Ruby
MRuby::CrossBuild.new('android-arm64') do |conf|
toolchain :androidndk, arch: 'arm64', platform: 'android-21' # 'android-19' or before cannot be used to build for 64bit architecture
end
```
=> Update androidndk.rake to add support 64bit architectures.

include/mruby.h
mrb_get_mid Returns the name Symbol of the current method
mrb_get_argc Returns the number of arguments sent to the current method
These are struct member accessors; makes the ability to query the current method more obvious.
=> mrb_get_mid and mrb_get_argc

tasks/toolchains/android.rake
As discussed in #2983 I renamed the `AndroidNDK` class to just `Android` and the  toolchain from `:androidndk` to just `:android` too.
=> Rename androidndk tolchain to just android

tasks/toolchains/androidndk.rake
I forgot to evaluate 'flags' variable. So, all options of LDFLAGS are not applied.
This change will fix the bug.
=> Fix issue: LDFLAGS is not applied correctly.

src/fmt_fp.c
That `#if` was getting a bit ridiculous. There are no plans for a `long double` version of `mrb_float` anyway or are there?
=> call always frexp() instead of frexpl()

include/mruby.h, include/mruby/gc.h, include/mruby/object.h, mrbgems/mruby-objectspace/src/mruby_objectspace.c, src/error.c, src/gc.c, src/state.c, src/vm.c
This restructures and refactors the GC code. This is part of something bigger, but is useful on its own.
I would have run the GC tests if I'd known how to do that ?
All GC related data is now encapsulated in the `mrb_gc` struct. Related declarations, definitions and macros have been moved to `gc.h` or replaced with something better.
In particular, the ugly `is_dead`, `is_black` etc. macros are no longer public and there are no more
GC related unprefixed structure declarations.
This code makes use of C99 flexible array members. Apparently these are even supported by recent
versions of MSVC. However, if you want to support older versions, we might need to add a hack.
=> GC cleanup

src/gc.c
The return type of the `mrb_objspace_each_objects` function is `void`. So this return statement with an expression is unnecessary and also violates a constraint. From C99 §6.8.6.4:
>A return statement with an expression shall not appear in a function whose return type is void.
=> remove return

test/t/float.rb
>/home/travis/build/mruby/mruby/test/t/float.rb:201:17: ambiguous first argument; put parentheses or even spaces
=> fix ambiguous first argument warning

test/bintest.rb
Fail to debian package build.
Because not define $SHELL environment variable at debian build tool.
More Info : https://github.com/mruby-debian/mruby/issues/1
=> fail to debuild

tasks/mruby_build_gem.rake
Since mgem's function almost the same as git gems, but you can see they already
avoid pulling from source after the gem has already been cloned.
You can see from the `load_special_path_gem` method found in the file
`mruby_build_gem.rake`, or extracted here:
```ruby
if File.exist? mgem_list_dir
git.run_pull mgem_list_dir, mgem_list_url if $pull_gems
else
FileUtils.mkdir_p mgem_list_dir
git.run_clone mgem_list_dir, mgem_list_url, "--depth 1"
end
```
Also, later in this same method; mgem will set the `git` params.
Doing this will trigger the following block:
```ruby
if File.exist?(gemdir)
if $pull_gems
git.run_pull gemdir, url
else
gemdir
end
else
end
```
You can see here, this checks if `$pull_gems` is enabled before pulling.
Lastly, the final condition for this method is here:
```ruby
if …
```
=> This patch changes git gem behavior to never pull gems unless specified.

src/version.c
`RUBY_ENGINE_VERSION` is equivalent to `MRUBY_VERSION`. It would be a
standard way to get the interpreter version (without a case expression).
[Opal](https://github.com/opal/opal/commit/c537e69868be4d60e5b0f2e61fa3b938eb515376), [Rubinius](https://github.com/rubinius/rubinius/commit/8212c460b97a6f277db35de5295f046a868eb8ac), and [JRuby](https://github.com/jruby/jruby/issues/2751) already implement it, but [CRuby doesn't (yet)](https://github.com/ruby/ruby/pull/858).
=> add RUBY_ENGINE_VERSION

src/numeric.c, test/t/integer.rb
related #3023 
sorry negative number don't care.
```ruby
$ ./bin/mirb --version
mruby 1.2.0 (2015-11-17) 
$ ./bin/mirb
> -3<<29
=> -1610612736
> -3<<30
=> 1073741824
> -3<<31
=> -2147483648
```
this PR fix it.
```ruby
$ ./bin/mirb 
> -3<<29
=> -1610612736
> -3<<30
=> -3221225472
> -3<<31
=> -6442450944
```
=> Bugfix nagative-number lshift() bit overflow

mrbgems/mruby-math/src/math.c
erf() and other similar mathematical functions are available in MSVC starting from VS2012 (_MSC_VER == 1700).
=> Fix check for VisualStudio Version in mruby-math gem

mrbgems/mruby-compiler/core/parse.y
Following https://github.com/mruby/mruby/commit/4440566b9522ae5ff6b2bce7b3d8ecd232304eea, I found another little typo, this time in the compiler.
=> Fix MRB_DISABLE_STDIO typo.

mrbgems/mruby-test/init_mrbtest.c, mrbgems/mruby-test/mrbgem.rake
If we make the core tests a dependency on the mruby-test gem,
we don't need to worry about maintaining the core test irep alone.
This patch also removes unnecessary dependencies for assert_rb codegen and test_rbireps.
=> Remove mrbtest irep

mrbgems/mruby-time/src/time.c
Implemented round(double) function  within mruby-time gem, for it is missing on VisualStudio compilers where _MSC_ver < 1800
=> Implemented round(double) function when _MSC_VER < 1800

src/object.c
Wondering why they are different. I used `ruby 2.0.0p645` and `mruby 1.2.0 (2015-11-17)` to get following result.
```
$ cat foobar.rb
class A; end
puts ObjectSpace.each_object(A) {|k| puts k}
puts ObjectSpace.each_object(singleton_class) {|k| puts k}
$ ruby foobar.rb
0
main
1
$ mruby foobar.rb
0
trace:
[0] foobar.rb:3
foobar.rb:3: class or module required (TypeError)
```
If this is a bug, then my best guess to fix this is adding case statement for `MRB_TT_SCLASS` in mrb_obj_is_kind_of() in src/object.c. From my quick check it looks fixed but totally no idea if this is the right way.
=> Add case statement of MRB_TT_SCLASS in mrb_obj_is_kind_of()

test/t/integer.rb
Similar to #3005 
Maybe there's something we can fix in the parser?
/cc @cremno
=> Fix "ambiguous first argument" warning

mrbgems/mruby-compiler/core/parse.y
My understanding is that the peek functions of parser.y are expected to just _peek_ into what characters are coming, without changing the state of the parser.
However, `peekc_n` is not resetting the change to `p->column` made by `nextc`.
Therefore, when the peek functions are called under certain conditions, the column number becomes incorrect, as reported in #3053.
This PR fixes the issue by decrementing `p->column` in `peekc_n` after a successful to `nextc`.
=> fix miscalculation of column number in `peekc_n`

mrbgems/mruby-bin-debugger/tools/mrdb/apibreak.c, mrbgems/mruby-math/src/math.c, src/dump.c, src/fmt_fp.c, src/string.c
build error on VS2012 because ignoring _MSC_VER=1700 in mrbgems/mruby-math/src/math.c
```
#if defined _MSC_VER && _MSC_VER < 1700
```
I fixed some other compilation warnings.
http://denx.jp/mruby-on-unity
=> fix build on VS2012

mrbgems/mruby-bin-debugger/tools/mrdb/cmdrun.c, mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c, mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.h
So far I have added a 'next' was not supported by mrdb.
This enables step-over during debugging.
'next' is available by entering the 'next' or 'n' at the prompt.
reference:http://qiita.com/Y_uuu/items/f71cf8c94f36d54d2d1e
=> mrdb: Added 'next' command.

mrbgems/mruby-compiler/core/node.h, mrbgems/mruby-random/src/random.h
RANDOM_H / NODE_H is easy name to be duplicate.
=> rename include blocker

mrblib/array.rb
Condition length <= self.length and length = self.length-1 are always true.
elm.nil? and length >= self.length are always false so break is not executed.
=> Refactor Array#each

mrbgems/mruby-struct/src/struct.c, mrbgems/mruby-struct/test/struct.rb
* Use `assert_*` method in `Struct` test.
* Improve `Struct#[]` and `Struct#[]=` tests. Checks raised exceptions and negative value index.
* Optimization using `mrb_check_intern_str()` seems to conflict with `NameError` raising when it is implemented as how it's defined in specification.
=> Improve `Struct` test.

include/mruby.h, src/backtrace.c, src/error.c, src/load.c, src/state.c, src/vm.c, test/t/exception.rb
GitHub: fix #2902, #2917
The current implementation traverses stack to retrieve backtrace. But
stack will be changed when some operations are occurred. It means that
backtrace may be broken after some operations.
This change (1) saves the minimum information to retrieve backtrace when
exception is raised and (2) restores backtrace from the minimum
information when backtrace is needed. It reduces overhead for creating
backtrace Ruby objects.
The space for the minimum information is reused by multiple
exceptions. So memory allocation isn't occurred for each exception.
=> Support backtrace after method calls

src/string.c
Use `memchr` for performance.
This code was copy from https://github.com/ruby/ruby/blob/2f2a5c3ae9f9e7a4d09b1500de8d864f48d69cad/re.c#L264-L269
```shell
$ uname -v
Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64
```
```ruby
s = "b"
str = ("a" * 100 + s)
t = Time.now
str.index(s)
puts Time.now - t
```
before => 0.000788
after  => 0.000508
---
```ruby
s = "b"
str = ("a" * 100 * 1024 * 1024 + s)
t = Time.now
str.index(s)
puts Time.now - t
```
before => 0.225474
after  => 0.008658
=> Use memchr for performance

include/mruby/throw.h
setjmp/longjmp are very slow on OS X; _setjmp/_longjmp should be used for implementing TRY-CATCH.
The reason is as stated in the man pages of OSX, quoting:
> ```
> The setjmp()/longjmp() pairs save and restore the signal mask while _setjmp()/_longjmp() pairs save and restore only
> the register set and the stack.  (See sigprocmask(2).)
> ```
With the change, benchmark/bm_ao_render.rb became 20% faster (11.791 seconds => 9.668 seconds) on my MacBook Pro.
Shown below is the profile result of the master branch running mb_ao_render.rb on OS X.
=> use _setjmp/_longjmp on OS X

include/mruby/value.h
This PR adds macros that map `MRB_PRI?` to `PRI?NN` depending on the size of `mrb_int`.
Such macro makes us easy to use printf (and its variant) to stringify the values of `mrb_int`.
=> provide macro to ease using printf mrb_int

src/symbol.c
**before**
```ruby
p :== #=> :==
p :!= #=> :!=
p :=~ #=> :=~
p :!~ #=> :"!~"
```
**after**
```ruby
p :== #=> :==
p :!= #=> :!=
p :=~ #=> :=~
p :!~ #=> :!~
```
I think **after** behavior is more better than **before** because same as CRuby.
=> symname_p support `!~`

src/backtrace.c
There is a problem when MRB_INT64 is enabled.
Linux printf manpage(http://linux.die.net/man/3/printf) says about this.
> The precision
>
> An optional precision, in the form of a period ('.') followed by an optional decimal digit string. Instead of a decimal digit string one may write "*" or "*m$" (for some decimal integer m) to specify that the precision is given in the next argument, or in the m-th argument, respectively, which must be of type int.
=> printf precision parameter must be 'int' type

src/backtrace.c
The code to iterate over backtrace locations was changed in #3065, but unfortunately `output_backtrace` was not correctly updated to forward the callback.
=> Fix segfault on mrb_exc_backtrace.

tasks/toolchains/clang.rake, tasks/toolchains/gcc.rake, tasks/toolchains/visualcpp.rake
The following error and warning occurs when run `ruby ./minirake` in `ruby 1.8.7`.
```
/*****/mruby/tasks/toolchains/gcc.rake:1: warning: multiple values for a block parameter (2 for 1)
from /*****/mruby/tasks/mruby_build.rake:30
rake aborted!
undefined method `cc' for #<Array:0x100715970>
./rakefile:15:in `load'
```
This error has occurred from #2978.
I applied the changes of #2978 to `:clang`, `:gcc` and `:visualcpp` toolchains.
=> Fix build error in ruby 1.8.

mrbgems/mruby-kernel-ext/test/kernel.rb, src/string.c
=> Fix passing all zero string to Kernel#Integer

src/gc.c, src/vm.c
Think about the following Ruby script:
segv.rb:
begin
lambda do
lambda do
"x" * 1000 # NoMemoryError
end.call
end.call
rescue
raise
end
If memory can't allocate after `"x" * 1000`, mruby crashes.
Because L_RAISE: block in mrb_vm_exec() calls mrb_env_unshare() via
cipop() and mrb_env_unshare() uses allocated memory without NULL check:
L_RAISE: block:
L_RAISE:
// ...
while (ci[0].ridx == ci[-1].ridx) {
cipop(mrb);
// ...
}
cipop():
static void
cipop(mrb_state *mrb)
{
struct mrb_context *c = mrb->c;
if (c->ci->env) {
mrb_env_unshare(mrb, c->ci->env);
}
c->ci--;
}
mrb_env_unshare():
MRB_API void
mrb_env_unshare(mrb_state *mrb, struct REnv *e)
{
size_t len = (size_t)MRB_ENV_STACK_LEN(e);
// p is NULL in this case
mrb_value *p = (mrb_value *)mrb_malloc(mrb, sizeof(mrb_value)*len); …
=> Fix SEGV on re-raising NoMemoryError

examples/mrbgems/ruby_extension_example/mrbgem.rake
=> Fix missing dependency on mruby-print to support 'puts'

doc/limitations.md
As suggested in issue #3085 it would be interesting to get an overview which limitations of mruby are "by design". I started here with these two:
- Kernel.raise in rescue
- Array passed to puts
If the overall style is accepted by @matz I will proceed adding.
=> Limitations

tasks/toolchains/openwrt.rake
Under https://github.com/deuwert/openwrt-mruby I developed since quite a while a mruby package for OpenWRT. For people who are not aware of this software, I just mention here that it is a Linux distribution which is optimised for embedded systems with a very strong cross compiling toolchain. My personal view is that the package seems to be useful enough to be committed to the upstream package repository of OpenWRT. Before I do that I would like to make it as slick as possible, for that I would love to relocate the toolchain configuration of mruby upstream.
=> Add toolchain support for OpenWRT

doc/limitations.md
This pull requests documents the following limitations of mruby:
- defined?
- alias on global variables
- Operator modification
- Kernel.binding missing
=> Add more limitations

mrbgems/mruby-test/mrbgem.rake
In an used build path mruby-test wasn't updating mrbtest.c in the
case that the mgem selection was changed. This lead to:
- a missing reference in case a GEM was removed
- ignoring all new GEMs added to the build configuration
This fix keeps track of the active gems and demands a rebuild of
mrbtest.c in case that the gem selection changed.
fix #3094
=> Fix bug in mruby-test gem (fix #3094)

mrbgems/mruby-eval/src/eval.c
Hello,
Before:
~~~~
$ ./bin/mruby -e 'p eval("__FILE__")'
Segmentation fault (core dumped)
~~~~
After:
~~~~
$ ./bin/mruby -e 'p eval("__FILE__")'
"(eval)"
~~~~
Thank you,
=> Fix segfault when `eval("__FILE__")` is executed

mrblib/enum.rb
Hello,
~~~~
$ ./bin/mruby -e '[255, 255, 255, 255, 255].hash'
trace:
[0] /tmp/mruby/mrblib/enum.rb:387:in Enumerable.hash
[1] /tmp/mruby/mrblib/array.rb:17:in Array.each
[2] /tmp/mruby/mrblib/enum.rb:385:in Enumerable#hash
[3] -e:1
/tmp/mruby/mrblib/enum.rb:387: can't convert Float into Integer (TypeError)
~~~~
This is caused by `0 ^ 0x8000_0000 #=> TypeError`.  I'm unsure if this is an intended limit, but if so, `Enumerable#hash` should be fixed.
Thank you,
=> [255, 255, 255, 255, 255].hash raises "can't convert Float into Integer"

src/class.c
The else block doesn't return a value, so the compiler gives a warning when compiling with -std=c99 flag
=> Avoid Error when Compiling with -std=c99 flag

src/backtrace.c
It looks like the logic to reallocate the backtrace was flawed,
based on the wrong variable (loc_raw->i, which, as I have verified,
decreases from 16 to 0 instead of increasing)
I am not sure if this is the correct fix
=> The original code crashed when mrb->backtrace.n grew to 16.

src/backtrace.c
Was really hoping to solve #3118 (& therefor jbreeden/mruby-apr#9), but no such luck.
Still, this fixes the segfault in #3122 for me.
```sh
[jared:~/projects/mruby-spec] cat test.rb 
def gen
e0 = nil
begin
1.times {
raise 'foobar'
}
rescue => e
e0 = e
end
e0
end
e = gen
GC.start
gen
GC.start
p e.backtrace
[jared:~/projects/mruby-spec] mruby ./test.rb 
["./test.rb:18"]
```
(Of course, the backtrace is still losing information about where the exception was actually raised)
=> Null check for irep & initialize loc.lineno

mrbgems/mruby-eval/src/eval.c
mrbgems/mruby-eval/src/eval.c: In function ‘create_proc_from_string’:
mrbgems/mruby-eval/src/eval.c:152:10: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
file = "(eval)";
^
=> Suppress a warning

src/backtrace.c, src/error.c, src/gc.c
Fix segmentation fault by backtrace and GC
GitHub: fix #3122
It reverts #3126. #3126 fixes the segmentation fault but generates
broken backtrace.
This change fixes the segmentation fault and generates correct
backtrace. The strategy of this change is "generating backtrace while
irep is alive".
/tmp/test.rb:
def gen
e0 = nil
begin
1.times {
raise 'foobar'
}
rescue => e
e0 = e
end
e0
end
e = gen
GC.start
gen
GC.start
puts e.backtrace.join("\n")
Run:
% bin/mruby /tmp/test.rb
/tmp/test.rb:5:in Object.gen
/home/kou/work/ruby/mruby.kou/mrblib/numeric.rb:77:in Integral#times
/tmp/test.rb:4:in Object.gen
/tmp/test.rb:13
FYI:
% ruby -v /tmp/test.rb
ruby 2.3.0p0 (2015-12-25) [x86_64-linux-gnu]
/tmp/test.rb:5:in `block in gen'
/tmp/test.rb:4:in `times'
/tmp/test.rb:4:in `gen'
/tmp/test.rb:13:in …
=> Fix SEGV by backtrace and GC

build_config.rb
Since the default `host` build enables debug mode, I think we should add an another build just for benchmarking mruby.
=> Add default benchmark build config

tasks/mrbgem_spec.rake
When I tried to build [mruby-gtk3](https://github.com/ppibburr/mruby-gtk3), sometimes faild by inflation of include_paths. It contains many -I"/some/path/mruby-cfunc/include".
I guess it should be a 'set', without duplication.
=> Reduce compiler include_paths

test/bintest.rb
```:visualcpp``` toolchain set ```conf.file_separator = '\\'``` by default.
Dir.glob return empty array by backslash separator.
=> Fix doesn't work bintest on :visualcpp toolchain

src/vm.c
mrb_vm_define_class() may realloc() mrb->c->stack because it calls
mrb_funcall() for inherited hook. If mrb->c->stack is realloc()-ed, regs
refers orphan address.
=> Add missing regs update

tasks/toolchains/visualcpp.rake
CRuby v1.8 dose not support named capture.
```
$ ruby -v
ruby 1.8.7 (2013-06-27 patchlevel 374) [i686-darwin13.4.0]
$ rake
rake aborted!
SyntaxError: src/github.com/ksss/mruby/tasks/toolchains/visualcpp.rake:56: undefined (?...) sequence: /Version (?<v>\d{2}\.\d{2}\.\d{5})/
$ ./minirake
(in src/github.com/ksss/mruby)
rake aborted!
src/github.com/ksss/mruby/tasks/toolchains/visualcpp.rake:56: undefined (?...) sequence: /Version (?<v>\d{2}\.\d{2}\.\d{5})/
./rakefile:10:in `load'
```
Since this fix https://github.com/mruby/mruby/pull/3139
@cremno Could you review this? (I don't have visual studio)
=> Avoid Syntax Error on CRuby v1.8

src/version.c
`RUBY_ENGINE_VERSION` and `MRUBY_VERSION` should refer to the same string.
Rationale: One less object is created and [JRuby does it too](https://github.com/jruby/jruby/blob/915993886ae6663586d893b7d237f750068aceb5/core/src/main/java/org/jruby/RubyGlobal.java#L133-L141).
=> fix MRUBY_VERSION value

src/kernel.c, test/t/kernel.rb
```ruby
class Foo
def foo
end
end
class Bar < Foo
def bar
end
end
p Foo.new.public_methods(false)
p Bar.new.public_methods(false)
p Bar.new.public_methods.include?(:foo)
```
CRuby works as below:
```
[:foo]
[:bar]
true
```
But mruby does:
```
[:foo]
[:bar]
false
```
=> Fix public methods

mrbgems/mruby-sprintf/src/sprintf.c
On OSX & clang v7.3.0 appear these warning.
```
/Users/yuki/src/github.com/ksss/mruby/mrbgems/mruby-sprintf/src/sprintf.c:37:11: warning: shifting a negative signed value is undefined
[-Wshift-negative-value]
*t |= EXTENDSIGN(3, strlen(t));
^~~~~~~~~~~~~~~~~~~~~~~~
/Users/yuki/src/github.com/ksss/mruby/mrbgems/mruby-sprintf/src/sprintf.c:20:32: note: expanded from macro 'EXTENDSIGN'
#define EXTENDSIGN(n, l) (((~0 << (n)) >> (((n)*(l)) % BITSPERDIG)) & ~(~0 << (n)))
~~ ^
/Users/yuki/src/github.com/ksss/mruby/mrbgems/mruby-sprintf/src/sprintf.c:37:11: warning: shifting a negative signed value is undefined
[-Wshift-negative-value]
*t |= EXTENDSIGN(3, strlen(t));
^~~~~~~~~~~~~~~~~~~~~~~~
/Users/yuki/src/github.com/ksss/mruby/mrbgems/mruby-sprintf/src/sprintf.c:20:76: note: expanded from macro …
```
=> Fix warning shift-negative-value

include/mruby/throw.h
It seems that there is a problem in case of using C and C++ gems at same time.
for example:
you write in build_config.rb like this.
```rb
conf.gem :github => 'kjunichi/mruby-mrmagick'
conf.gem :github => 'matsumoto-r/mruby-redis'
```
compile errors occur.
```txt
CC    build/mrbgems/mruby-redis/src/mrb_redis.c -> build/host/mrbgems/mruby-redis/src/mrb_redis.o
In file included from /Users/kjunichi/work/mruby/mrmagick/mruby/build/mrbgems/mruby-redis/src/mrb_redis.c:45:
/Users/kjunichi/work/mruby/mrmagick/mruby/include/mruby/throw.h:44:3: error: type name does not allow storage class
to be specified
static mrb_int jmpbuf_id;
^
/Users/kjunichi/work/mruby/mrmagick/mruby/include/mruby/throw.h:45:3: error: type name requires a specifier or
qualifier
mrb_jmpbuf() : impl(jmpbuf_id++) {}
^ …
```
=> C doesn't have try-catch

mrbgems/mruby-string-ext/mrblib/string.rb, mrbgems/mruby-string-ext/test/string.rb
I think, almost all of the user of mruby expect mruby works same as the CRuby.
So, I think `String#insert` should be destructive same as the CRuby.
And current `String#insert` implementation is slightly complicated.
I reimplemented this and fix to destructive.
=> String#insert should be destructive

mrbgems/mruby-struct/src/struct.c, mrbgems/mruby-struct/test/struct.rb
```rb
Struct.new(:foo) do
def bar
end
end
Struct.new(:baz).new.bar
```
This case should raise NoMethodError, But nothing.
=> Should not define to `Struct` class

mrbgems/mruby-string-ext/mrblib/string.rb
`String#char` and `String#each_char` aren't same methods.
This patch support like this (same as CRuby).
```rb
"foo".each_char.with_index do |ch, index|
end
```
=> Support to call without block to String#each_char

mrbgems/mruby-string-ext/mrblib/string.rb
Here are some benchmarks:
each_char:
a = "a" * 1000000
a.each_char do |x|
end
Without this change:
% time bin/mruby /tmp/each_char.rb
bin/mruby /tmp/each_char.rb  1.07s user 0.02s system 99% cpu 1.088 total
With this change:
% time bin/mruby /tmp/each_char.rb
bin/mruby /tmp/each_char.rb  0.52s user 0.01s system 99% cpu 0.530 total
2 times faster with this change.
codepoints:
a = "a" * 1000000
a.codepoints do |x|
end
Without this change:
% time bin/mruby /tmp/codepoints.rb
bin/mruby /tmp/codepoints.rb  1.16s user 0.05s system 99% cpu 1.216 total
With this change:
% time bin/mruby /tmp/codepoints.rb
bin/mruby /tmp/codepoints.rb  0.56s user 0.02s system 99% cpu 0.589 total
=> Reduce needless Array generation in some String methods

mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c
Fix warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
=> intptr_t should be used instead of uint32_t to hold a pointer.

mrbgems/mruby-compiler/core/parse.y
fix syntax errors with chained assignment with op assign.
reported [Bug:12669] in bugs.ruby-lang.org fixed in CRuby 2.4.
=> parse.y: fix chained assignments

mrbgems/mruby-string-ext/src/string.c, mrbgems/mruby-string-ext/test/string.rb
Fixed a problem which String#ord returns a negative value, if specify character code of 0x80 or later.
=> Fix String#ord failure which return a negative value

mrbgems/mruby-compiler/core/parse.y
allow parenthesised statement as a method argument.
reported [Feature:12686] in bugs.ruby-lang.org fixed in CRuby 2.4.
=> parse.y: lparen_arg statement

mrbgems/mruby-eval/src/eval.c, mrbgems/mruby-eval/test/eval.rb
I try to fix #3191.
Before, `mrb->c->ci->env` keep and pass to env of proc when make a closure.
https://github.com/mruby/mruby/blob/0d9aa830aa7bc7c1fd79c46085d21b1286e66993/src/proc.c#L61
So, stack when call `instance_eval` get back it when make a closure.
```rb
a = 1
b = 2
c = 3
o = Object.new
p o.instance_eval("[a, b, c, o, self]")
#=> [1, 2, 3, #<Object:0x7ff749818c90>, #<Object:0x7ff749818c90>]
p o.instance_eval("[1].each { break [a, b, c, o, self] }")
#=> [nil, nil, nil, nil, main]
```
But proc env should be that of receiver.
And `closure_setup` make new env on current context.
https://github.com/mruby/mruby/blob/501e1ef2605541b98b6f0d2ba2fec69ff068f1cf/src/proc.c#L37-L64
So, I propose this patch.
=> instance_eval env should remake Fix #3191

mrbgems/mruby-compiler/core/parse.y
Hi there,
I'm very new to mruby.
I encountered a small memory leak when using mruby-eval,
it was small(maybe 8bytes for once for glibc)
but ate all physical memory on my system after one day of stress test.
I've dug it and found mrbc_context.filename is not freed when
the context is freed. I know this conversion has been closed at #1878 and
I understand this behavior never cause problem if application creates
only one mrb_context for one mrb_state. 
However, mruby-eval allows to create many contexts in one mrb_state.
This pull request tries to fix the memory leak, I'm not sure it's correct or not
but it works for me.
=> Fix mrbc_filename leak

tasks/mrbgem_spec.rake
This can be useful, for example, in order to simplify the setup of "universal" gems, i.e. gems that can be built both for standard ruby and for mruby. The `mrbgem.rake` file, for example, could explicitly set a different base name for ruby and C source files.
=> In mrbgem_spec.rake, added support for @mrblib_dir @objs_dir, so that a gem can have custom source directory names

src/vm.c
This patch fix two issue if callinfo over CALLINFO_INIT_SIZE(32)
- Fix method name in top-level
- Fix SEGV when call Exception#backtrace
```rb
1.times{1.times{1.times{1.times{1.times{1.times{1.times{1.times{
1.times{1.times{1.times{1.times{1.times{1.times{1.times{1.times{
begin
eval('raise')
rescue => e
print e.backtrace
end
}}}}}}}}
}}}}}}}}
```
This code have rundom results.
```
$ mruby t.rb
["(eval):1:in Object.rand", "t.rb:6:in Object.call", "mruby/mrblib/numeric.rb:77:in Integral#times", ... , "t.rb:3"]
```
`Object.rand` never call in script and this string sometimes chenge `Object.__attached__`, `Object.INFINITY` or SEGV.
```rb
$ mruby t.rb
[1]    41204 segmentation fault  mruby t.rb
```
This issue's reasone is here.
https://github.com/ksss/mruby/blob/501e1ef2605541b98b6f0d2ba2fec69f …
=> Should clear method name

mrbgems/mruby-eval/src/eval.c
I'm trying project what run [ruby/spec](https://github.com/ruby/spec) by mruby. (https://github.com/ksss/mruby-spec)
I encountered SEGV on spec for /language.
On `get_closure_irep` in eval.c, It is a possibility that unshare stack env (cioff=-1) comes.
And It will read `mrb->c->cibase[-1]`.
https://github.com/mruby/mruby/blob/9040086e927781018dc9b89d0d160dbba4e76297/mrbgems/mruby-eval/src/eval.c#L29
```rb
def m
Proc.new { eval('raise') }
end
1.times{1.times{1.times{1.times{1.times{1.times{1.times{1.times{
1.times{1.times{1.times{1.times{1.times{1.times{1.times{1.times{
m.call
}}}}}}}}
}}}}}}}}
```
=> Fix SEGV when unshared env

src/array.c, test/t/syntax.rb
Currently, These code got segmentation fault.
```rb
o = Object.new
def o.to_a
nil
end
a = *o
```
```rb
o = Object.new
def o.to_a
nil
end
a = case o
when *o
1
end
```
Splat operation should return an array.
And should raise an error if result of convert by to_a is not array or nil.
This behavior same with CRuby.
This fix have an incompatibility for `mrb_ary_splat`.
But I'm believing this is a good way for mruby.
=> Fix SEGV when splat object

src/load.c, src/proc.c, src/string.c
ref #3215
If a function (such as mrb_read_irep_file()) is declared without MRB_API
in header file (such as include/mruby/dump.h), implementation of the
function in source file (such as src/load.c) should also defined without
MRB_API.
If MRB_API is mismatch, Visual C++ reports link error with C2375 error
code: https://msdn.microsoft.com/en-us/library/5k6kw95a.aspx
=> Remove needless MRB_API

mrbgems/mruby-compiler/core/codegen.c
I found unexpected behavior.
```rb
def yie
yield
end
def bre
yie {
1+1
break
}
end
p bre #=> display 2, but should be nil
```
You can check this behavior on [ruby/spec/language/break_spec.rb](https://github.com/ruby/spec/blob/d05fabfe0ba3774710d912d2802d6d235c1ed8ae/language/break_spec.rb)
This patch fix 2 cases of specs
before:
F..FFF..F.FFF.FFEEE..FE.F.FEE.E
after:
...FFF....FFF.FFEEE..FE.F.FEE.E
Fixed specs:
https://github.com/ruby/spec/blob/d05fabfe0ba3774710d912d2802d6d235c1ed8ae/language/break_spec.rb#L10-L13
https://github.com/ruby/spec/blob/d05fabfe0ba3774710d912d2802d6d235c1ed8ae/language/break_spec.rb#L91-L94
=> Fix unexpected behavior with break

tasks/toolchains/android.rake
Added macOS NDK search paths.
The Android SDK now has NDK installation built in, so the task will now favour that if no ndk_home is set.
~/Library/Android is the default for macOS.
The gcc toolchain path has quotes now, this is a minor change but it fixes the possibility of spaces in that path - keeps it consistent with the use of quotes for other paths in the task.
=> Android mips/mips64 support

tasks/toolchains/android.rake
This adds GCC compiler support back into the Android build rule. It is there for support, as the default for Android is now Clang (with GCC deprecated).
There are a few things omitted that were in the old Android task; namely hard/soft floating point support and the cortex a8 fix. These should probably be handled as cflags outside of the rule itself.
=> Android Task GCC support re-added

src/kernel.c
t.rb
```rb
class A
def respond_to_missing? method, bool
p [method, bool]
end
end
p A.new.respond_to?(:foo)
```
Actual
```
$ mruby t.rb
[:foo, false]
[:foo, false]
```
Expect
```
$ ruby t.rb
[:foo, false]
true
```
=> Kernel#respond_to? should return true|false only

mrbgems/mruby-array-ext/mrblib/array.rb
The sentence `Negative values of +index+ count from the end of the array.` can be interpreted that it only holds if a block is given. Clarify it.
=> Update documentation of fetch

include/mruby.h, mrbgems/mruby-compiler/core/codegen.c, src/class.c, src/variable.c, src/vm.c, test/t/exception.rb
Works the same way as mrb_class_defined but uses mrb_const_defined_at with a given outer class to test if an inner class is defined.
Example code for checking if an inner class of a module is defined:
```c
void
mrb_example_gem_init(mrb_state* mrb) {
struct RClass *example_outer, *example_inner;
mrb_bool cd;
example_outer = mrb_define_module(mrb, "ExampleOuter");
example_inner = mrb_define_class_under(mrb, example_outer, "ExampleInner", mrb->object_class);
cd = mrb_class_under_defined(mrb, example_outer, "ExampleInner");
// If mrb_class_under_defined returns 1 then puts "True"
// If mrb_class_under_defined returns 0 then puts "False"
if (cd == 1){
puts("True");
}
else {
puts("False");
}
}
```
=> Add mrb_class_defined_under

mrbgems/mruby-enum-ext/mrblib/enum.rb, mrbgems/mruby-enum-ext/test/enum.rb
I tryed [mruby-spec](https://github.com/ksss/mruby-spec) with enumerable and encountered infinite loop
Because this code run inifinity
```rb
class Empty
include Enumerable
def each
end
end
Empty.new.cycle { break :nope }
```
So, I supported all specs in https://github.com/ruby/spec/blob/27960d06e0ce92c37f074450f0eab4b0519b118c/core/enumerable/cycle_spec.rb without Enumerable#size
=> Reimplement Enumerable#cycle 

src/class.c, test/t/module.rb
`Module#define_method` supports Proc object in CRuby.
How about supporting this behavior in mruby?
=> Module#define_method supports proc argument

mrbgems/mruby-struct/src/struct.c, src/class.c, src/string.c
- `Struct#values_at`
- `Module#define_method`
- `String#chop`
- `String#chop!`
=> Correct argument specifications for few methods

src/range.c, test/t/range.rb
In comments say *"Ranges are immutable, so that they should be initialized only once."*
But Range object can rewrite by `Range#initialize`.
```rb
$ mirb
> range = (0..1)
=> 0..1
> range.send(:initialize, 1, 3)
=> 1..3
> range
=> 1..3
```
CRuby raise NameError in this case.
```rb
$ irb
irb(main):001:0> (0..1).send(:initialize, 1, 3)
NameError: `initialize' called twice
```
=> Ranges should not rewrite

.travis.yml
`travis-rubies` now uses 3 Mac jobs to create archives for various OS
releases.
This is a bit wasteful if multiple builds pass in a short period.
Instead, Travis CI is now running a nightly build of mruby-head
(around 22:30 UTC). This will happen regardless of the state of the
master branch.
=> Remove webhook notification for Travis CI

src/range.c, test/t/range.rb
```rb
p (1...10).include?(9) #=> true
p (1...10).include?(10) #=> false
```
```rb
p (1...10).include?(9) #=> true
p (1...10).include?(10) #=> true
```
Maybe missed in https://github.com/mruby/mruby/commit/be5986b2b4fc1534d753d53ac26081c98ce8883d
=> Fix condition of Range#include?

mrbgems/mruby-range-ext/src/range.c, mrbgems/mruby-range-ext/test/range.rb
```rb
$ mirb
> (1.0..15.9).size
=> 16
> (0..Float::INFINITY).size
=> -2147483648
```
```rb
$ irb
irb(main):001:0> (1.0..15.9).size
=> 15
irb(main):002:0> (0..Float::INFINITY).size
=> Infinity
```
This fix passed all specs of that https://github.com/ruby/spec/blob/66daf290cb49707190481b4cf24e700010cd53bf/core/range/size_spec.rb
=> Fix Range#size results

mrbgems/mruby-sprintf/test/sprintf.rb
This is an artifact discovered during #3258. `1 << 15` is too big to fit a 16-bit int.
=> Fix for sprintf test exceeding bounds with MRB_INT16

include/mrbconf.h, include/mruby.h, include/mruby/boxing_nan.h, include/mruby/value.h
This is an artifact discovered during #3258. 
Fixed NaN boxing for 64-bit configrations on platforms that use full 48-bit usermode pointers
Definition of boxed pointer is following:
`111111111111TTTT TTPPPPPPPPPPPPPP PPPPPPPPPPPPPPPP PPPPPPPPPPPPPPPP`
Previously, only the last 32-bit were set, and remaining 14 bits were zeroed when setting `ttt`:
```c
(o).value.ttt = (0xfff00000|(((tt)+1)<<14));
```
Currently, remaining 14 bits are preserved. Have also added architecture detection code and an assertion on pointer and type in `mrb_obj_value`.
=> Fixed NaN boxing for 64-bit configrations

mrbgems/mruby-range-ext/mrblib/range.rb, mrbgems/mruby-range-ext/src/range.c, mrbgems/mruby-range-ext/test/range.rb
`Range#first` with argument works like `Enumerable#take`.
`Range#first` shouldn't call `Range#to_a` on infinity range.
```rb
$ mirb
> (0..Float::INFINITY).first(3)
```
So, I reimplemented `Range#first` with Ruby code.
Because it hard to write `break` in iterator on C functions.
And this implementation passed specs of that https://github.com/ruby/spec/blob/66daf290cb49707190481b4cf24e700010cd53bf/core/range/first_spec.rb
(I know that it's a bit too strictly)
=> Reimplements Range#first

include/mruby/re.h
Fixed `extern "C"` to use `MRB_BEGIN/END_DECL` in `re.h`
(although we could also drop it entirely since all the files has is a single `#define`)
=> Fixed C declaration in re.h

mrbgems/mruby-random/src/random.c, mrbgems/mruby-random/test/random.rb
Array#sample can segfault if the array is modified during `mrb_get_args` because the length is determined before the arguments are retrieved
@matz
=> Fix segfault in Array#sample

mrbgems/mruby-sprintf/src/sprintf.c, mrbgems/mruby-sprintf/test/sprintf.rb
This code can cause a segfault currently:
```ruby
class Fixnum
def chr
nil
end
end
"%c" % 0
```
@matz
=> Fix segfault when Fixnum#chr doesn't return a string

mrbgems/mruby-enum-ext/mrblib/enum.rb
```rb
class A
def to_int
3
end
end
(0..10).take(A.new)
```
```rb
class B
include Enumerable
def each
raise "wow"
end
end
B.new.take(0)
```
This fix passed all specs of that https://github.com/ruby/spec/blob/66daf290cb49707190481b4cf24e700010cd53bf/core/enumerable/shared/take.rb
=> Fix Enumeable#take some incompatibility

include/mruby.h, mrbgems/mruby-range-ext/src/range.c, mrbgems/mruby-test/driver.c, test/assert.rb
This is an artifact discovered during #3258.
When single-precision float is used, `1e-12` cannot be used as *epsilon*. New constant for the test driver is introduced.
=> Fixed float tolerance in tests when MRB_USE_FLOAT is set

mrbgems/mruby-struct/src/struct.c, mrbgems/mruby-struct/test/struct.rb
Otherwise this can cause a segfault
=> Remove constant when a struct is redefined.

mrbgems/mruby-compiler/core/codegen.c, test/t/codegen.rb
Reported by https://hackerone.com/jpenalbae
=> Fix segfault caused by empty condition in ternary

mrbgems/mruby-struct/src/struct.c, mrbgems/mruby-struct/test/struct.rb
Otherwise this can lead to an out-of-bounds read and RCE
=> Don't allow array parameter in Struct.new

mrbgems/mruby-enum-ext/mrblib/enum.rb
`Enumerable#first` with argument should be same as `Enumerable#take`
See also https://github.com/mruby/mruby/pull/3271
```rb
class A
include Enumerable
def each
yield 1
end
end
class B
def ==(*)
true
end
end
A.new.first(B.new)
```
This fix passed all specs of that https://github.com/ruby/spec/blob/913edd49cd02424dcb3f2ead76e549d8bb4d92bd/core/enumerable/first_spec.rb
=> Fix incompatibility for Enumerable#first

include/mruby/boxing_nan.h
This is an artifact discovered during #3258.
Previously, a part of the `mrb_value` was left uninitialized with 16-bit integers.
=> Fixed NaN boxing when MRB_INT16 is set

include/mruby/boxing_word.h
This is an artifact discovered during #3258.
32-bit `void*` conflicts with 64-bit `mrb_int`.
=> Safeguard against using MRB_INT64 with MRB_WORD_BOXING in 32-bit mode

mrbgems/mruby-compiler/bintest/mrbc.rb, mrbgems/mruby-compiler/core/parse.y
Otherwise there will be a segfault when it's used in `void_expr_error`
=> Interpret argument in 'f ()' as nil instead of nothing

src/array.c
@matz 
The following code crashes MRuby when built in the default configuration:
```ruby
[0]*300_000_000
```
This happens because the maximum array length is `MRB_INT_MAX-1`, and so an array could require up to `(MRB_INT_MAX-1) * sizeof(mrb_value)` bytes to store. This value can be larger than 32 bits, which overflows `blen`. To fix this problem, I've changed `blen` to a `size_t`. Since `ARY_MAX_SIZE` is no larger than `SIZE_MAX / sizeof(mrb_value)` no overflow can occur after this change.
The second overflow check is unnecessary, so I've removed it.
The bug was reported by Hugh Davenport (https://hackerone.com/haquaman).
=> Use size_t to calculate bytes needed for array.

mrbgems/mruby-enum-lazy/mrblib/lazy.rb, mrbgems/mruby-enum-lazy/test/lazy.rb
When `to_enum` method called by `Enumerable::Lazy` object, It lost information for lazy.
I think It should keep.
```rb
p (0..Float::INFINITY).lazy.to_enum(:each_slice, 2).map { |a| a.first * a.last }.first(4)
```
```sh
$ mruby t.rb
...inifinite loop...
```
```sh
$ ruby t.rb
[0, 6, 20, 42]
```
=> Implement Enumerable::Lazy#to_enum and enum_for

mrbgems/default.gembox, mrbgems/mruby-enum-lazy/mrbgem.rake, mrbgems/mruby-enum-lazy/mrblib/lazy.rb, mrbgems/mruby-enum-lazy/test/lazy.rb
I think that Lazy class should be under Enumerator class instead of Enumerable module.
```rb
$ ruby -e 'p [].lazy.class'
Enumerator::Lazy
```
=> Change Lazy class outer

mrbgems/mruby-enumerator/mrblib/enumerator.rb
Expect behavior.
```sh
$ ruby -e 'p Enumerator::Generator.new{|y| y << 1 << 2 << 3}.map{|i| i * i }'
[1, 4, 9]
```
=> Support Enumerable methods

src/array.c
@matz 
There are a couple other places where an array size calculation can overflow. First, in `ary_modify` where the byte size should be calculated using `size_t` instead of `mrb_int` (much like https://github.com/mruby/mruby/pull/3304). And second, in `ary_concat` where the addition of the two array lengths can overflow.
The following input demonstrates a segfault in `ary_concat`:
```ruby
a = [0]
31.times { a.concat(a) }
```
After this change it exits with `array size too big (ArgumentError)`.
=> Prevent array size calculation overflows.

src/array.c
@matz 
I found a couple more integer overflow issues, this time in `ary_expand_capa` and `mrb_ary_unshift_m`. The first can cause an infinite loop, which can be demonstrated by building MRuby with `MRB_INT16` and executing `puts [0] * 0x6000`. The second allows an `unshift` to exceed the maximum array size.
=> Fix more integer overflows.

src/proc.c, test/t/proc.rb
@matz 
The following code results in a crash:
```ruby
Proc.remove_method(:initialize)
a = Proc.new {}
b = Proc.new {}
a.initialize_copy(b)
```
This patch corrects the problem by checking `a->body.irep` before dereferencing it.
This issue was reported by https://hackerone.com/brakhane.
=> Fix segfault in mrb_proc_copy.

mrbgems/mruby-enumerator/mrblib/enumerator.rb, mrbgems/mruby-enumerator/test/enumerator.rb
```rb
p [1,2,3].each.with_index(nil).to_a
```
```rb
a = []
[1,2,3].each.with_index(10).with_index(20) { |*i| a << i }
p a
```
=> Fix some incompatibility for Enumerator#with_index

src/object.c, test/t/kernel.rb
This is to avoid segfault when WORD_BOXING is enabled
=> Use mrb_ptr instead of mrb_cptr in Kernel#to_s

src/vm.c
Testcase (couldn't get it to work as a test):
```
def nil.b
b *nil
end
nil.b
```
=> Fix stack move segfaulting in OP_ARYCAT

include/mrbconf.h
Detect 64-bit arch. by checking the size of size_t, instead of using a hard-coded list.
=> set `MRB_64BIT` if the sizeof(size_t) is 8

src/string.c
…lt errno macro
Addresses issue https://github.com/mruby/mruby/issues/3326 specifically for platforms that define errno as a macro.
=> Removed the errno declaration from string.c

src/hash.c, test/t/hash.rb
Hash#dup copies default_proc in CRuby:
```
$ ruby -e 'h = Hash.new {|h,k| 123}; p h.dup[0]'       
123
```
So default_proc should also be copied in mruby.
=> Copy default_proc by Hash#dup.

src/gc.c
* fixes partial copy of objects in GC root array (due to missing `* sizeof(mrb_value)`)
* restores the behavior that permitted an unregistered object to be used as an argument
The issues were detected while trying to update the mruby used by H2O in https://github.com/h2o/h2o/pull/1135.
=> fix issues of mrb_gc_unregister introduced in 09b1185

include/mruby/compile.h, mrbgems/mruby-compiler/core/parse.y
Rationale: you would no longer need to parse Ruby scripts twice to catch parse errors.
Fixes #3248
=> Promote load_exec to mruby API as mrb_load_exec (fixes #3248)

src/string.c
const is already used at the top of string.c, so we can guarantee that the compiler supports the const keyword at this position of the code.
This macro also does not work for circumstances where \_\_STDC__ is not defined and your compiler has not definition (the default is to disable the const keyword, this does not sound like intentional behaviour).
=> Removed unnecessary const macro - const keyword is already a dependency

mrbgems/mruby-compiler/core/codegen.c, test/t/codegen.rb
The issue is that when there are more than 126 arguments an array needs
to be created to pass the arguments on with.
Reported by https://hackerone.com/revskills
=> Fix segfault when undef is called with more than 126 arguments

mrbgems/mruby-compiler/core/codegen.c, test/t/codegen.rb
There seemed to be some unused code leftover in `gen_values` that can cause a segmentation fault if gen_values is used with more than 127 arguments in a NOVAL context.
This fixes that issue by removing the unused code
=> Fix segfault in gen_values with NOVAL and more than 127 args

src/gc.c
When a dead TT_FIBER object refers to a dead-and-shared TT_ENV object, both of the two gets collected, since neither of them are marked.
In such case, if the TT_ENV object is freed before the TT_FIBER object, a pointer within the TT_FIBER object referring to the TT_ENV object becomes invalid, which leads to freed memory access or segmentation fault if the page that contained the TT_ENV object was released prior to the destruction of the TT_FIBER object.
=> do not destroy a page with an active TT_ENV

mrbgems/mruby-compiler/core/codegen.c, test/t/codegen.rb
As reported by https://hackerone.com/haquaman
The current code for NODE_NEGATE can cause a register misalignment, as it pushes values onto the stack even when its return value isn't used. This PR fixes it with a short circuit if the result isn't used (which leads to the code being optimized away entirely if the tree is NODE_FLOAT or NODE_INT)
=> Don't generate code for NODE_NEGATE if the result isn't used

mrbgems/mruby-bin-mruby/bintest/mruby.rb, src/gc.c
This fixes an issue where a built-in class can get garbage collected, put onto the freelist, and reused. This can lead to instantiating an object with an MRB_TT that doesn't match its class.
=> Mark all the built-in classes during GC sweep

include/mruby/class.h, include/mruby/object.h, include/mruby/string.h, src/array.c, src/hash.c, src/kernel.c, src/string.c, test/t/array.rb, test/t/hash.rb, test/t/kernel.rb
close https://github.com/mruby/mruby/issues/2028
I want to use `Object#freeze` for Array and Hash to make them read-only. It's convenient to restrict regions in which you can modify a value. It improves maintainability because it makes easier to search where a value is modified.
=> Implement Object#freeze

tasks/mrbgem_spec.rake
Example usage:
MRuby::Gem::Specification.new('mruby-onig-regexp') do |spec|
if spec.search_package('onigmo')
spec.cc.defines += ["HAVE_ONIGMO_H"]
elsif spec.search_package('oniguruma')
spec.cc.defines += ["HAVE_ONIGURUMA_H"]
else
end
end
=> Support pkg-config in mrbgem.rake

src/range.c
@matz 
Without this, the following snippets segfault:
```ruby
[].values_at true
```
```ruby
Struct.new.new.values_at true
```
The issue was reported by https://hackerone.com/dkasak, who also provided the patch.
=> Check type before calling mrb_range_ptr.

src/string.c, test/t/string.rb
@matz
Currently, the following inputs (and others) crash MRuby:
```ruby
'1e-2147483648'.to_f
'1e2147483648'.to_f
```
This happens because `exp` is equal to -2147483648 here:
https://github.com/mruby/mruby/blob/73cc08772f1a11140b238525698bce0664326a50/src/string.c#L2943
Negating `exp` there leaves it as -2147483648 (since 2147483648 = -2147483648 for 32-bit signed integers). This then results in an out-of-bounds read from `powersOf10` a few lines later.
I've tried to solve the problem by limiting `fracExp` and `exp` to reasonable values. (MRI also limits the exponent to 19999.)
This issue was reported by https://hackerone.com/revskills.
=> Fix crash when exponent is -2147483648

mrbgems/mruby-string-ext/mrblib/string.rb, mrbgems/mruby-string-ext/src/string.c
`String#prepend` have unexpected behavior.
```rb
s = "abcdefghijkl"
p s.prepend(s)
#=> "abcdefghijkl\000\000\000\360\002\000\000\000\000\000\000\360"
```
I think it will be able to write more simply.
And fix #3357
=> Rewrite String#prepend with Ruby

tasks/libmruby.rake
There seems to be an unnecessary escape character '\' in libmruby.flags.mak.
I think #800 is the cause.
=> Removed ununnecessary escape character '\' in libmruby.flags.mak

test/assert.rb
I'd like to pass when `assert` block returns a false value because the block may be tested sufficiently by `assert_*`.
If doesn't pass the value, test code will be failed unexpectedly. For example, my mrbgem's test:
```ruby
assert 'K2Hash#open' do
...
db = K2Hash.new(...
assert_true db.empty?
db.close #=> nil
end
```
It fails and the reason isn't told.
```
$ ./minirake test
...
Fail: K2Hash#open (mrbgems: mruby-k2hash)
Skip: Module#prepend super in alias  super does not currently work in aliased methods
Total: 964
OK: 963
KO: 1
Crash: 0
Time: 0.52 seconds
rake aborted!
Command Failed: ["build/host/bin/mrbtest"]
Rakefile:119:in `block (2 levels) in <top (required)>'
```
=> Pass when assert returns a false value

tasks/mrbgem_spec.rake
In case `LDFLAG` contains `-Wl,--as-needed` or `--as-needed` is enabled by default, `-l` flags should appear after objs specifiction.
----
For instance, try building mruby tool includes mattn/mruby-onig-regexp with `LDFLAG="-Wl,--as-needed"`.
=> Put package's libs flag after %{objs}

include/mruby/string.h
Change `RSTR_ENBED_LEN(RSTRING(s))` to `RSTR_EMBED_LEN(RSTRING(s))`.
It's a trap of macro in C.
=> Fix a typo in string.h.

src/error.c
@matz 
Fixes this: https://github.com/mruby/mruby/commit/7523cdf3404230213cb858f38bd91135d478a7f3#commitcomment-20436148
=> Fix broken MRB_INT64

mrbgems/mruby-kernel-ext/src/kernel.c, mrbgems/mruby-kernel-ext/test/kernel.rb
I implemented `Kernel.#caller` in my free time.
I think it useful for debugging.
If you don't agree to add this to mruby/mruby, I'll be able to make another repository as mrbgem.
=> Implement Kernel.#caller

mrbgems/mruby-proc-ext/test/proc.rb, src/proc.c, test/t/proc.rb
CRuby's `Proc` class does't have `initialize` method.
And It raises some issues when it called `Proc.remove_method(:initialize)`
I think, `Proc` class shouldn't have `initialize` method in mruby too.
ref: #3356
=> Proc shouldn't have `initialize` method

src/array.c
It's a small change.
before
```rb
a = [].freeze
a[0] = 1 #=> can't modify frozen array (RuntimeError)
a[:b] = 1 #=> can't convert Symbol into Integer (TypeError)
```
after
```rb
a = [].freeze
a[0] = 1 #=> can't modify frozen array (RuntimeError)
a[:b] = 1 #=> can't modify frozen array (RuntimeError)
```
=> Should raise RuntimeError when object frozen

src/array.c
Referenced to CRuby's array.c(rb_ary_splice)
fix #3405
```rb
ary = Array.new(1024)
ary[0x7ffffc00,1024] = Array.new(1024)
#=> index 2147482624 too big (IndexError)
```
It's also passed https://github.com/mruby/mruby/issues/3354
```rb
ary = Array.new(1023)
ary[0x7ffffc00,0] = Array.new(1024)
#=> index 2147482624 too big (IndexError)
```
And count of fails in mruby-spec doesn't change(5 fails).
I'm not confident about GC... Please review.
=> Rewrite mrb_ary_splice

src/array.c
Fix for https://github.com/mruby/mruby/commit/fdec607cd06bc12c844fd71bdb75db74f909ff74
=> Refactoring: Use array_copy instead of for loop

mrbgems/mruby-random/src/random.c
The following input demonstrates a crash due to a null pointer dereference:
```ruby
$r = Random.new
a = Object.new
def a.to_int
$r.rand
end
$r.initialize a
```
This happens because this line calls `mrb_get_args`, which can execute Ruby code: https://github.com/mruby/mruby/blob/6420951463ec9ace9eecb50923dc6a1925a45d31/mrbgems/mruby-random/src/random.c#L137
This allows `mrb_random_rand` to be called at a time when the object's data pointer is still NULL.
I've fixed that by moving the `get_opt` call to the top of `mrb_random_init`.
This issue was reported by https://hackerone.com/eboda
=> Fetch arguments earlier in mrb_random_init to avoid a crash.

mrbgems/mruby-bin-mruby/bintest/mruby.rb
I found that the mruby-bin's bintest case added at [this commit](https://github.com/mruby/mruby/commit/f7a891fa8979bdb82410e1adc98765013cc29a79) requires `Class(Module)#name`, which is defined at [mruby-class-ext mgem](https://github.com/mruby/mruby/blob/master/mrbgems/mruby-class-ext/src/class.c#L17), not *at core*.
This would not break mruby's upstream test, but breaks bintests of binary tools(such as mruby-cli ones) which create a `mruby` binary additionally.
ref: https://github.com/mruby/mruby/commit/f7a891fa8979bdb82410e1adc98765013cc29a79#diff-1d3b69d05e6068fdd48537dda6e5cb62R55
=> Fix usage of Class#name in mruby-bin-mruby's bintest

src/kernel.c, test/t/kernel.rb
```rb
a = 1
Proc.new { |a| Kernel.local_variables }.call(2)
```
=> Kernel#local_variables: Make result array unique

src/string.c
The following example produces an incorrect output:
```ruby
$s = "Test \#{x}"
puts $s.inspect
```
This outputs `"Test #{x}"`, whereas the correct output would be `"Test \#{x}"`.
The problem is that the parameter for `IS_EVSTR` is off by one, since `*p` is the current character (i.e. `c`), not the next one.
=> Fix interpolation escaping in String.inspect

mrbgems/mruby-string-ext/mrblib/string.rb, mrbgems/mruby-string-ext/src/string.c, mrbgems/mruby-string-ext/test/string.rb
- `String#ljust` and `String#rjust` are now C functions to improve performance
- infinite loop because of an empty padding argument is now prevented (`ArgumentError` is raised)
- extra tests for `ljust`/`rjust` added
Fixes #3445.
Before (d0ecf862d9d2e7aed461bc9360686449f56c5d25):
$ echo '"".ljust(10000000);"".rjust(10000000)' | time bin/mruby
8.26 real         8.16 user         0.05 sys
After (981105b3e6758455646e9834b1c2695bf774a401):
$ echo '"".ljust(10000000);"".rjust(10000000)' | time bin/mruby
0.22 real         0.20 user         0.01 sys
=> String#ljust and String#rjust reimplementation (fix #3445)

minirake
Referenced https://github.com/ruby/rake/blob/af15762f972a3f8322a9b5904d56fe2ff3dd8352/lib/rake/file_task.rb#L21
Rakefile
```
file "a.txt" do
system "echo hello > a.txt"
end
file "b.txt" => "a.txt" do
system "cp a.txt b.txt"
end
task :default => "b.txt"
```
```
$ touch b.txt
$ ruby minirake --trace
Invoke default (already=[], needed=[true])
rake aborted!
No such file or directory @ rb_file_s_stat - a.txt
minirake:241:in `stat'
minirake:241:in `timestamp'
minirake:233:in `block in needed?'
minirake:233:in `collect'
minirake:233:in `needed?'
minirake:91:in `invoke'
minirake:95:in `block in invoke'
minirake:95:in `each'
minirake:95:in `invoke'
minirake:467:in `block in run'
minirake:466:in `each'
minirake:466:in `run'
minirake:484:in `<main>'
```
```
$ rake --trace
** Invoke default …
```
=> Fix build error when trace mode

mrbgems/mruby-string-ext/mrblib/string.rb, mrbgems/mruby-string-ext/src/string.c, mrbgems/mruby-string-ext/test/string.rb, src/string.c
Unfortunately, #3447 breaks `ljust`/`rjust` for UTF-8 strings.
I've tried fixing this in C, but managing UTF-8 strings in C is quite error-prone. So, I've tried to re-implement them again in Ruby, but in a more optimized way.
I've also added a small optimization to `String#*`.
Without `MRB_UTF8_STRING`:
$ echo '"".ljust(10000000);"".rjust(10000000)' | time bin/mruby
0.04 real         0.02 user         0.01 sys
With `MRB_UTF8_STRING`:
$ echo '"".ljust(10000000);"".rjust(10000000)' | time bin/mruby
0.51 real         0.48 user         0.02 sys
Also, #3448 was discovered while working on this fix.
=> String#ljust and String#rjust reimplemented with optimized Ruby

src/string.c
This reverts commit d1bc7caecaf337976351934d5910726106601bd9.
I've compared both versions and it seems that this optimization is unnecessary, so I'm reverting it to simplify the code. It was also mistakenly checking for `len`, where in fact it should check `n` (and later repeat the same char `len` times).
=> Revert "Optimization for String#* for 1-byte strings"

tasks/mrbgem_spec.rake
Fixes #3418.
I've tried to make the fix as small as possible.
Previously we had 2 places where compilers were configured (`Specification#setup` –  config options – and `List#check` – include paths).
That caused a problem when someone tries to use gem table only to build the dependencies (as in #3418) and does not want to define compilers rules.
From the other hand, we already configure compilers in `List#check` method, so, I think, it make sense to define rules there too.
=> Separate compilers setup from config setup

examples/targets/build_config_android_arm64-v8a.rb, examples/targets/build_config_android_armeabi.rb, tasks/toolchains/android.rake
This PR updates build script for Android.
In usual case, required LDFLAGS and CFLAGS should be set by default.
If anyone need overwriting these flags, it can be done in `build_config.rb`.
I think, for many mruby users/developers, no requiring many flags to build mruby is good.
NOTE:
- Please use Android NDK `r12b` or later (recommended is latest `r13b`)
- When use Android NDK `r11c`, cannot build mruby by gcc for mips64 (by clang is okay)
- Security flags (e.g. `-Wa,--noexecstack`) is omitted (please set in your `build_config.rb` if needed).
=> Update android build script.

include/mruby/numeric.h
Clang 3.8 and 3.9 have problem compiling mruby in 32-bit mode, when `MRB_INT64` is set because of missing `__mulodi4` and similar functions in its runtime. We need to use custom checked arithmetic implementation for them.
=> Build fix for 32-bit clang 3.8/3.9 with MRB_INT64

examples/targets/build_config_android_armeabi_v7a_neon_hard.rb, tasks/toolchains/android.rake
As discussed in the comments for PR https://github.com/mruby/mruby/pull/3455#issuecomment-280048567
This adds support for the supplied Android build script to configure the hardware floating point for armeabi-v7a.
````ruby
MRuby::CrossBuild.new('android-armeabi-v7a-neon-hard') do |conf|
params = { 
:arch => 'armeabi-v7a', 
:mfpu => 'neon',
:mfloat_abi => 'hard',
}
toolchain :android, params
conf.gembox 'default'
end
````
This also adds a new example build script demonstrating this usage.
=> Additional options for Android build script.

mrbgems/mruby-bin-mruby/bintest/mruby.rb, mrbgems/mruby-compiler/core/parse.y
With this small change, parse.y can be compiled with yacc on NetBSD6.  Yacc uses a variable named "yylval" in generated code and it conflicts with the macro this patch renames.
=> Build with byacc

.gitlab-ci.yml, Rakefile, tasks/gitlab.rake
Previously I've proposed #3258 as a method to test mruby on different build configurations (and found many bugs with rarely used combinations). However that method vastly increased Travis build times which is unfortunate. I was thinking about a way to enforce compatibility without such side-effect. Lately I was experimenting with GitLab CI and found it to be an excellent candidate for such testing.
I've created a mirror of the official mruby repository, which is automatically updated every 24h:
https://gitlab.com/dabroz/mruby
This patch introduces Gitlab testing, using GitLab CI, to test many different configurations:
- 32/64 bit architecture
- float/double
- 16/32/64 bit int size
- none/NaN/word boxing
- ASCII/UTF8
using various compilers:
- gcc-4.7
- gcc-4.8
- gcc-4.9
- gcc-5
- gcc-6
- …
=> GitLab.com tests for multiple configurations

src/string.c, test/t/string.rb
```
$ cat t.rb
p "".index ""
p "hello".index("", 5)
```
```
$ mruby t.rb
nil
nil
```
```
$ ruby -v t.rb
ruby 2.5.0dev (2017-01-12 trunk 57313) [x86_64-darwin16]
0
5
```
```
=> String#index shouldn't return nil when "".index ""

mrblib/string.rb, test/t/string.rb
`String#gsub` supports only string pattern argument.
Corresponding captures never used in this case.
=> \1 sequences as empty strings

mrblib/string.rb, test/t/string.rb
`String#gsub` have an infinite loop pattern.
```rb
"hello".gsub("", ".")
```
I rewrote `String#gsub` in case of args.length == 2.
=> Avoid infinity loop when empty string pattern

mrbgems/mruby-sprintf/src/sprintf.c, mrbgems/mruby-sprintf/test/sprintf.rb
Get rid of out-of-bound access when single % at the end.
The latter test case doesn't fail with cruby, because shared sub-strings are not allowed in the middle, right now.
=> Fix out-of-bound access

mrblib/string.rb, test/t/string.rb
- Use duplicated object for block args
- Suuport custom separator
- Support to return enumerator when no block given
=> Some update for `String#each_line`

minirake
```rb
$ cat t.rake
require 'fileutils'
file "a.txt" do |t|
p t.name
FileUtils.touch(t.name)
end
task "b.txt" => "a.txt" do |t|
p t.name
FileUtils.touch(t.name)
end
file "c.txt" => "b.txt" do |t|
p t.name
FileUtils.touch(t.name)
end
```
```
$ rm -f {a,b,c}.txt
$ rake c.txt -f t.rake
"a.txt"
"b.txt"
"c.txt"
$ rake c.txt -f t.rake
"b.txt"
"c.txt"
$ rake c.txt -f t.rake
"b.txt"
"c.txt"
$ ./minirake c.txt -f t.rake
(in /Users/ksss/src/github.com/ksss/mruby)
"b.txt"
$ touch b.txt
$ ./minirake c.txt -f t.rake
(in /Users/ksss/src/github.com/ksss/mruby)
"b.txt"
$ rake c.txt -f t.rake
"b.txt"
"c.txt"
```
I think, minirake should call "c.txt" file task block
=> MiniRake::Task#timestamp should use Time.now only

mrbgems/mruby-sprintf/src/sprintf.c
```
$ cat t.rb
o=Object.new
def o.to_int
1
end
p "%*d" % [o, 1]
```
```
$ ruby t.rb
"1"
$ mruby t.rb
```
The cause is that `mrb_fixnum` calls with any object(e.g. MRB_TT_OBJECT).
=> sprintf: Should use mrb_int for any object

mrblib/string.rb, test/t/string.rb
This PR has 2 points for `String#gsub` and `String#gsub!`
- Support to return Enumerator for String#gsub,gsub!
- Callback should yield with pattern every time
=> Update String#gsub and String#gsub!

mrblib/string.rb, test/t/string.rb
```rb
"abc".sub("", ".")
#Expect => ".abc"
#Actual => "a.bc"
"abc".sub(""){ "." }
#Expect => ".abc"
#Actual => "a.bc"
```
=> Fix result if pattern is empty

mrbgems/mruby-kernel-ext/test/kernel.rb, src/backtrace.c
`Kernel#caller` result lost lineno from https://github.com/mruby/mruby/commit/dcf6a413cab097e39d2d883d7c8c297d29ea43b8 .
Maybe, @matz forgot to fix it.
=> Fix lost lineno

src/hash.c
=> Renumber hash keys during dup since there may be duplicates.

mrbgems/mruby-time/src/time.c, src/numeric.c, test/t/float.rb
I'm concerned about this use case.
```c
mrb_value v = mrb_funcall(mrb, num, "to_i", 0)
mrb_int i = mrb_fixnum(v);
if (i == 0) {
// ...
```
example: https://github.com/iij/mruby-pack/blob/88a7fedea413568a1ff0410e109ff55a03b63a5f/src/pack.c#L1022
If `num` is `Float::INFINITY`, then `i` is `0`.
But I think, It's not expected value.
This behavior is compatible with CRuby.
```
$ ruby -e 'Float::INFINITY.to_i'
from -e:1:in `<main>'
-e:1:in `to_i': Infinity (FloatDomainError)
```
=> Should raise FloatDomainError

mrbgems/mruby-enumerator/mrblib/enumerator.rb, mrbgems/mruby-enumerator/test/enumerator.rb
In previous version,
```
a = [3, 2, 1]
e = a.each
e.sort_by(&:to_i) # => []
```
In this version,
```
a = [3, 2, 1]
e = a.each
e.sort_by(&:to_i) # => [1, 2, 3]
```
=> Fix Enumerator#each_with_index with block

mrbgems/mruby-proc-ext/src/proc.c, mrbgems/mruby-proc-ext/test/proc.rb
```rb
p lambda { |*| }.parameters
```
=> Fix parameters when noname rest

appveyor.yml
A too small depth size will fail ```git checkout``` in the old AppVeyor's CI Queue.
This commit change the depth size from 1 to 50(Travis CI's default).
=> Change AppVeyor's clone_depth

mrbgems/mruby-time/src/time.c
@matz The fix for https://github.com/mruby/mruby/issues/3561 produces incorrect results when `usec` is a large negative value:
```
> Time.at(0, -1e16)
=> Fri Mar 23 07:26:39 1336
```
The correct value (as reported by CRuby) is:
```
irb(main):001:0> Time.at(0, -1e16)
=> 1653-02-10 01:13:20 -0500
```
The reason for this is that floating point inaccuracy can leave `tm->usec` with a value that is larger than 1000000 after the first `if` statement, which causes the second `if` statement to execute as well. To solve this problem, I've added an `else` so that only one of the cases can execute. This produces the correct result:
```
> Time.at(0, -1e16)
=> Mon Feb 10 01:13:19 1653
```
=> Correctly handle large negative usec value.

src/vm.c
it allow compiler modify stack size with `-D` option, for debugging purpose mainly.
=> Attach a name to  embbeded value of rescue/ensure stack size

mrbgems/mruby-bin-mirb/tools/mirb/mirb.c
If MRuby is built without libreadline, then a buffer overflow occurs in mirb when a line 1023 characters or longer is read:
```
$ ruby -e 'puts "0"*1023' | bin/mirb
> Segmentation fault (core dumped)
```
This happens because mirb reads into a 1024-byte buffer, but doesn't leave enough space for the `\n` and `\0` that will be appended to the input. This PR fixes the off-by one.
This issue was reported by https://hackerone.com/geeknik
=> Fix an off-by-one causing a buffer overflow in mirb.

src/kernel.c
The following input demonstrates a null pointer dereference:
```ruby
class X < Module
def initialize
end
end
X.new.clone
```
ASAN report:
```
==27567==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000105e43143 bp 0x7fff59ddab50 sp 0x7fff59ddaa80 T0)
==27567==The signal is caused by a READ memory access.
==27567==Hint: address points to the zero page.
#0 0x105e43142 in kh_copy_mt class.c:19
#1 0x105ed2315 in copy_class kernel.c:244
#2 0x105ebf207 in init_copy kernel.c:255
#3 0x105ebd840 in mrb_obj_clone kernel.c:315
#4 0x105f8c618 in mrb_vm_exec vm.c:1279
#5 0x105f8179f in mrb_vm_run vm.c:829
#6 0x105fb48b9 in mrb_top_run vm.c:2674
#7 0x106085ba5 in mrb_load_exec parse.y:5780
#8 0x1060864f5 in mrb_load_file_cxt parse.y:5789
#9 0x105e1d9e6 in main mruby.c:227
#10 …
```
=> Check if sc->mt is initialized before copying it.

src/class.c
BTW, isn't `arg_i` and `i` always same in `mrb_get_args`?
I don't want two same variables if those are always same.
=> Add missing `arg_i++` to fix bug of `s!` in mrb_get_args.

src/pool.c
To avoid warnings from undefined behavior sanitizer.
( https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html )
=> Align pool allocator with 8 byte in 64-bit environment.

mrbgems/mruby-bin-mruby-config/mrbgem.rake, mrbgems/mruby-bin-mruby-config/mruby-config, mrbgems/mruby-bin-mruby-config/mruby-config.bat, tasks/libmruby.rake
It makes possible to add dependency to libmruby	to my app's Makefile as	below:
```
LIBMRUBY_PATH=`mruby-config --libmruby-path`
myapp : $(OBJS) $(LIBMRUBY_PATH)
```
=> Add --libmruby-path support to mruby-bin-mruby-config.

mrbgems/mruby-compiler/bintest/mrbc.rb, mrbgems/mruby-compiler/core/parse.y
`skips()` is `mrb_bool` function, should return `FALSE` at EOF, not `EOF`.
=> Fix embedded document with unterminated terminator

src/vm.c
This reverts commit a1d32af91692c2b624e9c04fcd94aa958dbba626.
I am unsure about specifics of this change, but it seems to break building 32-bit version of mruby on my OSX setup:
```
Process 46763 launched: './mruby/build/test-32bit/bin/mrbtest' (i386)
mrbtest - Embeddable Ruby Test
Process 46763 stopped
* thread #1: tid = 0xeb10d8, 0x00056500 mrbtest`mrb_class(mrb=0x01900000, v=mrb_value @ 0xbfffe9d4) + 192 at class.h:50, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x4)
frame #0: 0x00056500 mrbtest`mrb_class(mrb=0x01900000, v=mrb_value @ 0xbfffe9d4) + 192 at class.h:50
47  	  case MRB_TT_ENV:
48  	    return NULL;
49  	  default:
-> 50  	    return mrb_obj_ptr(v)->c;
51  	  }
52  	}
53  	
(lldb) bt
* thread #1: tid = 0xeb10d8, 0x00056500 …
```
=> Restore 32-bit OSX builds

include/mruby/value.h
This adds macOS support to mrb_ro_data_p, fixes #3636.
=> Add macOS support to mrb_ro_data_p

mrbgems/mruby-sprintf/src/sprintf.c, mrbgems/mruby-sprintf/test/sprintf.rb
Fix #3648
ruby/spec results
[spec/core/string/modulo_spec.rb](https://github.com/ruby/spec/blob/562cc9a0a8b9d2782474a5bd75c619d6cd285a32/core/string/modulo_spec.rb)
before:
Clash on https://github.com/ruby/spec/blob/562cc9a0a8b9d2782474a5bd75c619d6cd285a32/core/string/modulo_spec.rb#L306
after:
1 file, 111 examples, 466 expectations, 37 failures, 16 errors, 0 tagged (It was able to run to the end!)
ref: https://github.com/ruby/ruby/blob/15196f4c6df6859f825cd16c90d8c27fdcf2400b/sprintf.c#L1018-L1027
=> Fix segmentation fault ref: #3648

mrbgems/mruby-compiler/core/codegen.c
@matz 
Fixes #3642 as suggested by https://hackerone.com/avisaven in https://github.com/mruby/mruby/issues/3642#issuecomment-300277550
=> Change return back to break in the default case.

src/string.c
=> Make string embad from shared

src/backtrace.c
Calling `mrb_format(mrb, "%S:%S", str, mrb_fixnum_value(loc->lineno))` with a fixnum results in the vm calling `to_s` to convert the fixnum to a string. This produces a bug where [mrb_callinfo](https://github.com/mruby/mruby/blob/master/src/backtrace.c#L113) changes during retrieval of backtrace.
To fix this, the fixnum can be converted to a string before being passed to `mrb_format`.
=> Avoid call to_s during backtrace traversal

mrbgems/mruby-string-ext/mrbgem.rake, mrbgems/mruby-string-ext/mrblib/string.rb, mrbgems/mruby-string-ext/src/string.c, mrbgems/mruby-string-ext/test/string.rb
The documented code didn't working as expected.
```rb
"9".upto("11").to_a   #=> []
"25".upto("5").to_a   #=> ["25"]
"07".upto("11").to_a  #=> ["07", "08", "09", "10", "11"]
```
I've fixed like this.
```rb
"9".upto("11").to_a   #=> ["9", "10", "11"]
"25".upto("5").to_a   #=> []
"07".upto("11").to_a  #=> ["07", "08", "09", "10", "11"]
```
The ruby/spec for `String#upto` passed all without `Enumerator#size` (using by [mruby-spec](https://github.com/ksss/mruby-spec))
https://github.com/ruby/spec/blob/97fe8c7cfd7a7e4833ae2edab4df21e3ea6bc093/core/string/upto_spec.rb
before
```
$ make TESTS=spec/core/string/upto
...
mruby 1.2.0 (2015-11-17)
1)
String#upto doesn't call block with self even if self is less than stop but stop length is less than self length FAILED
Expected ["25"] to equal [] …
```
=> Reimplement String#upto

src/array.c, test/t/array.rb
before ( ce6c05600af11f540302145ff4b6988a5a37518a )
```
$ time ./build/host/bin/mruby benchmark/bm_so_lists.rb
./build/host/bin/mruby benchmark/bm_so_lists.rb  52.75s user 0.75s system 97% cpu 54.662 total
```
after
```
$ time ./build/host/bin/mruby benchmark/bm_so_lists.rb
./build/host/bin/mruby benchmark/bm_so_lists.rb  8.52s user 0.18s system 99% cpu 8.733 total
```
=> Should only check frozen fix #3737

test/assert.rb
The `msg` outside the block was not modified since it was shadowed by `msg` inside the block.
=> fixed printing failed assertions

mrbgems/mruby-class-ext/test/module.rb, src/class.c, test/t/module.rb
Placing a module inside a namespace with `Module#const_set` was not factored in when calling `Module#to_s`:
```ruby
module Namespace
const_set :Mod, Module.new
end
Namespace::Mod.to_s # => "#<Module:0x155cdf0>
```
This patch fixes it, so that:
```ruby
Namespace::Mod.to_s # => "Namespace::Mod"
```
=> Fixed Module#to_s and #name for #const_set modules

tasks/mrbgem_spec.rake
Currently, the root folder containing the ruby files of a gem to compile (mrblib/) cannot be customized. The gemspec offers methods like `mrblib_dir=` and `rbfiles=`, but that's of little value: The gemspec is evaluated in [mrbgem_spec.rake#L84](https://github.com/mruby/mruby/blob/aa3cb0466e39d8a0f548f569461efec1ca07bb6b/tasks/mrbgem_spec.rake#L84) but the file list using `mrblib_dir` is already compiled in [mrbgem_spec.rake#L61](https://github.com/mruby/mruby/blob/aa3cb0466e39d8a0f548f569461efec1ca07bb6b/tasks/mrbgem_spec.rake#L61). Also, the file list is already used in [mrbgem_spec.rake#L66](https://github.com/mruby/mruby/blob/aa3cb0466e39d8a0f548f569461efec1ca07bb6b/tasks/mrbgem_spec.rake#L66).
To be able to at least set the files with `rbfiles=`, lines 66 and 67 have to happen after …
=> Fixed setting custom rbfiles in gemspec

mrblib/00class.rb, test/t/module.rb
Module#include and #prepend returned the list of included modules instead of the module instance.
=> Fixed return value of Module#include and #prepend

mrbgems/mruby-array-ext/mrblib/array.rb, mrbgems/mruby-enumerator/mrblib/enumerator.rb, mrbgems/mruby-hash-ext/mrblib/hash.rb, mrblib/array.rb, mrblib/hash.rb, mrblib/numeric.rb, mrblib/range.rb
Replaced `yield if block_given?` with `block.call if block` because the latter is ~20% faster than the former:
```
$ time build/bench/bin/mruby -e '
def m
yield if block_given?
end
i = 10_000_000
while i > 0; m{}; i -= 1 end'
real    0m1.899s
user    0m1.899s
sys     0m0.000s
```
```
$ time build/bench/bin/mruby -e '
def m(&b)
b.call if b
end
i = 10_000_000
while i > 0; m{}; i -= 1 end'
real    0m1.511s
user    0m1.510s
sys     0m0.001s
=> Improved speed of enumeration methods

src/hash.c
This patch cuts the time to create new hashes almost in half:
Before:
```
$ time build/bench/bin/mruby -e "
i = 10_000_000
while i > 0
h = {}
i -= 1
end"
real    0m2.136s
user    0m2.123s
sys     0m0.007s
$ time build/bench/bin/mruby -e "
i = 10_000_000
while i > 0
h = {a:1, b:2, c:3, d:4}
i -= 1
end"
real    0m4.248s
user    0m4.248s
sys     0m0.000s
```
After:
```
$ time build/bench/bin/mruby -e "
i = 10_000_000
while i > 0
h = {}
i -= 1
end"
real    0m1.377s
user    0m1.374s
sys     0m0.003s
$ time build/bench/bin/mruby -e "
i = 10_000_000
while i > 0
h = {a:1, b:2, c:3, d:4}
i -= 1
end"
real    0m2.272s
user    0m2.261s
sys     0m0.003s
```
=> Improved speed of creating new hash tables

mrbgems/mruby-hash-ext/mrblib/hash.rb, mrbgems/mruby-hash-ext/test/hash.rb
I was implement `Hash#compact` and `Hash#compact!` to mruby-hash-ext.
I saw this document and code.
* http://ruby-doc.org/core-2.4.1/Hash.html#method-i-compact
* https://github.com/mruby/mruby/blob/f9c3ebd29d7410be209b3f22b9923f0f81f0141d/mrbgems/mruby-array-ext/mrblib/array.rb#L218-L251
and exec below code.
```
$ irb -v
irb 0.9.6(09/06/30)
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
$ irb
irb(main):001:0> {:a => true, :b => nil}.compact!
=> {:a=>true}
irb(main):002:0> {:a => true}.compact!
=> nil
```
CRuby document says.
Array http://ruby-doc.org/core-2.4.1/Array.html#method-i-compact
> compact! → ary or nil
> Removes nil elements from the array.
> 
> Returns nil if no changes were made, otherwise returns the array.
Hash …
=> add method(compact, compact!) and test of Hash to mruby-hash-ext

src/vm.c
One additional thing: While going through the code I was wondering if sections:
https://github.com/mruby/mruby/blob/8bf492f12707777c321dcf40494f757947649f62/src/vm.c#L1366-L1369
and 
https://github.com/mruby/mruby/blob/8bf492f12707777c321dcf40494f757947649f62/src/vm.c#L1560-L1563
are needed or could be removed.
In both cases the stack should have room for the block. Actually, the stack was just accessed at the block's offset a few lines earlier. Removing those lines does not break any tests.
=> Some more vm refactorings

include/mruby/array.h, src/array.c
This patch makes reduce code size (about 2048bytes in 32bit Cygwin) and a little speed up (about 1% in best benchmark test).
=> Improve Array structure

mrbgems/mruby-hash-ext/src/hash-ext.c
The new C version of `Hash#compact!` (introduced in 6c61a60609e973f3dec00e86ca6f1519ae83e1e3) does not check whether the internal khash is initialized before operating on it. As a result, code such as the following causes a null pointer dereference:
```ruby
class X < Hash
def initialize
end 
end
X.new.compact!
```
I've fixed the issue by adding a null check.
This issue was reported by Dinko Galetic & Denis Kasak (https://hackerone.com/dgaletic).
=> Check whether internal khash is initialized in Hash#compact!

src/fmt_fp.c
Fixes:
```
C:\projects\mruby\src\fmt_fp.c(123) : warning C4244: 'return' : conversion from 'ptrdiff_t' to 'int', possible loss of data
C:\projects\mruby\src\fmt_fp.c(178) : warning C4244: 'return' : conversion from 'ptrdiff_t' to 'int', possible loss of data
C:\projects\mruby\src\fmt_fp.c(206) : warning C4244: 'initializing' : conversion from 'ptrdiff_t' to 'int', possible loss of data
C:\projects\mruby\src\fmt_fp.c(220) : warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
C:\projects\mruby\src\fmt_fp.c(224) : warning C4244: '=' : conversion from 'ptrdiff_t' to 'int', possible loss of data
C:\projects\mruby\src\fmt_fp.c(251) : warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
C:\projects\mruby\src\fmt_fp.c(329) : warning C4244: …
```
=> Fix MSVC warnings in fmt_fp.c

mrbgems/mruby-sprintf/test/sprintf.rb
Fixed test:
```
$ CFLAGS='-DMRB_INT16=1' rake test
[...]
ArgumentError: String#% %d => number (100000) too big for integer (mrbgems: mruby-sprintf)
Skip: Struct.new removes existing constant  redefining Struct with same name cause warnings
Skip: Module#prepend super in alias  super does not currently work in aliased methods
Total: 970
OK: 969
KO: 0
Crash: 1
Time: 0.27 seconds
rake aborted!
Command failed with status (1): ["build/test/bin/mrbtest"...]
[...]
```
=> Fix string test with 16-bit integers

include/mruby.h
Fixes:
```
/builds/dabroz/mruby/mrbgems/mruby-range-ext/src/range.c:142:71: error: use of undeclared identifier 'FLT_EPSILON'
mrb_float err = (fabs(beg_f) + fabs(end_f) + fabs(end_f-beg_f)) * MRB_FLOAT_EPSILON;
^
/builds/dabroz/mruby/include/mruby.h:76:27: note: expanded from macro 'MRB_FLOAT_EPSILON'
#define MRB_FLOAT_EPSILON FLT_EPSILON
^
1 error generated.
```
=> Fix building with MRB_USE_FLOAT=1

test/assert.rb, test/t/module.rb
`assert_nothing_raised` didn't check the given exceptions anyway.
=> Refactored #assert_raise and #assert_nothing_raised

src/numeric.c
Hi all,
I'm running some C code analysis tool that pointed me to this small code fragment. I'm suggesting this patch to try to make the source code more understandable by removing mixing of ternary if statements with attributions.
Would you guys agree with this type of changes? The tools pointed me to almost 20 cases like this one in the source code of mruby.
=> Trying to make the code more readable

mrbgems/mruby-compiler/core/parse.y
While running mruby with address sanitizer, it detected a small error in parse.y where some bytes are copied from an unallocated area. This practically causes no harm because the location is immediately rewritten with correct data, but I had to correct it in order to continue with my debugging.
You may want to fix it in the official repo.
=> Correct a small error in parse.y

include/mruby.h, src/class.c
also add `mrb_vm_get_argc` and `mrb_get_argv`
Fixes #3825
It doesn't look like the original version of `mrb_get_argc` was used anywhere in mruby.
=> correctly handle *splat arguments in mrb_get_argc

appveyor.yml, appveyor_config.rb
Current appveyor.yml uses PATH to add Cygwin's bin directory for using bison. If Cygwin's ruby overrides AppVeyor's default Ruby, It might be bad for bintest of mruby.
=> Appveyor Improvements

src/backtrace.c, src/error.c
When an exception is not caught by rescue cluases of the current block, mruby re-throw it using `OP_RAISE`.  But`OP_RAISE` overwrites backtrace information of the exception unconditionally so a part of backtrace information is stripped away.
```rb
% cat a.rb
def fun
begin
xyzzy
rescue NoMemoryError
end
end
fun
```
```
% bin/mruby a.rb
trace:
[0] a.rb:8
a.rb:8: undefined method 'xyzzy' for main (NoMethodError)
```
The backtrace output above does not point to the location where an exception was originally thrown, but _the caller_ of the procedure.  With this patch, mruby points to the correct location.
```
% bin/mruby a.rb
trace:
[0] a.rb:8
[1] a.rb:3:in fun
a.rb:3: undefined method 'xyzzy' for main (NoMethodError)
```
=> don't strip away backtrace info when an exception is re-thrown

src/variable.c
It seems that checking `base` does not make sense, because:
1. It looks like all calls of `const_get` implicitly guarantee that `base` is not null.
2. Neither `mrb_obj_value` nor `mrb_funcall_argv` does not seem to support null as an argument, so a segfault will occur anyway.
=> Removed useless condition

mrbgems/mruby-socket/test/sockettest.c
I know it's only used in tests but just to avoid noise.
=> Fix memory leak found by leak sanitizer.

test/assert.rb
We can see gem name in skip message by this fix
=> Use same format between Fail and Skip

mrbgems/mruby-io/test/file.rb
When MSVC, "File.readlink fails with non-symlink" test was failed even if raising NotImplementedError
=> Skip "File.readlink fails" test on MSVC

mrbgems/mruby-socket/test/addrinfo.rb
Skiped below tests on Windows platform.
- Addrinfo.unix
- Addrinfo#afamily
=> Skip tests on Windows platform

mrbgems/mruby-bin-debugger/tools/mrdb/apibreak.c, mrbgems/mruby-bin-debugger/tools/mrdb/apilist.c, mrbgems/mruby-bin-debugger/tools/mrdb/cmdmisc.c, mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c, mrbgems/mruby-compiler/core/lex.def, src/string.c
Changes applied:
- Removing "register" keyword
- Fixing const pointer to pointer assignments
- Adding type casts to rb_malloc calls
=> Make source compilable with C++17

mrbgems/mruby-time/src/time.c, mrbgems/mruby-time/test/time.rb
Test env: gcc 4.8.5 (Linux)
Current mruby specific timegm() at mrbgems/mruby-time/src/time.c cannot returns minus value.
I tested with following Ruby code and result is following:
```
assert('Time.new with Dec 31 23:59:59 1969 raise ArgumentError') do
assert_raise(ArgumentError) {Time.new(1969, 12, 31, 23, 59, 59)} # Passed
end
assert('Time.gm with Dec 31 23:59:59 1969 raise ArgumentError') do
assert_raise(ArgumentError) {Time.gm(1969, 12, 31, 23, 59, 59)} # Failed
end
```
I still cannot understand why ArgumentError is raised at Dec 31 23:59:59 1969,
but if Time.gm is called with older than 1970, returns unix time "31535999" internally
and behave differently with Time.new.
I changed timegm() can returns minus value when older than 1970 is input with TIme.new and TIme.gm.
Test code details …
=> mruby-time: Fix mruby specific timegm() cannot return minus

mrbgems/mruby-io/src/io.c, mrbgems/mruby-io/test/io.rb
`close_on_exec` flag of duplicated object should be true.
And I think, It is not need that close fd when failed.
Because `fd` and `fd2` will close by GC on `fptr_finalize`.
=> Should be true for close_on_exec flag

mrbgems/mruby-socket/mrbgem.rake
`spec.add_dependency` search mruby-io and mruby-pack on mgem-list by other third-party mrbgems.
=> Depend mruby-io and mruby-pack in mruby core

tasks/toolchains/visualcpp.rake
The code does not work with internationalized versions of Visual Studio. 
It will capture the returned string in the local codepage encoding and make ruby exit
with an invalid UTF8 error message.
Also the word "Version" might be translated and not appear in the output.
=> Uncommented the Visual Studio version check 

mrbgems/mruby-test/init_mrbtest.c, mrbgems/mruby-test/mrbgem.rake
Since in leak sanitizer all the memories allocated by `mrb_state` gets reported as leaked memories.
=> Close `mrb_state` before error exit.

include/mruby.h, src/class.c
I added feature to ``mrb_get_args()`` function for forced block argument.
By giving two consecutive ``&``, exception is raised if block is not given.
```c
/* raise exception if no block given */
mrb_get_args(mrb, "&&", &block);
```
I tried to labor saving in the processing that required block. How is it?
=> Give me block by mrb_get_args() (forced block arguments)

mrbgems/mruby-io/mrblib/io.rb
Since `IO.read filename, mode: 'rb'` won't work in windows .
=> Pass same mode parameter to `IO.sysopen` and `IO.open` in `IO.read`.

src/array.c
Since it causes assertion failure in mruby-capacity.
In embedded array it checks the embedded array capacity and cause assertion failure before expanding capacity.
https://103.128.221.202.static.iijgio.jp/jenkins/view/0-master-mrbgem/job/master-mruby-capacity/1/console
=> Set array length after expanding capacity.

src/string.c, test/t/string.rb
Since it raised `TypeError` from 1.3: https://wandbox.org/permlink/mQ6E4k3GNATbBZ31
=> Return nil if type differ in `String#<=>`.

mrbgems/mruby-enum-ext/mrblib/enum.rb, mrbgems/mruby-enum-ext/test/enum.rb
- Support block yielding for `Enumerable#zip`
- Argument should raise TypeError instead of NoMethodError
=> Support block yielding for Enumerable#zip

mrbgems/mruby-enumerator/mrblib/enumerator.rb, mrbgems/mruby-enumerator/test/enumerator.rb
for fix some specs
- [passes each element of the result array to a block and return nil if a block is given](https://github.com/ruby/spec/blob/a585ec35d185435e5c11f371ba4ed2a29d8817bd/core/enumerable/zip_spec.rb#L11-L17)
- [converts arguments to arrays using #to_ary](https://github.com/ruby/spec/blob/a585ec35d185435e5c11f371ba4ed2a29d8817bd/core/enumerable/zip_spec.rb#L23-L27)
- [converts arguments to enums using #to_enum](https://github.com/ruby/spec/blob/a585ec35d185435e5c11f371ba4ed2a29d8817bd/core/enumerable/zip_spec.rb#L29-L34)
- [gathers whole arrays as elements when each yields multiple](https://github.com/ruby/spec/blob/a585ec35d185435e5c11f371ba4ed2a29d8817bd/core/enumerable/zip_spec.rb#L36-L39)
=> Reimplement `Enumerable#zip` with Enumerator

src/vm.c
Since `mrb_exec_irep` doesn't overwrite `ci->env` it may causes use after free error with `MRB_GC_STRESS`, address sanitizer, [iij/mruby-require](http://github.com/iij/mruby-require).
To fix this `REnv` of `RProc` associated to callinfo needs to be adjusted too.
```
require loop check : .                                                                                                                                                                                                                                                                  
require nest : ================================================================= …
```
=> Fix possible heap use after free in `mrb_exec_irep` and stack expanding.

include/mruby.h
Error message:
C:\projects\groonga\vendor\mruby-source\include\mruby.h(1098): error C2375: 'mrb_gc_arena_save' : redefinition; different linkage [C:\projects\groonga\vendor\mruby\mruby.vcxproj]
C:\projects\groonga\vendor\mruby-source\include\mruby.h(1083) : see declaration of 'mrb_gc_arena_save'
C:\projects\groonga\vendor\mruby-source\include\mruby.h(1099): error C2375: 'mrb_gc_arena_restore' : redefinition; different linkage [C:\projects\groonga\vendor\mruby\mruby.vcxproj]
C:\projects\groonga\vendor\mruby-source\include\mruby.h(1084) : see declaration of 'mrb_gc_arena_restore'
We may be able to fix this by just removing `MRB_API` but I didn't try it yet. Because  we already have static declarations of them.
=> Fix build error on Windows with MRB_BUILD_AS_DLL

src/load.c, src/string.c
closes #3997.
In compiler built with `MRB_INT64`, it treats integer as `Fixnum` that doesn't fit to `int32_t`.
=> Fallback to float when compiled binary with 64bit compiler.

src/backtrace.c
Since it's noisy and may cause an error in specific environment.
```
/home/takeshi/dev/mruby/src/backtrace.c:55:13: runtime error: pointer index expression with base 0x000000000000 overflowed to 0xfffffffffffffffc
#0 0x801b29 in each_backtrace /home/takeshi/dev/mruby/src/backtrace.c:55:13
#1 0x7fd347 in packed_backtrace /home/takeshi/dev/mruby/src/backtrace.c:206:3
#2 0x7fc831 in mrb_keep_backtrace /home/takeshi/dev/mruby/src/backtrace.c:225:15
#3 0x6bcbbc in mrb_exc_set /home/takeshi/dev/mruby/src/error.c:238:7
#4 0x6be277 in mrb_exc_raise /home/takeshi/dev/mruby/src/error.c:249:3
#5 0x7b1e74 in mrb_f_raise /home/takeshi/dev/mruby/src/kernel.c:903:5
#6 0x5a8df9 in mrb_vm_exec /home/takeshi/dev/mruby/src/vm.c:1469:18
#7 0x58aa70 in mrb_vm_run /home/takeshi/dev/mruby/src/vm.c:947:12
#8 …
```
=> Fix undefined error of pointer dereference.

mrblib/array.rb
Current implementation of `Enumerable#sort` is vulnerable to malicious input.  It should not consume system stack.
```
% bin/mruby -e 'a = 1.upto(600).to_a + 600.downto(1).to_a; a.map{ |i| [i] }.sort'
[0] -e:1
[1] /d/home/tsahara/src/mruby-master/mrblib/array.rb:234:in sort
[2] /d/home/tsahara/src/mruby-master/mrblib/array.rb:228:in sort!
[3] /d/home/tsahara/src/mruby-master/mrblib/array.rb:216:in __sort_sub__
[4] /d/home/tsahara/src/mruby-master/mrblib/array.rb:216:in __sort_sub__
[5] /d/home/tsahara/src/mruby-master/mrblib/array.rb:216:in __sort_sub__
[6] /d/home/tsahara/src/mruby-master/mrblib/array.rb:216:in __sort_sub__
[7] /d/home/tsahara/src/mruby-master/mrblib/array.rb:216:in __sort_sub__
[8] /d/home/tsahara/src/mruby-master/mrblib/array.rb:216:in …
```
=> sort method should not consume system stack.

src/gc.c
If MRB_TT_ENV has stack shared flag or bidx flag, flags is too large
than the real stack size.
=> Fix wrong the number of marked objects of MRB_TT_ENV in gray mark phase

src/vm.c
https://103.128.221.202.static.iijgio.jp/jenkins/view/0-master-mrbgem/job/master-mruby-aws-sigv4/37/consoleFull
BTW is modifying `self` value of env OK?
=> Fix heap use after free on mruby-aws-sigv4.

mrbgems/mruby-pack/test/pack.rb
When running the mruby-pack test with big endian, test data is incorrect,
so it will fail with "i" and "I".
------
Fail: pack/unpack "i" (mrbgems: mruby-pack)
- Assertion[1] Failed: Expected to be equal
Expected: "\xff\xff\xc7\xcf"
Actual: "\xff\xff\xcf\xc7"
- Assertion[2] Failed: Expected to be equal
Expected: [-12345]
Actual: [-14385]
Fail: pack/unpack "I" (mrbgems: mruby-pack)
- Assertion[1] Failed: Expected to be equal
Expected: "\x00\x0090"
Actual: "\x00\x0009"
- Assertion[2] Failed: Expected to be equal
Expected: [12345]
Actual: [14640]
------
This will fix the test data at big-endian.
Signed-off-by: Nobuhiro Iwamatsu <iwamatsu@nigauri.org>
=> Fix test of mruby-pack with big-endian CPUs

src/vm.c
Currently `envadjust` checks `oldbase <= env->stack < oldbase + newsize`, but it's wrong - we should use oldbase + **oldsize** as the upper bound.
After https://github.com/mruby/mruby/pull/3991, in one `envadjust` call, an `env `can be checked 2 times (when `ci[0]->env` and `ci[1]->proc->e.env` are identical). If newbase is allocated immediately after oldbase, `env->stack` pointer accidentally gets adjusted 2 times and refers out of range of the new stack area.
To reproduce, consume large amount of stack and then refer some lexical variable (`x`) in a closure.
```ruby
def doit(depth)
return if depth == 0
v0, v1, v2, v3, v4, v5, v6, v7, v8, v9 = (1..10).map { 'BROKEN' }
doit(depth - 1)
end
x = 'OK'
proc {
doit(100)
puts x
}.call
```
$ seq 10 | xargs  -n 1 build/host/bin/mruby repro.rb
``` …
```
=> fix env->stack misadjusting: fix #4029

mrbgems/mruby-eval/test/eval.rb, src/vm.c
As discussed in https://github.com/mruby/mruby/issues/4021, the commit 26e436e24797f0c3228bc9900615afe7d2e29ddf caused problems around `ci->env`. If I understand correctly, there're no reasons to set it in there.
=> fix broken lexical variables

mrbgems/mruby-socket/src/socket.c
To avoid conflicts with multiple definitions of inet_ntop and inet_pton
```
C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libWs2_32.a(dghfs00169.o):(.text+0x0): multiple definition of `inet_pton'
722C:/projects/iss/mruby/build/host/lib/libmruby.a(socket.o):C:/projects/iss/mruby/mrbgems/mruby-socket/src/socket.c:80: first defined here
```
if compiled with:
```c
```
=> [mruby-socket] Declare inet_ntop and inet_pton as static

minirake
Since with `Thread.pass` ruby process will eat up all the CPU times of a core.
=> Increase sleep duration exponentially instead of `Thread.pass`.

mrbgems/mruby-io/src/file.c
The current master does not build with MRB_WITHOUT_FLOAT.
This change allows to built it successfully.
=> Support MRB_WITHOUT_FLOAT to mruby-io

tasks/toolchains/android.rake
This PR adds _more recent_ default AndroidStudio Linux Android NDK to default NDK search path
Since only one line of code added, I didn't create a new branch
No modification to core/mrbgems, so no test case needed
:beer:
=> Added ~/Android/Sdk/ndk-bundle as default NDK home

mrbgems/mruby-test/mrbgem.rake
I guess since 1d7c69a windows builds seem to be broken when `enable_test` is activated.
```sh
Errno::ENOENT: No such file or directory @ dir_s_mkdir - mruby:Z:/Documents
```
The fix makes sure that we pass a valid file path and not the name of the rake file task.
=> [mruby-test] Fix task name is not necessarily a valid path

mrbgems/mruby-socket/test/addrinfo.rb, mrbgems/mruby-socket/test/socket.rb
This PR fixes its own failing tests where requested services like `smtp` are not available resulting into error message like:
```
SocketError: Addrinfo.tcp => getaddrinfo: Servname not supported for ai_socktype (mrbgems: mruby-socket)
```
=> [mruby-socket] Network services might not be available

include/mruby/boxing_word.h
When use `MRB_WORD_BOXING` on 32-bit mode, currently `sizeof(mrb_value)` is 8 bytes.
- `$ cat sample1.c`
```c
#define MRB_WORD_BOXING
#include <stdio.h>
int
main(int argc, char *argv[])
{
printf("sizeof(mrb_value): %d bytes\n", sizeof(mrb_value));
return 0;
}
```
- `$ mingw32-gcc -Iinclude -o sample1.exe sample1.c && wine sample1.exe`
```
sizeof(mrb_value): 8 bytes
```
- After patched, `$ mingw32-gcc -Iinclude -o sample1.exe sample1.c && wine sample1.exe`
```
sizeof(mrb_value): 4 bytes
```
I doing not use it, I do not strongly want to be fixed, but in a 32 bit environment it seems better to be 4 bytes.
The build_config.rb for testing is in <https://gist.github.com/dearblue/f02dceb7143729689755e6557f43f913>.
This fix can not be combined with `MRB_ENABLE_BUILTIN_SYMBOLS` …
=> Fix to sizeof(mrb_value) is 4 bytes with MRB_WORD_BOXING on 32-bit mode

doc/guides/mrbgems.md, include/mruby.h, minirake, mrbgems/mruby-bin-debugger/bintest/print.rb, mrbgems/mruby-compiler/core/codegen.c, mrbgems/mruby-socket/src/socket.c, test/t/literals.rb, test/t/module.rb
This pull request fixes minor typos in comments, docs, and error messages.
=> Fix misspelling words in comments, docs

mrbgems/mruby-compiler/core/codegen.c
I'm trying to change the parser a bit to suit my needs.
When I tried to use the NODE_NEGATE, I got very weird behavior.
With this AST:
```
00001   NODE_BEGIN:
00001     NODE_NEGATE
00001       NODE_CALL(.):
00001         NODE_CONST MyClass
00001         method='func' (15)
00001         args:
00001           NODE_INT 0 base 10
00001           NODE_INT 1 base 10
```
I got this bytecode:
```
irep 0x7ffcd1c0fc40 nregs=2 nlocals=1 pools=0 syms=1 reps=0
1 000 OP_LOADI      R1      -32767
1 001 OP_SUB        R0      :-      2
1 002 OP_STOP
```
So I changed the bytecode generator to get:
```
irep 0x7fb29ec0fc40 nregs=5 nlocals=1 pools=0 syms=3 reps=0
1 000 OP_GETCONST   R1      :MyClass
1 001 OP_LOADI      R2      0
1 002 OP_LOADI      R3      1
1 003 OP_SEND       R1      :func …
```
=> Fix weird behavior of the NODE_NEGATE

tasks/mrbgems.rake
Currently `XXX_gem_final()` is called in the same order as `XXX_gem_init()`.
I seems that it would be better to reverse this, but how is it?
- Currently sample `host/mrbgems/gem_init.c`:
```c
static void
mrb_final_mrbgems(mrb_state *mrb) {
GENERATED_TMP_mrb_mruby_sprintf_gem_final(mrb);     /* 1 */
GENERATED_TMP_mrb_mruby_print_gem_final(mrb);       /* 2 */
GENERATED_TMP_mrb_mruby_error_gem_final(mrb);       /* 3 */
GENERATED_TMP_mrb_mruby_fiber_gem_final(mrb);       /* 4 */
GENERATED_TMP_mrb_mruby_enum_ext_gem_final(mrb);    /* 5 */
GENERATED_TMP_mrb_mruby_enumerator_gem_final(mrb);  /* 6 */
GENERATED_TMP_mrb_mruby_string_ext_gem_final(mrb);  /* 7 */
}
void
mrb_init_mrbgems(mrb_state *mrb) {
GENERATED_TMP_mrb_mruby_sprintf_gem_init(mrb);      /* 1 */ …
```
=> Reversing gems final

mrbgems/mruby-sprintf/src/sprintf.c
https://github.com/mruby/mruby/issues/4108 was addressed in 625976d7931006bae7e960e561ecdaccb0cb6a28, but signed integer overflows can still occur. I'm concerned that compilers might decide to optimize away the overflow checks, so I've rewritten the code in a way that should avoid signed integer overflows.
I also noticed that the overflow check in `GETNUM` was incorrect, so I fixed that as well.
=> Prevent signed integer overflow.

src/class.c
When not defined a outer module name, class type is "Class".
- Currently:
```ruby
a = Module.new
a::B = Module.new
p [a, a::B] # => [#<Module:0x801825890>, #<Class:0x801825890>::B]
```
- After patched:
```ruby
a = Module.new
a::B = Module.new
p [a, a::B] # => [#<Module:0x801825890>, #<Module:0x801825890>::B]
```
=> Fix outer module name

include/mrbconf.h, src/class.c, src/variable.c
I tried it possible to assign an anonymous class/module name.
This is useful for meta-programming.
It is enabled by setting `conf.cc.defines << "MRB_IMPROVE_META_PROGRAMMING"` to `build_config.rb`.
- sample script (`sample.rb`):
```ruby
p a = Class.new
A = a
p A
B = A
Object.instance_exec { remove_const :A }
p B
class C
d = Class.new
p d
D = d
end
p C::D
e = Class.new {
f = Class.new
const_set(:F, f)
}
p e::F
E = e
p E::F
```
- Result by default (same as master and 1.4.1):
```
$ ./build/host/bin/mruby sample.rb
#<Class:0x801825890>
#<Class:0x801825890>
#<Class:0x801825890>
#<Class:0x8018254a0>
#<Class:0x8018254a0>
#<Class:0x801825290>::F
#<Class:0x801825290>::F
```
- Result with `MRB_IMPROVE_META_PROGRAMMING` configuration:
```
$ ./build/host2/bin/mruby sample.rb
#<Class:0x801825890>
A
A …
```
=> Assignment of anonymous class/module name

mrbgems/mruby-string-ext/src/string.c
Dinko Galetic & Denis Kasak noticed that strings beginning with `\xff` can cause a crash in `str_squeeze` because `s[0]` is treated as a signed value, causing it to be equal to `lastch`, which is -1. After this occurs, `i` is decremented and `s[-1]` is accessed.
The following inputs demonstrate crashes:
```ruby
"\xff00000000000000000000000".squeeze("\xff")
```
```ruby
"\xff00000000000000000000000".squeeze!("\xff")
```
```ruby
"\xff00000000000000000000000".squeeze
```
```ruby
"\xff00000000000000000000000".squeeze!
```
Changing `s` to an `unsigned char *` fixes the problem.
=> Fix comparisons in str_squeeze.

mrbgems/mruby-enum-ext/mrblib/enum.rb, mrblib/array.rb, test/t/array.rb
The current implementation of Array#sort! is quicksort.  It is known to be fast on average but very slow ("vulnerable" in other words) for some inputs (cf. #4007).  Mergesort is fast enough for any inputs.  Another good point of mergesort is that it is a stable algorithm.   Quicksort is unstable.  In my opinion, the default sort algorithm should be easy to use and safe for any inputs.
||quicksort|mergesort|
|---|---|---
| average performance | O(nlogn) | O(nlogn) (a bit slower than quicksort) |
| worst case performance | **O(n^2)** | O(nlogn) |
| average memory usage | O(logn) | **O(n)** |
| worst case memory usage | O(n) [*1] | O(n) |
[*1] it can be O(logn) in theory.
=> replace quicksort with mergesort.

include/mruby/irep.h
I spent a while trying to figure out why memory appeared to get corrupted when calling `mrb_load_irep`, but not when calling `mrb_load_string_cxt`. Problems with names having hex characters, when calling `methods` as such. I figured out that `mrb_load_irep` expected it's irep as a literal, were as I was supplying it temporally from the stack. This implementation makes sense for most applications.
Im not sure how obvious this problem would have been to everyone working with _mruby_, I might suggest adding some documentation to `mrb_load_irep` such as this PR.
Ill leave it to your discretion.
=> Add documentation to mrb_load_irep

mrbgems/mruby-sleep/README.md, mrbgems/mruby-sleep/example/sleep.rb
I fixed the example code of mruby-sleep so that it works.
*   Sleep module is undefined. So, delete the module name.
*   Specify the core library instead of the external library.
=> Fix sleep example

include/mruby.h, include/mruby/boxing_nan.h, include/mruby/boxing_word.h, include/mruby/class.h, include/mruby/data.h, include/mruby/object.h, include/mruby/proc.h, include/mruby/string.h
I think that some macros and arguments are better to enclose in parenthesis.
=> Fix parenthesis for macros

include/mrbconf.h, mrbgems/mruby-pack/src/pack.c
`BYTE_ORDER` and `BIG_ENDIAN` macros are not defined by clang and gcc on FreeBSD amd64, so defined `MRB_ENDIAN_BIG` always.
- by GCC-8.2
```
$ gcc8 -dM -E -xc -o - /dev/null | egrep 'BYTE_ORDER|_ENDIAN' | sort
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
```
- by clang-7.0
```
$ clang70 -dM -E -xc -o - /dev/null | egrep 'BYTE_ORDER|_ENDIAN' | sort
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __LITTLE_ENDIAN__ 1
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
```
I noticed it when building with `MRB_NAN_BOXING`.
- - - -
Macros such as BYTE_ORDER are not defined by …
=> Fix byte order

tasks/toolchains/gcc.rake
The gcc and clang have `-Wundef` which warns undefined macros.
Since it is not included in `-Wall`, how about considering adding intentionally?
- - - -
In MSVC, `/w34668` will be similarly warned.
https://github.com/dearblue/mruby/commit/82327b9e4fc8f9b529874ea84df8e92d3916aa8d
Since `__STDC_VERSION__` is warned as undefined, it was not included in the patch.
https://ci.appveyor.com/project/dearblue/mruby/build/job/f3bjosftdol73vjj
=> Append cflags for undefined macro

mrbgems/mruby-bin-mruby/mrbgem.rake
=> mruby-bin-mruby: Add test dependency.

mrbgems/mruby-io/test/io.rb
=> io: Skip TTY test for environments that TTY device is unavailable.

mrblib/float.rb, mrblib/mrblib.rake, src/numeric.c
- Avoid hack for `MRB_WITHOUT_FLOAT` in build scripts
- Avoid runtime dispatch for `MRB_WITHOUT_FLOAT`
=> Integrate mrblib/float.rb into src/numeric.c

mrbgems/mruby-compiler/core/codegen.c
Fix the following issue:
**Good**
$ bin/mruby -e 'p(-0.0)' #=> "-0"
**Bad**
$ bin/mruby -e 'a=0.0; p(-0.0)' #=> "0"
=> Fix `0.0` and `-0.0` handling.

mrbgems/mruby-time/include/mruby/time.h, mrbgems/mruby-time/src/time.c
Because the only way to create `Time` object is to call methods of mruby.
=> Add `Time` object creation API

mrbgems/mruby-bin-mruby/bintest/mruby.rb, src/dump.c, src/load.c
~~~ruby
p(2e308)
p(-2e308)
~~~
~~~
inf
-inf
~~~
~~~
$ bin/mrbc example.rb
$ bin/mruby -b example.mrb
0
-0
~~~
Float infinity representation is `inf` on dump and it is converted by
corresponding `String#to_f` on load.
- Introduce new representations (`i`: +infinity, `I`: -infinity)
- Allow old representations (`inf`, `-inf`, `infinity`, `-infinity`) too
- Raise error for unknown representations (use corresponding `Kernel#Float`)
=> Fix dump/load float leteral evaluate to infinity

src/numeric.c, src/state.c, test/t/float.rb
~~~ruby
p Float::INFINITY.to_s  #=> "inf"
p 50.0.to_s             #=> "50"
p 1e20.to_s             #=> "1e+20"
~~~
~~~ruby
p Float::INFINITY.to_s  #=> "Infinity"
p 50.0.to_s             #=> "50.0"
p 1e20.to_s             #=> "1.0e+20"
~~~
=> Improve compatibility to CRuby for `Float#to_s`

src/dump.c
`%g` use shorter representation than `%e`.
=> Use `%g` instead of `%e` for float representation in dump format

lib/mruby/build.rb
Build fails with the setting where `conf.build_dir=<rel path>` and `conf.enable_cxx_exception` are described in `build_config.rb`.
- `test_build_config.rb`:
```ruby
MRuby::Build.new do |conf|
toolchain :gcc
conf.build_dir = "build/host"
enable_cxx_exception
end
```
- before patched:
```
$ MRUBY_CONFIG=test_build_config.rb ./minirake
(in /usr/home/dearblue/works/ruby/mruby.git)
rake aborted!
Don't know how to rake /usr/home/dearblue/works/ruby/mruby.git/build/host/mrbgems/mruby-compiler/core/y.tab.c
```
The `MRuby::Build#compile_as_cxx` method converts the path given as a rule to an absolute path, but this patch does not convert but gives it as it is.
=> Build fails when set `conf.build_dir=<rel path>` and `conf.enable_cxx_exception`

mrbgems/mruby-print/mrblib/print.rb
`Kernel#sprintf` is defined in `mruby-sprintf`
=> Remove definition of `Kernel#sprintf` in `mruby-print`

mrbgems/mruby-sleep/src/mrb_sleep.c, mrbgems/mruby-sleep/test/sleep_test.rb
Time interval value can be zero, and float (in `Kernel#sleep`)
=> Refine error message for time interval

Rakefile
Avoid directory creation when run `rake -T` etc.
=> Avoid a side effect when run Rake without execution of tasks

mrbgems/mruby-time/src/time.c
The result of the following code are expected to be 0, but it is 1000000.
> t = Time.utc 2015; 2000.times { t+=0.0005; } ; t.usec
=> 1000000
> t = Time.utc 2015; 2000.times { t-=0.0005; } ; t.usec
=> 1000000
I change the used variables when carry-up and carry-down.
=> fix Time about carry-up and carry-down

mrbgems/mruby-compiler/core/codegen.c, test/t/class.rb, test/t/module.rb
~~~ruby
p(class A end)          #=> A
p(class << self; end)   #=> #<Class:#<Object:0x7fdc3880e420>>
p(module B end)         #=> B
~~~
~~~ruby
p(class A end)          #=> nil
p(class << self; end)   #=> nil
p(module B end)         #=> nil
~~~
=> `class`/`module` expression  with empty body should return `nil`

include/mruby/string.h, mrbgems/mruby-symbol-ext/src/symbol.c, mrbgems/mruby-symbol-ext/test/symbol.rb, src/string.c
Before:
p :あ.size  #=> 3
After:
p :あ.size  #=> 1
=> Fix `Symbol#size` for multi-byte characters with `MRB_UTF8_STRING`

src/state.c
I am lazy, so I'm happy if I can pass `NULL` to `mrb_open_core()`.
=> NULL safed `mrb_open_core()`

mrbgems/mruby-bin-config/mrbgem.rake
- Use `MRuby::Gem::Specification`
- Fix a binary name is added to `MRuby::Build#bins` multiple times
- Close file immediately (avoid using `open(...).read`)
- Simplify
=> Refine `mrbgems/mruby-bin-config/mrbgem.rake`

include/mruby/value.h, src/symbol.c
When building with `MRB_WORD_BOXING` in 32 bit mode, symbols are destroyed depending on the character string length.
```
$ build/host32-word/bin/mruby -e 'p [:zzzzzz, :ZZZZZ]'
[:zzzzb, :ZZZd]
```
In 32-bit mode with `MRB_WORD_BOXING`, only the value of` mrb_sym` is guaranteed 24 bits, there are only 4 spaces for lower case letters and 3 letters for numeral alphabet mixture.
For this reason, I restricted the length of the character string that can be inline packed symbols with this combination of configurations.
The "inline packed symbols" is nice idea :thumbsup:
=> Fix destroyed "inline packed symbols" on 32 bit mode with `MRB_WORD_BOXING`

src/backtrace.c
`sizeof(struct backtrace_location)` is 24 bytes -> 16 bytes in LP64
data model etc.
=> Reorder members in `struct backtrace_location`

mrbgems/mruby-bin-debugger/tools/mrdb/apiprint.c, mrbgems/mruby-bin-debugger/tools/mrdb/apiprint.h, mrbgems/mruby-bin-debugger/tools/mrdb/cmdmisc.c, mrbgems/mruby-bin-debugger/tools/mrdb/cmdprint.c, mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c, mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.h
Currently, we cannot get a list of local variables in mrdb because mrdb's `eval` command uses `instance_eval` to evaluate expressions.
To be more precise, `eval local_variables` always prints `[:e]` because evaluation is implemented as `instance_eval("begin\n#{expr}\nrescue => e\ne\nend")` in `mrb_debug_eval()` 
```
$ cat test.rb
foo = :bar
$ ./bin/mrdb test.rb
(test.rb:1) eval local_variables
$1 = [:e]   #### This is NOT what we want...
(test.rb:1)
```
This PR adds `info locals` command, which can print expected names of local variables by evaluating `local_variables` directly.
```
$ cat test.rb
foo = :bar
$ ./bin/mrdb test.rb
(test.rb:1) info locals
$1 = [:foo]
(test.rb:1)
```
=> mrdb: add "info locals" command

test/assert.rb
For the following reasons:
- Previous behavior is confusable because it's different from test/unit rubygem's `assert_true`
- Tests may pass unintentionally in an inappropriate way; ref #4285 #4287
=> `assert_true`/`assert_false` should pass when actual is only `true`/`false`

mrbgems/mruby-struct/mrblib/struct.rb
This method seems to be mistakenly put into `Object` instead of `Struct`
since it's in `struct.rb` and daf83946b says:
> add #dig to Array,Hash and Struct
=> Move `Object#dig` to `Struct#dig`

test/assert.rb
Skip: GC in rescue => backtrace isn't available (mrbgems: mruby-test)
Skip: GC in rescue => backtrace isn't available (core)
=> Refine mrbgem name in assertion failure/skip message for core test

mrbgems/mruby-io/test/file.rb
`mruby-time` is included in test dependencies.
=> Remove unneeded `const_defined?(:Time)` in `mruby-io` test

test/assert.rb
Skip: File.expand_path (with ENV) =>  (mrbgems: mruby-io)
Skip: File.expand_path (with ENV) (mrbgems: mruby-io)
=> Remove unneeded `=>` in test skip/error messages

mrbgems/mruby-compiler/core/parse.y, test/t/string.rb
This is a patch that concatenate consecutive string literals at the syntax parse stage.
When long strings are divided into multiple lines and described, it is possible to suppress the concatenation process at run time.  
Unlike CRuby, expressions with only strings included in expression expansion are not concatenated.
- mruby HEAD:
```
$ ./build/host/bin/mruby -v -e 'p "A" "B" "C#{?D}E" "F" "G#{1; ?H}I" "J"'
mruby 2.0.0 (2018-12-11)
-e:1:6: syntax error, unexpected tSTRING_BEG, expecting $end
SyntaxError: syntax error
```
- After patched:
```
$ ./build/host/bin/mruby -v -e 'p "A" "B" "C#{?D}E" "F" "G#{1; ?H}I" "J"'
mruby 2.0.0 (2018-12-11)
00001   NODE_BEGIN:
00001     NODE_FCALL:
00001       NODE_SELF
00001       method='p' (71)
00001       args:
00001         NODE_DSTR …
```
=> String literal concatenation

mrbgems/mruby-compiler/core/parse.y
There is this prefix in CRuby and `mrb_warn()`.
=> Add `warning: ` prefix to parser warning message

mrbgems/mruby-test/driver.c, test/assert.rb, test/bintest.rb, test/report.rb
- An exception do not raise when mrbtest fail.
- There are no useful informations in exception message and backtrace.
=> Do not raise an exception when bintest fail

mrbgems/mruby-metaprog/src/metaprog.c, mrbgems/mruby-metaprog/test/metaprog.rb, src/variable.c, test/t/kernel.rb
- `@@?` etc are invalid class variable name.
- `@1` etc are invalid instance variable name.
=> Fix class/instance variable name validation

appveyor.yml
Build time becomes less than half. FYI, `minirake -j4` is the following failure:
C:\projects\mruby\mrbgems\mruby-inline-struct\test\inline.c: fatal error C1041: cannot open program database 'C:\projects\mruby\vc140.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
mrbtest - Embeddable Ruby Test
...........................
Total: 1165
(snip)
Time: 1.19 seconds
bintest - Command Binary Test
.....................
Total: 21
(snip)
Time: 0.39 seconds
mrbtest - Embeddable Ruby Test
...........................
Total: 1165
(snip)
Skip: 23
Time: 1.15 seconds
(snip)
>>> Test cxx_abi <<<
>>> Bintest host <<<
>>> Test host <<<
>>> Test full-debug <<<
>>> Bintest cxx_abi <<<
>>> Test full-debug <<<
mrbtest - Embeddable Ruby Test
...........................
Total: 1165
(snip)
Time: …
=> Use Rake instead of MiniRake on AppVeyor

test/assert.rb
`assert_float` is always passed when expected value and/or actual value are
infinity or NaN. This behavior seems unintentional.
Before this patch:
```ruby
assert_float(Float::INFINITY, 1.0)  #=> pass
assert_float(-Float::INFINITY, 1)   #=> pass
assert_float(1, 1/0)                #=> pass
assert_float(1, -1/0)               #=> pass
assert_float(1.0, Float::NAN)       #=> pass
assert_float(Float::NAN, 1)         #=> pass
```
After this patch:
```ruby
assert_float(Float::INFINITY, 1.0)  #=> fail: Expected 1.0 to be Infinity.
assert_float(-Float::INFINITY, 1)   #=> fail: Expected 1 to be -Infinity.
assert_float(1, 1/0)                #=> fail: Expected Infinity to be 1.
assert_float(1, -1/0)               #=> fail: Expected -Infinity to be 1.
assert_float(1.0, Float::NAN)       #=> fail: …
```
=> Fix dealing with infinity and NaN in `test/assert.rb:assert_float`

include/mruby.h
`va_list` is defined in stdarg.h.
```
CC    src/array.c -> build/host/src/array.o                                    
In file included from /d/home/tsahara/src/mruby-master/src/array.c:7:          
/d/home/tsahara/src/mruby-master/include/mruby.h:1151: error: expected declarati
on specifiers or '...' before 'va_list'                                        
In file included from /d/home/tsahara/src/mruby-master/src/array.c:7:          
/d/home/tsahara/src/mruby-master/include/mruby.h:1151: error: expected declarati
on specifiers or '...' before 'va_list'                                        
rake aborted!                                                                  
Command failed with status (1): [gcc -g -std=gnu99 -O3 -Wall -Werror-implic...] …
```
=> fixes build on OpenBSD.

src/variable.c
```ruby 
Object.const_set :A, Module.new{const_set :B, Class.new}
ab = A::B.to_s
p ab         #=> "A::B" # Good
ab[0] = "x"
p A::B.to_s  #=> "x::B" # Bad
```
=> Fix modifiable class name

src/state.c
Three-digit exponent issue was fixed via another workaround (63b8f5c).
=> Remove unnecessary `_set_output_format` call

mrbgems/mruby-array-ext/mrblib/array.rb, src/array.c
They are not included in ISO standard.
=> Move `Array#(append|prepend)` from core to `mruby-ary-ext`

mrbgems/mruby-compiler/core/parse.y
Dinko Galetić and Denis Kasak (https://hackerone.com/dgaletic) noticed that ec1688807ef301483321919778b2ccb578822767 introduced a number of buffer overflow vulnerabilities. For example, the following inputs all demonstrate crashes:
```ruby
pro_fselfsemfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfsekfselfselfselfselfselfselfselfselfselfselselfselfselfselftelfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfsdlfself<<<<-0pro_fselfsemfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselselfselfselfselftelfselfselfselfselfselfselfelfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfselfsdlfself<<<<-0pro_fselfsemfselfselfselfselfselfself …
```
=> Fix buffer overflows in parser.

test/assert.rb
Avoid arithmetic operations when `exp` and/or `act` are infinity or NaN.
=> Refine `assert_float`

src/vm.c
$ bin/mruby -e '(Float::INFINITY - Float::INFINITY).nan?'
zsh: segmentation fault
`SET_FLOAT_VALUE` is not used. It is needed for normalizing NaN.
In my environment, this issue could be reproduced only when
`infinity - infinity`, however `SET_FLOAT_VALUE` should be used in all
arithmetic operations (regardless of boxing setting), I think.
So I fixed all similar codes by extracting to macro.
=> Fix broken NaN with `MRB_NAN_BOXING`

mrbgems/mruby-compiler/core/parse.y
- Currently (`0x` ???):
```
% ./build/host/bin/mruby -e $'\177'
-e:1:1: Invalid char in expression: 0x
SyntaxError: syntax error
```
- After patched (to `0x7F`):
```
% ./build/host/bin/mruby -e $'\177'
-e:1:1: Invalid char in expression: 0x7F
SyntaxError: syntax error
```
=> Fix hexdigits convertion

mrbgems/mruby-compiler/core/codegen.c, src/gc.c, src/symbol.c
- `free_heap()` in src/gc.c
- `symhash()` in src/symbol.c
- `no_optimize()` in mrbgems/mruby-compiler/core/codegen.c
```
% nm --defined-only --extern-only build/host/lib/libmruby_core.a | egrep -v ' mrbc?_| kh_|^[a-z_\.]+:' | uniq
0000000000000dd0 T symhash
0000000000001760 T free_heap
0000000000000000 T calc_crc_16_ccitt
0000000000002070 T no_optimize
```
=> Fix leaked function symbols

mrbgems/mruby-test/driver.c, src/numeric.c, src/variable.c
Older gcc's don't permit these variables to be declared within `for` loops.
=> Fix compilation on gcc 4.9.x

include/mruby/boxing_word.h, include/mruby/value.h
CRuby can use `obj == Qtrue` and `obj == Qfalse` if a strict comparison is required.
But mruby has no alternate it.
=> Add `mrb_true_p()` and `mrb_false_p()` macro functions

mrblib/string.rb, test/t/string.rb
```ruby
'a'[0] = 1        #=> 1
'a'[:a] = '1'     #=> ArgumentError
'a'[:a, 0] = '1'  #=> ArgumentError
'a'[0, :a] = '1'  #=> ArgumentError
'a'[0, 1] = 1     #=> 1
```
```ruby
'a'[0] = 1        #=> TypeError
'a'[:a] = '1'     #=> TypeError
'a'[:a, 0] = '1'  #=> TypeError
'a'[0, :a] = '1'  #=> TypeError
'a'[0, 1] = 1     #=> TypeError
```
=> Add type check (conversion) in `String#[]=`

include/mruby/boxing_word.h
In `SET_OBJ_VALUE()`, branch isn't removed because `switch` condition isn't
constant expression.
=> Expand `BOXWORD_SET_VALUE()` macro in `include/mruby/boxing_word.h`

include/mruby.h, include/mruby/boxing_word.h, include/mruby/class.h, include/mruby/data.h, include/mruby/value.h
Changed some functions defined under the `include/` directory from `static inline` to `MRB_INLINE`.
The purpose is to make it easy to understand as part of the exposed C API.
However, I may have changed the extra functions to `MRB_INLINE`.
=> Change modifier to `MRB_INLINE` from `static inline`

mrbgems/mruby-metaprog/test/metaprog.rb, src/class.c, src/kernel.c, test/t/class.rb
Singleton class of frozen object should be frozen
```ruby
p (class << Object.new.freeze; self end).frozen?                #=> false
sc = class << (o=Object.new); self end; o.freeze; p sc.frozen?  #=> false
```
```ruby
p (class << Object.new.freeze; self end).frozen?                #=> true
sc = class << (o=Object.new); self end; o.freeze; p sc.frozen?  #=> true
```
=> Singleton class of frozen object should be frozen

include/mruby/value.h
This is a patch that allows the user to define the `mrb_ro_data_p()` function.
It becomes effective by adding `MRB_USE_CUSTOM_RO_DATA_P` to `conf.cc.defines` in `build_config.rb`.
(Limitation) It can not be defined as an inline function.
Defining `MRB_USE_ETEXT_EDATA` in ESP32 will increase RAM usage (the cause will be described later).
So, if we could use the user-definable `mrb_ro_data_p ()` function, we could reduce it by 3.6 KiB.
- without `MRB_USE_ETEXT_EDATA`:
```
free heap size (in bytes):
before `mrb_open()`:   298728
after `mrb_open()`:   117836 (delta  -180892)
```
- with `MRB_USE_ETEXT_EDATAP`:
```
free heap size (in bytes):
before `mrb_open()`:   298728
after `mrb_open()`:    76636 (delta  -222092)
```
- Patched with `MRB_USE_CUSTOM_RO_DATA_P`:
```
free heap size (in bytes): …
```
=> Add customized `mrb_ro_data_p()`

doc/guides/mrbconf.md, include/mrbconf.h
Updated document for `MRB_USE_CUSTOM_RO_DATA_P`.
I also updated the following matters that I noticed in the process.
- (Add) `MRB_USE_ETEXT_EDATA`
- (Add) `MRB_NO_INIT_ARRAY_START`
- (Modify) `MRB_INT16`
- (Add) `MRB_INT32`
- (Modify) `MRB_INT64`
- (Add) `MRB_WITHOUT_FLOAT` - comment is based on ref #3827
- (Add) `MRB_METHOD_CACHE` - comment is based from `include/mrbconf.h`
- (Add) `MRB_METHOD_CACHE_SIZE` - comment is based from `include/mrbconf.h`
- (Add) `MRB_METHOD_TABLE_INLINE` - comment is based from `include/mrbconf.h`
- (Add) `MRB_ENABLE_ALL_SYMBOLS`
*I am only converting by Google Translate, so I can not express details.
Please point out or correct any deficiencies.*
=> Update document for `MRB_USE_CUSTOM_RO_DATA_P` and some configurations

mrbgems/mruby-struct/test/struct.rb
Because this test is always skipped.
=> Commented out "Struct.new removes existing constant" test

test/assert.rb
The default message for the second argument should be set to the first
argument because only one argument is normally specified.
=> Refine the default values of `flunk`

mrbgems/mruby-bin-mruby/bintest/mruby.rb, mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
- Write message to stderr instead of stdout.
- Avoid duplicate message output (`SyntaxError`, `ScriptError` etc).
- Refine invalid option message.
- Suppress redundant usage output.
- Fix some incorrect exit code.
=> Refine error message output for `mruby` command

mrbgems/mruby-bin-mruby/bintest/mruby.rb, mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
- Modify some error messages for consistency.
- Add test for codegen error.
- Use regular expression for error message matching in test.
=> Small fix in `mruby-bin-mruby`

mrbgems/mruby-io/src/file.c, mrbgems/mruby-io/src/file_test.c, mrbgems/mruby-io/test/mruby_io_test.c, mrbgems/mruby-socket/src/socket.c
Because it always allocate new string. Replace with the followings:
- Use `RSRING_PTR` if string is guaranteed to be null-terminated.
- Use `mrb_string_value_cstr` or `mrb_get_args("z")` if return value isn't
modified.
=> Avoid using `mrb_str_to_cstr` if possible

mrbgems/mruby-io/test/file.rb, src/string.c
- Extract null byte check to function.
- Avoid string allocation if null byte is included.
- Use `str_new` instead of `mrb_str_dup` + `mrb_str_modify`
=> Refactor `mrb_str_to_cstr` and `mrb_string_value_cstr`

oss-fuzz/config/mruby_fuzzer.options
This PR
- Adds a space between earlier ossfuzz options
- Adds two new options
- `only_ascii` ensures that the fuzzer generates only ASCII input
- `fork=8` ensures that the fuzzer does not halt on the first timeout/out-of-memory issue, while parallelizing fuzzing across 8 independent processes.
=> Update ossfuzz options

mrbgems/mruby-time/src/time.c, mrbgems/mruby-time/test/time.rb
- A leading charactor for day is space.
- Time zone does not included.
```ruby
Time.gm(1982,3,4,5,6,7).asctime  #=> "Thu Mar 04 05:06:07 UTC 1982"
```
```ruby
Time.gm(1982,3,4,5,6,7).asctime  #=> "Thu Mar  4 05:06:07 1982"
```
=> Fix `Time#(asctime|ctime)` according to ISO Ruby

mrbgems/mruby-time/src/time.c, mrbgems/mruby-time/test/time.rb
- Ruby compatibility.
- Add UTC offset (time zone informations was not included by #4433).
- More readable.
```ruby
p Time.gm(2003,4,5,6,7,8,9)        #=> Sat Apr  5 06:07:08 2003
p Time.local(2013,10,28,16,27,48)  #=> Mon Oct 28 16:27:48 2013
```
```ruby
p Time.gm(2003,4,5,6,7,8,9)        #=> 2003-04-05 06:07:08 UTC
p Time.local(2013,10,28,16,27,48)  #=> 2013-10-28 16:27:48 +0900
```
I use `strftime(3)` because UTC offset can be added and program size become
smaller than the other implementations (using `sprintf(3)`, self conversion
etc) in my environment.
=> Refine `Time#(to_s|inspect)`

include/mruby/variable.h, src/class.c, src/variable.c, test/t/module.rb
Fix the following issues:
```ruby
A = Class.new.freeze              #=> FrozenError
Module.new::B = Class.new.freeze  #=> FrozenError
String::B = Module.new.freeze     #=> FrozenError
```
=> Fix name assignment to frozen anonymous class/module

lib/mruby/build/command.rb
If $rake_root_fiber is used, sh runs command in another Fiber. If
command is ran in another Fiber, "rescue RuntimEerror" can't rescue
exception for system(...) failure.
How to reproduce:
$ CC="gcc -std=gnu99" ./minirake
(in /home/kou/work/ruby/mruby.kou)
CC    mrbgems/mruby-compiler/core/codegen.c -> build/test/mrbgems/mruby-compiler/core/codegen.o
sh: 1: gcc -std=gnu99: not found
rake aborted!
Command Failed: ["gcc -std=gnu99" -g -std=gnu99 ...]
=> Add support for CC="gcc --option ..." again

oss-fuzz/mruby_proto_fuzzer.cpp, oss-fuzz/proto_to_ruby.cpp, oss-fuzz/proto_to_ruby.h, oss-fuzz/ruby.proto
This PR
- adds source and header files necessary to build and run [proto fuzzer](https://github.com/google/fuzzer-test-suite/blob/master/tutorial/structure-aware-fuzzing.md) on oss-fuzz
- adds a simple proto specification for the ruby language
Once this PR is merged, I will push changes necessary to build the proto fuzzer to oss-fuzz.
=> proto fuzzer: Add source files necessary to compile proto fuzzer

mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb
Because these methods work if object is `Comparable`, and `Numeric` is
`Comparable`.
=> Move `Integral#(zero|nonzero|positive|negative)?` to `Numeric`

include/mrbconf.h
Not only mruby, it is one of the difficult things to adjust the performance vs. memory efficiency of the software.
If the approximate target device is divided and the adjustment value for it is prepared by default, it is a good indicator to do fine adjustment.
This PR divides into four profiles.
***Caution: There is no basis for the definitions in the patch.***
- `MRB_CONSTRAINED_BASELINE_PROFILE` - for microprocessors. Reduce memory consumption.
- `MRB_BASELINE_PROFILE` - Default value of mruby.
- `MRB_MAIN_PROFILE` - For desktop computers. Assume that a huge amount of RAM, 10 MiB or more, is on board.
- `MRB_HIGH_PROFILE` - for servers. Assume that mruby VM has a long life.
As you can see the profile name has been ~~stolen~~ imitated from H.264.
=> (Proof of Concept) mruby tuning profiles [ci skip]

src/numeric.c
This method is only used in `Integral#step`
=> Move `Numeric#__coerce_step_counter` to `Integral`

include/mruby/dump.h, src/load.c
Because it is not currently output by `mrbc`.
=> Remove "LINE" section reader

mrbgems/mruby-rational/mrblib/rational.rb, src/numeric.c
Having these methods in Numeric can get in the way of creating subclasses of
Numeric because they only support Fixnum and Float.
=> Move `**`,`/`,`quo`,`div` and comparison methods to Integral from Numeric

include/mruby/dump.h, include/mruby/irep.h, src/load.c
This patch appends `_buf` to some functions that read irep, and adds a function to check the buffer size as an argument.
Also, confirmation of the binary version is done by the internal `read_binary_header()` function which is called indirectly.
- `MRB_API mrb_irep *mrb_read_irep_buf(mrb_state *mrb, const void *buf, size_t bufsize)`
- `MRB_API mrb_value mrb_load_irep_buf(mrb_state *mrb, const void *buf, size_t bufsize)`
- `MRB_API mrb_value mrb_load_irep_buf_cxt(mrb_state *mrb, const void *buf, size_t bufsize, mrbc_context *c)`
If you give `bufsize = -1`, the buffer size is virtually not checked.
The `read_binary_header ()` function has been changed to return `MRB_DUMP_READ_FAULT` if the size of irep itself is larger than the buffer size.
----
The `mrb_read_irep ()` function, etc. assumes …
=> Read irep from buffers

include/mruby/range.h, mrbgems/mruby-array-ext/src/array.c, mrbgems/mruby-kernel-ext/src/kernel.c, mrbgems/mruby-string-ext/src/string.c, src/array.c, src/range.c, src/string.c
Since the `mrb_range_beg_len()` function is `MRB_API`, I think it is better to return an enumeration value rather than returning a magic number.
The name written in this patch may be used in the future, so I think it is better to add one more word.
But I didn't think of a good name.
=> Name the return value of `mrb_range_beg_len()`

src/string.c
- Before patched:
```
$ mruby -e 'p (-12..-1).map { |i| "Hello"[i] }.join'
"HelloHello"
```
- After patched:
```
$ mruby -e 'p (-12..-1).map { |i| "Hello"[i] }.join'
"Hello"
```
=> Fix double rounded by negative index for `String#[]`

include/mruby.h, src/state.c
When I found this function, I expected it to behave the same as the `alloca(3)` function, but it is accually the `mrb_alloca()` function does not free the heap until the `mrb_close()` function is called.
Also, even if it is deleted, it can be replaced with the combination of the `MRB_TT_DATA` object and the `mrb_gv_set()` function if it is sure necessary.
----
I suggest removing function or changing the function name (This patch is removing function).
As far as I inspected it lightly, it is not used in mruby core and core gems.
In mgem-list's mruby gems, only `mruby-dll` has referenced `mrb_alloca()` symbol from `mruby.def`.
=> Remove `mrb_alloca()` function

mrbgems/mruby-rational/mrblib/rational.rb, mrbgems/mruby-rational/test/rational.rb
Consider a Numreic class like `Complex` that does not have `<=>` but `==`
works (`0i == 0r` is `true`).
=> Fix `Rational#==(Complex)`

test/t/string.rb
Because there is not assertion in this test and NUL character literal is
used in other tests.
=> Remove "Check the usage of a NUL character" test

mrbgems/mruby-metaprog/src/metaprog.c, mrbgems/mruby-metaprog/test/metaprog.rb, src/kernel.c, test/t/kernel.rb
This method is defined in `mruby-metaprog` gem.
=> Remove `Kernel#global_variables` from core

mrbgems/mruby-io/src/file_test.c, mrbgems/mruby-io/src/io.c
`mrb_get_datatype()` used in `mruby-io` is obsoleted by `include/mruby/data.h`.
https://github.com/mruby/mruby/blob/2847692d5900745630e1db484884a0bb5fffba7e/include/mruby/data.h#L58-L60
=> Replace obsolete macros

mrbgems/mruby-proc-ext/src/proc.c, mrbgems/mruby-proc-ext/test/proc.rb
$ bin/mruby -e 'p proc{}'  #=> #<Proc:0x7fd5eb8206d0@-e::1>
$ bin/mruby -e 'p proc{}'  #=> #<Proc:0x7fd5eb8206d0@-e:1>
=> Remove redundant colon in `Proc#inspect` (`mruby-proc-ext`)

mrbgems/mruby-metaprog/test/metaprog.rb, src/variable.c
- They are not include in Ruby.
- Appear in duplicate when `$1`-`$9` are defined.
=> `Kernel#global_variables` should not include undefined `$1`-`$9`

include/mruby/class.h, mrbgems/mruby-struct/src/struct.c, mrbgems/mruby-struct/test/struct.rb, src/class.c
$ bin/mruby -e 'p Struct.new("A-")'
#=> Struct::"A-"
$ bin/mruby -e 'p Struct.new("A-")'
#=> NameError: identifier A- needs to be constant
=> Fix class name validation in `Struct.new`

mrbgems/mruby-struct/src/struct.c
The following branch condition is always true:
```c
// mrbgems/mruby-struct/src/struct.c:187 in make_struct_define_accessors()
if (is_local_id(mrb, name) || is_const_id(mrb, name)) {
```
=> Remove a meaningless branch condition in `mruby-struct`

mrbgems/mruby-struct/src/struct.c
$ bin/mruby -e 'Struct.new(:a,:b).new[-3]'
#=> offset -1 too small for struct(size:2) (IndexError)
$ bin/mruby -e 'Struct.new(:a,:b).new[-3]'
#=> offset -3 too small for struct(size:2) (IndexError)
=> Fix index in error message of `Struct#[]`

mrbgems/mruby-class-ext/src/class.c
`mrb_class_path()` always returns a new string or `nil`.
=> Remove unneeded `mrb_str_dup()` in `Module#name`

src/string.c
For example on 32 bit mode, when `p = 0xfffffffd`, `e = 0xfffffffe` and `len = 4`, the sum of `p` and `len` can be to `1`, and comparison with `e` will to be false.
As a result, a segmentation fault occurs by referring to address 0.
----
I think that it is not realistic unless the address space is 16 bits, but just in case.
=> Fix potential overflow in `utf8len()`

src/hash.c
Previous example doesn't work because string key (frozen) can't be modified.
=> Refine `Hash#rehash` example [ci skip]

src/gc.c
Because immediate values are not registered.
=> Compare obj pointer directly instead of using mrb_obj_eq in mrb_gc_unregister

include/mruby/boxing_word.h
`(r).value.bp` and `v` have the same value due to assignment of the line
preceding the removed line.
=> Remove unneeded statement in `SET_OBJ_VALUE` with `boxing_word.h`

mrbgems/mruby-rational/src/rational.c
This PR contains the patch of simply halving the numerator and denominator if they do not fit into `mrb_int`.
If this is a problem, please point out.
=> Fix rational new on 32 bits mode

include/mruby/string.h, mrbgems/mruby-string-ext/src/string.c, mrbgems/mruby-string-ext/test/string.rb, src/string.c
```
$ bin/mruby -e '
p "あa".byteslice(1)
p "bar".byteslice(3)
p "bar".byteslice(4..0)
'
```
"a"
""
RangeError (4..0 out of range)
"\x81"
nil
nil
=> Fix `String#byteslice` with `MRB_UTF8_STRING` and some edge cases

src/string.c
```shell
mruby/mruby/src/string.c:1722:4: warning: label 'bytes' defined but not used [-Wunused-label]
bytes:
^~~~~
```
=> Silence unused label warnings from gcc; ref #4524

README.md
A part of a fix for issue mruby/mruby.github.io#50
=> Fix broken links for mruby.org

mrbgems/mruby-string-ext/test/string.rb, mrbgems/mruby-symbol-ext/test/symbol.rb, test/t/string.rb
It cannot be used for `String#size` test if judging whether or not `MRB_UTF8_STRING` is defined by result of `String#size`.
=> Use `__ENCODING__` in tests

mrblib/string.rb, src/string.c, test/t/string.rb
The purpose is to eliminate string objects that are temporarily created during processing.
Even if `MRB_UTF8_STRING` is defined, ~~it works as before as long as it is checked by me~~.
The behavior has been changed when an invalid string is given as UTF-8. See <https://github.com/mruby/mruby/pull/4541#issuecomment-506950966>
The error message should be almost the same as the current implementation.
----
And I simplified `mrb_str_aref_m()` and `mrb_str_aref()` too.
It is integration with part of argument parsing used by `mrb_str_aset_m()`.
=> Replace `String#[]=` method by C implements

mrbgems/mruby-bin-mruby/bintest/mruby.rb, mrbgems/mruby-complex/test/complex.rb, mrbgems/mruby-io/test/io.rb, mrbgems/mruby-pack/test/pack.rb, mrbgems/mruby-rational/test/rational.rb, test/assert.rb
When nesting `assert` used in test, it is indented and displayed.  
Assertion numbers are concatenated by `"-"` at this time.
The purpose is to match the apparent numbers when failing with `assert_mruby` which is defined by `mrbgems/mruby-bin-mruby/bintest/mruby.rb` for example.
Child assertions "skip" and "info" are reported as parent assertions "info" and `$ok_test += 1`.
The child assertions "ko" and "crash" are reported as the parent assertion "ko" and `$ko_test += 1`.
When child assertions are mixed, "ko" takes precedence.
If you use `"."` As a concatenation character, I think it is easy to confuse it with the ISO Ruby section number when it is displayed.  
So we chose `"-"` as the concatenation character.
Note that this patch conflicts with #4320.
- `$mrbtest_assert_idx` takes `nil` …
=> Nested `assert` for mrbtest

src/etc.c
```shell
$ bin/mruby -e '1.respond_to?(2)'  #=> nil is not a symbol
```
```shell
$ bin/mruby -e '1.respond_to?(2)'  #=> 2 is not a symbol nor a string
```
=> Fix and refine error message in `mrb_obj_to_sym()`

src/string.c, test/t/string.rb
It minimizes the number of `utf8len ()` calls per character.
- `RSTRING_CHAR_LEN()` is only used when `pos` is given a negative value.
- `pos` is kept in character units, and is not converted between bytes.
The string search algorithm is Boyer-Moore-Horspool algorithm (Quick Search algorithm).
As a side effect, the correct position is returned even if an invalid UTF-8 string is given.
```console
% ./mruby@master -e 'p ("\xd1" * 100 + "#").index("#")'
50
% ./mruby@improve-index -e 'p ("\xd1" * 100 + "#").index("#")'
100
% ruby26 -e 'p ("\xd1" * 100 + "#").index("#")'
100
```
The other behavior should be the same as the current implementation.
=> Improve performance `String#index` with UTF-8

src/string.c
This patch fixes the heap buffer overflow shown at https://github.com/mruby/mruby/pull/4569#issuecomment-510850076.
The performance loss is a few percent.
=> Fix heap buffer overflow; fix #4569

lib/mruby/build/command.rb
`-MP` flag is used in `tasks/toolchains/android.rake`.
=> Consider `-MP` flag specified when parsing `.d` file

mrbgems/default.gembox
I think `mruby-method` gem is used more than `mruby-objectspace` gem.
=> Add `mruby-method` gem to `default.gembox` [ci skip]

mrbgems/mruby-pack/src/pack.c, mrbgems/mruby-pack/test/pack.rb
The pack/unpack "m" directive should be treated as a length rather than an element count.
And fixes empty array refers.
For example, `"".unpack("")` evaluates to `[]`.
=>  Fix pack/unpack for base64; ref #4556

src/string.c
I revenge #4529 (without permission).
----
I compared with the file that actually exists.
Acquisition and processing of sample file:
- ASCII only HTML - `2000-2FFF` (530,693 bytes)
```console
% fetch https://en.wikibooks.org/wiki/Unicode/Character_reference/2000-2FFF
```
- Mixed Japanese UTF-8 HTML - `book.utf-8.html` (3,100,523 bytes)
```console
% fetch -o- https://www.freebsd.org/doc/ja_JP.eucJP/books/handbook/book.html | nkf -Eu > book.utf-8.html
```
- Almost Japanese UTF-8 TEXT - `uchuno_hajimari.utf-8.txt` (517,378 bytes)
from https\://www.aozora.gr.jp/cards/000226/card1150.html
```console
% fetch -o- https://www.aozora.gr.jp/cards/000226/files/1150_ruby_38564.zip | tar xf - -O uchuno_hajimari.txt | nkf -Su > uchuno_hajimari.utf-8.txt
```
- Japanese UTF-8 HTML - `ゲゲゲの鬼太郎の登場キャラクター` …
=> Improve `utf8len()` performance with UTF-8

mrbgems/mruby-range-ext/mrblib/range.rb
$ bin/mruby -e 'p (2...4.0).min'  #=> TypeError
$ bin/mruby -e 'p (2...4.0).min'  #=> 2
=> Fix `(fixnum_value ... float_value).min` with `mruby-range-ext`

src/string.c
`String#inspect` can set `MRB_STR_ASCII` flag to receiver and return value
because it checks character byte length.
=> Set `MRB_STR_ASCII` flag in `String#inspect`

src/class.c, src/kernel.c, test/t/module.rb
$ bin/mruby -e 'p Module.new.freeze.dup.frozen?'  #=> true
$ bin/mruby -e 'p Module.new.freeze.dup.frozen?'  #=> false
=> Fix `Module#dup` to frozen module

mrbgems/mruby-numeric-ext/src/numeric_ext.c, mrbgems/mruby-numeric-ext/test/numeric.rb, mrbgems/mruby-string-ext/src/string.c, mrbgems/mruby-string-ext/test/fixnum.rb, mrbgems/mruby-string-ext/test/numeric.rb
Because they're defined in both `mruby-string-ext` and `mruby-numeric-ext`
(they seem more natural to define in N, but `mruby-string-ext` depends on
`Integral#chr`).
=> Integrate `Integral#chr` (`Fixnum#chr`) to `mruby-string-ext`

mrbgems/mruby-string-ext/mrblib/string.rb, mrbgems/mruby-string-ext/src/string.c, mrbgems/mruby-string-ext/test/numeric.rb, mrbgems/mruby-string-ext/test/string.rb
Currently, `Integral#chr` in mruby changes behavior by `MRB_UTF8_STRING`
setting.
before this patch:
$ bin/mruby -e 'p 171.chr'  #=> "\xab"  (`MRB_UTF8_STRING` is disabled)
$ bin/mruby -e 'p 171.chr'  #=> "«"     (`MRB_UTF8_STRING` is enabled)
This behavior is incompatible with Ruby, and a little inconvenient because
it can't be interpreted as ASCII-8BIT with `MRB_UTF8_STRING`, I think.
So add encoding argument according to Ruby.
after this patch:
$ bin/mruby -e 'p 171.chr'                #=> "\xab"
$ bin/mruby -e 'p 171.chr("ASCII-8BIT")'  #=> "\xab"
$ bin/mruby -e 'p 171.chr("UTF-8")'       #=> "«"
Allow only `String` for encoding because mruby doesn't have `Encoding`
class, and `"ASCII-8BIT"` (`"BINARY"`) and `"UTF-8"` (only with
`MRB_UTF8_STRING`) are valid values (default is …
=> Add encoding argument to `Integral#chr`

mrbgems/mruby-array-ext/test/array.rb
- No guarantees about the order in which the permutations/combinations
are yielded.
- Drop dependency on `Enumerator`.
=> Refine `Array#(permutation|combination) test`

mrbgems/mruby-time/include/mruby/time.h, mrbgems/mruby-time/src/time.c
This patch fixes the lack of precision for `Time`.
ref: https://github.com/mruby/mruby/commit/d74355061bffe9762dabd2e303525002d3e6a585#commitcomment-34467316
- `Time.local` and `Time.utc` are able to use with `MRB_INT16 + MRB_WITHOUT_FLOAT`.
```console
% ./build/host-MRB_INT16+MRB_WITHOUT_FLOAT/bin/mruby -e 'p Time.local(2345, 6, 7, 8, 9, 10)'
2345-06-07 08:09:10 +0900
```
- `time_t` is converted directly from the Ruby object.
```console
% ./build/host-MRB_INT32+MRB_USE_FLOAT/bin/mruby -e 'p Time.at 1564228479'
2019-07-27 20:54:39 +0900
```
- `time + sec` and` time - sec` are not affected by the precision of `mrb_float`.
```console
% ./build/host-MRB_INT16+MRB_USE_FLOAT/bin/mruby -e 't = Time.now; (-2..2).each { |i| p [t + i, t - i] }'
[2019-07-27 20:33:39 +0900, 2019-07-27 20:33:43 …
```
=> Fix the lack of precision for `Time`; ref d74355061

mrbgems/mruby-enum-chain/mrblib/chain.rb
I think `Enumerator::Chain#initialize_copy` is unnecessary because CRuby
doesn't clone elements.
FYI, the remaining `each_with_object` in `Enumerator::Chain#initialize_copy`
was correction omission in #4599.
=> Remove `Enumerator::Chain#initialize_copy`

mrbgems/mruby-time/src/time.c
strftime() on Windows returns locale encoding time zone for "%z" even
if MSDN says "%z" is "The offset from UTC in ISO 8601 format; no
characters if time zone is unknown" in MSDN:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=vs-2019
So we need to convert encoding of string from strftime().
=> Fix Time#to_s encoding on Windows

mrbgems/mruby-bin-mruby/bintest/mruby.rb, mrbgems/mruby-complex/test/complex.rb, mrbgems/mruby-io/test/io.rb, mrbgems/mruby-pack/test/pack.rb, mrbgems/mruby-rational/test/rational.rb, test/assert.rb, test/t/numeric.rb
- I think "Info" is used only to `skip` (@dearblue right?), so change to "Skip".
- Changed the default value of `assert` and specify the argument explicitly at the caller of `assert` because it is unnatural "Assertion failed" is output even though the assertion doesn't fail.
```ruby
def assert_foo(exp, act)
assert do
assert_equal exp[0], act[0]
assert_equal exp[1], act[1]
end
end
def assert_bar(exp, act)
assert do
skip
end
end
def assert_baz(exp, act)
assert do
assert_equal exp, act
assert_bar exp, act
end
end
assert 'test#skip_in_nested_assert' do
assert_baz 1, 1
end
```
```text
?..
Info: test#skip_in_nested_assert (core)
- Assertion[1]
Info: Assertion failed (core)
- Assertion[1-2]
Skip: Assertion failed (core)
Total: 3
OK: 2
KO: 0
Crash: 0
Warning: 0
Skip: 1
```
```text
???
Skip: …
```
=> Refine message to `skip` in nested `assert`

mrbgems/mruby-time/src/time.c, mrbgems/mruby-time/test/time.rb
Use own implementation to calculate UTC offset on Visual Studio 2015 or
earlier or MinGW because `strftime("%z")` on these environments does not
conform C99.
=> Fix UTC offset representation in `Time#to_s` on some environments; ref #4604

mrbgems/mruby-test/driver.c, mrbgems/mruby-test/mrbgem.rake, mrbgems/mruby-test/vformat.c, src/error.c, test/t/vformat.rb
```text
%[modifier]specifier
```
```text
----------+------------------------------------------------------------
Modifier  | Meaning
----------+------------------------------------------------------------
!     | Convert to string by corresponding `inspect` instead of
| corresponding `to_s`.
----------+------------------------------------------------------------
```
```text
----------+----------------+--------------------------------------------
Specifier | Argument Type  | Note
----------+----------------+--------------------------------------------
c     | char           |
d,i    | mrb_int        |
f     | mrb_float      |
l     | char*, mrb_int | Arguments are string and length.
n     | mrb_sym        |
s     | char*          | Argument is NUL terminated string.
t     | mrb_value …
```
=> Add new specifiers/modifiers to format string of `mrb_vfromat()`

mrbgems/mruby-test/vformat.c, src/error.c, test/t/vformat.rb
It potentially not work when `mrb_float` is `float` because `float` variable
in variable length arguments is promoted to `double`.
Also I fixed build with `MRB_WITHOUT_FLOAT`.
=> Fix `mrb_vformat("%f")` with `MRB_USE_FLOAT`

include/mruby/numeric.h, mrbgems/mruby-numeric-ext/src/numeric_ext.c
- Added macros available from C to `include/mruby/numeric.h`.
- Added the constants available from Ruby space to `mruby-numeric-ext`.
Since `MRB_FLT_ROUNDS` can change its behavior, it is defined as a class method.
=> Add constants for floating point number

mrbgems/mruby-complex/mrblib/complex.rb, mrbgems/mruby-complex/src/complex.c, mrbgems/mruby-complex/test/complex.rb
Complex#abs is reimplemented in terms of Math.hypot. This function is defined in terms of the C99 hypot() function, which overflows only if the final result is not representable.
Example: without this modification, Complex(3e200, 4e200).abs returns infinity. The correct answer is 5e200.
The case of Complex divided by Complex is reimplemented in C, to maintain its performance. The implementation uses the textbook formula for complex division, but performs the arithmetic on (significand, exponent) pairs. This change avoids a great many needles overflows.
Example: without this modification, (1e201+1e201i) / (1e200+1e200i) returns (NaN+NaNi). The correct answer is (10.0+0.0i).
I have not attempted to reimplement multiplication this way. Complex multiplication can needlessly overflow in a few …
=> Avoid premature overflow in Complex#abs and Complex#/

include/mruby/string.h, src/string.c
The condition to make an embedded string was incorrect. Because there were
several similar codes, extracted into `RSTR_EMBEDDABLE_P` macro.
=> `mrb_str_modify_keep_ascii` can embed one more byte

src/gc.c, src/string.c
I think the string buffer of NOFREE string always exists and does not need
to be released, so it can be shared as another NOFREE string.
Also changed the `mrb_shared_string` field order so that eliminate padding if
`int` and `mrb_int` sizes are less than pointer size.
=> SHARED/FSHARED string is not required when sharing NOFREE string

src/string.c, test/t/string.rb
Previously `String#rindex` returned the wrong index when given an invalid UTF-8 string.
=> Fix `String#rindex` with invalid UTF-8 string

include/mruby/string.h, src/string.c
Introduce `RSTR_SET_TYPE_FLAG` macro to set the specified string type flag and
clear the others.
=> Refactor set/unset string type flags

include/mruby.h, include/mruby/irep.h, mrbgems/mruby-bin-debugger/tools/mrdb/apibreak.c, mrbgems/mruby-bin-debugger/tools/mrdb/apiprint.c, mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c, mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.h, mrbgems/mruby-compiler/core/codegen.c, mrbgems/mruby-eval/src/eval.c, src/array.c, src/backtrace.c, src/class.c, src/codedump.c, src/error.c, src/load.c, src/proc.c, src/state.c, src/vm.c
I thought about inline mruby bytecode like 5b1f25a, but iseq is basically no problems even if it is immutable.
However, there is a compatibility problem because the structure and functions are changed as an API.
Third party programs that incorporate mruby may stop working.
=> Prohibit changes to iseq in principle

src/string.c
Because this field is used as capacity of string buffer.
=> Rename `mrb_shared_string::len` to `mrb_shared_string::capa`

mrbgems/mruby-io/test/file.rb, mrbgems/mruby-io/test/mruby_io_test.c
If tests containing mruby-io are run in parallel, problems may occur due to the same symbolic link names.
https://github.com/mruby/mruby/blob/83dab1ee0d0d3aa76e44f7fbf14360ee501be151/mrbgems/mruby-io/test/file.rb#L180-L187
Perhaps you can solve the problem described at https://github.com/mruby/mruby/pull/4636#issuecomment-522312628.
=> Make symbolic link names unique for test

mrbgems/mruby-string-ext/src/string.c, src/string.c
- `mrb_str_index_m()` and `mrb_str_rindex()`
Make `mrb_get_args()` called only once from called twice.
- `mrb_str_byteslice()`
Replace `goto` with `if ~ else`.
=> Simplify get arguments

mrbgems/mruby-compiler/core/parse.y
`strncat()` also needs `'\0'`.
=> Suppress warnings for `strncat()`

include/mruby/common.h
When building WebAssembly targets with clang (e.g. wasm32-unknown-unknown), all
symbols are hidden by default. To export a symbol, it must be marked with
__attribute__((visibility("default")))
Rather than detecting this exotic target in mruby, allow MRB_API to be defined
externally.
=> Allow external definition of MRB_API macro

include/mruby/object.h, include/mruby/string.h, src/gc.c, src/string.c
On 64-bit CPU, there is padding in `RBasic`, so reorder the fields and use
it as buffer of embedded string. This change allows 4 more bytes to be
embedded on 64-bit CPU.
However, an incompatibility will occur if `RString::as::ary` is accessed
directly because `RString` structure has changed.
=> Use `RBasic` padding for embedded string on 64-bit CPU

Rakefile, lib/mruby/build.rb, lib/mruby/build/command.rb, lib/mruby/build/load_gems.rb
Inspired by https://udzura.hatenablog.jp/entry/2018/12/05/143801
Creates lock file to `"#{MRUBY_CONFIG}.lock`.
When pulled or `checksum_hash` is set should be updated with it.
Lock file looks like:
```yaml
---
builds:
host:
https://github.com/mattn/mruby-onig-regexp.git:
url: https://github.com/mattn/mruby-onig-regexp.git
branch: master
commit: 354c0df670fe6822528d5a508fb7722233f4b920
```
=> Support lock file for git.

Makefile.doc
I have error at make clean at no doxygen environment. 
% make clean
rm -r doxygen
rm: doxygen: No such file or directory
*** Error code 1
Stop.
This is work around for this error.
=> make clean error workaround

Rakefile, lib/mruby/build.rb, lib/mruby/build/load_gems.rb, lib/mruby/lockfile.rb
- Defer YAML library and lock file loading until needed.
- Don't write empty parts into lock file.
- Extract code to read/write lock file to `MRuby::Lockfile`.
- `MRuby::Lockfile.disable` disables the use of lock file.
---
The use of lock file is enabled by default (without external gem) and only the `mruby_version` part is written. However, since `mruby_version` part is unused and lock file doesn't make sense, I think it is better to disable the use of lock file by default.
=> Refine processing for gem lock file

include/mruby/boxing_no.h, include/mruby/error.h, src/vm.c
ref: https://github.com/mruby/mruby/pull/4483#issuecomment-498001736
In this configuration, `tt` of `RBreak::val` is set into `RBreak::flags`.
=> Fix `RBreak` exceeding 6 words on 32-bit mode w/o boxing and `MRB_USE_FLOAT`

mrbgems/mruby-io/test/file.rb, mrbgems/mruby-io/test/mruby_io_test.c
Because the linker gives a warning on FreeBSD 12.0.
```
warning: mktemp() possibly used unsafely; consider using mkstemp()
```
Even with travis-ci, there was a warning:
https://travis-ci.org/mruby/mruby/jobs/573416883#L1335-L1338
```
warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
```
=> Create a symbolic link in the temporary directory; fix #4642

mrbgems/mruby-random/src/random.c
Array index became potentially negative because `uint32_t` is cast to
`mrb_int`.
=> Fix `Array#sample` with `MRB_INT32`

.gitignore
Currently, `y.tab.c` is generated to under the `build/` directory.
=> Remove unneeded `/src/y.tab.c` in `.gitignore`

include/mruby/boxing_word.h, include/mruby/object.h, include/mruby/value.h
The default implementation of `mrb_immediate_p` uses `mrb_type`. However,
in `MRB_WORD_BOXING`, `mrb_type` has many branches and is inefficient, so
provide an implementation that does not use `mrb_type`.
=> Implement `mrb_immediate_p` macro for `MRB_WORD_BOXING`

mrbgems/mruby-array-ext/mrblib/array.rb, mrbgems/mruby-array-ext/test/array.rb
```terminal
$ bin/mruby -e '[1].permutation(-1){|v| p v}'  #=> [1]
```
```terminal
$ bin/mruby -e '[1].permutation(-1){|v| p v}'  #=> no output
```
=> `Array#permutation` with a negative argument should not yield

mrbgems/mruby-enum-chain/mrblib/chain.rb, mrbgems/mruby-enum-chain/test/enum_chain.rb
```ruby
e = [1]
def e.rewind; p :r end
c = e.chain(e)
c.each{break c}.rewind
```
```terminal
:r
:r
```
```terminal
:r
```
=> `Enumerator::Chain#rewind` shouldn't rewind elements aren't iterated

test/assert.rb
I added `assert_not_nil` method.
Of course there are other ways.
```ruby
assert_true target != nil
assert_false target.nil?
#etc...
```
However, I thought it was superior in terms of readability.
```ruby
assert_not_nil target
```
I did the following check.
```ruby
assert('assert_not_nil pass') do
assert_not_nil 'hoge'
end
assert('assert_not_nil fail') do
assert_not_nil nil
end
```
```
Fail: assert_not_nil fail (core)
- Assertion[1]
Expected nil to not be nil.
```
Please check.
=> Add `assert_not_nil` method

include/mruby/boxing_word.h
This change increases the max length of lower inline symbols to 5 bytes.
=> Increase symbol bit size on 32-bit mode with `MRB_WORD_BOXING`

src/error.c
If `MRB_INT16` is specified, the variable length argument `mrb_int` is converted to `int`.
----
When building with GCC (gcc-9.2.0), a warning is displayed.
```
src/error.c: In function 'mrb_vformat':
src/error.c:329:65: warning: 'mrb_int' {aka 'short int'} is promoted to 'int' when passed through '...'
329 |           i = *p == 'd' ? (mrb_int)va_arg(ap, int) : va_arg(ap, mrb_int);
|                                                                 ^
src/error.c:329:65: note: (so you should pass 'int' not 'mrb_int' {aka 'short int'} to 'va_arg')
src/error.c:329:65: note: if this code is reached, the program will abort
```
If I run it on FreeBSD as it is, it crashed by `SIGILL`.
----
**NOTE**: This patch may be undesirable because the value given as `int` will be converted to 16-bit …
=> Fix `mrb_vformat()` crashes with `MRB_INT16`

tasks/toolchains/clang.rake
`-Wzero-length-array` is not a mandatory option, so the original is better.
=> Revert part of "Refine `tasks/toolchains/(gcc|clang).rake`" (07c6b7f0)

mrbgems/mruby-compiler/core/parse.y
CRuby supports a 'o' `Regexp` option for `Regexp` literals, e.g. `/foo/o` that disables multiple interpolation passes.
This commit adds support for parsing such literals. Nothing is done with the option, it is consumed and ignored by the parser.
=> Support parsing a Regexp literal with 'o' option

mrbgems/mruby-io/mrblib/io.rb
"Fix broken UTF-8 characters by `IO#getc`" (https://github.com/mruby/mruby/commit/992ba476a95136eaad5b9b208d4ca5a1ca31324d) increases the object code size without `MRB_UTF8_STRING` too, so I would like to improve if there is a better solution (but no idea).
=> Fix mruby-io

src/class.c
1. Cache argv first in each specifiers for `mrb_get_args()`; ref #3090
In terms of specifiers, argv is never referenced after a method call as shown in #3090.
Reduction of object code can be expected.
If you need to refer to argv after a method call in the same loop, update argv after the method call.
2. Integrated the `!` modifier part.
As a side effect, all specifiers now accept the `!` modifier.
----
The object file size comparison uses cross-compileable GCC available in FreeBSD 12.0.
Only `src/class.c` is compiled with `-Os` switch.
The compared branches are:
0.[2f9b1fdb0](https://github.com/mruby/mruby/commit/2f9b1fdb0c6ec4835b66b26db52ef7b98b9554b8) : Currently master
1.[f312638ec](https://github.com/mruby/mruby/commit/f312638ecd0d9d884d0600c5ad44f4c00a6c313b) : Cache argv first in …
=> Shrink `mrb_get_args()`

src/numeric.c, test/t/integer.rb
```terminal
$ bin/mruby -e 'p 3.to_s(2)'
[0] -e:1
-e:1: 'to_s': wrong number of arguments (1 for 0) (ArgumentError) 
```
```terminal
$ bin/mruby -e 'p 3.to_s(2)'
"11"
```
=> Fix `Fixnum#(to_s|inspect)` argument specs

doc/guides/mrbconf.md, include/mrbconf.h, include/mruby/value.h, src/load.c
In lld linked programs, .rodata comes before .text, thus mrb_ro_data_p
will return false for strings in .rodata. Change the lower bound from
_etext to __ehdr_start to catch these cases. This works for ld.bfd, gold
and lld, and it does not have false positives even if .init_array does
not exist.
Remove the branch that uses _edata: strings in .data can be modified so
this is semantically incorrect. Delete the `__APPLE__` branch (its
manpages say get_etext() and get_edata() are strongly discouraged).
.init_array has been adopted by most ELF platforms to supersede .ctors.
Neither _etext nor _edata is used, so rename MRB_USE_ETEXT_EDATA to
MRB_USE_EHDR_START.
-------------------------------
This removes code added by #3639 @Asmod4n You can use `MRB_USE_CUSTOM_RO_DATA_P` instead. The `_edata` …
=> Rename MRB_USE_ETEXT_EDATA to MRB_USE_LINK_TIME_RO_DATA_P and support lld linked programs

include/mruby/boxing_word.h, include/mruby/value.h
The default implementations of type predicate macros use `mrb_type`.
But `mrb_type` with `MRB_WORD_BOXING` isn't very efficient, so the new
implementations avoid `mrb_type`.
=> Implement all type predicate macros for `MRB_WORD_BOXING`

include/mruby/value.h
The value of `MRB_TT_HAS_BASIC` is meaningless because `MRB_TT_HAS_BASIC` is
no longer used with `MRB_WORD_BOXING` at b2c3d88f.
=> Remove `MRB_TT_HAS_BASIC` macro

mrbgems/mruby-sprintf/src/sprintf.c
Match the type with the caller and related functions.
=> Keep the type of `posarg` consistent

src/error.c
If a `break` global jump occurs from mruby space via `mrb_protect()`, `mrb_exc_raise()` will raise a `TypeError` exception if you use `mrb_exc_raise()` to resend.
As a countermeasure, this patch makes `mrb_exc_raise ()` also accept `MRB_TT_BREAK` objects.
Example (C code is in last because it is a few large):
- Before patched:
```console
% gcc -Wall -g3 -Og -Iinclude rbreak.c build/host/lib/libmruby.a -lm
% ./a.out
rbreak.c:19:trial_yield
rbreak.c:33:test_enter: type=MRB_TT_BREAK
TypeError: exception object expected
```
- After patched:
```console
% gcc -Wall -g3 -Og -Iinclude rbreak.c build/host/lib/libmruby.a -lm
% ./a.out
rbreak.c:19:trial_yield
rbreak.c:33:test_enter: type=MRB_TT_BREAK
:broken
```
- Sample C code (`rbreak.c`):
```c
#include <mruby/error.h>
#include …
```
=> Allow rethrowing `MRB_TT_BREAK`

include/mruby/hash.h
The type `mrb_hash_value` is no longer used by the segmented list implementation (ref e8dcfe1 and e65d426).
=> Remove unnecessary type `mrb_hash_value`

mrbgems/mruby-compiler/core/parse.y
Add support for the following node types:
- NODE_DSYM
- NODE_WORDS
- NODE_SYMBOLS
- NODE_LITERAL_DELIM
=> Dump more node types in `mrb_parser_dump`

src/pool.c
These are included in `mruby.h`.
As a background, if `enable_cxx_abi` is specified, the macro that defines the maximum value in `stdint.h` is undefined depending on the environment.
- Confirmed with gcc on FreeBSD 12.0 and mingw32-gcc available on FreeBSD.
- `INTPTR_MAX`, `INT64_MAX` and `UINT64_MAX` are defined by `cstdint` added in C++11. But `toolchains :gcc` adds `-std=c++03`, so the macros are not defined.
- To have these defined in `C++03`, `__STDC_CONSTANT_MACROS` must be defined in advance. This is already done by `mruby.h`.
=> Remove duplicates header files in `src/pool.c`

mrbgems/mruby-print/mrblib/print.rb
In the old implementation, `Kernel#printf` raise error if `mruby-sprintf`
gem isn't specified before `mruby-print` gem. The new implementation
eliminates this ordering issue. This way is the same as `Kernel#printf` and
`IO#printf` in `mruby-io` gem.
=> Drop initialization dependency from `mruby-print` to `mruby-sprintf`

mrbgems/mruby-bin-debugger/tools/mrdb/apiprint.c, mrbgems/mruby-bin-debugger/tools/mrdb/cmdprint.c
```
$ echo 'p true' | bin/mrdb /dev/null
(/dev/null:1) mruby application exited.
FrozenError: can't modify frozen String
(-:0)
```
```
$ echo 'p true' | bin/mrdb /dev/null
(/dev/null:1) $1 = true
(/dev/null:1)
```
=> Fix that `print` command raises `FrozenError` in `mrdb`; ref 1f5a7f2f

src/string.c
Because it may not create `struct mrb_shared_string`.
=> Rename `str_make_shared()` to `str_share()` in `src/string.c`

src/string.c
The heap string buffer of POOL string always exists, does not need to be
released, and read only, so it can be shared as NOFREE string.
=> SHARED string is not required when sharing POOL string

src/class.c
- Use `mrb_sym_name_len` instead of `mrb_sym_name` (class name should not
be escaped).
- Avoid `mrb_str_dup` (it is unnecessary to be shared string because it is
changed).
=> Refactor `mrb_class_name_class`

src/dump.c
In commit 401ad4586ffe8bc26740f49f9049132ad2c50539, add `extern` like this:
https://github.com/mruby/mruby/commit/401ad4586ffe8bc26740f49f9049132ad2c50539#diff-669d4cc5c9c8f4573c5f8d57f5dcab20
When including byte code in C function,
```
mrbc -g -Bwatchcode -owatch_ruby.h watch.rb
```
the `extern` cause compile error.
```
watch_ruby.h:11:1: error: declaration of 'watchcode' with no linkage follows extern declaration
watchcode[] = {
^~~~~~~~~
watch_ruby.h:4:22: note: previous declaration of 'watchcode' was here
extern const uint8_t watchcode[];
```
This patch fixes the problem.
=> Remove constant export declaration for MRBC output compiled as C

mrbgems/mruby-io/mrblib/kernel.rb
`Kernel#getc` has been removed since Ruby 1.9 and is not defined in ISO.
=> Remove `Kernel#getc`

src/string.c
```ruby
s = "\u3042"
p s.size
s.dump
p s.size
```
```
1
3
```
```
1
1
```
=> Fix incorrect `MRB_STR_ASCII` flag update in `mrb_str_dump`

src/string.c
```ruby
COUNT = 300000
SIZE = 10000
s = "a" * SIZE
s.size  # set `MRB_STR_ASCII` flag
i = 0
while i < COUNT
s[-1]
i += 1
end
```
```
$ time mruby benchmark.rb
2.06 real         2.05 user         0.00 sys
```
```
$ time mruby benchmark.rb
0.05 real         0.04 user         0.00 sys
```
=> Optimize `str_subseq` with `MRB_UTF8_STRING` to ASCII only string

src/string.c
```
$ mruby -e '
COUNT = 150000
SIZE = 10000
strs = Array.new(COUNT) do
s = "a" * SIZE
s.size  # set `MRB_STR_ASCII` flag
s
end
i = 0
t = Time.now
while i < COUNT
strs[i][-2..-1] = ""
i += 1
end
printf "%.2f sec\n", Time.now - t
'
1.10 sec  # before
0.07 sec  # after
```
=> Optimize `chars2bytes` with `MRB_UTF8_STRING` to ASCII only string

mrbgems/mruby-array-ext/test/array.rb
`Object.const_defined?(:Enumerator)` is always false because
`mruby-enumerator` is not specified in `test_dependency`. I don't
think this test is necessary.
=> Remove test that depend on `mruby-enumerator` from `mruby-array-ext`

mrbgems/mruby-compiler/core/parse.y
```
$ bin/mruby -e 'p <<EOS
1
EOS'
-e:4:0: can't find heredoc delimiter "EOS" anywhere before EOF
-e:4:0: syntax error, unexpected $end, expecting tHEREDOC_END or tHD_STRING_PART or tHD_STRING_MID
```
```
$ bin/mruby -e 'p <<EOS
1
EOS'
"1\n"
```
=> Fix here document with EOF

mrbgems/mruby-class-ext/src/class.c, mrbgems/mruby-symbol-ext/mrblib/symbol.rb, src/class.c, src/symbol.c, src/variable.c
This feature was reverted from Ruby 2.7.
=> Revert "Implement Ruby2.7's frozen strings from `Symbol#to_s`"

include/mrbconf.h, mrbgems/mruby-compiler/core/parse.y
I think they can always be enabled because the regular expression literal is
always enabled.
=> Always enable the rational and complex literals

include/mruby/array.h, include/mruby/string.h, include/mruby/value.h, src/string.c
Previously, `mrb_int` was used as the type that represents the buffer size
on memory, but the sizes of `RString` and `RArray` exceed 6 words when
`MRB_INT64` is enabled on 32-bit CPU.
I don't think it is necessary to be able to represent the buffer size on
memory that exceeds the virtual address space. Therefore, for this purpose,
introduce `mrb_ssize` which doesn't exceed the sizes of `mrb_int` and
pointer.
I think all `mrb_int` used for this purpose should be changed to
`mrb_ssize`, but currently only the members of the structures (`RString`,
`mrb_shared_string`, `RArray` and `mrb_shared_array`) are changed.
=> Introduce `mrb_ssize` type for buffer size on memory; ref #4483

mrbgems/mruby-bin-mruby/bintest/mruby.rb, mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
```
$ bin/mruby -ce 1
bin/mruby: Cannot open program file: 1
```
```
$ bin/mruby -ce 1
Syntax OK
```
=> Support short options concatenation to `mruby` command

mrbgems/mruby-bin-mruby/bintest/mruby.rb, mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
```
$ bin/mruby -e 'p ARGV' a b
["bin/mruby", "-e", "p ARGV", "a", "b"]
```
```
$ bin/mruby -e 'p ARGV' a b
["a", "b"]
```
=> Fix `ARGV` value in `mruby` command (regression by #4827)

include/mruby/boxing_word.h, include/mruby/string.h, include/mruby/value.h, src/string.c, src/symbol.c
The bit width terminology is unified to `BIT` according to `MRB_ INT_BIT`
and `CHAR_BIT`. Also the bit position terminology is unified to `BIT_POS`.
=> Rename `BITSIZE` to `BIT` and `BIT` to `BIT_POS` for consistency

mrbgems/mruby-bin-mruby/bintest/mruby.rb, mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
```
$ bin/mruby -e 'p ARGV' -- -x
bin/mruby: invalid option -- (-h will show valid options)
```
```
$ bin/mruby -e 'p ARGV' -- -x
["-x"]
```
=> Support `--` (end of options) to `mruby` command

mrbgems/mruby-bin-mruby/bintest/mruby.rb, mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
```
$ bin/mruby --verbose -e 'p 1'
bin/mruby: Cannot open program file: --verbose
```
```
$ bin/mruby --verbose -e 'p 1'
(snip)
irep 0x7fe97041df30 nregs=4 nlocals=1 pools=0 syms=1 reps=0 iseq=11
file: -e
1 000 OP_LOADSELF R1
(snip)
1
```
=> Fix `mruby --verbose` (regression by #4827)

include/mruby/boxing_nan.h, include/mruby/boxing_no.h, include/mruby/boxing_word.h, include/mruby/value.h
```ruby
max32 = 2**30 - 1 + 2**30
min32 = -max32-1
[max32, max32+1, min32, min32-1].each{|n| p [n, n.class]}
```
```
[2147483647, Float]
[2147483648, Float]
[-2147483648, Float]
[-2147483649, Float]
```
```
[2147483647, Fixnum]
[2147483648, Float]
[-2147483648, Fixnum]
[-2147483649, Float]
```
=> Fix `MRB_FIXNUM_SHIFT` with `MRB_WORD_BOXING`, `MRB_INT32` and `MRB_64BIT`

mrbgems/mruby-time/src/time.c
Silence the following warning:
```
/mruby/mrbgems/mruby-time/src/time.c:258:60: warning: result of comparison of constant -9223372036854775808 with expression of type 'mrb_int' (aka 'int') is always false [-Wtautological-constant-out-of-range-compare]
if ((mrb_time_int)i > MRB_TIME_MAX || MRB_TIME_MIN > i) {
~~~~~~~~~~~~ ^ ~
```
=> Silence Clang warning with `MRB_INT32` and `MRB_64BIT` in `time.c`

mrbgems/mruby-time/src/time.c
Silence the following warnings:
```
/mruby/mrbgems/mruby-time/src/time.c:871:15: warning: result of comparison of constant 9223372036854775807 with expression of type 'time_t' (aka 'long') is always false [-Wtautological-constant-out-of-range-compare]
if (tm->sec > MRB_INT_MAX || tm->sec < MRB_INT_MIN) {
~~~~~~~ ^ ~~~~~~~~~~~
/mruby/mrbgems/mruby-time/src/time.c:871:40: warning: result of comparison of constant -9223372036854775808 with expression of type 'time_t' (aka 'long') is always false [-Wtautological-constant-out-of-range-compare]
if (tm->sec > MRB_INT_MAX || tm->sec < MRB_INT_MIN) {
~~~~~~~ ^ ~~~~~~~~~~~
/mruby/mrbgems/mruby-time/src/time.c:887:16: warning: result of comparison of constant 9223372036854775807 with expression of type 'time_t' (aka 'long') is always false …
```
=> Silence Clang warning with `MRB_INT64` and `MRB_32BIT` in `time.c`

src/gc.c
* The allocated memory is guaranteed to be aligned for any data type (it was
not guaranteed when string type is embed).
* Make allocation size exactly specified size (does not allocate space for a
null byte).
=> Refine `mrb_alloca()`

src/string.c
```
$ bin/mruby -e 'Float("1_a")'
-e:1: invalid string for float(a) (ArgumentError)
```
```
$ bin/mruby -e 'Float("1_a")'
-e:1: invalid string for float("1_a") (ArgumentError)
```
=> Fix the error message of `Kernel#Float`

src/class.c
If ":" is after "|" and there is no "?" or "*", the keyword argument could not be obtained and it was not initialized with `undef`.
For example: "|oo:"
----
Even before the patch (mruby-2.1.0), ":|o" and "|o*:" etc work without problems.
However, "|oo:" described as an example is not assigned to keyword arguments at all.
Therefore, if the variable is accessed as it is, SIGSEGV will be executed in some cases.
Sorry!
=> Fix keyword arguments not be obtained with `mrb_get_args()`; Fix #4754

mrbgems/mruby-kernel-ext/test/kernel.rb, src/string.c, test/t/string.rb
Consecutive `_` is not allowed as a numeric expression:
```ruby
1_2__3             #=> SyntaxError
Float("1_2__3")    #=> ArgumentError
Integer("1_2__3")  #=> ArgumentError
"1_2__3".to_i      #=> 12
```
But `String#to_f` accept it, so I fixed the issue.
Before this patch:
```ruby
"1_2__3".to_f      #=> 123
```
After this patch:
```ruby
"1_2__3".to_f      #=> 12
```
=> Fix that `String#to_f` accepts consecutive `_` as a numeric expression

mrbgems/mruby-kernel-ext/test/kernel.rb, src/string.c, test/t/string.rb
```ruby
Integer("_1")  #=> 1
"_1".to_i      #=> 1
```
```ruby
Integer("_1")  #=> ArgumentError
"_1".to_i      #=> 0
```
=> Fix behavior of `String#to_i`/`Kernel#Integer` to numbers starting with `_`

mrbgems/mruby-kernel-ext/test/kernel.rb, src/string.c, test/t/string.rb
```ruby
Integer("1_ ")  #=> 1
```
```ruby
Integer("1_ ")  #=> ArgumentError
```
=> Fix behavior of `Kernel#Integer` to numbers ending with `_` and spaces

src/array.c
```
$ mruby -e '[].each(1){}'  #=> no error
```
```
$ mruby -e '[].each(1){}'  #=> ArgumentError: wrong number of arguments
```
=> Fix arguments check to `Array#each`

mrbgems/mruby-io/README.md, mrbgems/mruby-io/mrbgem.rake, mrbgems/mruby-pack/README.md, mrbgems/mruby-pack/mrbgem.rake, mrbgems/mruby-sleep/mrbgem.rake, mrbgems/mruby-sleep/src/mrb_sleep.c, mrbgems/mruby-socket/README.md, mrbgems/mruby-socket/mrbgem.rake
It is writing side by side with the original authors.
----
Although it is redundant, it is the simplest description.
For your reference, list the added commits.
| gem name     | year | release | commit                                   |
| ------------ | ---- | ------- | ---------------------------------------- |
| mruby-io     | 2017 |   1.4.0 | d75266dd1bade53255044460a9cd74596addaa84 |
| mruby-pack   | 2017 |   1.4.0 | a5412d48fd1bb55288cb168a92efd0f2045781c1 |
| mruby-socket | 2017 |   1.4.0 | 73ef548c6386a1101b5d95654bcb142ab83149c7 |
| mruby-sleep  | 2018 |   2.0.0 | 44fdd53f2e5bac6fe1cbc2ceb653aa5f2de965e6 |
=> Add "mruby developers" into some gems; Resolve #4709

src/class.c
The `#prepend_features` and `#module_function` methods are not haves for class objects.
=> Remove module only methods from class

mrbgems/mruby-io/test/mruby_io_test.c
=> Fix mruby-io test for mingw32

src/backtrace.c, src/error.c, src/print.c
The following improvements are made according to Ruby's behavior:
- Match location number to index.
- Remove duplicate most recent call output.
- Fix that first call is not output when array (unpacked) backtrace.
```ruby
def a; raise "error!" end
def b; a end
begin
b
rescue => e
e.backtrace if ARGV[0] == "unpack"  # unpack backtrace
raise e
end
```
```console
$ bin/mruby example.rb unpack
[0] example.rb:2:in b
[1] example.rb:1:in a
example.rb:1: error! (RuntimeError)
```
```console
$ bin/mruby example.rb unpack
[2] example.rb:4
[1] example.rb:2:in b
example.rb:1:in a: error! (RuntimeError)
```
=> Refine output of `mrb_print_error()`

include/mruby/class.h, src/error.c, src/string.c, test/t/exception.rb
Because location info (file name and line number) is kept in the backtrace,
it should not be kept in the result of `inspect` (and the exception object
itself), I think.
```ruby
begin
raise "err"
rescue => e
p e
end
```
```
example.rb:2: err (RuntimeError)
```
```
err (RuntimeError)
```
=> Remove location info from `Exception#inspect`

src/error.c
If `mrb_sym` is smaller than `int`, it is promoted to `int`.
=> Fix potentially crash in `%n` of `mrb_vformat()` with 64-bit `int`

mrbgems/mruby-compiler/core/parse.y, test/t/syntax.rb
```console
$ bin/mruby rb -e '_0=:l; p ->{_0}.()'
-e:1:13: _0 is not available
-e:1:13: syntax error, unexpected $end, expecting '}'
```
```console
$ bin/mruby rb -e '_0=:l; p ->{_0}.()'
:l
```
=> `_0` is not numbered parameter

minirake
```console
$ ./minirake --foo; echo $?
invalid option: --foo
0
```
```console
$ ./minirake --foo; echo $?
invalid option: --foo
1
```
=> Use `exec` instead of `system` in `minirake` for exit status

.travis.yml
* Use `rake` instead of `minirake`.
* Remove `gperf` configuration.
Execution time seems to be reduced by about 15%.
=> Refine `.travis.yml`

lib/mruby/build/command.rb, lib/mruby/build/load_gems.rb
With this change, if the checkout fails, it will stop with an error.
The purpose is to avoid deleting working branch history when developing gem.
Also, make sure that directories are also displayed during `git reset` and `git checkout`.
----
Removing the `.lock` file every time, or calling the `MRuby::Build#disable_lock` method can avoid losing the working branch, but I think it's better to raise an error.
This suggestion will be withdrawn if there are other good practices.
=> Use `git checkout` instead of `git reset`

.travis.yml
Parallel execution of tests makes log difficult to see due to mixing.
=> Parallelize compilation only on Travis CI

lib/mruby/build.rb
Double quotes for filenames was removed from both filename and cygwin_filename by the commit  b7bc03aa18f3cc5eac0bbd6690e24062df9fe837.
However cygwin needs it to recognize windows style file path.
=> Add double quotes for cygwin filenames #4904

include/mruby/class.h, src/class.c, src/gc.c
```ruby
GC.start
c = Class.new
p c            #=> #<Class:0x7fd6a180e790>
c.new          #=> cache `c.new`
c = nil
GC.start       #=> `c` is GCed
r = Range.dup
p r            #=> #<Class:0x7fd6a180e790>
r.new(2, 3)    #=> ArgumentError: 'initialize':
```
An entry of method cache is identified by class pointer and method
id. However, reusing memory after GC may create a class with the same
pointer as the cached class.
Cleared method caches of the class when the class is GCed.
=> Fix potentially use of wrong method cache

Rakefile, lib/mruby/build.rb, lib/mruby/build/command.rb, lib/mruby/build/load_gems.rb, lib/mruby/gem.rb, mrbgems/mruby-bin-config/mrbgem.rake, mrbgems/mruby-compiler/mrbgem.rake, mrbgems/mruby-test/mrbgem.rake, mrblib/mrblib.rake, tasks/doc.rake, tasks/libmruby.rake, tasks/mrbgems.rake
- Respect `--verbose(-v)` and `--dry-run(-n)` options.
- Silence warnings to keyword arguments on Ruby 2.7.
=> Use Rake DSL instead of commands of `FileUtils`

Rakefile, lib/mruby-core-ext.rb, lib/mruby/build.rb, lib/mruby/build/command.rb
The incompatibility that the commands of `FileUtils` origin output verbose
by default due to the changes in d8a5163b and 26e6e75b is also fixed.
=> Use `Rake.verbose` instead of `$verbose` and `$pp_show` in build scripts

.gitlab-ci.yml, tasks/gitlab.rake
There was an error in the `.gitlab-ci.yml` generation script, so it was also
fixed.
=> Use `rake` instead of `minirake` in `.gitlab-ci.yml`

mrbgems/mruby-io/test/mruby_io_test.c
What I intended to fix in #4869 was a patch for an old MinGW.
Recent MinGWs have their own `mkstemp()` function.
I knew this after checking the patch #4903.
----
For your reference, the commits added to MinGW are also shown:
- mingw32: (2014-12-02) https://osdn.net/projects/mingw/scm/git/mingw-org-wsl/commits/ed7dcf1eb8b2fefb647b45a3f472524bb63fd870
- mingw-w64: (2015-01-07) https://sourceforge.net/p/mingw-w64/mingw-w64/ci/f713f639f6f017371c5176f4deab07d1a92473b4/
MinGW provided by the official package of FreeBSD is old.
(I did not know this....)
=> Fix builds for modern mingw; fix #4869

mrbgems/mruby-time/src/time.c
Silence the following warnings:
```
/mruby/mrbgems/mruby-time/src/time.c:260:55: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if ((MRB_INT_MAX > MRB_TIME_MAX && i > 0 && i > MRB_TIME_MAX) ||
^
```
=> Silence GCC warning in `time.c` on Travis CI

src/fmt_fp.c
`MRB_WITHOUT_FLOAT` is *un*defined, and if you build it as C ++ ABI for `MRB_DISABLE_STDIO` or Windows, the situation will be the same as #4750.
So I will fix it.
I borrowed it from take-cheeze's without permission, but I am able to confirm it in the log data by GithubActions:
https://github.com/take-cheeze/mruby/runs/360977783#step:4:833
=> Do not include `stdint.h` before `mruby.h`; ref #4750

src/string.c
Because literal pool may be released by GC.
```ruby
s1 = eval('"abcdefghijklmnopqrstuvwxyz01"')
GC.start
p s1  #=> "\x00\x00\x00\x00\x00\x00\x00\x90\x00\x00\x00\x00\x00\x00\x00\x90\x03\x00stuvwxyz01"
```
=> Revert "SHARED string is not required when sharing POOL string" (75949836)

include/mruby.h, mrbgems/mruby-io/src/io.c, mrbgems/mruby-socket/src/socket.c, mrbgems/mruby-struct/src/struct.c, src/error.c, src/hash.c, src/kernel.c
To unify the style of messages.
=> Add `mrb_num_args_error()` for "wrong number of arguments" error

src/class.c
The behavior when returning from a function without `va_end()` is undefined.
=> Call `va_end()` before return

mrbgems/mruby-io/include/mruby/ext/io.h, mrbgems/mruby-io/mrblib/file_constants.rb, mrbgems/mruby-io/src/file.c, mrbgems/mruby-io/src/io.c
Note that this bit flags are not compatible with the native flags defined in `#include <fcntl.h>`.
=> Support bit flags for `IO.open`

mrbgems/mruby-io/src/io.c
An as-of-yet incomplete project of mine embedding mruby in iOS has revealed that `struct timeval` on recent versions of Darwin iOS is defined in `sys/time.h`.
This should have a minimal impact on other platforms.
<details>
If you wish to have a test for this I will be able to produce one in time. Currently I use a very hacked up xcode project file that includes a set of C files generated by mrbgems, and the project file is not fit for general consumption because it only includes a very specific set of mrbgems.
Once I have a working project file generation tool I will share it and this problem will become obvious, or if you have a minimal project using iOS you can see this issue.
I may be doing it wrong and could have been a build setting away from making mruby compile on iOS without this …
=> Include time.h for ios

.github/workflows/main.yml
OSS-Fuzz was wondering if mruby would use CIFuzz, a new feature being rolled out 
in OSS-Fuzz. It allows for pull requests to be fuzzed in CI using fuzz targets enabled 
in OSS-Fuzz. Documentation for this feature can be found [here](https://google.github.io/oss-fuzz/getting-started/continuous-integration/). 
Let us know if you have any questions!
=> Add CIFuzz action
