mruby/mruby

include/mruby.h
mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c
mrbgems/mruby-bin-mirb/tools/mirb/mirb.c
mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
tools/mrbc/mrbc.c

* `mrb_show_version()`
* `mrb_show_copyright()`

Removed duplicated declarations.

---

src/error.c

Use mrb_exc_new_str_lit().

---

mrbgems/mruby-string-ext/mrblib/string.rb
mrbgems/mruby-string-ext/test/string.rb

add String#ljust into mruby-string-ext

---

README.md

update stable version number in README

---

doc/debugger/README.md

This commit is for updating the debugger readme to follow the rules for capitalizing titles, add some prepositions and determiners.
Hope this helps :)

update grammar and preposition for debugger readme

---

src/vm.c

Right now everything works, there's no critical needs to adopt this.
However, I just think I might be better to use setter macro instead of directly setting the variables, since we already have the macros :)

Use setter macro instead of directly setting values

---

test/t/integer.rb

Sorry. My test(#2762) appears warning. This patch fix it

Fix to avoid warning

---

src/parse.y

parser: fix possible null dereferences

---

src/codegen.c
test/t/syntax.rb

fix splat without assignment

---

src/string.c

String#split fails to split some strings on their second or later separators.
```ruby
a = "a.b.c.d"; p a
b = a.gsub('.', '-'); p b
c = b.split('-'); p c
```
```
% mruby a.rb
"a.b.c.d"
"a-b-c-d"
["a", "b-c-d"]
% ruby a.rb
"a.b.c.d"
"a-b-c-d"
["a", "b", "c", "d"]
```

String#split fails to split on second or later separator

---

include/mruby/throw.h
src/codegen.c
src/error.c
src/parse.y
src/vm.c

Move "src/mrb_throw.h" to "include/mruby/throw.h".

---

test/t/syntax.rb

They all fail at the moment. At least one of them may even cause a segfault.

failing multiple assignment with rest tests

---

AUTHORS
doc/api/README.md
doc/api/mruby.h.md
doc/api/value.h.md

I wrote more documentation for some of the functions found in mruby.h and value.h. I also wrote examples of how they can be used.

Added more documentation for some of the functions found in mruby.h and value.h

---

mrbgems/mruby-compiler/core/codegen.c

see https://github.com/mruby/mruby/issues/2769#issuecomment-107511261

push only after OP_GETCONST in VAL mode

---

src/string.c

mruby not support regexp, so remove these samples.

[ci skip] Remove some Srting#split samples

---

doc/mrbgems/README.md
tasks/mrbgem_spec.rake
tasks/mruby_build_gem.rake

This pull request adds `:mgem` gem loader to load mrbgem from mgem-list.
And it will support auto mrbgem dependencies solving from mgem-list and core mrbgems too.

Add :mgem gem loading.

---

mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-string-utf8/src/string.c
src/dump.c

Just some style issues.
(see #2871)

Coverity: fix missing break in switch defects

---

src/fmt_fp.c
tasks/toolchains/androideabi.rake

I pull request at github  first time.
If anything do wrong, please tell me, thanks!

fix androideabi cross-compile error : undefined reference to 'frexpl'

---

src/etc.c

Remove non-need tmp value in mrb_obj_to_sym

---

src/array.c

Remove duplicated RARRAY_LEN check in ary_elt

---

mrblib/array.rb

* use x.nil? instead of x == nil
* delete no-need space

array.rb: refactor some code

---

mrblib/array.rb
mrblib/enum.rb
mrblib/numeric.rb
mrblib/range.rb
mrblib/string.rb

* Avoid using {...} for multi-line blocks
* Remove redundant code
* Add space in default value assignment

Refactor mrubygem code (range.rb, numeric.rb, string.rb, array.rb, enum.rb)

---

doc/api/mruby/string.h.md

I wrote some documentation for the C API in the string.h. I left out examples this time because I'm thinking that maybe examples aren't necessary for this reference despite positive feedback doing so has gotten. I was planning to get more into that stuff on my future blog posts about mruby. If I'm wrong about this please let me know.

C string.h API documentation.

---

mrblib/string.rb
test/t/string.rb

cf. http://docs.ruby-lang.org/en/2.2.0/String.html#method-i-5B-5D-3D

support String#[pos, len]= val

---

README.md

Small copy and styling updates

Small Markdown updates to README.md

---

mrbgems/mruby-bin-mruby/bintest/mruby.rb
mrbgems/mruby-bin-strip/bintest/mruby-strip.rb
mrbgems/mruby-compiler/bintest/mrbc.rb
test/bintest.rb

* correct command name
* quote strings by each OSs's way.

fix tests on windows.

---

src/string.c
test/t/string.rb

chop with utf-8. fix #2967

---

mrbgems/mruby-print/src/print.c

code is encoded by utf-8
```
puts "森鷗外"
```
When print string into tty, it should be displayed correctly on windows.
But when output into non-tty, it should be utf-8 remaining.

print unicode on windows console

---

build_config.rb
include/mruby.h

Wrote reference documentation for mrb_obj_dup, and mrb_obj_respond_to. I Also fixed a mistake I made on mrb_class_defined.

Added more YARD docs to mruby.h

---

src/numeric.c

fix_lshift & fix_rshift can return float.

fix comment

---

build_config.rb

Fix MRB_ENABLE_DEBUG_HOOK config typo left from 4440566

---

travis_config.rb

Enable full-debug build on travis using `MRB_ENABLE_DEBUG_HOOK`

---

mrbgems/mruby-compiler/core/codegen.c

Compilation was failing on Darwin at least.

Fix typo on MRB_DISABLE_STDIO.

---

mrbgems/mruby-numeric-ext/mrblib/numeric_ext.rb
mrbgems/mruby-numeric-ext/test/numeric.rb

I want to use Numeric#nonzero? in mruby, like CRuby.

Support Numeric#zero? and Numeric#nonzero?

---

mrbgems/mruby-array-ext/mrblib/array.rb
mrbgems/mruby-array-ext/test/array.rb
mrbgems/mruby-hash-ext/mrblib/hash.rb
mrbgems/mruby-hash-ext/test/hash.rb
mrbgems/mruby-string-ext/mrblib/string.rb
mrbgems/mruby-string-ext/test/string.rb

and `Array#to_ary` that is used in Array.try_convert.

add {Array|Hash|String}.try_convert

---

mrbgems/mruby-bin-mirb/tools/mirb/mirb.c

works as same as irb
```
$ cat test.rb
puts "foo"
$ mirb test.rb hello
foo
=> nil
> p ARGV
["hello"]
=> ["hello"]
```

mirb should take filename and arguments.

---

.travis.yml

/cc @banzaiman
https://github.com/mruby/mruby/commit/bfcc55fbf98665b33ca7110349aeb66d3ef0df1d#commitcomment-14812510

Test against latest xcode

---

include/mruby.h

Added documentation for mrb_funcall(), mrb_funcall_argv(), mrb_funcall_with_block(), and mrb_intern_cstr().

Added YARD docs in new mruby.h

---

src/variable.c
test/t/class.rb

Fix class variable reference in module

---

README.md

A lot less friction than compiling from source :-)

Update README to mention ruby version management tools

---

src/class.c

mrb_get_args() keeps pointer of the current stack. But address of the
current stack maybe changed by method call.
'i' format character calls #to_i when the argument isn't integer but
has #to_i.
Here is a code that may call #to_i in mrb_get_args():
case 'i':
// ...
default:
*p = mrb_fixnum(mrb_Integer(mrb, ARGV[arg_i]));
break;
// ...
Here is a code #to_i is called:
class X
def initialize(i)
@i = i
end
def to_i
@i
end
end
[][X.new(0), 0] # X#to_i is called
So, mrb_get_args() shouldn't keep pointer and use it. mrb_get_args()
should always refer mrb->ci->stack to use valid address of the current
stack.

Fix SEGV by stack extension in mrb_get_args()

---

mrbgems/mruby-compiler/core/parse.y

Fix a typo

---

appveyor.yml
appveyor_config.rb

AppVeyor is Windows CI (http://www.appveyor.com/).
It is very helpful for the development of mruby.

Add appveyor.yml

---

src/vm.c

See https://github.com/mruby/mruby/pull/3142#issuecomment-201138873

Use stack directly

---

src/vm.c

d4ee409ae912dec6eb719a5727da4566f817d9d8 should remove this line.

Remove needless assignment

---

include/mruby/numeric.h

Somewhat related to #3149 which will be fixed by a future PR.

improve checked mrb int arithmetic implementation

---

include/mruby/numeric.h
src/numeric.c
src/vm.c

add function for checked mrb_int multiplication

---

doc/guides/mrbgems.md

I had been confused so I added.

Update doc, write about add_test_dependency

---

src/vm.c
test/t/syntax.rb

Should raise LocalJumpError when no block given

---

include/mruby/string.h

Please review this documentation for string.h

yard docs for string.h

---

mrbgems/mruby-compiler/core/parse.y

simplify tOP_ASGN rules by command_rhs and arg_rhs rules with
%prec.

parse.y: simplify 90e8ce5

---

test/t/exception.rb

This typo appears in our CI and I just noticed it, I figured I could fix it with this very simple commit :-)

Correct method name

---

test/t/lang.rb

Ｔｈｉｓ　is regression test for my project (JIT of mruby). I think this test is useful for developer optimizing VM of mruby.

Add new test for optimize VM

---

mrbgems/mruby-compiler/core/codegen.c
test/t/codegen.rb

Reported by https://hackerone.com/dkasak

Fix unsafe peephole optimization

---

mrbgems/mruby-string-ext/src/string.c
mrbgems/mruby-string-ext/test/string.rb

Prevents RCE
Reported by https://hackerone.com/raydot

Read length after args in String#setbyte

---

src/string.c
test/t/string.rb

Get String length after args in String#chomp!

---

src/class.c
test/t/class.rb

Reported by https://hackerone.com/jpenalbae

Fix segfault on remove_method with invalid argument

---

mrbgems/mruby-proc-ext/src/proc.c
mrbgems/mruby-proc-ext/test/proc.rb
src/proc.c
test/t/proc.rb

Fix calling .arity on Proc with undefined `initialize`

---

mrbgems/mruby-compiler/core/codegen.c
test/t/codegen.rb

Reported by https://hackerone.com/haquaman

Fix codegen issue causing misaligned register

---

mrbgems/mruby-compiler/core/codegen.c
mrbgems/mruby-compiler/core/parse.y
test/t/codegen.rb

As reported by https://hackerone.com/jpenalbae

Fix nested empty heredoc causing segfault

---

mrbgems/mruby-time/src/time.c
mrbgems/mruby-time/test/time.rb

Reported by https://hackerone.com/raydot

Fix null pointer dereference in mrb_time_initialize

---

include/mruby/variable.h

It's not much, but still an improvement

Added documentation on function for globals

---

src/kernel.c
test/t/kernel.rb

Otherwise the code in the test will segfault
@matz I'm not sure whether we need to copy over just the TT or all the flags

Copy over INSTANCE_TT when duping class

---

test/t/array.rb
test/t/class.rb
test/t/hash.rb
test/t/syntax.rb

This patch adds tests for recently fixed bugs which [I reported](https://github.com/mruby/mruby/issues?q=is%3Aissue+author%3Anaclyhara).
refs #3235 #3236 #3239 #3272 #3273 #3274 #3302 #3275

Add test for recently fixed bugs

---

mrbgems/mruby-compiler/core/codegen.c
test/t/codegen.rb

Reported by https://hackerone.com/haquaman

Fix segfault when using result of rest assignment

---

src/vm.c
test/t/nomethoderror.rb

Can lead to segfault
Reported by @charliesome

Fix instances where return value of mrb_method_search_vm is unchecked

---

examples/targets/build_config_RX630.rb

There are some "Gadget Renesas Boards" which can run mruby.
This example is for them.

Added example for cross-compiling on Renesas RX630

---

src/string.c

Do nothing when empty string

---

src/string.c

Check overflow string length

---

src/kernel.c
test/t/kernel.rb

Fix segv when primitive value

---

src/array.c

Check array max size

---

MITL
include/mruby.h

The yearly update of Copyright information.

Update Copyright to 2017

---

src/kernel.c

Fix https://github.com/mruby/mruby/issues/3372

Check intern object returned by mrb_check_string_type

---

src/error.c
test/t/nomethoderror.rb

@matz 
This is a rebase of https://github.com/mruby/mruby/pull/3323 to see if the AppVeyor problem goes away.

Fix 36fc1f14 not checking in the right location

---

mrbgems/mruby-compiler/core/codegen.c

@matz 
Fixes #3390.
An explanation of the problem is here: https://github.com/mruby/mruby/issues/3390#issuecomment-274208632

Remove problematic optimization from NODE_MASGN codegen

---

mrbgems/mruby-compiler/core/parse.y

Fix incorrect parsing of block parameters.

---

mrbgems/mruby-time/src/time.c
mrbgems/mruby-time/test/time.rb

And some cases should raise FloatDomainError

Fix infinity loop ref #3546

---

src/array.c
test/t/array.rb

Set proper class to subclass of Array

---

mrbgems/mruby-enum-ext/mrblib/enum.rb
mrbgems/mruby-enum-ext/test/enum.rb

Change return value of Enumberable#each_cons

---

mrbgems/mruby-enum-ext/mrblib/enum.rb
mrbgems/mruby-enum-ext/test/enum.rb

Change return value of Enumerable#each_slice

---

mrbgems/mruby-sprintf/src/sprintf.c

Sprintf refactor

---

mrbgems/mruby-string-ext/src/string.c

Latest fix was freeing the buffer while it was still in use.
Fixes #3712

Save gc_arena after buffer got allocated

---

test/t/iterations.rb

added basic tests for while/until/break/next

---

mrbgems/mruby-sprintf/test/sprintf.rb

added tests for #3736

---

include/mruby/string.h
src/class.c
src/string.c
test/t/module.rb

I hope I got the method names right in c7018ea. I tried to follow the naming conventions I saw in the code base.

Extended Module#const_get to support class paths

---

AUTHORS

via https://github.com/mruby/mruby/pull/3769#issuecomment-321404291

Updated AUTHORS

---

src/vm.c

The following input raised an error that it shouldn't:
```
$ bin/mruby -e 'class SCls
def method_missing(m, *)
puts "calling missing #{m}"
end
end
class Cls < SCls
def unknown
super(
1,2,3,4,5,6,7,8,9,0,
11,2,3,4,5,6,7,8,9,0,
21,2,3,4,5,6,7,8,9,0,
31,2,3,4,5,6,7,8,9,0,
41,2,3,4,5,6,7,8,9,0,
51,2,3,4,5,6,7,8,9,0,
61,2,3,4,5,6,7,8,9,0,
71,2,3,4,5,6,7,8,9,0,
81,2,3,4,5,6,7,8,9,0,
91,2,3,4,5,6,7,8,9,0,
101,2,3,4,5,6,7,8,9,0,
111,2,3,4,5,6,7,8,9,0,
121,2,3,4,5,6)
end
end
Cls.new.unknown'
trace:
[0] -e:25
-e:25: can't convert Fixnum into Proc (TypeError)
```
To blame was:
```
if (n == CALL_MAXARGS-1) {
[...]
n++;
}
[...]
if (n == CALL_MAXARGS) {
bidx = a+2;
}
[...]
blk = regs[bidx];
```
This got the third register instead of the last one with the block and tried to convert it into a proc. The …

Fixed calling missing method through super with 126 args

---

src/vm.c

Reset ci in OP_SUPER after potential realloc

---

test/assert.rb

re https://github.com/mruby/mruby/pull/3799#issuecomment-325918047

Allowed to pass multiple exceptions to assert_raise

---

mrbgems/mruby-proc-ext/test/proc.rb
test/t/proc.rb

Tested local jump errors caused by break in a proc

---

mrbgems/mruby-struct/src/struct.c

Fix alias for Struct accessors.
Currently:
```ruby:ruby
X = Struct.new(:a, :set_to_)
class X
alias set_to_a a=
end
p x = X.new(1, 2)
x.set_to_a :CHANGED
p x
```
Patched:
```ruby:ruby
X = Struct.new(:a, :set_to_)
class X
alias set_to_a a=
end
p x = X.new(1, 2)
x.set_to_a :CHANGED
p x
```
- - -
Different object size by clang-4.0 on FreeBSD 11.1R amd64:
```shell
$ readelf -s build/host/mrbgems/mruby-struct/src/struct.o
```
* Currently:
```
Num:    Value          Size Type    Bind   Vis      Ndx Name
5: 0000000000001d20   408 FUNC    LOCAL  DEFAULT    2 make_struct_define_accessors
24: 0000000000002140    76 FUNC    LOCAL  DEFAULT    2 mrb_struct_ref
27: 0000000000002230   158 FUNC    LOCAL  DEFAULT    2 mrb_struct_set_m
```
* Patched:
```
Num:    Value          Size Type    Bind   Vis …
```

fix alias for Struct accessors

---

include/mruby/proc.h

I revised MRB_METHOD_PROC macro's argument fn to m.

Revise MRB_METHOD_PROC macro's argument

---

mrbgems/mruby-socket/src/socket.c

mingw have ssize_t defined in windows.h

fix build on mingw

---

mrbgems/mruby-io/test/file.rb
mrbgems/mruby-io/test/io.rb
mrbgems/mruby-io/test/mruby_io_test.c

Fixed mruby-io test failure on Windows platform.
Tested on MSVC and MinGW.

Fixed mruby-io test failure on Windows platform.

---

include/mruby.h
mrbgems/mruby-io/src/io.c

filename should be string in locale

use filename in locale

---

mrbgems/mruby-io/test/mruby_io_test.c

fix crash bug on Windows

---

mrbgems/mruby-io/test/mruby_io_test.c

Maybe, appveyor will be green.

fix mkstemp implementation for MSVC

---

mrbgems/mruby-io/README.md
mrbgems/mruby-io/src/io.c
mrbgems/mruby-io/test/io.rb

This is ported PR from https://github.com/iij/mruby-io/pull/27

Implement IO#initialize_copy

---

mrbgems/mruby-socket/test/sockettest.c

This warning was displayed when building.
```
/Users/ksss/src/github.com/ksss/mruby/mrbgems/mruby-socket/test/sockettest.c:13:15: warning: 'tempnam' is
deprecated: This function is provided for compatibility reasons only. Due to security concerns
inherent in the design of tempnam(3), it is highly recommended that you use mkstemp(3) instead.
[-Wdeprecated-declarations]
char *tmp = tempnam(NULL, "mruby-socket");
^
/usr/include/stdio.h:395:1: note: 'tempnam' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security conc...
^
/usr/include/sys/cdefs.h:180:48: note: expanded from macro '__deprecated_msg'
#define __deprecated_msg(_msg) __attribute__((deprecated(_msg)))
```

Shouldn't use tempnam

---

mrbgems/mruby-socket/test/sockettest.c

Thanks https://github.com/mruby/mruby/commit/f7ff2d0ee34dc1d35b2f2fb9bafe1a5bae37a494
But need one more fix.

include io.h on mingw

---

src/gc.c

Fix possible memory access error.

---

doc/guides/mrbgems.md
lib/mruby/build/load_gems.rb

Add `:path` option for git repository.

---

mrbgems/mruby-socket/src/socket.c

https://github.com/iij/mruby-socket/commit/36d016afd663d34607c843d03371bedb71efa34e

Catch up with latest mruby-socket.

---

mrbgems/mruby-socket/src/socket.c

https://github.com/mruby/mruby/pull/3984#issuecomment-376024997

Revert #3984 .

---

mrbgems/mruby-enum-ext/mrblib/enum.rb

`each_with_object` arity should be 1

Refactoring for `Enumerable#each_with_object`

---

mrblib/hash.rb

This PR fixes the problem mentioned in https://github.com/mruby/mruby/issues/4030#issuecomment-393747821

let Hash#merge keep ifnone value

---

mrbgems/mruby-test/mrbgem.rake

Compares gem list before writing it.

Fix unnecessary rebuild of tests.

---

mrbgems/mruby-socket/mrbgem.rake
mrbgems/mruby-socket/src/socket.c

fix issues caused by variable length sockaddr_un.

incorporate fixes from iij/socket

---

mrbgems/mruby-bin-mirb/tools/mirb/mirb.c
mrbgems/mruby-io/src/file.c
mrbgems/mruby-io/src/io.c

mrb_locale_free() should be used for the return value of
mrb_locale_from_utf8().

Fix wrong free function

---

mrbgems/mruby-bin-mruby-config/mrbgem.rake
mrbgems/mruby-compiler/mrbgem.rake
mrbgems/mruby-test/mrbgem.rake
tasks/libmruby.rake
tasks/mrbgems.rake

Found by parallel minirake: #4051.

Fix build scripts.

---

.travis.yml
minirake

`sh` won't block until specific number of child processes with this change.
Needs #4050 to be merged.
Adds `-j` / `--jobs` option like `make` command.

Make minirake parallel.

---

minirake

Seems job limiting wasn't working.

Fix job waiter of minirake.

---

minirake

To fix blocking issue in #4056.

Use `Thread.pass` instead of sleeping.

---

.travis.yml

This PR is just for refactoring `.travis.yml`.
The result on my repository is here.
https://travis-ci.org/junaruga/mruby/builds/437593562

Refactor .travis.yml to remove duplicated env: MRUBY_CONFIG.

---

mrbgems/mruby-string-ext/src/string.c

Keep `tr_pattern` static if possible

---

lib/mruby/build.rb

To check debug build from mrbgems.

Add debug flag to `MRuby::Build`

---

src/dump.c
src/load.c

Fix dump and load with endianness

---

mrbgems/mruby-class-ext/mrblib/module.rb
mrbgems/mruby-class-ext/test/module.rb

I added these methods for my project and I figured I would see if you wanted to merge them.

Adds Module#< and Module#<=

---

include/mruby/hash.h
src/hash.c

Add `mrb_hash_size()` function

---

Rakefile

~~~
$ rake -T test
rake test_test  # run all mruby tests
~~~
~~~
$ rake -T test
rake test  # run all mruby tests
~~~

Refine description for rake test tasks.

---

mrbgems/full-core.gembox

Dependencies order is auto detected.

Simplify full-core.gembox

---

minirake

https://github.com/mruby/mruby/pull/4101#pullrequestreview-187752352

Fix `$rake_root_fiber` checking

---

include/mruby/range.h
mrbgems/mruby-range-ext/src/range.c
src/gc.c
src/range.c
test/t/range.rb

Developers must use following APIs for accessing attributes of RRange
because RRange structure depends on boxing setting.
- `mrb_range_beg`
- `mrb_range_end`
- `mrb_range_excl_p`

range: Embed edges in RRange on boxing environment.

---

include/mruby/range.h
src/range.c

Functions order, name, linkage and so on.

range: Refactor range.h/range.c

---

test/t/exception.rb

By the way, I don't know whether `__send__` is needed in the test ...

Use `__send__` instead of `send`; ref #4207

---

src/symbol.c

`sym_inline_unpack_with_bit()` is moved inside of `sym_inline_unpack()`
because this is used only one place.

Add length argument for `sym_inline_unpack()`

---

src/backtrace.c

- Move calling `mrb_debug_get_filename()` to after `lineno` check.
- Remove unneeded array check in `print_backtrace()`.
- Add a few `const` qualifier.

Refactor `src/backtrace.c`

---

build_config.rb
tasks/toolchains/gcc.rake
tasks/toolchains/openwrt.rake
tasks/toolchains/visualcpp.rake

`DISABLE_GEMS` is automatically set (or unset); ref #790

Remove explicit set of `DISABLE_GEMS`

---

test/assert.rb

ref: https://github.com/mruby/mruby/pull/4296#discussion_r261868710

`GEMNAME` is undefined in bintest

---

tasks/toolchains/clang.rake
tasks/toolchains/gcc.rake

Refer also CXX and CC env vars as linker command in gcc and clang toolchain

---

include/mruby/variable.h
src/class.c
src/variable.c
test/t/module.rb

`X!` etc are invalid constant name.

Fix constant name validation

---

appveyor.yml

- Add Visual Studio 2017.
- Enable `shallow_clone` for saving build time.
- Cache extracted WinFlexBison.

Refine `appveyor.yml`

---

test/assert.rb

Based on test-unit RubyGem.
- Assertion[1] Failed: Expected 1 to be nil
Expected: nil
Actual: 1
- Assertion[2] Failed: Expected [1, 3] to include 2
Collection: [1, 3]
Object: 2
- Assertion[1]
<1> was expected to be nil
- Assertion[2]
<[1, 3]> was expected to include
<2>

Remove redundant content in assertion failure message and diff

---

src/symbol.c
test/t/symbol.rb

Remove implementation of `Symbol#===`

---

src/gc.c

Include `RFiber` and `RIstruct` as a part of `RVALUE`

---

mrbgems/mruby-io/test/io.rb

fix an error in a test that occurred on windows msvc

Fix test in mruby-io

---

mrbgems/mruby-random/test/random.rb

And simplify tests for `Array#shuffle` and `Array#shuffle!`.

Add `Array#sample` test

---

lib/mruby/gem.rb

Fixes the twiddle wakka comparison algorithm to support passing only a major number.
Also fixes a variable name and updates an example.

Fixes the twiddle wakka comparison algorithm

---

mrbgems/mruby-compiler/core/parse.y

Removed duplicates in the code entered for "Concatenate string literal".
----
Most of the modifies are indent change.
```
% git diff -w --stat origin/master clean-duplicate
mrbgems/mruby-compiler/core/parse.y | 15 +++++++--------
1 file changed, 7 insertions(+), 8 deletions(-)
```

Clean duplicate code

---

mrbgems/mruby-rational/mrblib/rational.rb
mrbgems/mruby-rational/test/rational.rb

Reported by Sergey Ukrainskiy: https://github.com/mruby/mruby/commit/f5fb1307b017fb972c12b4ec4b1866d789b0ca09#r33590698

Fix `Rational#<=>(Numeric)`

---

mrbgems/mruby-array-ext/src/array.c
src/array.c

I moved comments in unaffected lines for justification.

Fix argument specs to `Array`

---

src/string.c
test/t/string.rb

Reverses UTF-8 strings without allocated heap for working memory.

Change to UTF-8 string reversing with in place

---

src/string.c

This patch is showed in #4549.

Fix heap buffer overflow; ref #4549

---

mrbgems/mruby-bin-debugger/tools/mrdb/mrdbconf.h
mrbgems/mruby-math/src/math.c
mrbgems/mruby-random/src/random.c
mrbgems/mruby-range-ext/src/range.c
mrbgems/mruby-time/src/time.c

The purpose is to clarify the error if there is a needed/conflicts configuration at compile time.

Error needed/conflicts configuration

---

mrbgems/mruby-compiler/core/parse.y

Originally, it was not necessary to change. I made mistake.

Revert #4300

---

src/class.c

The approach is the same as #4523.
Also integrated the common parts of `mrb_mod_attr_reader()` and `mrb_mod_attr_writer()` functions.

Use stack memory for small name of attr accessors

---

mrbgems/mruby-time/src/time.c

Warnings:
- If `MRB_TIME_T_UINT` is defined, the compiler issues a warning with an integer comparison of different signs.
- It is mentioned that the `usec` variable passed to the `mrb_to_time_t()` function may not be initialized

Suppress compiler warnings for mruby-time; fix #4600

---

minirake

Support pathmap notation, recursive dependencies search, and so on.

Improve MiniRake rule enhancement for Rake compatibility

---

build_config.rb

Since iij/mruby-io is deprecated

Use mruby-onig-regexp instead in example

---

src/string.c

Prioritize embedded string in the following functions:
- `str_new_static`
- `str_new`
- `mrb_str_new_capa`
- `mrb_str_pool`
The reasons are as follows:
- Consistency with `mrb_str_byte_subseq` and `str_replace`.
- Memory locality increases and may be slightly faster.
- No conversion cost to embedded string when modifying the string.

Prioritize embedded string over nofree (or normal) string

---

lib/mruby/build.rb

Separate repos directory and build directory

---

mrbgems/mruby-bin-mirb/tools/mirb/mirb.c

I think underscore variable in irb is useful.
This pull request is adding it to mirb.

add special local variable _ in mirb

---

CONTRIBUTING.md

The refinement was based on comment from @matz.

Refine documentation for C99 compliance; ref #4685 [ci skip]

---

mrbgems/mruby-class-ext/src/class.c
mrbgems/mruby-fiber/src/fiber.c
mrbgems/mruby-metaprog/src/metaprog.c
mrbgems/mruby-object-ext/src/object.c
mrbgems/mruby-objectspace/src/mruby_objectspace.c
mrbgems/mruby-proc-ext/src/proc.c
src/proc.c

Some error messages will be changed.

Entrust "no block given" error to `mrb_get_args()`

---

src/string.c
test/t/string.rb

Also fix document about type of the first argument.

Simplify arguments check in `String#index`

---

src/string.c
test/t/string.rb

Also fix document about type of the first argument.

Simplify arguments check in `String#rindex`

---

mrbgems/mruby-compiler/core/parse.y

The string is also escaped according to https://github.com/mruby/mruby/commit/2de757eef0ff677dc677094e0f02597598d8565e.
I checked during work #4303, but I forgot.
- Before patch:
```console
% ./build/host/bin/mruby -v -e '"foo\nbar"'
mruby 2.0.1 (2019-04-04)
00001   NODE_BEGIN:
00001     NODE_STR "foo
bar" len 7
irep 0x800d42310 nregs=2 nlocals=1 pools=1 syms=0 reps=0 iseq=6
file: -e
1 000 OP_STRING     R1      L(0)    ; "foo\nbar"
1 003 OP_RETURN     R1
1 005 OP_STOP
```
- After patch:
```console
% ./build/host/bin/mruby -v -e '"foo\nbar"'
mruby 2.0.1 (2019-04-04)
00001   NODE_BEGIN:
00001     NODE_STR "foo\nbar" len 7
irep 0x800d23310 nregs=2 nlocals=1 pools=1 syms=0 reps=0 iseq=6
file: -e
1 000 OP_STRING     R1      L(0)    ; "foo\nbar"
1 003 …
```

Escape the AST string

---

include/mruby/ops.h

Fix the comment to match the actual operation.

Fix opcode semantics comment miss.

---

include/mruby.h
src/class.c

Keyword arguments are now expanded by the `mrb_get_args()` function.
As before, mruby core and core gems should assume that keyword arguments cannot be handled directly from C.
For the interface, I referred to CRuby's `rb_get_kwargs()`.
For implementation, I referred to `OP_KARG` or etc.
----
When `MRB_ENABLE_KEYWORD_SPECIFIER` was defined, `bin/mruby` increased by about 800 bytes when building with `gcc -Os` on FreeBSD 12.
Even in the raw state, it has increased by about 130 bytes due to the addition of error messages.
```console
% ls -l mruby@*
-rwxr-xr-x  1 dearblue  dearblue  615448 10月  6 18:06 mruby@master
-rwxr-xr-x  1 dearblue  dearblue  615576 10月  6 18:06 mruby@patched
-rwxr-xr-x  1 dearblue  dearblue  616344 10月  6 18:05 mruby@patched+kwargs
```
----
You can check the test code …

Get keyword arguments with `mrb_get_args()`

---

lib/mruby/build.rb
lib/mruby/build/load_gems.rb
lib/mruby/gem.rb

closes #4759
Example lock file: https://gist.github.com/take-cheeze/9fa673ffef3ee660f1c4a5967f3c4692

Add mrbgem version field to lock file

---

src/string.c

- Keep `MRB_STR_ASCII` flag.
- Avoid a string object creation.

Refactor `mrb_string_value_cstr`

---

README.md
mruby-source.gemspec

- `http` -> `https`
- Remove `www.`

Change the URL of `mruby.org` [ci skip]

---

src/backtrace.c

`struct backtrace_location` is created only in `each_backtrace()`, and
the `filename` field will never be null (it will be `(unknown)` if null).

Remove unneeded null checks to `struct backtrace_location::filename`

---

mrbgems/mruby-metaprog/src/metaprog.c

If `#methods` traverse the super class, it includes the methods that were does `undef` in the subclass.
Before patched:
```terminal
% bin/mruby -e 'p Module.instance_methods - Class.instance_methods'
[]
```
After patched:
```terminal
% bin/mruby -e 'p Module.instance_methods - Class.instance_methods'
[:append_features, :extend_object]
```

Fix for `#methods` to include methods that were `undef`

---

mrbgems/mruby-io/mrblib/file.rb

And rename `File.concat_path` to `File._concat_path`.

Avoid method in method

---

mrbgems/mruby-bin-debugger/bintest/print.rb

```console
Fail: mruby-bin-debugger(print) error (mrbgems: mruby-bin-debugger)
- Assertion[2]
Expected true to be false.
```
```console
Fail: mruby-bin-debugger(print) error (mrbgems: mruby-bin-debugger)
- Assertion[2]
Expected "$2 = undefined method 'bar' (NoMethodError)\n" to be start_with? "$2 = (eval):2: undefined method".
```

Refine the assertion failure message in mrdb print tests

---

src/class.c

The behavior of these two variables is the same.

Integrate `i` and `arg_i` in `mrb_get_args()`

---

examples/targets/build_config_dreamcast_shelf.rb

Thanks to @yujiyokoo for demonstrating mruby usage on Sega Dreamcast at RubyConf AU 2020!
See more here: https://youtu.be/ni-1x5Esa_o

Added example for cross-compiling for Sega Dreamcast (sh-elf).

---

AUTHORS
mrbgems/mruby-io/src/file.c

added several types of paths for windows only
and some additions :D

Traditional, UNC, and Drive Path

---

build_config.rb
examples/targets/build_config_ArduinoDue.rb
examples/targets/build_config_IntelEdison.rb
examples/targets/build_config_IntelGalileo.rb
examples/targets/build_config_RX630.rb
examples/targets/build_config_chipKITMax32.rb
examples/targets/build_config_dreamcast_shelf.rb
lib/mruby/build/command.rb
tasks/toolchains/gcc.rake
tasks/toolchains/openwrt.rake
tasks/toolchains/visualcpp.rake

Modified the build to quote filenames so that it builds when files have spaces

build when directories and files have spaces

---

lib/mruby/gem.rb
mrbgems/mruby-io/mrbgem.rake
mrbgems/mruby-socket/mrbgem.rake

We can use the path to detect windows. Path from windows can begin with a volume.

Validate windows by Dir testing

---

.travis.yml

* Disable automatic update and clean up on `brew install` (install time
160 sec -> 5 sec).
* Avoid using deprecated keys.

Refine `.travis.yml`

---

lib/mruby/build.rb
travis_config.rb

Because some changes have been overridden.

Revert part of "Start GitHub Actions" (4ce3997c)

---

appveyor_config.rb

Respect CFLAGS, CXXFLAGS, and LDFLAGS env vars in appveyor_config.rb

---

appveyor.yml

This issue is a correction error at 5a682bfc.

Set `STDOUT.sync=true` when testing on AppVeyor [skip travis]

---

include/mruby/proc.h
test/t/kernel.rb

Fixed shift width for `MRB_ENV_SET_BIDX()`

---

src/vm.c

- Returns the updated call info.
- Unify the processing around `cipush()`.
- `cipop()` restores the stack.

Extend the `cipush()` and `cipop()` functions

---

lib/mruby/build/command.rb

```
Before this commit:
$ rake
...
$ rm build/host/src/gc.o
$ rake
rake aborted!
Don't know how to build task '/home/foo/mruby/build/host/src/gc.o' (See the list of available tasks with `rake --tasks`)
...
After this commit:
$ rake
...
$ rm build/host/src/gc.o
$ rake
CC    src/gc.c -> build/host/src/gc.o
...
With gcc 9.3.0 on Ubuntu 20.04, build/host/src/array.d looks like:
/build/host/src/array.o: /src/array.c \
/include/mruby.h /include/mrbconf.h \
/include/mruby/common.h \
...
/include/mruby/range.h \
/src/value_array.h
and it has been parsed to:
[
"/include/mruby.h /include/mrbconf.h", # incorrectly parsed
"/include/mruby/common.h",
...
"/src/value_array.h",
]
After this change, *.d will be parsed correctly.
[
"/src/array.c",
"/include/mruby.h",
"/include/mrbconf.h", …
```

Fix *.d parsing with gcc 9.3.0

---

lib/mruby/build/command.rb

I did a stupid mistake on https://github.com/mruby/mruby/pull/5079 by accident, I'm sorry.

Fix skipping reading file

---

mrbgems/mruby-bin-mirb/tools/mirb/mirb.c
mrbgems/mruby-compiler/mrbgem.rake
src/mruby_core.rake

The problem was manifested by commit 5069fb15e41998dffef8e0ba566b3a82be369ba3.

Fixed build with `conf.enable_cxx_exception`

---

oss-fuzz/mruby_proto_fuzzer.cpp
oss-fuzz/proto_to_ruby.h

See https://github.com/google/oss-fuzz/pull/4583

ossfuzz: Fix mruby include paths

---

src/dump.c

Revert "Check if irep->reps is NULL in lv_defined_p"

---

lib/mruby/core_ext.rb

* Output even with `rake -v` (to help debugging)
* Not output when `rake -s`

Change output condition in `_pp`

---

Rakefile
src/symbol.c

Chang to compare string length first.
* https://github.com/shuujii/mruby-presym_find-benchmark
```console
Previous: 10.240772M i/s (25M times in 2.441222s)
New: 16.412985M i/s (25M times in 1.523184s)
```

Optimize `presym_find`

---

include/mruby/irep.h
mrbgems/mruby-compiler/core/codegen.c
src/dump.c
src/load.c
src/vm.c

Follow commit 7150c6753933f12a2ba63769fb7b3a44cfcddd3d .

Change the catch handler address to 32 bits

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/lint.yml
.github/workflows/main.yml
.gitlab-ci.yml
.yamllint

- Run only on pull request
- Add a `.yamllint` config file
- Lint YAML

feat(CI): add a GitHub Action to lint the YAML

---

.github/workflows/spell-checker.yml
mrbgems/mruby-compiler/core/codegen.c
mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c
mrbgems/mruby-io/src/file.c

- Fix spelling
- Run only on pull request
- Using https://github.com/client9/misspell

feat(CI): add a GitHub Action to check spelling

---

.github/workflows/lint.yml
.markdownlint.yml
doc/guides/compile.md
doc/guides/debugger.md
doc/guides/mrbconf.md
doc/guides/mrbgems.md
doc/limitations.md
mrbgems/mruby-io/README.md
mrbgems/mruby-pack/README.md
mrbgems/mruby-sleep/README.md
mrbgems/mruby-socket/README.md
mrbgems/mruby-test/README.md

Run on pull request only
Using https://www.npmjs.com/package/markdownlint-cli
Lint Markdown for rules:
- MD009/no-trailing-spaces
- MD012/no-multiple-blanks
- MD022/blanks-around-headings
- MD031/blanks-around-fences
- MD032/blanks-around-lists

feat(CI): add a GitHub Action to lint the Markdown

---

mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c
test/t/literals.rb

Sorry, I have made a mistake in my previous PR https://github.com/mruby/mruby/pull/5246 and forgot to check for empty lines in squiggly heredocs.

Fix for empty lines in squiggly heredocs

---

src/codedump.c

replace ; to : of OPT_SETGV in codedump.c

---

src/hash.c

The idea of using `size_t` in `ea_next_capa_for` is by @dearblue.

Avoid 64-bit operations in `src/hash.c`; close #5201

---

src/dump.c

Non-ASCII characters are allowed to local variable names, so they are not
always named presym.

Consider the case a local variable name does not become a named presym

---

include/mruby/presym.h
include/mruby/presym/scanning.h

Add the following functions:
- mrb_intern_cstr
- mrb_define_singleton_method
- mrb_define_class_under
- mrb_define_module_under

Add scan target functions for presym

---

build_config/cross-32bit.rb
lib/mruby/build.rb
tasks/presym.rake

Fix the following issues.
* https://github.com/mruby/mruby/pull/5220#issuecomment-757204258
* https://github.com/mruby/mruby/pull/5220#issuecomment-757205572

Fix build error in cross-build with presym

---

src/hash.c

The Hash implementation assumed that there were always empty buckets, but
sometimes there were only active or deleted buckets (no empty buckets).
Therefore, fix it so that this situation does not occur.
```ruby
class A
attr_reader :v
def initialize(v) @v = v end
def ==(o) @v == o.v end
def hash; @v end
def to_s; "#{self.class}[#{@v}]" end
alias eql? ==
alias inspect to_s
end
keys = (0..31).map{A.new(_1)}
h = {}
(0..16).each{h[keys[_1]] = _1}
(17..31).each do
k = keys[_1]
h[k] = _1
h.delete(k)
end
p h.keys
```
```console
[A[0], A[1], A[2], A[3], A[4], A[5], A[6], A[7], A[8], A[9], A[10], A[11], A[12], A[13], A[14], A[15], A[16], A[30], A[31]]
```
```console
[A[0], A[1], A[2], A[3], A[4], A[5], A[6], A[7], A[8], A[9], A[10], A[11], A[12], A[13], …
```

Fix that Hash may not contain any empty buckets

---

src/dump.c
src/load.c

Fix TYPO and checking minor version in RITE BINARY HEADER

---

mrbgems/mruby-struct/mrblib/struct.rb

Because now the `Struct` class is always defined when this file is included.

No need to check class definition

---

src/hash.c

In `h_check_modified()`, in the case of `MRB_NO_BOXING`, `ht_ea()` or
`ht_ea_capa()` for AR may read uninitialized area. Therefore, do not use
those macros for AR in `MRB_NO_BOXING` (but in the case of `MRB_64BIT`,
`ht_ea_capa()` is the same as `ar_ea_capa()`, so use it).
fix #5332

Avoid possibility of reading uninitialized areas in `h_check_modified()`

---

.github/workflows/lint.yml
mrbgems/mruby-hash-ext/src/hash-ext.c
test/check-for-trailing-whitespace.sh

Run on pull request only.
Use a shell script to check for trailing whitespace in all files.
Fail if trailing whitespace is found.

feat(CI): check for trailing whitespace

---

benchmark/bm_ao_render.rb
build_config/ArduinoDue.rb
build_config/RX630.rb
build_config/chipKITMax32.rb
tasks/mrbgems.rake
tasks/toolchains/android.rake

Changed `Javascript` to `JavaScript`

chore: fix spelling

---

mrbgems/mruby-objectspace/src/mruby_objectspace.c

- T_COMPLEX
- T_RATIONAL
- T_FALSE
- T_FREE
- T_TRUE
- T_SYMBOL
- T_UNDEF

Reorganize types for `ObjectSpace.count_objects`

---

src/vm.c

Previously, the following code would cause a `SIGSEGV`.
```ruby
mm = method(:throw)
define_method(:throw, ->(*args) { mm.call(*args) })
catch { |tag| throw tag }
```
I think the reason is in the `mrb_yield_with_class()` function:
- Even if a C function is called, `CI_ACC_SKIP` is used
- `cipop()` is not done if globally jumping from a C function

Fix `SIGSEGV` with mruby-method + mruby-catch

---

src/dump.c

Adds debug information for gems built under enable_debug.
Consider the code:
```
[1,2].reverse_each do |val|
val.invalid_method
end
```
Before this patch: (with enable_debug)
```
[1] test.rb:1
test.rb:2: undefined method 'invalid_method' (NoMethodError)
```
After this patch: (with enable_debug)
```
[2] test.rb:1
[1] ...mruby/mrbgems/mruby-array-ext/mrblib/array.rb:297:in reverse_each
test.rb:2: undefined method 'invalid_method' (NoMethodError)
```
While this might seem like a fairly minor improvement, when you've got 10 stack frames within gems which aren't visible, it makes quite a lot of difference. No changes in behavior should occur when mrbc isn't using the debug flag.

mrbc: Dump debug info with -g option

---

mrbgems/mruby-catch/src/catch.c
src/class.c
src/proc.c

The following methods will be made static.
- `Class#new`
- `Proc#call`
- `Kernel#catch`
Previously, static const RProc could not be registered as a method, but this has been changed to allow it.

Making a proc object static for a method with static irep

---

mrbgems/mruby-binding-core/src/binding-core.c

Avoid ill-advised `goto`

---

include/mruby/gc.h
mrbgems/mruby-catch/src/catch.c
src/class.c
src/dump.c
src/gc.c
src/proc.c
src/vm.c

Replaces the magic number `7` except in `src/gc.c`.

Introduce `MRB_GC_RED`

---

doc/opcode.md

Put the script to convert from `include/mruby/ops.h` at https://gist.github.com/dearblue/c30f9f58a5e3c3a57fa1cfd3570b19c2

Enclose the table contents of `opcode.md` as code

---

CONTRIBUTING.md
doc/guides/compile.md
doc/guides/mrbgems.md

Standardize commands inside backticks

---

.github/linters/.markdown-lint.yml
TODO.md
doc/guides/mrbgems.md
doc/guides/symbol.md
doc/mruby3.md
mrbgems/mruby-io/README.md
mrbgems/mruby-method/README.md
mrbgems/mruby-pack/README.md
mrbgems/mruby-socket/README.md

Lint Markdown
https://github.com/DavidAnson/markdownlint#rules--aliases

Enable markdownlint rules MD003,MD005,MD007

---

src/vm.c

It does not need to hold an anonymous proc for constant search.
Also, this change can be expected to cause an anonymous proc to be GC'd.
This is useful for metaprogramming that makes heavy use of the `class`/`module`/`def` syntax in the `class_eval`/`eval` method.
Example:
- code
```ruby
p ObjectSpace.count_objects
String.class_eval do
def a
end
end
p ObjectSpace.count_objects
String.class_eval do
eval <<~CODE
def b
end
CODE
end
p ObjectSpace.count_objects
```
- result of building mruby-head (d63c0df6b) with `build_config/default.rb`
```
{:TOTAL=>1024, :FREE=>262, :T_PROC=>495, :T_ENV=>61, ...}
{:TOTAL=>1024, :FREE=>259, :T_PROC=>497, :T_ENV=>62, ...}
{:TOTAL=>1024, :FREE=>255, :T_PROC=>500, :T_ENV=>63, ...}
```
- result of building mruby with this patch and `build_config/default.rb`
``` …
```

Drop unnecessary upper procs linked from class/module/def syntax

---

test/t/syntax.rb

Hi, thanks for the commit fdd5ce8fac8f306f71f336f07f0a537b8626e6d6.
I've added the test case of this.

Add a testcase of #4137 fix

---

include/mruby.h
src/class.c

Please refer to the two commit messages.

Checks the frozen object with `mrb_get_args()`

---

mrbgems/mruby-bin-mirb/tools/mirb/mirb.c

I think this is an improvement on the existing language, but happy to defer to whatever existing norms and decisions y'all have developed. Cheers!

Use gender-neutral pronouns

---

mrbgems/mruby-random/src/random.c
mrbgems/mruby-random/test/random.rb

ref: https://docs.ruby-lang.org/ja/3.0.0/method/Random/i/bytes.html

Added `Random.#bytes` method

---

include/mruby/ops.h
src/vm.c

There was a discrepancy in the actual behavior, assertions, and documentation.
Therefore, I modified it based on the actual behavior.

Fixed a discrepancy in `OP_ASET`

---

README.md

Changed `Actual` to `actual` mid sentence

Fix word casing in the README

---

include/mruby/boxing_nan.h

It seems to be preferable to be able to handle pointers of type `char` as well.
For this purpose, `mrb_nanbox_tt_inline` has been reorganized.
- `MRB_NANBOX_TT_POINTER` has been split into `MRB_NANBOX_TT_OBJECT` and `MRB_NANBOX_TT_CPTR`
- `MRB_NANBOX_TT_SYMBOL` has been merged into `MRB_NANBOX_TT_MISC`

Allows handling of unaligned cptrs for `MRB_NAN_BOXING`

---

mrbgems/mruby-compiler/core/codegen.c
src/vm.c

Fixing keyword arguments with `super`

---

mrbgems/mruby-errno/README.md

As requested in the comments for https://github.com/mruby/mruby/pull/5638 , here are the changes to the README as a separate PR.

Updated mruby-errno/README.md to pass the lint checks.

---

.github/workflows/super-linter.yml

From https://github.com/mruby/mruby/pull/5683

Run Super-Linter only once

---

src/gc.c

One extra element was included.

Fixed bounds check for `heap_p()` function in `src/gc.c`

---

mrbgems/mruby-compiler/core/codegen.c

At the same time, the saving and restoration of unwanted object arenas was removed.
In addition, the common code to extend the pool that existed before has been grouped together and newly established as `lit_pool_extend()`.
Note that previously the variable `i` was updated at that time, but since it is the same as the value at the end of a `for` statement, it has been omitted.
The original catalyst was that `bin/mrbc` with the `MRB_WORD_BOXING` + not `MRB_BOXWORD_NO_FLOAT_TRUNCATE` configuration caused `bin/mrbtest` with the `MRB_NO_BOXING` configuration to fail.
Upon investigation, I concluded that avoiding the creation of temporary objects would prevent the truncation of floating point numbers.
Therefore, this patch also prevents the `rake test` from failing with the following …

Avoid creating temporary objects with `new_lit()` in `codegen.c`

---

mrblib/string.rb

Each byte value is now retrieved inside the loop.

Improvements to `String#each_byte`

---

src/vm.c

If necessary, adjust the pointer on the VM stack after `mrb_stack_extend()`.

Introduce `mrb_stack_extend_adjust()`

---

benchmark/bm_ao_render.rb

delete unnecessary code

---

benchmark/bm_ao_render.rb

delete unused variable

---

CONTRIBUTING.md

Knowing about `SKIP` is useful
https://pre-commit.com/#temporarily-disabling-hook

Add docs on the `SKIP` pre-commit environment variable

---

.github/workflows/super-linter.yml

Following the basic example shown here
https://github.com/github/super-linter#example-connecting-github-action-workflow

Super-Linter: Lint modified files only

---

.github/workflows/codeql-analysis.yml

CodeQL: fix type use array

---

tasks/toolchains/android.rake

Remove whitespace

---

src/vm.c

When `cipush()` extends "callinfo", GC may occur.
In this case, there was a problem that prepared arguments were spoiled depending on the situation when `cipush()` is called.
Therefore, in the problematic part, `cipush()` is prepared first, and then the arguments are prepared.
The reason for passing `CINFO_DIRECT` to `cipush()` is that it is simply ignored in the `MRB_CATCH()` part of `mrb_vm_exec()`.
Also, the argument processing parts of `mrb_funcall_with_block()` and `mrb_yield_with_class()` are combined and made independent as `funcall_args_capture()`.

Protect prepared arguments when GC occurs in `cipush()`

---

src/vm.c

Not exactly the same, but I think there were some things that should have been fixed in the original `OP_SUPER`.
It also directly describes `ARGUMENT_NORMALIZE()`, which is no longer required to be independent.
The problem in #5774 is something I noticed while writing this patch.
The following are the differences between `OP_SEND` and `OP_SUPER` at this time (commit a0c02e0a6).
```
diff -U7 -L OP_SEND -L OP_SUPER \
<(git cat-file -p a0c02e0a6:src/vm.c | head -n 1797 | tail -n $((1797 - 1733))) \
<(git cat-file -p a0c02e0a6:src/vm.c | head -n 1932 | tail -n $((1932 - 1876)))
```
```diff
--- OP_SEND
+++ OP_SUPER
@@ -1,64 +1,56 @@
-      ARGUMENT_NORMALIZE(a, &c, insn);
+      ARGUMENT_NORMALIZE(a, &b, OP_SUPER);
-      recv = regs[a];
-      cls = mrb_class(mrb, recv);
+      cls = …
```

Integrate the second half of `OP_SUPER` with `OP_SENDB`

---

Makefile
Rakefile

Runs `pre-commit run --all-files`

Add `lint` target to the Makefile

---

.pre-commit-config.yaml
codespell.txt
mrbgems/mruby-string-ext/src/string.c

https://pre-commit.com/#pre-commit-autoupdate

pre-commit autoupdate, fix spelling, update codespell.txt

---

LICENSE
include/mruby.h

It's nearly 2023 but better late than never 🙃

Update year in LICENSE file

---

examples/mrbgems/mruby-YOUR-bigint/TODO-HINT.md
examples/mrbgems/mruby-YOUR-bigint/core/bigint.c
examples/mrbgems/mruby-YOUR-bigint/mrbgem.rake
mrbgems/mruby-bigint/README.md

- This document was translated from Japanese by [DeepL](https://www.deepl.com/).
- `examples/mrbgems/mruby-YOUR-bigint` is provided under the [Creative Commons Zero License](https://creativecommons.org/publicdomain/zero/1.0/) for ease of copying.
- I am not sure if this content is sufficient.......

Add `examples/mrbgems/mruby-YOUR-bigint`

---

mrbgems/mruby-set/.travis.yml
mrbgems/mruby-set/LICENSE
mrbgems/mruby-set/README.md
mrbgems/mruby-set/test/mrb_set.rb

Run `pre-commit run --all-files`
Failing tests listed here:
https://github.com/mruby/mruby/actions/runs/3300669124/jobs/5445399360

gha: fix pre-commit

---

mrbgems/mruby-set/mrblib/mrb_set.rb

- Alias `#===` to `#include?`
- Alias `#filter!` to `#select!`
- Fix `#subset?` and `#proper_subset?` for Set-like objects.
- Fix `#==`
- Fix `#inspect` for self-referencing sets.
- Add `#<=>` and `#join`

mrb_set.rb: improve ruby/spec compliance.

---

Makefile
Rakefile

Makefile/Rakefile: add checkupdate target

---

.pre-commit-config.yaml
oss-fuzz/mruby_proto_fuzzer.cpp
oss-fuzz/proto_to_ruby.cpp
oss-fuzz/proto_to_ruby.h
test/t/syntax.rb

The indentation settings have been taken from the `.editorconfig` file
https://github.com/Lucas-C/pre-commit-hooks

pre-commit: add hooks `forbid-tabs` and `remove-tabs`

---

mrbgems/mruby-fiber/src/fiber.c

fiber.c: fix grammar

---

mrbgems/mruby-io/src/io.c

errno must be set before mrb_sys_fail

---

src/vm.c

- Now that it is called after `cipush()`, pass in a new ci pointer.
- Removed the parameters `clsp`, `a`, and `c`, which are no longer needed since they now operate directly on `ci`.
- Change the parameter `super`, which is treated as a boolean, to `mrb_bool`.
- Leave the parameter `mid`. Because if `prepare_missing()` raises the exception `NoMethodError`, `ci->mid` must not be set when suppressing extra information on the stack trace. However, set `ci->mid` here, since the preparation is completed at the end of the function.

Changed `prepare_missing()` parameters

---

mrbgems/mruby-fiber/src/fiber.c

However, this may not be the case depending on where the `FiberError` raises.

Avoid `abort()` when `FiberError` occurs in `mrb_fiber_resume()`

---

Doxyfile

Additional document files for doxygen

---

doc/guides/mrbconf.md
doc/mruby3.0.md

https://en.wikipedia.org/wiki/Single-precision_floating-point_format
https://en.wikipedia.org/wiki/Double-precision_floating-point_format

Fix spelling

---

CONTRIBUTING.md
tasks/doc.rake

In my editor terminal the links come up blue and clickable which opens the default browser.

Add more building documentation

---

doc/guides/mrbgems.md

Added tips for giving blocks to `MRuby::Build#gem`

---

mrbgems/mruby-io/src/io.c

ref. commit 9deb52c7b2ba6028d996172bfdd6cf8a0405ce1c

Replaced `NO_IO_POPEN` with `MRB_NO_IO_POPEN`

---

.pre-commit-config.yaml

Run `rake checkupdate`

---

mrbgems/mruby-fiber/src/fiber.c

Remove unreachable codes in `Fiber#resume`

---

README.md

https://en.wikipedia.org/wiki/Home_page

`README.md` fix spelling: `home-page` -> `homepage`

---

mrbgems/default.gembox

Update `default.gembox` add mruby debugger `mrdb`

---

src/numeric.c

Returns the value of `Integer#~` from `mrb_bint_rev()`

---

src/string.c
test/t/string.rb

Tests for overflow fail, which will be resolved by #5985.

Fix bugs in `String#bytesplice`

---

.pre-commit-config.yaml

https://github.com/pre-commit/pre-commit-hooks#file-contents-sorter

pre-commit: file-contents-sorter ensure each line is unique

---

mrbgems/mruby-bin-config/mruby-config
mrbgems/mruby-bin-config/mruby-config.bat

Added output for C++ and Assembly, ObjectiveC.
---
This is part of my current plan 74949b3...06836cd.

Extends `bin/mruby-config`

---

tasks/libmruby.rake

This is part of my current plan 74949b3...06836cd.

Fix libmruby name for VisualC++

---

.pre-commit-config.yaml
examples/mrbgems/mruby-YOUR-bigint/TODO-HINT.md
src/string.c

https://pre-commit.com/#pre-commit-autoupdate

pre-commit autoupdate; fix spelling

---

tasks/libmruby.rake

Corrected wrong `MRUBY_PACKAGE_DIR`

---

Dockerfile
docker-compose.yml

https://stackoverflow.com/questions/30256386/how-to-copy-multiple-files-in-one-layer-using-a-dockerfile
https://docs.docker.com/compose/compose-file/compose-file-v3/

docker: use less image layers and update compose version

---

src/vm.c

`OP_RAISEIF` should be easier to relate than `OP_RETURN`.

Move `L_RAISE` and `L_BREAK` blocks to `OP_RAISEIF`

---

src/vm.c

- Removed `mrb` and `ci` parameters.
- Added `irep` parameter. The caller must guarantee that `irep->clen > 0`.

Changed parameters for `catch_handler_find()`

---

.github/linters/.yaml-lint.yml
.github/workflows/oss-fuzz.yml
.github/workflows/super-linter.yml
.gitignore
.pre-commit-config.yaml
.prettierrc
SECURITY.md
build_config/dreamcast_shelf.rb
doc/guides/compile.md
doc/guides/debugger.md
doc/guides/gc-arena-howto.md
doc/guides/link.md
doc/guides/mrbconf.md
doc/guides/mrbgems.md
doc/guides/symbol.md
doc/internal/boxing.md
doc/mruby3.0.md
docker-compose.yml
mrbgems/mruby-bigint/README-fgmp.md
mrbgems/mruby-io/README.md
mrbgems/mruby-pack/README.md

Fix `pre-commit` failure from `prettier`

---

mrbgems/mruby-enum-ext/mrblib/enum.rb
mrbgems/mruby-enum-ext/test/enum.rb

Add Enumerable#grep_v to mruby-enum-ext
https://docs.ruby-lang.org/ja/latest/method/Enumerable/i/grep_v.html

Add Enumerable#grep_v to mruby-enum-ext

---

include/mruby.h
mrbgems/mruby-complex/src/complex.c
mrbgems/mruby-object-ext/src/object.c
mrbgems/mruby-rational/src/rational.c
src/numeric.c
src/object.c
src/symbol.c

Some method definitions were changed to use this function.

Introduce `mrb_obj_itself()`

---

.github/workflows/super-linter.yml

https://github.com/super-linter/super-linter/releases/tag/v6.0.0
https://github.com/super-linter/super-linter/pull/5120

super-linter: remove `ERROR_ON_MISSING_EXEC_BIT` check

---

src/gc.c

The caller is a boolean value from the first.

Change the `end` parameter of `obj_free()` to a boolean type

---

.github/workflows/build.yml

https://github.com/actions/runner-images?tab=readme-ov-file#available-images
refs #6005

gha: add macOS 14 to the build

---

src/vm.c

Previously, `mrb->exc` would remain replaced by a `break` object if a rewind operation was performed during the processing of a `OP_STOP` instruction. This problem has existed since #5060, when it was introduced in mruby-3.0.
However, as of mruby-3.0, a manual or third-party generator is required to cause the `OP_STOP` instruction to be issued. Therefore, it is believed that this has not had an impact until now.

Fix `OP_STOP` with exception

---

.github/linters/.hadolint.yaml
.github/workflows/super-linter.yml
Dockerfile

https://github.com/super-linter/super-linter?tab=readme-ov-file#configure-super-linter
https://github.com/hadolint/hadolint
https://github.com/hadolint/hadolint?tab=readme-ov-file#configure
https://github.com/hadolint/hadolint/wiki/DL3042

super-linter: validate the `Dockerfile` with `hadolint`

---

.pre-commit-config.yaml

https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#destroyed-symlinks
Another check or test we can have

Add `pre-commit` hook `destroyed-symlinks`

---

src/vm.c

The state of a fiber switched due to an exception occurrence was incorrectly set to "Suspended".
```ruby
Fiber.new {
begin
Fiber.new { 0 / 0 }.resume
rescue
p Fiber.current
end
}.resume
```

Fix status of fiber after switched by exception raised

---

src/vm.c

Suppress heap allocation for strings.

Remove `localjump_error()`

---

mrbgems/mruby-test/driver.c
mrbgems/mruby-test/mrbgem.rake

This was the unintentional catalyst for finding the problem in #6329, but it is preferable to add a test if necessary.

Restore the GC arena with tests.

---

src/vm.c

For role clarity, distinguish between `ci` and `return_ci`.
---
This is a modified version of commit a6fd41a in #6307.
As for the last commit of my plan, 0b5b6c1, I don't know how it will turn out, as the results from the real benchmark are not good.

Add `return_ci` in `CHECKPOINT_MAIN()` of `OP_RETURN`

---

src/array.c

`mrb_equal()` may call `obj.==` method internally.
Therefore, using an unupdated pointer and length after `mrb_equal()` could result in a read/write to an invalid address.
Fresh properties must always be obtained regardless of the result of `mrb_equal()`.
Also, `ary_modify()` must be called each time before writing.
ref. #6339

Fix use-after-free in `mrb_ary_delete()`

---

.pre-commit-config.yaml

https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#check-json
Adds another check/test to our pre-commit framework for checking JSON files
We have one JSON file at `.github/linters/mlc_config.json`

Add `pre-commit` hook `check-json`

---

include/mruby/irep.h

irep did not compile with this typo.

Fix a typo in irep.h

---

.github/workflows/build.yml

https://github.com/actions/runner-images#available-images

Build and test on macOS 13

---

.github/workflows/build.yml

gha: add Ubuntu 24.04 to the build

---

include/mruby/boxing_no.h

I want to rename it because I was confused about what `NIX` meant.

boxing_no.h: rename BOXNIX_SET_VALUE -> BOXNO_SET_VALUE

---

mrbgems/mruby-compiler/core/parse.y

Put `#include <stdlib.h>` in `parse.y`

---

mrbgems/mruby-bigint/core/bigint.c

Fixes https://github.com/mruby/mruby/issues/6456

bigint: fix bug with division of a small number by a bigint

---

.github/workflows/build.yml

https://github.com/actions/runner-images?tab=readme-ov-file#available-images
https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md

gha: update `build.yml` try `windows-2025` image

---

.pre-commit-config.yaml

https://www.npmjs.com/package/prettier

pre-commit: update prettier to the latest version

---

.pre-commit-config.yaml

https://nodejs.org/en
https://pre-commit.com/#pre-commit-autoupdate

pre-commit: autoupdate and update node LTS version

---

src/class.c

The method table (mt_tbl) in src/class.c previously only rehashed when it became completely full. With linear probing, this could lead to significant performance degradation for lookups and insertions as the table approached full capacity.
This change introduces a load factor (MT_LOAD_FACTOR_NUM/MT_LOAD_FACTOR_DEN, set to 3/4 or 0.75). The mt_put function now checks if adding a new element would cause the table's size to meet or exceed this load factor relative to its allocated capacity. If so, it triggers a rehash before inserting the new element.
This helps maintain more empty slots in the hash table, improving the average-case performance of linear probing and reducing the likelihood of worst-case scenarios. The existing initial allocation size and doubling strategy for rehashing are …

Improve method table performance by rehashing at 75% load factor.

---

tasks/mrbgems.rake

Tested with `RUBYOPT=--enable-frozen-string-literal make`

Fix build strings that must be mutable

---

src/variable.c

This commit corrects the placement of C-style block comments for MRB_API functions in src/variable.c. Comments are now placed directly before each function definition as per standard documentation practices.

Fix: Correct placement of comments in src/variable.c

---

.github/linters/.rubocop.yml
.pre-commit-config.yaml

https://docs.rubocop.org/rubocop/integration_with_other_tools.html#git-pre-commit-hook-integration-with-pre-commit
refs #6207

pre-commit add rubocop with one rule spaces for indentation

---

mrbgems/mruby-bin-debugger/bintest/mrdb.rb
mrbgems/mruby-bin-debugger/bintest/print.rb

sed s/Mruby/MRuby/g

---

doc/limitations.md

Update limitations.md to add behavior on small hash

---

.github/workflows/claude-code-review.yml
.github/workflows/claude.yml
.pre-commit-config.yaml

- Run pre-commit and fix lint errors
- pre-commit updates; make oxipng hook more robust
https://nodejs.org/en/download
https://www.npmjs.com/package/prettier

pre-commit fixes and updates

---

include/mruby/internal.h
src/kernel.c
src/variable.c

`mrb_obj_iv_inspect()` is an internal implementation function and is not called by any function other than `mrb_obj_inspect()`.

Merge `mrb_obj_iv_inspect()` into `mrb_obj_inspect()`

---

.github/workflows/codeql-analysis.yml

https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql#about-codeql

Add CodeQL Analysis for GitHub Actions

---

Rakefile
doc/guides/mrbgems.md
lib/mruby/gem.rb
mrbgems/mruby-compiler/mrbgem.rake
tasks/mrbgems.rake

Set up all GEMS before mruby core tasks definition
