mruby/mruby

examples/targets/build_config_dreamcast_shelf.rb

This configuration was successfully tested on GNU/Linux (Ubuntu), MinGW-w64/MSYS2, Cygwin, macOS and MinGW/MSYS (DreamSDK). It will generate the `host` binaries plus the `dreamcast` binaries, usable with KallistiOS (KOS).

Improving comments in the cross-compiling sample for the Sega Dreamcast.

---

appveyor.yml
include/mrbconf.h

Because we can't use the highest 2 bits of function pointers.
I couldn't reproduce this with the existing tests.
https://ci.appveyor.com/project/kou/mruby/builds/31199291/job/tkh6ady3xwxnvogj works well without `MRB_METHOD_T_STRUCT`.
But I added some 32bit Windows entries to `appveyor.yml`. I don't add "Visual Studio 2013 32bit" case because it failed with `Math.atan2` test:
https://ci.appveyor.com/project/kou/mruby/builds/31199291/job/tkh6ady3xwxnvogj
```text
Fail: Math.atan2 (mrbgems: mruby-math)
- Assertion[5]
Expected NaN to be 2.356194490192345.
- Assertion[6]
Expected NaN to be -2.356194490192345.
- Assertion[7]
Expected NaN to be 0.7853981633974483.
- Assertion[8]
Expected NaN to be -0.7853981633974483.
```
It's not related to this case.
I couldn't reproduce this with existing …

Enable MRB_METHOD_T_STRUCT by default on 32bit Windows

---

mrbgems/mruby-io/src/file.c

On mirb
```
File.expand_path("~")
```
Result in windows
```
(mirb):1: non-absolute home (ArgumentError)
```
I have added some code for this. I like it when combined :)

Absolute path for windows

---

mrbgems/mruby-io/src/file.c

Me again
There was a typo resulting in an error during compile.
```
#define IS_PATHSEP(x) (x == '/' || x == '\')
```
to
```
#define IS_PATHSEP(x) (x == '/' || x == '\\')
```
Just that.

Fix unfinished changes

---

mrbgems/mruby-io/include/mruby/ext/io.h
mrbgems/mruby-io/src/io.c
mrbgems/mruby-io/test/io.rb
mrbgems/mruby-io/test/mruby_io_test.c

It is available by default in environments where `__unix__` is defined.
Other environments are enabled by defining `MRB_WITH_IO_PREAD_PWRITE` (requires an implementation of `pread()` and `pwrite()` functions).
In any case, you can disable it by defining `MRB_WITHOUT_IO_PREAD_PWRITE`.

Implement `IO#pread` and `IO#pwrite`

---

mrbgems/mruby-metaprog/src/metaprog.c

However, the behavior of `#call` on the method object of `local_variables` is not corrected.

Fix NULL pointer dereferences in mrb_local_variables; fix #4955

---

src/vm.c

If `mrb->jmp` is `NULL` and the function `mrb_funcall_with_block()` is called, GC Arena is returned from the function with over-used.
- A normal (no global exodus) return will consume two GC Arena's.
- In the event of an exception, five GC Arena are consumed.
This patch reduces consumption in both cases to one.

Fix `mrb_funcall_with_block()` uses more GC arena

---

lib/mruby/build.rb
lib/mruby/build/command.rb

I removed `cygwin_filename()` method because Cygwin's pathnames are in UNIX format.

Merged `cygwin_filename()` into `filename()`.

---

mrbgems/mruby-bin-config/mrbgem.rake

The build error occurred when the "build/XXX/bin" directory did not exist.

Fixed a build error in mruby-config

---

include/mruby/numeric.h
mrbgems/mruby-sprintf/src/sprintf.c
mrbgems/mruby-sprintf/test/sprintf.rb
src/fmt_fp.c

For "width specifier" and "specifier flags", I get diff `src/fmt_fp.c` and musl (`src/stdio/vfprintf.c` in `git://git.musl-libc.org/musl`) and combined them.

 Support `MRB_DISABLE_STDIO` for mruby-sprintf; ref #4954

---

include/mruby/boxing_nan.h
include/mruby/boxing_word.h
include/mruby/value.h
src/etc.c

Previously, if `MRB_NAN_BOXING` is defined, for example, `mrb_cptr_value()` could not keep an odd address.
If it is `MRB_32BIT`, it can be embedded in `NaN` as it is.
If it is `MRB_64BIT`, some operations are shared with `MRB_WORD_BOXING`.
In this case, the MRB_API function `mrb_nan_boxing_cptr_value()` is defined.

Fix `MRB_TT_CPTR` object with `MRB_NAN_BOXING`

---

mrbgems/mruby-io/include/mruby/ext/io.h

The comment is for messages when `MRB_INT16` and `MRB_WITHOUT_FLOAT` are specified at the same time.
The comment itself is no longer needed now that `MRB_INT16` is gone.

Removed comments mentioning `MRB_WITHOUT_FLOAT`; ref 2e661e8

---

include/mruby/array.h
src/array.c

When removing elements from an array, it is possible to avoid creating an empty array.
Before this patch:
```c
mrb_ary_splice(mrb, ary, head, len, mrb_ary_new(mrb));
```
After this patch:
```c
mrb_ary_splice(mrb, ary, head, len, mrb_undef_value());
```

Support `undef` for `mrb_ary_splice()` instead of `[]`

---

mrbgems/mruby-io/test/mruby_io_test.c

mruby-io cannot create temporary AF_UNIX socket when working directory is vboxfs or NFS.
This is a workaround to test in such kind of filesystems.

Test mruby-io in tmpdir when AF_UNIX cannot be created on cwd

---

src/class.c
src/string.c

When using `mrb_any_to_s()` for debugging purposes, giving an object whose class is `NULL` no longer causes a SIGSEGV and no crash.
This is achieved by making `mrb_class_name()` and `mrb_str_cat_cstr()` null safe.
----
I want to display a `MRB_TT_BREAK` object.

Makes `mrb_any_to_s()` accept an object whose class is `NULL`

---

lib/mruby/build.rb

Printing them in sorted order makes it easier to find the desired gem.
But it has come to completely ignore the dependency.

Sorting the list of gems at build time by name

---

include/mrbconf.h

Hello,
We can't also use the highest 2 bits of function pointers on 32bit GNU/Linux same as https://github.com/mruby/mruby/pull/4948.
How about we decide whether 32bit architecture by using `MRB_32BIT`?

Enable MRB_METHOD_T_STRUCT by default on 32bit GUN/Linux

---

mrbgems/mruby-compiler/core/codegen.c

It was making a negative integer if the highest-order bit of a 16-bit integer was 1.
no patched:
```ruby
p 0x7fff  # => 32767
p 0x8000  # => -32768
p 0xffff  # => -1
p 0x10000 # => 65536
```

Fix boundary check for `OP_LOADI16`; ref fa8668c

---

src/dump.c

The `FLAG_BYTEORDER_NATIVE` and `FLAG_BYTEORDER_NONATIVE` are no longer needed.

Remove byteorder constants; ref 87576b8

---

doc/opcode.md

The difference of `include/mruby/ops.h` is applied.
- OP_NOP - update semantics
- OP_GETSV - update semantics
- OP_SETSV - update semantics
- OP_GETUPVAR - update prefix
- OP_SETUPVAR - update prefix
- OP_JMPIF - update operands and semantics
- OP_JMPNOT - update operands and semantics
- OP_JMPNIL - add entry
- OP_ONERR - update semantics
- OP_POPERR - update prefix
- OP_EPOP - update prefix
- OP_SENDB - update semantics
- OP_ADD - update prefix and operands
- OP_ADDI - update operands and semantics
- OP_SUB - update prefix and operands
- OP_SUBI - update semantics
- OP_MUL - update prefix and operands
- OP_DIV - update prefix and operands
- OP_EQ - update prefix and operands
- OP_LT - update prefix and operands
- OP_LE - update prefix and operands
- OP_GT - update prefix and operands
- …

Update `doc/opcode.md` [ci skip]

---

src/vm.c

It's a meaningless patch that has no effect at the moment, but I've noticed it, so I'm putting it out.

Get an irep symbol if it's `OP_GETSV` or `OP_SETSV`

---

src/hash.c

```ruby
class A
def eql?(o)
p self.class
super
end
def hash
1
end
end
class B < A; end
h = {A.new => 1}
h[B.new]
```
```console
A
```
```console
B
```

Unify `eql?` receiver in `Hash` according to Ruby

---

include/mruby/compile.h
include/mruby/irep.h

From discoveries in #5001, adding documentation on the unexpected behavior of calling mrb_load_* functions leaking RProc objects. I took a look at the load_iseq paths and they exhibit the same behavior, so I documented that as well.
@matz expressed concern that fixing the leaking behavior in the core `load_iseq` or `mrb_load_exec` functions may cause other GC problems, so best case we can do currently is explain the situation and demonstrate how to overcome it.

Adding warnings for mrb_load functions leaking RProc objects

---

appveyor.yml
appveyor_config.rb

The following error occurs when using `rake -m` on AppVeyor:
```
fatal error C1041: cannot open program database 'C:\projects\mruby\vc140.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
```
Therefore, the issue is solved by not creating the PDB file. It is expected
to be somewhat faster by not generating debugging information (I don't think
debugging information is necessary for normal CI).

Retry `rake -m` on AppVeyor [skip travis]

---

include/mruby/array.h
src/array.c
src/vm.c
test/t/kernel.rb

Formerly, `__send__(*args)` modified `args` with `Array#shift`.
This bug affects optcarrot.
This changeset avoids the array destruction by using
`args = args[1, len-1]`.

Do not destruct rest arguments for __send__

---

mrbgems/mruby-compiler/core/y.tab.c
mrbgems/mruby-compiler/mrbgem.rake

I sometimes see Bison related problems in setting up build environments.
Therefore to remove Bison from build time dependencies, add `y.tab.c`
generated by Bison to the repository.
The reduction of dependency at build time also reduces the labor and time
for setup and installation in CI.
In addition, a path in `#line` directive is converted to a relative path so
that its path is constant regardless of development environments.

Add `y.tab.c` to remove Bison from build dependencies; ref 4ce3997c

---

tasks/mrbgems.rake

When building current mruby, adding new mgems by modifying `build_config.rb` or `mrbgems.rake` will additonally check out mgems into project. That is as we expect.
But `#{build_dir}/mrbgems/gem_init.c` won't be re-generated and re-built for now.
That file should have a dependency to mgems' directories and source files.

Detect newly added mrbgems when re-creating gem_init.c

---

include/mruby.h

Building and using `mruby.h` with the Microsoft compiler emits warnings
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\float.h(69): warning C4005: 'DBL_EPSILON': macro redefinition
mruby.h(78): note: see previous definition of 'DBL_EPSILON'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\float.h(83): warning C4005: 'FLT_EPSILON': macro redefinition
mruby.h(75): note: see previous definition of 'FLT_EPSILON'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\float.h(98): warning C4005: 'LDBL_EPSILON': macro redefinition
mruby.h(81): note: see previous definition of 'LDBL_EPSILON'
```
Including `float.h` looks like it fixes the issue. It looks like we include `float.h` elsewhere so this looks like a safe addition.

Fix float constant redefinition warnings

---

mrbgems/mruby-metaprog/src/metaprog.c
mrbgems/mruby-metaprog/test/metaprog.rb

This patch is resolve first case in #3710.

Get local variable names from orphan block; ref #3710

---

mrbgems/mruby-time/src/time.c
src/numeric.c
src/object.c

- `Fixnum#to_s`, `Fixnum#inspect`
- `Float#to_s`, `Float#inspect`
- `NilClass#to_s`, `NilClass#inspect`
- `FalseClass#to_s`, `FalseClass#inspect`
- `TrueClass#to_s`, `TrueClass#inspect`
- `Time#to_s`, `Time#inspect`

Set `MRB_STR_ASCII` flag to some stringize methods

---

test/assert.rb

Backtrace is useful for debugging.

Print exception backtrace if possible without `-v` in test

---

test/assert.rb

Check if the constant GEMNAME is defined before use in `assert.rb`
This is added to prevent an undefined constant error when using
`assert.rb` in other environments - for example, testing CRuby.
Before
```
ruby -I test -r assert -e "assert('w') { assert_true true; assert_true false }; report"
Traceback (most recent call last):
2: from -e:1:in `<main>'
1: from /home/user/mruby/test/assert.rb:107:in `assert'
/home/user/mruby/test/assert.rb:59:in `assertion_string': uninitialized constant GEMNAME (NameError)
3: from -e:1:in `<main>'
2: from /home/user/mruby/test/assert.rb:119:in `assert'
1: from /home/user/mruby/test/assert.rb:125:in `rescue in assert'
/home/user/mruby/test/assert.rb:59:in `assertion_string': uninitialized constant GEMNAME (NameError)
```
After
```
ruby -I test -r assert -e …
```

only use GEMNAME if defined in assert.rb

---

mrbgems/mruby-test/mrbgem.rake

An error may occur when performing `rake clean all` or `rake clean test`.
The directory is needed before writing to `mrbgems/mruby-test/assert.c`.

Need `build/XXX/mrbgems/mruby-test` directory

---

mrbgems/mruby-metaprog/src/metaprog.c

The following code was causing SIGSEGV:
```ruby
Module.method(:nesting).call
```

Remove `mrb_assert()` in `Module.nesting`

---

.github/workflows/build.yml
appveyor.yml
mrbgems/mruby-random/src/random.c

Quite the interesting issue here.
Summary of changes
===
- Work around MSC and MSC++ compiler bug where it would optimize away a union access which may contain a static value in random.c
- Updated appveyor config, added MS 2019 compilers, and uses the highest Ruby version available on the appveyor image
- Removed special compiler flags in github actions MSC build
Description
===
Currently the tests with master fails with the Microsoft compiler v19 with optimizations enabled. This _only_ happens with MSC and from what I can determine only with MSC > 19. The simplest reproduction is the Ruby expression from the Random test
```ruby
[1, 2].shuffle Random.new
```
Passing a Random instance to an Array causes a segfault. I have some insight as to what happens though I do not know how to fix it …

Work around MSC optimization generating non functional code with Array#shuffle

---

src/etc.c

Currently it looks like a bug where `object_id` of `true` and `false` is both zero. It looks like we expect the macro `MakeID2` as a bit shift `<<` instead of xor `^`.
This uses hardcoded values similar to how C Ruby uses a bitshift for special object names. I would prefer calculating the actual `intptr_t` of `nil`, `false` and `true` instances in the `mrb_state` though from what I can tell there aren't actual instances of these special values created? We also use `0` for free/undefined types and `false`. I did not change that, though I can if it's felt safe.
Before
```
> true.object_id
=> 0
> false.object_id
=> 0
> nil.object_id
=> 1
```
After
```
> true.object_id
=> 3
> false.object_id
=> 0
> nil.object_id
=> 4
```

object_id of true, false, and undef are all 0

---

.github/workflows/build.yml
appveyor.yml

Following from discussion on #5028 
- Does not use `rake -m` for avoiding mixing output from rake tasks. Further, it appears building with `-m` introduces other issues while performing separate build and test tasks. The project builds in less than a minute so I do not think the parallelization helps.
- Removes MSC build from github actions
- Removes VS 2013 from Appveyor matrix as 2013 is no longer supported by MS (https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing)
@shuujii I think this addresses your comments?

Update Windows CI settings

---

src/state.c

This function is removed by 9644ad5.

Remove the prototype declaration `mrb_free_backtrace()`

---

mrbgems/mruby-io/src/io.c

Legacy MinGW and MinGW-w64 had own `ssize_t`.

Fix `ssize_t` for mingw; ref #5030

---

mrbgems/mruby-test/mrbgem.rake
tasks/mrbgems.rake

The `${build_dir}/mrbgems/gem_init.c` generation condition has been changed
at #5010, but it is somewhat insufficient, for example, there was a problem
with `rake && rake test`, which was also regenerated in `rake test`.

Fix `${build_dir}/mrbgems/gem_init.c` generation condition; ref #5010

---

include/mruby/gc.h
include/mruby/hash.h
include/mruby/variable.h
mrbgems/mruby-objectspace/mrbgem.rake
mrbgems/mruby-objectspace/src/mruby_objectspace.c
mrbgems/mruby-objectspace/test/objectspace.rb
src/gc.c
src/hash.c
src/variable.c

Hello, this is my first significant contribution. I hope the review is not a burden.
This implements the mri method of `ObjectSpace.memsize_of`. With mruby we care a great deal about tracking resource use therefore I feel this is useful. All of the code is new, none copied. The mruby structures differ from C Ruby structures so existing C Ruby code isn't useful.
One difference between this implementation and the mri one is an addition of a `recurse` parameter. Specifying `ObjectSpace.memsize_of obj, recurse: true` will recursively descend into collection members and instance variables. Do let me know if I should not include this option and I will remove it.
Additionally, I added a protocol for `MRB_TT_DATA` objects. If a data object implements the `memsize` method this code will call that …

Add ObjectSpace.memsize_of

---

mrbgems/mruby-objectspace/src/mruby_objectspace.c
mrbgems/mruby-objectspace/test/objectspace.rb

Much simpler and I hope less error prone than before.

Add ObjectSpace.memsize_of_all

---

src/hash.c

The function corresponding to `ht_hash_func()` was as follows in the days of
khash implementation (before d78acc7a).
```c
mrb_hash_ht_hash_func(mrb_state *mrb, mrb_value key)
{
enum mrb_vtype t = mrb_type(key);
...
switch (t) {
...
default:
hv = mrb_funcall(mrb, key, "hash", 0);
h = (khint_t)t ^ (khint_t)mrb_fixnum(hv);
break;
}
...
}
```
When switched to the segmented list implementation (d78acc7a), this function
was changed as follows.
```c
sg_hash_func(mrb_state *mrb, seglist *t, mrb_value key)
{
enum mrb_vtype tt = mrb_type(key);
...
switch (tt) {
...
default:
hv = mrb_funcall(mrb, key, "hash", 0);
h = (size_t)t ^ (size_t)mrb_fixnum(hv);
break;
}
...
}
```
Since the argument `t` was added, the variable for type tag was changed from
`t` to `tt`, but the variable used in the expression …

Use type tag for hash code in `ht_hash_func()`

---

mrbgems/mruby-os-memsize/src/memsize.c

The `recurse` keyword is removed by f00657ead7c3e5f6f9a346d7797a280b5c9f02fa.

Update document for `ObjectSpace.memsize_of` [ci skip]

---

tasks/benchmark.rake

- Use POSIX format instead of GNU extension for `time` command.
For example FreeBSD's `time(1)` does not have GNU extensions available.
- Sort `benchmark/bm_*.rb`.
This is because the order of the bar graph cannot be uniquely determined depending on the result of `Dir.glob`.

Improve `rake benchmark`

---

include/mruby.h

The use of `struct` is an idea by @dearblue.

Allow `mrb_static_assert()` to be used outside of functions

---

mrbgems/mruby-io/src/file.c

It is described as `struct __stat32` in the MSVC reference manual.
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions?view=vs-2019
But it doesn't really exist, so it must use `struct _stat32`.
It also replaces `struct __stat64` with `struct _stat64` to make it look nicer.

Use `struct _stat32` instead of `struct __stat32`

---

include/mruby.h

* `_Static_assert` can also be used with `-std=gnu99` on GCC >= 4.6.
* `static_assert` can be used on MSVC.
* `static_assert` can be used even on old G++/Clang++ if
`__GXX_EXPERIMENTAL_CXX0X__` is defined.

Use normal `static_assert` in `mrb_static_assert` as much as possible

---

include/mruby/common.h
mrbgems/mruby-io/src/file.c
mrbgems/mruby-io/src/io.c

With recent changes in the `mruby-io` gem, it's now impossible to build **mruby** under the legacy MinGW environment. This little PR solve that issue.
The `MRB_MINGW32_LEGACY` macro has been added in `common.h` in order to identify the legacy MinGW environment. Please also note [MinGW](http://www.mingw.org) should not be confused with [MinGW-w64](http://www.mingw-w64.org).
For more info about MinGW defined macros used here, see: https://sourceforge.net/p/predef/wiki/Compilers/

mruby-io: Fixing compilation issue under the legacy MinGW environment

---

Rakefile

* e.g. symbols like "foo[]=" make invalid C codes... even in comments!
* https://github.com/mattn/mruby-http/blob/master/src/mrb_http.c#L652

Ensure exact match for symbols like `foo!/foo?/foo=` on presym.inc generation

---

Rakefile

Old patterns skip ruby files like `mrblib/foo/bar.rb`. I've added glob patterns to improve coverage.

Scan ruby files in directories

---

include/mruby.h

It seems to be unnecessary from mruby-1.0.0 or earlier.

Remove `enum call_type`

---

include/mruby/compile.h
lib/mruby/gem.rb
mrbgems/mruby-bin-mirb/bintest/mirb.rb
mrbgems/mruby-bin-mirb/tools/mirb/mirb.c
mrbgems/mruby-bin-mruby/bintest/mruby.rb
mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
mrbgems/mruby-compiler/core/parse.y

- Add `mrbc_cleanup_local_variables()` function with `MRB_API`
- In `mirb` command, the `_` variable is defined after the `-r` switch

Fix take over file scope variables with `mruby` and `mirb` command

---

lib/mruby/build/command.rb

As pointed out by @shuujii on https://github.com/mruby/mruby/pull/5079 ,
multi-path in single-line could be appear even with older-gcc or clang.

*.d format is version-independent

---

src/string.c

since mrb_str_to_str() also does it.

Remove redundant type-check

---

examples/mrbgems/c_and_ruby_extension_example/mrblib/example.rb
examples/mrbgems/c_and_ruby_extension_example/src/example.c
examples/mrbgems/c_extension_example/src/example.c
examples/mrbgems/ruby_extension_example/mrblib/example.rb

Before this commit:
```sh
mruby -e 'CRubyExtension.ruby_method' # => A Ruby Extension
mruby -e 'CRubyExtension.c_method'    # => A C Extension
mruby -e 'CExtension.c_method'        # => A C Extension
mruby -e 'RubyExtension.ruby_method'  # => A Ruby Extension
```
After this commit:
```sh
mruby -e 'CRubyExtension.ruby_method' # => CRubyExtension: A Ruby Extension
mruby -e 'CRubyExtension.c_method'    # => CRubyExtension: A C Extension
mruby -e 'CExtension.c_method'        # => CExtension: A C Extension
mruby -e 'RubyExtension.ruby_method'  # => RubyExtension: A Ruby Extension
```

examples/mrbgems: clarify the caller

---

include/mruby.h
mrbgems/mruby-eval/src/eval.c
mrbgems/mruby-io/src/file.c
mrbgems/mruby-socket/src/socket.c
mrbgems/mruby-string-ext/src/string.c
src/class.c

- The `s` specifier is a string pointer obtained without performing `mrb_str_modify()`, so it cannot be changed.
- The `z` specifier cannot be changed because it is a string pointer obtained by `RSTRING_CSTR()` which returns `const char *`.

Prohibit string changes by "s"/"z" specifier of `mrb_get_args()`

---

mrbgems/mruby-range-ext/test/range.rb

Fix improper test in `mrbgems/mruby-range-ext/test/range.rb` that tests Range#max even though it is the part of Range#min.

fix improper test of Range#min

---

src/numeric.c

Fixed improper argument of mrb_fixnum_value().
When built with MRB_WITHOUT_FLOAT flag, build fails as below:
```
$ CFLAGS="-DMRB_WITHOUT_FLOAT" rake
CC    src/vm.c -> build/host/src/vm.o
CC    src/error.c -> build/host/src/error.o
CC    src/dump.c -> build/host/src/dump.o
CC    src/string.c -> build/host/src/string.o
CC    src/init.c -> build/host/src/init.o
CC    src/hash.c -> build/host/src/hash.o
CC    src/numeric.c -> build/host/src/numeric.o
/home/wataru/dev-mruby/src/numeric.c: In function ‘integral_div’:
/home/wataru/dev-mruby/src/numeric.c:161:27: warning: passing argument 1 of ‘mrb_fixnum_value’ makes integer from pointer without a cast [-Wint-conversion]
161 |   return mrb_fixnum_value(mrb, mrb_fixnum(xv) / y);
|                           ^~~
|                           |
| …
```

Fix argument error when built with MRB_WITHOUT_FLOAT flag

---

mrbgems/mruby-string-ext/mrblib/string.rb

Remove unnecessary assignment in String#upto.
`len` is already assigned to in L409 and not modified afterwards. So no need to assign in L425.

Remove unnecessary assignment in String#upto

---

README.md
include/mruby/version.h

Change mruby version to `3.0.0` for preview.
Some document (e.g. `doc/limitations.md`) has not changed yet.

mruby 3.0.0-preview.

---

include/mruby.h
src/array.c
src/class.c

The `mrb_get_argv()` function will now return `const mrb_value *`.
This is because it is difficult for the caller to check if it is a splat argument (array object) and to write-barrier if necessary.
----
This is a part of #5097.

Prohibit array changes by `mrb_get_argv()`

---

include/mruby.h
mrbgems/mruby-array-ext/src/array.c
mrbgems/mruby-eval/src/eval.c
mrbgems/mruby-fiber/src/fiber.c
mrbgems/mruby-hash-ext/src/hash-ext.c
mrbgems/mruby-io/src/file.c
mrbgems/mruby-io/src/io.c
mrbgems/mruby-metaprog/src/metaprog.c
mrbgems/mruby-method/src/method.c
mrbgems/mruby-print/src/print.c
mrbgems/mruby-proc-ext/test/proc.c
mrbgems/mruby-sprintf/src/sprintf.c
mrbgems/mruby-string-ext/src/string.c
mrbgems/mruby-struct/src/struct.c
mrbgems/mruby-test/driver.c
src/array.c
src/class.c
src/kernel.c
src/vm.c

The "a"/"*" specifier of the `mrb_get_args()` function will now return `const mrb_value *`.
This is because it is difficult for the caller to check if it is an array object and write-barrier if necessary.
And it requires calling `mrb_ary_modify()` on the unmodified array object, which is also difficult (this is similar to #5087).
----
This is a part of #5097.

Prohibit array changes by "a"/"*" specifier of `mrb_get_args()`

---

mrbgems/mruby-eval/src/eval.c
src/proc.c

The `mrb_env_new()` function is a global function, but it is still treated as an internal function.

Reorganize `env_new()` as `mrb_env_new()`

---

Rakefile
doc/mruby3.md

When `rake -m` and so on are used to build in parallel, building may be
started before presym files are generated. Then, for example, the following
error occurs and this issue is fixed.
```console
In file included from /Users/shuujii/mruby/mruby/include/mruby.h:92:
/mruby/mruby/include/mruby/presym.h:16:10: fatal error: '../build/presym.inc' file not found
#include <../build/presym.inc>
^~~~~~~~~~~~~~~~~~~~~
```

Fix parallel build

---

mrbgems/mruby-compiler/mrbgem.rake

In the case of `y.tab.o`, `y.tab.d` was not read, so `y.tab.c` was not
recompiled by updating header files.
It seemed that the cause was overwriting the rake rule, so I deleted
unnecessary settings.

Fix dependencies of `y.tab.o`

---

Rakefile

Fix that updating presym target files would recompile almost all files even
if symbols did not change.

Reduce recompilation when updating presym target files

---

src/state.c

If no gem was specified, it was warning because `init_mrbgems()` was not used.
ref: #4250

Suppress `-Wunused-function`

---

include/mruby/boxing_nan.h

`SET_CPTR_VALUE()` requires the `p` field on 32-bit CPU mode.

Fixed build NaN boxing with 32-bit CPU mode

---

mrbgems/mruby-io/src/io.c

We don't need to require valid STDIN/STDOUT/STDERR. If we require it, we
can't use mruby on environment that doesn't have valid
STDIN/STDOUT/STDERR such as Windows service process. Windows service
process doesn't have valid STDIN.

Don't check FD for STDIN/STDOUT/STDERR; #5114

---

include/mruby/boxing_nan.h
include/mruby/boxing_word.h
src/etc.c

This is to make it possible to distinguish between `mrb_value` and `mrb_sym` in C++ "Function overloading" and C11 "Generic selection".

Define `mrb_value` in struct for Word/NaN boxing

---

include/mruby/hash.h
mrblib/hash.rb
src/hash.c
test/t/hash.rb

* Change entry list from segmented list to flat array.
* Change value of hash bucket from pointer to entry to index of entry list,
and represent it by variable length bits according to capacity of hash
buckets.
* Store management information about entry list and hash table to `struct
RHash` as much as possible.
Only the results of typical situations on 64-bit Word-boxing are present
here. For more detailed information, including consideration, see below
(although most of the body is written in Japanese).
* https://shuujii.github.io/mruby-hash-benchmark
Lower value is better.
| Hash Size |   Baseline    |      New      |   Factor   |
|----------:|--------------:|--------------:|-----------:|
|        16 |          344B |          256B |   0.74419x |
|        40 |        1,464B | …

Reduce memory usage of Hash object

---

Rakefile
include/mruby.h
include/mruby/presym.h
mrbgems/mruby-compiler/core/codegen.c
mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c
mrbgems/mruby-io/src/io.c
mrbgems/mruby-kernel-ext/src/kernel.c
mrbgems/mruby-method/src/method.c
mrbgems/mruby-socket/src/socket.c
src/array.c
src/kernel.c
src/object.c
src/proc.c
src/symbol.c
src/vm.c

To be also able to build mruby without presym in the future. However, it is
NOT compatible with previous macros.
|       Type        |  Symbol  |           Old Usage          |    New Usage    |
|-------------------|----------|------------------------------|-----------------|
| Operator          | `&`      | `MRB_QSYM(and)`              | `MRB_OSYM(and)` |
| Special variable  | `$,`     | `mrb_intern_lit(mrb,"$,")`   | `MRB_XSYM(ofs)` |
| Class variable    | `@@foo`  | `MRB_QSYM(00_foo)`           | `MRB_CSYM(foo)` |
| Instance variable | `@foo`   | `MRB_QSYM(0_foo)`            | `MRB_ISYM(foo)` |
| Global variable   | `$foo`   | `mrb_intern_lit(mrb,"$foo")` | `MRB_GSYM(foo)` |
| Bang method       | `foo!`   | `MRB_QSYM(foo_b)`            | `MRB_BSYM(foo)` |
| Predicate method  | `foo?` …

Change name and usage of presym macros

---

include/mruby/hash.h
mrbgems/mruby-os-memsize/src/memsize.c
src/hash.c

* The term `hash_table` can be misleading because the return value of this
function includes memory usage of entire `Hash` object, including not only
hash table part but also entry list part, etc.
* This function takes a `Hash` object as a receiver and is defined in
`src/hash.c`, so it is natural to have a `mrb_hash_` prefix.

Rename `mrb_os_memsize_of_hash_table` to `mrb_hash_memsize`

---

include/mruby/class.h
mrbgems/mruby-metaprog/src/metaprog.c
src/class.c

The `MRB_API` function `mrb_mt_foreach()` previously used the private structure `struct mt_elem`.
Therefore, use `mrb_method_t` instead.
---
Alternatively, I think it's better to remove the `MRB_API`.

Don't use private structs with `mrb_mt_foreach()`

---

lib/mruby/build/command.rb

ref: https://github.com/mruby/mruby/pull/4959#discussion_r402086196
Compiles twice because it falls back to `build.filename(command)` when
`command` fails. This process was added at 9968af4 to support `ccache gcc`
etc. At that time, it seems that it was necessary because
`build.filename(command)` quoted the whole `command`, but now it does not
quote, so we can just run `build.filename(command)`.
```console
$ echo 1 > src/a.c
$ rake -v
```
```console
(snip)
gcc -std=gnu99 -g -O3 -Wall -Wundef -Wdeclaration-after-statement -Werror-implicit-function-declaration -Wwrite-strings -I"/mruby/mruby/include" -MMD -o "/mruby/mruby/build/host/src/a.o" -c "/mruby/mruby/src/a.c"
/mruby/mruby/src/a.c:1:1: error: expected identifier or '('
1
^
1 error generated.
gcc -std=gnu99 -g -O3 -Wall -Wundef …
```

Simplify `MRuby::Command#_run` to avoid duplicated compilation

---

tasks/toolchains/gcc.rake

There is no need to execute command in duplicate for the same
reason as #5128.

Remove redundant command execution in `header_search_paths`

---

src/gc.c

```ruby
int_count = ObjectSpace.count_objects[:T_INTEGER]||0
int = 1<<30
p (ObjectSpace.count_objects[:T_INTEGER]||0) - int_count
int = nil
GC.start
p (ObjectSpace.count_objects[:T_INTEGER]||0) - int_count
```
```console
1
1
```
```console
1
0
```

Fix that large integer is not GCed with Word-boxing

---

Rakefile

When building from outside `MRUBY_ROOT` (e.g. `rake -f`), gem files were not
scanned.

Fix paths of gem files to be scanned for presym

---

src/codedump.c
src/vm.c

```console
$ bin/mruby -ve '-0x40000000'
mruby 3.0.0preview (2020-10-16)
00001   NODE_BEGIN:
00001     NODE_NEGATE:
00001       NODE_INT 40000000 base 16
irep 0x6070000001e0 nregs=2 nlocals=1 pools=0 syms=0 reps=0 iseq=9
file: -e
/mruby/src/codedump.c:173:49: runtime error: left shift of 49152 by 16 places cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /mruby/src/codedump.c:173:49 in
1 000 OP_LOADI32	R1	-1073741824
1 006 OP_RETURN	R1
1 008 OP_STOP
/mruby/src/vm.c:1138:7: runtime error: left shift of 49152 by 16 places cannot be represented in type 'mrb_int' (aka 'int')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /mruby/src/vm.c:1138:7 in
```

Avoid undefined behavior

---

include/mruby/boxing_word.h

`mrb_bool`  on LLP64 environment seems to become false if, for example,
`mrb_value` is a pointer whose lower 32 bits are 0.

Use `uintptr_t` instead of `unsigned long` in `include/mruby/boxing_word.h`

---

.github/workflows/build.yml

I tried `$GITHUB_PATH` and `$GITHUB_ENV` instead of `set-env`, but
for some reason path was not recognized, so I changed to using
`ACTIONS_ALLOW_UNSECURE_COMMANDS`.

Fix deprecated `set-env` command error on GitHub Actions [ci skip]

---

lib/mruby/build.rb

The writers seem to be unnecessary because `MRuby::Build#enable_{bin,}test`
are used from the beginning.

Remove unused `MRuby::Build#enable_{bin,}test=`

---

tasks/toolchains/gcc.rake

* Consider `CC` envvar as C compiler on which to make the decision.
* Consider the case where C compiler is `ccache gcc`, etc.

Improve determining C++ compiler in `tasks/toolchains/gcc.rake`

---

src/class.c

This object is treated as an immediate value.

Unable for the `MRB_TT_CPTR` object to have a singleton class

---

build_config/boxing.rb

`boxing-nan-m64` was duplicated.

Fix incorrect build name and simplify `build_config/boxing.rb` [ci skip]

---

include/mruby/compile.h
mrbgems/mruby-bin-mruby/bintest/mruby.rb
mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
mrbgems/mruby-bin-strip/bintest/mruby-strip.rb
mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c

It is not decides by the extension.
The first 64 bytes of the file are read, and if there is a `NUL` symbol in it, it is recognized as a binary file and read as a `mrb` file.
If there is no `NUL` symbol, it is judged as a text file and it is processed as a Ruby script.
The `bin/mruby -b` switch is still available which treats the given file as a `.mrb` file.
New `MRB_API` function:
- `include/mruby/dump.h` and `src/load.c`
- `mrb_load_detect_file_cxt()` (remove with `MRB_DISABLE_STDIO`)
New internal function (not static):
- `include/mruby/compile.h` and `mrbgems/mruby-compiler/core/parse.y`
- `mrb_parse_file_continue()` (remove with `MRB_DISABLE_STDIO`)
- `mrb_load_file_continue_cxt()` (remove with `MRB_DISABLE_STDIO`)
NOTE:
- Even script files now always open in binary mode for …

Allow to mixed and specify `*.rb` and `*.mrb` in `bin/mruby`

---

mrbgems/mruby-metaprog/src/metaprog.c
src/class.c

Integrate the implementation with `Module#define_method`.
- Introduce the internal function `mrb_mod_define_method_m()` (no static)
- The `Object#define_singleton_method` method can now accept a second argument

Improved `Object#define_singleton_method`

---

Rakefile
lib/mruby/core_ext.rb

Because `_pp` is originally defined in `lib/mruby/core_ext.rb`, other global
functions are moved to the file.

Move global function for build to `lib/mruby/core_ext.rb`

---

Rakefile
lib/mruby/build/command.rb
lib/mruby/core_ext.rb
lib/mruby/gem.rb
mrbgems/mruby-test/mrbgem.rake

* Output `GEN` log for generated files
* `MRBC` log is outputted one for each `mrbc` execution
```console
CC    src/array.c -> build/host/src/array.o
(snip)
GEN   mrblib/*.rb -> build/host/mrblib/mrblib.c
MRBC mrblib/00class.rb
MRBC mrblib/10error.rb
(snip)
CC    mrbgems/mruby-time/src/time.c -> build/host/mrbgems/mruby-time/src/time.o
MRBC mrbgems/mruby-time/mrblib/time.rb
(snip)
CC    mrbgems/mruby-socket/test/sockettest.c -> build/host/mrbgems/mruby-socket/test/sockettest.o
MRBC mrbgems/mruby-socket/test/addrinfo.rb
MRBC mrbgems/mruby-socket/test/basicsocket.rb
(snip)
```
```console
GEN   build/presym
GEN   build/presym.inc
CC    src/array.c -> build/host/src/array.o
(snip)
GEN   mrblib/*.rb -> build/host/mrblib/mrblib.c
MRBC mrblib/00class.rb
mrblib/10error.rb
(snip)
CC …
```

Refine build log for generated files

---

src/load.c

`pool[i]` pointed to invalid memory.

Fix unintended variable shadowing

---

include/mruby/boxing_nan.h

If it gives clang-11.0 `-Wembedded-directive`, a warning will be reported in `include/mruby/boxing_nan.h`.
```
include/mruby/boxing_nan.h:48:2: warning: embedding a directive within macro arguments has undefined behavior [-Wembedded-directive]
include/mruby/boxing_nan.h:52:2: warning: embedding a directive within macro arguments has undefined behavior [-Wembedded-directive]
```
The cause of this is #5117.
ref. e993b83c509912f2d90ffece32c969a642f5df01

Avoid warnings from clang's "-Wembedded-directive"

---

Rakefile
lib/mruby/build.rb

Fix #5177 
I'm not sure this is the intended way. 
I've just split the two steps:
1) Calculating MRUBY_CONFIG
2) Loading MRUBY_CONFIG
... so Rakefile could hook between the 2 steps.

Fix #5177 by setting MRUBY_CONFIG early

---

doc/guides/mrbconf.md
src/symbol.c

However, compiling by `mrbc` fails with another issue (#5116).

Fix C source compilation with `MRB_USE_ALL_SYMBOLS`; ref #5187

---

lib/mruby/build.rb
lib/mruby/build/command.rb

For example, in the case of the C++ compiler, it is output as
`CXX  build/host/src/gc.cxx -> build/host/src/gc.cxx.o` (FYI, in the case
of `enable_cxx_abi`, it outputs `CC ...` because the option to compile as
C++ is added to C compiler).

Allow compiler name in build log to be customized

---

Rakefile
doc/guides/compile.md
include/mruby/presym.h
lib/mruby/build.rb
src/symbol.c
tasks/presym.rake

Previously, presym files were always created in `build/{presym,presym.inc}`.
However, this constraint is inconvenient because it is common to use
multiple build configurations and build targets in a single mruby tree.
Therefore, change to create presym file for each build target.

Create presym files for each build target

---

Rakefile
tasks/presym.rake

Fix the following two issues:
1. Compile failure when external gem is specified.
* https://github.com/mruby/mruby/pull/5194#issuecomment-734303442
2. When there are multiple build targets, presym parsing sometimes fails or
output result of presym is broken.
* https://github.com/mruby/mruby/pull/5194#issuecomment-734322142
The root cause of 2 is unknown, but it seems to occur when presym parsing is
performed in parallel, therefore I change them so that they are not run in
parallel.

Fix build failure; ref #5194

---

src/dump.c

Currently, the size of writing in heap by write_irep_record() is bigger than The size that is calculated by get_irep_record_size.
Therefore, irep is dumped over the size of allocating memory when we execute dump_irep().
`rake test` fail by the buffer overflow.
I used fc98aa290f6256ea64ca7792af483d4d31131cd5 in the following procedure.
```
% git clone git@github.com:kou/mruby-pp.git
% cd mruby-pp
% git submodule update --init
% git submodule update --remote
% rake test
% gdb --args "./mruby/build/host/bin/mrbc" -Bgem_mrblib_irep_mruby_pp -o- "./mrblib/0_prettyprint.rb" "./mrblib/1_pp.rb"
(gdb) b dump.c:804
(gdb) b dump.c:835
(gdb) start
(gdb) c
(gdb) p section_irep_size
$1 = 11990
(gdb) c
(gdb) p section_irep_size
$2 = 12002
```
mruby write the following data in write_irep_record().
``` …
```

Fix heap buffer overflow when dump irep

---

src/codedump.c

It became 32 bits in #5200, but only the upper 16 bits were printed.

Fixed print catch handler address in codedump; ref #5200

---

lib/mruby/build.rb
lib/mruby/gem.rb

Currently, the source file language in the core is C only, and C++,
Objective-C, and Assembly are not used, so Rake rules for them are removed.

Remove unused Rake rules

---

Rakefile

Currently, adding gems to build configuration and rebuilding does not
regenerate `presym`, which can lead to build errors.
Therefore in this case we need to remove the `presym` file and then rebuild
mruby, but when the` presym` file is regenerated we will need to recompile
most of the files, so it seems useful to have the `presym` file deleted by
`rake clean`.

Remove `build/presym{,.inc}` by `rake clean` [ci skip]

---

Rakefile
build_config/no-float.rb
lib/mruby/build.rb
lib/mruby/gem.rb
mrbgems/default.gembox
mrbgems/mruby-bin-mrbc/mrbgem.rake
mrbgems/mruby-compiler/mrbgem.rake
tasks/core.rake
tasks/libmruby.rake
tasks/mrblib.rake

Previously, `libmruby.a` was created even if only `mruby-bin-mrbc` or`
mruby-compiler` was specified for gem, but by specifying `disable_libmruby`,
the creation of `libmruby.a` can be suppressed.
The https://github.com/mruby/mruby/pull/5084#issuecomment-723521971
incompatibility seems to be difficult for users to avoid, so the original
behavior has been restored. Therefore, if we need `mrbc` other than the
`host` build, we need to explicitly specify `mruby-bin-mrbc` gem.
Due to the above changes, `build_config/boxing.rb` etc. will not work, but I
have added` mruby-bin-mrbc` to `default.gembox` to fix it. I don't think
this change is a big deal because originally `mruby-compiler` was included.

Make it possible that `libmruby.a` is not created

---

lib/mruby/build.rb

Call `super` (`block`) ahead so that creation of the `host` build can be
skipped if pre-built `mrbc` can be specified in the future.
close #5213.

Call `super` before creating `host` build in `MRuby::CrossBuild#initialize`

---

src/gc.c

Union initialization initializes the first member. The first member of
`RVALUE` is `struct free_obj`, but because it is only 4-words, it seems that
initialization after the 5th word is not ensured.
Therefore, I created 6-words `struct RVALUE_initializer` for initialization
and made it the first member.

Ensure initialization of `RVALUE_zero` in `mrb_obj_alloc`

---

lib/mruby/build.rb
mrbgems/mruby-bin-config/mrbgem.rake

If it adds `mruby-bin-config` inside `MRuby::CrossBuild`, the build will fail.
```ruby
MRuby::CrossBuild.new("cross-mingw32") do |conf|
toolchain "gcc"
compilers.each { |cc| cc.command = "mingw32-#{cc.command}" }
linker.command = "mingw32-gcc"
archiver.command = "mingw32-ar"
exts.executable = ".exe"
gem core: "mruby-bin-config"
end
```
```console
% rake30 MRUBY_CONFIG=mingw32_config.rb
...SNIP...
rake aborted!
Don't know how to build task '/var/tmp/mruby/build/cross-mingw32/bin/mruby-config.exe' (See the list of available tasks with `rake --tasks`)
```
I think I was able to build it before, but as far as I can see `mrbgems/mruby-bin-config/mrbgem.rake`, It's trying to ignore it in cross build.
https://github.com/mruby/mruby/blob/08d4365252d421f71800992b34684e320ce41ca6/mrbgems/mruby-bin-co …

Ignore `mruby-bin-config` in cross-building

---

Doxyfile
doc/guides/debugger.md

Pretty sure the rules are relaxed for code blocks when it comes to linting Markdown.
So the linter doesn't find the unneeded trailing whitespace in code blocks.
The `Doxyfile` is a text file and we don't have checking on the CI for those yet.

refactor: remove trailing whitespace

---

build_config/IntelGalileo.rb
doc/guides/mrbgems.md

- changed `github` to `GitHub`

refactor: fix case of GitHub and fix missing HTTPS on link

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/oss-fuzz.yml

* Skip if commit message contains `ci skip`, `skip ci`, or `skip gha`
ENCLOSED WITH BRACKETS (excluding lint job).
* Separate build and test. This is because builds can be run in parallel,
but running tests in parallel can cause logs to get mixed up or not
finished.
* Don't use Chocolatey because it seems to take 1-2 minutes to start up.
* Use the cache better.
* Use `actions/checkout@v2` instead of `actions/checkout@v1`.
* Remove unnecessary package installation.
* Remove unnecessary flag settings.
* Remove `-j` for rake because it doesn't seem to have any effect.
* Rename `main.yml` to `oss-fuzz.yml` to clarify.

Reorganize GitHub Actions configuration [skip travis][skip appveyor]

---

.github/workflows/spell-checker.yml

To avoid including `.git` directory.

Use `git ls-files` instead of `find` in `spell-checker.yml` [ci skip]

---

build_config/gameboyadvance.rb

Hey everyone!
I've gotten mruby running on a Nintendo GameBoyAdvance and wanted to contribute my build config to the project.
It's pretty simple. I modeled it after the Dreamcast one, but in this case I'm using the the devkitPro toolchain to do the cross-compiling.
The biggest drawback here is that I've only tested it on Linux. I don't have access to a Mac and would have no idea how to even start going about doing any development on a Windows machine, but since the build configs here seem to mostly act as examples, I think there's still plenty of value in adding it as-is.
Happy Holidays!

Add example for cross-compiling to Nintendo GameBoyAdvance

---

mrbgems/mruby-eval/src/eval.c

The comment says that if `mrb_parse_nstring()` returns `NULL`, it is only out of memory.
I'm worried about compatibility if I set the exception class to `NoMemoryError`, so it's still `RuntimeError`.

Improves out of memory messages for `eval`

---

AUTHORS
include/mruby/compile.h
mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c
test/t/literals.rb

Hello, I have added support for [squiggly heredocs](https://ruby-doc.org/core-2.7.2/doc/syntax/literals_rdoc.html#label-Here+Documents+-28heredocs-29) to mruby. Please tell me if I did anything wrong! (Should I commit `y.tab.c`?)

Add support for squiggly heredocs

---

mrbgems/mruby-hash-ext/src/hash-ext.c
mrbgems/mruby-hash-ext/test/hash.rb

This PR adds `Hash#except` to match mruby with Ruby 3

Add `Hash#except` [Ruby 3.0]

---

include/mruby/compile.h
mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c
test/t/literals.rb

This fixes most of the issues @shuujii mentioned in https://github.com/mruby/mruby/pull/5247
```ruby
p <<~EOS
\t
a
EOS
p <<~EOS
(hard tab)
a
EOS
p <<~EOS
\t(escaped tab)
a
EOS
```
```console
$ ruby examples.rb
"\t\n a\n"
"\t(hard tab)\na\n"
"\t(escaped tab)\n a\n"
```
```console
$ mruby examples.rb
"\t\n a\n"
"\t(hard tab)\n a\n"
"\t(escaped tab)\n a\n"
```

Fix mixed indentation and escaped tabs in squiggly heredocs

---

src/class.c

```console
$ bin/mruby -e '{}.key?'
-e:1: wrong number of arguments (ArgumentError)
```
```console
$ bin/mruby -e '{}.key?'
-e:1: wrong number of arguments (given 0, expected 1) (ArgumentError)
```

Refine error message from `mrb_get_arg1`

---

src/gc.c

The substance of the method was removed in commit 15ceb35e058a078f632a1ff7d0d424c59d48cd80.

Removed unusable `GC.test`

---

src/class.c
test/t/argumenterror.rb

```ruby
__send__         #=> wrong number of arguments
{}.default(1,2)  #=> wrong number of arguments
```
```ruby
__send__         #=> wrong number of arguments (given 0, expected 1+)
{}.default(1,2)  #=> wrong number of arguments (given 2, expected 0..1)
```

Refine "wrong number of arguments" message in `mrb_get_args`

---

include/mruby/compile.h
mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c
test/t/literals.rb

This fixes the issue @shuujii mentioned in #5249. (I forgot to check if spaces are at the beginning of the line before counting them as part of the indent.) Also, this PR includes a change to treat tabs as 8 spaces. (Thanks @shuujii! I wouldn't have noticed these things without your reviews!)
```ruby
p <<~EOS
( )
a
EOS
p <<~EOS
(hard tab)
(6 spaces)
EOS
p <<~EOS
(hard tab)
(8 spaces)
EOS
p <<~EOS
(hard tab)
(10 spaces)
EOS
```
```console
$ ruby example.rb
"( )\n a\n"
"\t(hard tab)\n(6 spaces)\n"
"(hard tab)\n(8 spaces)\n"
"(hard tab)\n  (10 spaces)\n"
```
```console
$ mruby example.rb
"( )\n a\n"
"\t(hard tab)\n(6 spaces)\n"
"(hard tab)\n(8 spaces)\n"
"(hard tab)\n  (10 spaces)\n"
```

Fix regression for squiggly heredocs

---

mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c
test/t/literals.rb

This fixes the issue @dearblue mentioned in #5251
```rb
p <<~TEXT1
a \
b
TEXT1
p <<~TEXT2
a \
b
TEXT2
```
```console
$ ruby test.rb
"a b\n"
"  a b\n"
```
Before:
```console
$ bin/mruby test.rb
"a   b\n"
"a b\n"
```
After:
```console
$ bin/mruby test.rb
"a b\n"
"  a b\n"
```

Fix for escaped newlines in squiggly heredocs

---

mrbgems/default-no-fpu.gembox
mrbgems/default-no-stdio.gembox
mrbgems/default.gembox
mrbgems/math.gembox
mrbgems/metaprog.gembox
mrbgems/stdlib-ext.gembox
mrbgems/stdlib-io.gembox
mrbgems/stdlib.gembox

I think that it is easy to use if it is divided according to the type of library and the general purpose.
It is a subdivision from the previous `default.gembox`.
By type gembox:
- `stdlib`: Add some standard Ruby methods not provided by core.
- `stdlib-ext`: Add some standard Ruby methods that are not provided by `stdlib`.
- `stdlib-io`: Provides `IO`, `File`, `Socket`, `print`, etc. Conflict with `MRB_NO_STDIO`
- `math`: Add a class related to math. Conflict with `MRB_NO_FLOAT`
- `metaprog`: Adds features related to metaprogramming.
Purpose gembox:
- `default.gembox`: Import the same gems as before
- `default-no-stdio.gembox`: Import the` stdlib` and `math`
- `default-no-fpu.gembox`: Import the` stdlib` only
---
I think there is room for debate about the gembox name and classification.

Take advantage of gembox

---

mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c

```rb
p <<~EOS
(space)\
(hard tab)
EOS
p <<~EOS
(hard tab)\
\t(escaped tab)
EOS
```
`ruby`:
```console
$ ruby test.rb
"(space)\t(hard tab)\n"
"\t(hard tab)\t(escaped tab)\n"
```
`mruby` before:
```console
$ mruby test.rb
" (space)\t(hard tab)\n"
"(hard tab)(escaped tab)\n"
```
`mruby` after:
```console
$ mruby test.rb
"(space)\t(hard tab)\n"
"\t(hard tab)\t(escaped tab)\n"
```

Fix line continuations with mixed indentation in squiggly heredocs

---

.github/workflows/build.yml
.travis.yml
appveyor.yml
build_config/ci/gcc-clang.rb
build_config/ci/msvc.rb

Set in build configuration to enable on all CI platforms.

Immediately flush output to stdout/stderr so that logs are not mixed on CI

---

tasks/doc.rake
tasks/gitlab.rake

Change the Rake task to one that uses namespaces as follows (previous task
names can also be used for compatibility).
| Previous Task  |    New Task    |
|----------------|----------------|
| api_doc        | doc:api        |
| capi_doc       | doc:capi       |
| clean_doc      | doc:clean      |
| clean_api_doc  | doc:clean:api  |
| clean_capi_doc | doc:clean:capi |
| view_api       | doc:view:api   |
| view_capi      | doc:view:capi  |
| gitlab_config  | gitlab:config  |
| gitlab_dockers | gitlab:dockers |

Use namespaces according to Rake conventions

---

build_config/ci/gcc-clang.rb
build_config/ci/msvc.rb

During parallel execution (build), it is sometimes flushed before line
breaks, and lines are concatenated.

Stop immediate flush to stdout/stderr when running in parallel on CI

---

.github/workflows/build.yml
.travis.yml
Rakefile
appveyor.yml
lib/mruby/build.rb
lib/mruby/gem.rb
mrbgems/mruby-test/mrbgem.rake
tasks/bin.rake
tasks/mrbgems.rake
tasks/test.rake

With this change, the test code will not be built unless `rake test` is
run, so there will be almost no side effects even if `enable_test` is
always set (but, gems specified by `add_test_dependency` are included
in `libmruby.a`).
Also added are `test: build` task, which only builds the test code
(including the main code), and `test: run` task, which only runs tests
independent of build. Therefore, the idiom for building in parallel and
not running tests in parallel is `rake -m test:build && rake test:run`.

Delay test code build until `rake test`

---

src/load.c
src/proc.c

Previously I used the `RData` object to avoid a memory leak in `mrb_irep` if `src/load.c` failed.
ref: https://github.com/mruby/mruby/pull/4250
commit: f1523d24042ca3416dc5b9be7b3fc220ddaed896
Considering that the `RProc` object will be created in the subsequent process, it is preferable to create the `RProc` object from the beginning.
Along with this, the inside of `read_irep()` is replaced with the processing centered on the `RProc` object.
The global function that returns the `mrb_irep` pointer is still provided for compatibility.

Replace `tempirep` with `RProc`

---

build_config/no-float.rb

Use `enable_test` to enable the test.

Remove unneeded `mruby-test` gem in `build_config/no-float.rb` [ci skip]

---

tasks/presym.rake

With the change in #5267, `build.products` no longer contains `mrbtest` when
`tasks/presym.rake` is loaded.

Remove unneeded check to `mrbtest` in `tasks/presym.rake`

---

mrbgems/mruby-bin-config/mrbgem.rake

The output directory will be `host-bin`, so it will be output as `<build-dir>/host-bin/mruby-config`.
It's still not available for target devices.

Create a `mruby-config` that can be run on the host by cross-building

---

mrbgems/mruby-io/src/io.c

- Use `mrb_notimplement_m()` instead.
- Hide the unused `option_to_fd()` when `TARGET_OS_IPHONE` is enabled.

Remove functions for unimplemented methods

---

tasks/test.rake

The cause is that `mrbgem.rake` of` mruby-test` gem is loaded when test
code is requested to be built, but when `mrbgem.rake` is loaded,
`MRuby::Gem.current` is updated, which is not thread safe.
Address this by not loading `mrbgem.rake` in parallel.

Fix that sometimes parallel build of test code fails; fix #5284

---

include/mruby.h
include/mruby/proc.h
lib/mruby/gem.rb
mrbgems/mruby-bin-mirb/tools/mirb/mirb.c
mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
mrbgems/mruby-class-ext/src/class.c
mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c
mrbgems/mruby-eval/src/eval.c
mrbgems/mruby-fiber/src/fiber.c
mrbgems/mruby-object-ext/src/object.c
src/backtrace.c
src/class.c
src/gc.c
src/kernel.c
src/proc.c
src/vm.c

Overview
- `mrb_callinfo::stack` will now indicate the current call level.
Previously, `stackent` saved the previous stack.
- `mrb_callinfo::pc` will now indicate the current call level.
Previously, this saved the previous one.
This change reverts commit a0c1e075e35c358d21934c28ff1bec4153502409.
- ` mrb_callinfo::argc` and` mrb_callinfo::acc` are represented by `int16_t`.
- Represents `mrb_callinfo::env` and `mrb_callinfo::target_class` with union.

Reorganize mrb_callinfo

---

mrbgems/mruby-io/test/mruby_io_test.c

Members of `struct sockaddr_un` are requesting the definitions of `sun_family` and `sun_path`.
https://pubs.opengroup.org/onlinepubs/009696699/basedefs/sys/un.h.html
But the other members are optional and environment dependent.
In fact, other members are defined in the BSD series.
from NetBSD-9.1 <https://github.com/NetBSD/src/blob/da504f75982b244b2288bc9970bbc203bd77a9c1/sys/sys/un.h#L49-L53>
```c
struct  sockaddr_un {
unsigned char   sun_len;        /* sockaddr len excluding NUL */
sa_family_t     sun_family;     /* AF_UNIX */
char    sun_path[104];          /* path name (gag) */
};
```
I found this problem through valgrind on FreeBSD.

Initialize all area of `struct sockaddr_un`

---

mrbgems/mruby-fiber/src/fiber.c

Please note that this pull request contains #5272.
The argument of the second `mrb_fiber_resume()` is not the return value of `Fiber.yield`, so it will be corrected.
I will post the result of trying with a slightly modified code of #5261.
```c
#include <mruby/compile.h>
#include <mruby/string.h>
#include <stdio.h>
mrb_state* mrb;
void p(mrb_value value) {
printf("--> %s\n", mrb_str_to_cstr(mrb, mrb_inspect(mrb, value)));
}
int main() {
mrb = mrb_open();
mrb_value fiber_class = mrb_obj_value(mrb_class_get(mrb, "Fiber"));
mrb_value proc = mrb_load_string(mrb,
"proc do |a| Fiber.yield(a + 1); end");
// ^~~~~~~~~~~~~~~~~~ ❓❓❓ What is this value?
mrb_sym new = mrb_intern_cstr(mrb, "new");
mrb_value fiber = mrb_funcall_with_block(mrb, fiber_class, new, 0, NULL, proc); …
```

Capture the return value of `Fiber.yield` via C; ref #5261

---

src/vm.c

When I `#call` the "proc" object created by the `mrb_proc_new_cfunc()` function from Ruby space, the return value did not go into the correct stack position.
This can destroy the calling variable.
This issue is now caused by #5272. sorry.

Fixed stack position of return value; ref #5272

---

mrbgems/mruby-os-memsize/src/memsize.c

If it gets an insubstantial method object with `obj.method`, it will raise a `SIGSEGV` with `ObjectSpace.memsize_of(method)`.
---
```console
% cat memsizeof.rb
class Object
def respond_to_missing?(mid, incpriv)
return true if mid == :xyz
super
end
end
m = "".method(:xyz)
p ObjectSpace.memsize_of m
% bin/mruby memsizeof.rb
zsh: segmentation fault (core dumped)  bin/mruby memsizeof.rb
```

Fix NULL pointer dereference with mruby-os-memsize and mruby-method

---

mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c

This is a missing change in #5272.
This issue was reported by @shuujii.
https://github.com/mruby/mruby/pull/5272#issuecomment-761819737

Fix build error for mruby-bin-debugger

---

include/mruby.h
include/mruby/presym/enable.h

The new macro (`MRB_E_SYM`) was not being used, so it is being used. Also
`MRB_E_SYM` is confusing with `MRB_SYM_E`, so change it to `MRB_ERROR_SYM`.

Fix "Use `MRB_SYM()` for error class retrieval"; ref 2ddfd50df

---

src/dump.c
src/symbol.c

Because it may not be expected result.
example: https://wandbox.org/permlink/F5Mp7IEJ1VY3CFLp

Avoid 'possible loss of data' casting in binary search

---

lib/mruby/build.rb
lib/mruby/gem.rb
tasks/presym.rake

This is because compiler's `-save-temps=obj` option creates `.i` with the
same name.

Rename `.i` created for presym scan to `.pi`

---

include/mruby/presym/enable.h
lib/mruby/presym.rb
src/symbol.c
tasks/presym.rake

Because a structure that is an element of `presym_table` has padding, split
it into individual arrays for name and length.
|        |   mruby    | libmruby.a |
|--------|------------|------------|
| Before | 1,087,444B | 1,476,872B |
| After  | 1,079,340B | 1,469,784B |

Split `presym_table` for reduced program size

---

build_config/default.rb
lib/mruby/build/command.rb
tasks/toolchains/gcc.rake
tasks/toolchains/openwrt.rake

If we modify an option that may have been specified by users, we may
make unintended changes, so it is better not to modify it as much as
possible, IMO.

Refine `preprocess_options`; ref d95ffb036

---

src/symbol.c

This was because it caused `SIGSEGV` when `mruby -v` displayed an unnamed variable.
```console
% bin/mruby -ve 'call { |(a, b)| }'
...SNIP...
irep 0x8007d0050 nregs=3 nlocals=1 pools=0 syms=1 reps=1 iseq=12
file: -e
1 000 OP_LOADSELF   R1
1 002 OP_BLOCK      R2      I(0:0x8007d00a0)
1 005 OP_SENDB      R1      :call   0
1 009 OP_RETURN     R1
1 011 OP_STOP
irep 0x8007d00a0 nregs=6 nlocals=5 pools=0 syms=0 reps=0 iseq=29
local variable names:
zsh: segmentation fault (core dumped)  bin/mruby -ve 'call { |(a, b)| }'
```

Check first `0` when converting symbols into strings

---

mrbgems/mruby-pack/src/pack.c

Previously, problems occurred when the `fixnum` was exceeded.
- 32-bit cpu mode with `MRB_WORD_BOXING` and `MRB_INT32`:
```console
% bin/mruby -e 'p [0x7fffffff].pack("N").unpack("N")'
-e:1: cannot unpack to Integer: 2147483647 (RangeError)
```
- 64-bit cpu mode with `MRB_WORD_BOXING` and `MRB_INT64`:
```console
% bin/mruby -e 'p [0x7fffffff_ffffffff].pack("q").unpack("q")'
-e:1: cannot unpack to Integer: 9223372036854775807 (RangeError)
```

Fixed `String#unpack` to handle the highest range of integer values

---

lib/mruby/build.rb

I would be glad if it was created under the host's build directory.
- `my_config.rb`
```ruby
MRuby::Build.new("host", "build/to/custom/directory") do |conf|
conf.toolchain "clang"
conf.build_dir = "build/to/another/directory"
end
```
- current (output directory is `build/host/mrbc`)
```console
% rake MRUBY_CONFIG=my_config.rb
Build summary:
================================================
Config Name: host
Output Directory: build/to/another/directory
================================================
================================================
Config Name: host/mrbc
Output Directory: build/host/mrbc
Binaries: mrbc
Included Gems:
mruby-bin-mrbc - mruby compiler executable
mruby-compiler - mruby compiler library
================================================
```
- this PR (output …

Build internal mrbc in an internal directory

---

src/vm.c

The following macros will be removed:
- `ENSURE_STACK_INIT_SIZE`
- `RESCUE_STACK_INIT_SIZE`
- `MRB_ECALL_DEPTH_MAX`

Remove unnecessary configuration macros; ref #5060

---

include/mruby/presym/disable.h
include/mruby/presym/enable.h
src/class.c

The `init_SYMBOLS()` function implicitly defined in `MRB_PRESYM_DEFINE_VAR_AND_INITER()` requires some familiarity when trying to find it from the caller.
By introducing `MRB_PRESYM_INIT_SYMBOLS()`, it is possible to find directly from the identifier.

Introduced `MRB_PRESYM_INIT_SYMBOLS()`

---

lib/mruby/build.rb

Build error occurred under the following conditions.
* `host` build is presym enabled and unspecified `mruby-bin-mrbc` gem.
* Build except `host` unspecified `mruby-bin-mrbc` gem and mrbcfile.
```ruby
MRuby::Build.new{|conf| conf.toolchain}
MRuby::Build.new("host2"){|conf| conf.toolchain}
```
```console
rake aborted!
external mrbc or mruby-bin-mrbc gem in current('host2') or 'host' build is required
/mruby/lib/mruby/build.rb:326:in `mrbcfile'
/mruby/tasks/mrblib.rake:9:in `block in <top (required)>'
/mruby/lib/mruby/build.rb:18:in `instance_eval'
/mruby/lib/mruby/build.rb:18:in `block in each_target'
/mruby/lib/mruby/build.rb:17:in `each'
/mruby/lib/mruby/build.rb:17:in `each_target'
/mruby/tasks/mrblib.rake:1:in `<top (required)>'
/mruby/Rakefile:27:in `load'
/mruby/Rakefile:27:in `<top …
```

Fix breakage where builds except `host` don't refer` mrbc` in `host`

---

tasks/presym.rake

`.pi` files are created for `.o` files that `build.products` depends on, but
an error will occur if the build rule is unknown, so add a check.
I don't think this situation would normally arise. However, in
`mattn/mruby-onig-regexp`, when using bundled onigmo, onigmo's `.o` files
are added to dependency of `libmruby.a` in the second and subsequent builds,
and mruby does not know the build rule, so the following error had occured.
```console
rake aborted!
Don't know how to build task '/mruby/build/host/mrbgems/mruby-onig-regexp/onigmo-6.2.0/libonig_objs/ascii.pi' (See the list of available tasks with `rake --tasks`)
```

Check if `.pi` build rules are defined

---

mrbgems/mruby-catch/mrblib/catch.rb

```ruby
begin
throw 1
rescue Exception => e
puts e.message
end
```
```console
uncaught throw :1
```
```console
uncaught throw 1
```

Fix message of `ThrowCatchJump` in `mruby-catch` gem

---

mrbgems/mruby-catch/mrblib/catch.rb
mrbgems/mruby-catch/test/catch.rb

Also implement the following changes.
* Add tests
* Use `Object#equal?` to compare tags for Ruby compatibility
* Use `attr_reader`

Make the argument of `Kernel#catch` optional as Ruby does

---

lib/mruby/build/command.rb

Prevents the auto-generated mrbc target source code from being compiled under host conditions.
This is because a build error occurred when `conf.enable_cxx_exception` was set.

Exclude `<build-dir>/mrbc/**/*` from rake target rules

---

tasks/test.rake

Because if the configuration file didn't contain any `conf.enable_test`, `rake test` would report an exception and exit.
```console
% cat my_config.rb
MRuby::Build.new { toolchain }
% rake MRUBY_CONFIG=my_config.rb test
...SNIP...
rake aborted!
NoMethodError: undefined method `invoke' for nil:NilClass
/var/tmp/mruby/tasks/test.rake:24:in `block (3 levels) in <top (required)>'
Tasks: TOP => test => test:build => test:build:lib
(See full trace by running task with --trace)
```

Ignore if `conf.enable_test` does not exist

---

lib/mruby/build.rb
lib/mruby/core_ext.rb

If the current directory is different from `MRUBY_ROOT` and it has` conf.build_dir` and `conf.enable_cxx_exception` set, it was generating a pathname outside of` build_dir`.
As a result, in some cases files unrelated to mruby could be linked.
```console
% pwd
/tmp/mruby/1/2/3/4/5/6
% mruby_dir=/tmp/mruby/a/b/c/d/mruby
% cat my_config.rb
MRuby::Build.new("host", "build/to/custom/directory") do
toolchain
enable_cxx_exception
end
% rake MRUBY_CONFIG=my_config.rb -f $mruby_dir/Rakefile > logs
% grep CXX logs
CXX   a/b/c/d/mruby/src/error-cxx.cxx -> a/b/c/d/mruby/src/error-cxx.o
CXX   a/b/c/d/mruby/src/gc-cxx.cxx -> a/b/c/d/mruby/src/gc-cxx.o
CXX   a/b/c/d/mruby/src/vm-cxx.cxx -> a/b/c/d/mruby/src/vm-cxx.o
CXX   a/b/c/d/mruby/mrbgems/mruby-compiler/core/codegen-cxx.cxx -> …
```

`compile_as_cxx` should generate a path under` conf.build_dir`

---

mrbgems/mruby-catch/mrblib/catch.rb
mrbgems/mruby-catch/src/mruby-catch.c

When there is a corresponding tag, the `RBreak` object is used to make a global jump.
Like CRuby, it can't be caught by `rescue`.
It is also the same as CRuby that it can be canceled in the middle by `ensure`.
The called `catch` method remains in the call stack, and the tag also remains in the stack at that time.
So it is possible to find the called location by searching the two.
Note that no method can be given to the `proc` object specified in `RBreak`.
Therefore, inside the `catch` method, the argument block is called in a seemingly meaningless closure.
Also, as a countermeasure against `alias` etc., the `proc` object, which is the body of the `catch` method, is saved when mrbgem is initialized.

Reimplement mruby-catch; ref #5321

---

src/hash.c
test/t/hash.rb

```ruby
h = {}
(1..17).each{h[_1] = _1}
(1..16).each{h.delete(_1)}
h.rehash
```
```console
==52587==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000006998 at pc 0x55a29cddf96b bp 0x7fff7b1b1720 sp 0x7fff7b1b1710
READ of size 4 at 0x602000006998 thread T0
#0 0x55a29cddf96a in ib_it_next /mruby/src/hash.c:639
#1 0x55a29cde2ca2 in ht_rehash /mruby/src/hash.c:900
#2 0x55a29cde379f in h_rehash /mruby/src/hash.c:996
#3 0x55a29cde7f3d in mrb_hash_rehash /mruby/src/hash.c:1735
#4 0x55a29ce77b62 in mrb_vm_exec /mruby/src/vm.c:1451
#5 0x55a29ce5fa88 in mrb_vm_run /mruby/src/vm.c:981
#6 0x55a29ceb87e1 in mrb_top_run /mruby/src/vm.c:2874
#7 0x55a29cf36bdf in mrb_load_exec mrbgems/mruby-compiler/core/parse.y:6805
#8 0x55a29cf36f25 in mrb_load_detect_file_cxt …
```

Fix heap-buffer-overflow for small `Hash` (HT) in `Hash#rehash`

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/oss-fuzz.yml

GitHub Actions now supports "skip ci" natively:
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

Remove "skip ci" hack to GitHub Actions [skip travis][skip appveyor]

---

doc/guides/compile.md

Update compile prerequisites in `doc/guides/compile.md` [ci skip]

---

.github/workflows/lint.yml

Official -> "The individual jobs in a workflow can interact with (and compromise) other jobs. For example, a job querying the environment variables used by a later job, writing files to a shared directory that a later job processes, or even more directly by interacting with the Docker socket and inspecting other running containers and executing commands in them.
This means that a compromise of a single action within a workflow can be very significant, as that compromised action would have access to all secrets configured on your repository, and can use the GITHUB_TOKEN to write to the repository. Consequently, there is significant risk in sourcing actions from third-party repositories on GitHub. "
https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions …

refactor: only use certified GitHub Actions to increase security

---

doc/guides/mrbgems.md
include/mruby/array.h
mrbgems/mruby-bin-debugger/bintest/print.rb
mrbgems/mruby-cmath/mrbgem.rake
mrbgems/mruby-cmath/src/cmath.c
mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c

Normally a single spell checker can't find all the mistakes or check all types of code.
These mistakes were found by another spell checker inside my editor with a more manual sift / find.

chore: fix spelling

---

.editorconfig

Helps keep the text file format consistent.
Multiple text editors and IDEs support it, and there may be plugins even if it is not supported.
https://editorconfig.org/
There should be various opinions about the number of characters per line, so I intentionally commented it out.
Anyway, 80 characters is painful.
The intention is not to force the use of the corresponding editor.
I just hope to help anyone using a compatible editor.
I have a plugin installed and used on Vim.

Introduce EditorConfig [skip ci]

---

.github/dependabot.yml

Set for GitHub Actions to check for update everyday.
When you add or update the dependabot.yml file, this triggers an immediate check for version updates. Any options that also affect security updates are used the next time a security alert triggers a pull request for a security update.
https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

feat: add Dependabot config file

---

lib/mruby/build/load_gems.rb

When your build_config.rb.lock has a lock entry whose commit is older than the latest commit in the branch like this,
```
https://github.com/ksss/mruby-file-stat.git:
url: https://github.com/ksss/mruby-file-stat.git
branch: master
commit: 66cf135ff9642d96a6127a79b307f6314e606deb
version: 0.0.0
```
it results in:
```
GIT   https://github.com/ksss/mruby-file-stat.git -> build/repos/host/mruby-file-stat
Cloning into '/home/mruby/code/mruby/build/repos/host/mruby-file-stat'...
GIT CHECKOUT DETACH /home/runner/work/mitamae/mitamae/mruby/build/repos/host/mruby-file-stat -> 66cf135ff9642d96a6127a79b307f6314e606deb
fatal: reference is not a tree: 66cf135ff9642d96a6127a79b307f6314e606deb
fatal: reference is not a tree: 66cf135ff9642d96a6127a79b307f6314e606deb
rake aborted!
```
Do not use `--depth …

Skip --depth=1 when it's locked

---

mrbgems/mruby-array-ext/mrblib/array.rb

I get an error because the current mruby does not have a `Kernel#warn` method.
But the warning itself is useful and I'll just comment it out in case it's implemented in the future.

Comment out `warn` used in the `Array#fetch` method

---

mrbgems/mruby-binding/mrbgem.rake
mrbgems/mruby-binding/mrblib/binding.rb
mrbgems/mruby-binding/src/binding.c
mrbgems/mruby-binding/test/binding.rb
mrbgems/mruby-eval/src/eval.c
mrbgems/mruby-eval/test/eval.rb
src/kernel.c

I'm trying to implement CRuby's `Binding` class. 
`Binding#local_variables` is easy.
But I couldn't implement `Binding#eval` because it's too difficult.
It failed in this case.
```rb
class A
class << self
def b
@a = 42
b = 'local_variable'
binding
end
end
end
p A.b.eval("[@a, b]")
```
Does anyone have a good idea?

Try Binding class

---

mrbgems/mruby-bin-mirb/mrbgem.rake
mrbgems/mruby-bin-mirb/tools/mirb/mirb.c

Since FreeBSD 11, which came out over four years ago, "readline" has been removed from the base system.
I thought it was strange...

Support libedit on mirb for FreeBSD

---

.github/workflows/lint.yml

Upgrade to  markdownlint-cli version 0.27.1

chore: upgrade markdownlint GitHub Action node version to 14

---

src/numeric.c

`mrb_cmp` uses `MRB_SYM` macro for `cmp` token, which uses the literal symbol `:cmp`. It should be using `MRB_OPSYM(cmp)` to use `:<=>`.
```
$ rake
$ ./bin/mirb
> class A; include Comparable; def <=>(other); 1; end; end
=> :<=>
> A.new..A.new
undefined method 'cmp' (NoMethodError)
```
```
$ rake
$ ./bin/mirb
> class A; include Comparable; def <=>(other); 1; end; end
=> :<=>
> A.new..A.new
=> #<A:0x7fcb3000cbc0>..#<A:0x7fcb3000cb60>
```

bug(presym): Fix mrb_cmp declaration of <=> symbol for funcall

---

lib/mruby/build.rb

If I break out of a block given to `MRuby::Build.new` with `break` or `throw`, I will get a seemingly inexplicable error because the `presym`-related initialization is not done.
```console
% cat build_config1.rb
MRuby::Build.new do
toolchain
break
end
% rake CONFIG=build_config1.rb
rake aborted!
external mrbc or mruby-bin-mrbc gem in current('host') or 'host' build is required
/var/tmp/mruby/lib/mruby/build.rb:332:in `mrbcfile'
/var/tmp/mruby/tasks/mrblib.rake:9:in `block in <top (required)>'
/var/tmp/mruby/lib/mruby/build.rb:18:in `instance_eval'
/var/tmp/mruby/lib/mruby/build.rb:18:in `block in each_target'
/var/tmp/mruby/lib/mruby/build.rb:17:in `each'
/var/tmp/mruby/lib/mruby/build.rb:17:in `each_target'
/var/tmp/mruby/tasks/mrblib.rake:1:in `<top (required)>' …
```

Allow `break` in `build_config`.

---

build_config/cross-mingw.rb

With this cross compiler configuration, all tests for full-core gembox on
Windows on GitHub Actions were successful.

Add configuration for MinGW cross compilation [ci skip]

---

build_config/nintendo_switch.rb

Cross Compiling configuration for the Nintendo Switch, it requires Nintendo SDK

Add example for cross-compiling to Nintendo Switch

---

mrbgems/mruby-kernel-ext/test/kernel.rb
mrbgems/mruby-proc-ext/test/proc.rb
src/backtrace.c
test/t/exception.rb

Previously backtraces involving code built without debug information just silently hid stack frames from backtraces.
Consider the code:
```
[1,2].reverse_each do |val|
val.invalid_method
end
```
Before this commit the output without debug symbols was:
```
[1] test.rb:1
test.rb:2: undefined method 'invalid_method' (NoMethodError)
```
After this commit the output is:
```
[2] test.rb:1
[1] (unknown):missing-lineno:in reverse_each
test.rb:2: undefined method 'invalid_method' (NoMethodError)
```
With full debug information the second frame in the backtrace refers to the source in the mruby-array-ext gem.

Add support for partial backtraces

---

src/dump.c

Under C++, there is no implicit conversion from `int` to `enum`, which caused a compilation error.

Fix build failures with `enable_debug` and `enable_cxx_abi`

---

build_config/dreamcast_shelf.rb

This PR contains the updated `build_config` for the **Sega Dreamcast** video-game console.

Updating dreamcast_shelf build configuration.

---

mrbgems/mruby-eval/src/eval.c
mrbgems/mruby-method/src/method.c
src/vm.c

Use `mrb_exec_irep()`. If possible, re-entry into the VM will be suppressed.
Note that due to the effect of being a tail-call, the backtrace of `Method#call` will be lost, and it will look as if the target method was called directly.
This change fixes the problem of infinite loops when redefining methods that make block calls using `mruby-method`.
```console
% bin/mruby -e 'mm = method(:proc); define_method(:proc, ->(*a, &b) { mm.call(*a, &b) }); p proc { 1 }'
[257] -e:1
[256] -e:1:in proc
[255] -e:1:in proc
...SNIP...
[1] -e:1:in proc
-e:1:in proc: stack level too deep (SystemStackError)
```
Also, this PR contains a patch to extend `mrb_exec_irep()`.

Reorganize `mcall()` in `mruby-method`

---

src/state.c

`state.c` makes a prototype declaration for the private
`mrb_protect_atexit` which is defined in `error.c`. `error.c` defines
this function with a void return type, but `state.c` defines the
prototype with an `int` return type.
This mismatch prevents mruby from linking on stricter compilers like
emscripten.
https://github.com/mruby/mruby/blob/810d13dacdd4cdf6ce55de85266f3ac26da520ef/src/error.c#L594-L595

Fix incorrect prototype on declaration of mrb_protect_atexit

---

include/mruby/error.h
mrbgems/mruby-error/mrbgem.rake
mrbgems/mruby-error/src/exception.c
src/vm.c

The purpose is two-fold:
1. to be able to specify a pointer directly when user data is used
When using `mrb_protect()`, it is necessary to allocate objects by `mrb_obj_cptr()` function when using user data.
Adding `mrb_protect_raw()` will make it simpler to reimplement `mrbgems/mruby-error`.
2. to correctly unwind callinfo when an exception is raised from a C function defined as a method (the main topic)
If a method call is made directly under `mrb_protect()` and a C function is called, control is returned from `mrb_protect()` if an exception occurs there.
In this case, callinfo is not restored, so it is out of sync.
Moreover, returning to mruby VM (`mrb_vm_exec()` function) in this state will indicate `ci->pc` of C function which is equal to `NULL`, and subsequent `JUMP` will cause …

Introducing the `mrb_protect_raw()` API function

---

mrbgems/mruby-sleep/mrbgem.rake

To align the spec like any other core mrbgems:
- Delete `spec.version`
- Set `spec.summary`

Update gem spec for `mruby-sleep`

---

src/vm.c

Commit d0f60182af9114f6840d993d74f492e483302805 introduced an exception as a limitation of mruby.
Subsequent CRuby-2.7 has changed its behavior to raise an exception.
ref: https://github.com/ruby/ruby/commit/55b7ba368696033f2e89b77cbcd4a05dec97b139

Raise `TypeError` with `super` inside `instance_eval` / `class_eval`

---

.github/workflows/lint.yml
.github/workflows/super-linter.yml
.pre-commit-config.yaml
build_config/IntelGalileo.rb
codespell.txt
doc/limitations.md
include/mruby/array.h
mrbgems/mruby-array-ext/mrblib/array.rb
mrbgems/mruby-complex/src/complex.c
mrbgems/mruby-error/src/exception.c
mrbgems/mruby-rational/src/rational.c
scripts/ci/pre-commit/sort-codespell-wordlist.sh
src/fmt_fp.c
src/vm.c
test/t/unicode.rb

Running pre-commit with GitHub Actions now gives us more tests and coverage
Remove duplicate GitHub Actions for merge conflicts and trailing whitespace
Remove duplicate checks for markdownlint and yamllint from the GitHub Super-Linter
Add new custom pre-commit hook running with a shell script to sort alphabetically and uniquify codespell.txt
Add new pre-commit hook to check spelling with codespell
https://github.com/codespell-project/codespell

 Run pre-commit with GitHub Actions

---

.github/linters/.markdown-lint.yml

Enable MD011 no-reversed-links - Reversed link syntax

Add the rules to the markdownlint config file as comments

---

.github/linters/.markdown-lint.yml
CONTRIBUTING.md
doc/guides/mrbgems.md
doc/guides/symbol.md

Fix C Markdown code block style

Enable markdownlint rule MD046 code-block-style

---

include/mruby.h
include/mruby/value.h
mrbgems/mruby-binding-core/src/binding-core.c
mrbgems/mruby-catch/src/catch.c
mrbgems/mruby-complex/src/complex.c
mrbgems/mruby-fiber/src/fiber.c
mrbgems/mruby-method/src/method.c
mrbgems/mruby-rational/src/rational.c
src/array.c
src/class.c
src/etc.c
src/gc.c
src/hash.c
src/object.c
src/proc.c
src/range.c
src/string.c
src/vm.c

Also, rewrite `type_name()` in `src/object.c` using `MRB_VTYPE_FOREACH()` added for implementation.

Added `MRB_OBJ_ALLOC()` macro that does not require a cast

---

.pre-commit-config.yaml
scripts/ci/pre-commit/sort-codespell-wordlist.sh

Remove unneeded bash script sort-codespell-wordlist.sh
https://github.com/pre-commit/pre-commit-hooks#file-contents-sorter

Add official pre-commit file-contents-sorter

---

mrbgems/mruby-eval/src/eval.c

The `mrbc_context` remained unreleased when the `mrb_parse_nstring()` function returned `NULL`.

Fix memory leak in `Kernel#eval`

---

mrbgems/mruby-compiler/core/codegen.c
mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c

If no new variable was defined in the `eval` method, the variable was hidden from the nested `eval` method.
```ruby
a = 1
p eval %(b = 2; eval %(a)) # => 1 (good)
p eval %(eval %(a)) # => undefined method 'a' (NoMethodError)
```
This issue has occurred since mruby 3.0.0.

Fixed finding variables defined in the upper proc failed

---

mrbgems/mruby-binding-core/src/binding-core.c
mrbgems/mruby-binding/mrblib/binding.rb
mrbgems/mruby-binding/src/binding.c
mrbgems/mruby-binding/test/binding.rb
mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c
mrbgems/mruby-eval/src/eval.c
mrbgems/mruby-method/src/method.c
src/proc.c
src/vm.c

Previously the following code did not produce the expected results:
```ruby
bx = binding
block = bx.eval("a = 1; proc { a }")
bx.eval("a = 2")
p block.call  # Expect 2 but return 1 due to a bug
```
The previous implementation of `Binding#eval` evaluated the code and then merged the top layer variables.
This patch will parse and expand the variable space before making a call to `eval`.
This means that the call to `Binding#eval` will do the parsing twice.
In addition, the following changes will be made:
- Make `mrb_parser_foreach_top_variable()`, `mrb_binding_extract_proc()` and `mrb_binding_extract_env()` functions private global functions.
- Remove the `posthook` argument from `mrb_exec_irep()`.
The `posthook` argument was introduced to implement the `binding` method.
This patch is …

Fixed finding variables from `proc` in `binding.eval` failed

---

mrbgems/mruby-array-ext/mrblib/array.rb
mrbgems/mruby-hash-ext/mrblib/hash.rb
mrbgems/mruby-io/mrblib/io.rb
mrbgems/mruby-string-ext/mrblib/string.rb
mrbgems/mruby-toplevel-ext/mrblib/toplevel.rb

```console
% for rb in `git ls-files '*/mrblib/*.rb' 'mrblib'`; do ruby30 -cw $rb > /dev/null; done
mrbgems/mruby-array-ext/mrblib/array.rb:389: warning: assigned but unused variable - ary
mrbgems/mruby-array-ext/mrblib/array.rb:663: warning: assigned but unused variable - len
mrbgems/mruby-hash-ext/mrblib/hash.rb:119: warning: possibly useless use of a variable in void context
mrbgems/mruby-hash-ext/mrblib/hash.rb:259: warning: assigned but unused variable - keys
mrbgems/mruby-io/mrblib/io.rb:229: warning: literal in condition
mrbgems/mruby-io/mrblib/io.rb:280: warning: literal in condition
mrbgems/mruby-string-ext/mrblib/string.rb:347: warning: assigned but unused variable - len
mrbgems/mruby-toplevel-ext/mrblib/toplevel.rb:2: warning: parentheses after method name is interpreted as an …
```

Avoid warnings with `ruby -cw`

---

mrbgems/mruby-bin-debugger/tools/mrdb/apibreak.c
mrbgems/mruby-bin-debugger/tools/mrdb/apilist.c
mrbgems/mruby-bin-debugger/tools/mrdb/apistring.c
mrbgems/mruby-bin-debugger/tools/mrdb/apistring.h
mrbgems/mruby-bin-debugger/tools/mrdb/cmdmisc.c

(cc: @mimaki)
I think it's a good idea to add and use these functions, because they're easier and safer (see #2652) to use than the previous (varying) combination of functions calls (`mrb_malloc()`+`strlen()`+`strncpy()` or `strcpy()`). They also simplify reading and maintaining the code a bit.
I'm unsure about the two new files, but I was also unsure about adding the functions to libmruby itself (`src/gc.c`).

mrdb: add and use mrb_debug_{str,strn}dup()

---

lib/mruby/gem.rb

When `disable_cdump` is declared on a Mrbgem spec, the procedure for loading MRuby code from the gem's `mrblib` directory is slightly different; instead of loading the mrblib code as a Proc built from the compiled irep, the compiled irep is loaded directly. The header files `mruby.h` and `mruby/proc.h` are needed only when the irep is loaded directly. They are currently included only when presym is disabled, they should be included whenever either presym is disabled *or* when `disable_cdump` is called. The `cdump?` predicate method happens to return true in either case (presym disabled *or* cdump disabled), so this change should be safe.

Mrbgem gem_init.c: add headers for irep loading when cdump is disabled, but presym is enabled

---

include/mruby.h

When doing `conf.enable_cxx_abi` and compiling with FreeBSD + clang or MinGW, such as `INTPTR_MAX` constant macro is not defined if `#include <stdint.h>` precedes `#include <mruby.h>`.
Currently I get a warning when I use an undefined macro, but if I don't notice it I get confused in a link error.
It can be expected that the problem will be easier to understand by making a clear error.
Adding `-Werror=undef` as a compiler flag can also result in an error, but this can be a problem if the system header file itself uses undefined macros, for example.
This patch does minimal confirmation only, but has no side effects.

Output an error if the `INTPTR_MAX` macro is undefined in C++

---

tasks/libmruby.rake

After building mruby, if the user compiles and links to `libmruby.a`, expose the included directory of the captured gems.
This is a change to the `<build-dir> /lib/libmruby.flags.mak` file and will result in being added to `bin/mruby-config --cflags`.
This eliminates the need for the user to look up the path and add the compiler flag if the user wants to take advantage of her gems publishing features.
In the main build with `rake CONFIG=...`, there is no problem because it can only be seen from the gems that depends directly and indirectly as before.
However, when compiling independently by the user using `bin/mruby-config`, a header file name collision may occur if a unique header directory is added.

Expose all header files of the gems for small compilation

---

include/mruby.h
mrbgems/mruby-inline-struct/test/inline.c
src/class.c

Previously, the `I` specifier only checked if the object was `MRB_TT_ISTRUCT`.
So it was at risk of getting pointers to different C structs if multiple classes were to use the `MRB_TT_ISTRUCT` instance.
Change this behavior and change the C argument corresponding to the `I` specifier to `(void *, struct RClass)`.
This change is not compatible with the previous mruby.
Please note that if the user uses the previous specifications, `SIGSEGV` may occur or the machine stack may be destroyed.
resolve #5527

Check the class with `I` specifier of `mrb_get_args()`

---

mrbgems/mruby-random/src/random.c

This is to avoid the approximation of `Random#rand` when `seed`s are close together.
For example, the first `#rand` values after doing `Random#srand(0)` and `Random#srand(1)` are very similar.
Below is the sequence of mruby before this patch was given a `seed` of `0...20`:
```console
% bin/mruby -e 'r = Random.new; 20.times { |i| r.srand(i); puts "seed=%2d  %s" % [i, 10.times.map { "%0.3f" % r.rand }.join(" ")] }'
seed= 0  0.643 0.585 0.198 0.732 0.087 0.605 0.548 0.468 0.573 0.966
seed= 1  0.643 0.585 0.198 0.607 0.370 0.605 0.633 0.593 0.395 0.439
seed= 2  0.643 0.585 0.197 0.981 0.652 0.730 0.875 0.713 0.529 0.269
seed= 3  0.643 0.585 0.198 0.857 0.934 0.730 0.960 0.216 0.286 0.523
seed= 4  0.643 0.585 0.197 0.231 0.217 0.605 0.959 0.958 0.478 0.482
seed= 5  0.643 0.585 0.197 0.106 …
```

Stirs internal state when `seed` is set in `Random`

---

include/mruby.h
mrbgems/mruby-cmath/src/cmath.c
mrbgems/mruby-compiler/core/codegen.c
mrbgems/mruby-complex/src/complex.c
mrbgems/mruby-math/src/math.c
mrbgems/mruby-numeric-ext/src/numeric_ext.c
mrbgems/mruby-range-ext/src/range.c
mrbgems/mruby-rational/src/rational.c
mrbgems/mruby-sprintf/src/sprintf.c
mrbgems/mruby-time/src/time.c
src/dump.c
src/load.c
src/numeric.c
src/string.c
src/vm.c

- `#include <math.h>` is done in `mruby.h`.
Eliminate the need to worry about the `MRB_NO_FLOAT` macro.
- Include mruby header files before standard header files.
If the standard header file is already placed before `mruby.h`, the standard header file added in the future tends to be placed before `mruby.h`.
This change should some reduce the chances of macros that must be defined becoming undefined in C++ or including problematic header files in a particular mruby build configuration.

Organize the include of header files

---

src/class.c

- Removed the `ARGV` macro.
The current path doesn't go into the mruby VM and there's also no need to separate variables.
- Use common functions to check object types.
- Use `mrb_ensure_string_type()` to check the string instead of `mrb_to_str()`.
This is for consistency with array and hash.
- Use `mrb_ensure_array_type()` to check the array instead of `to_ary()`.
- Use `mrb_ensure_hash_type()` to check the hash instead of `to_hash()`.
- Add and use `ensure_class_type()` to check class and module.
- Changed the argument index type from `mrb_int` to `int`.
Even if it is `int16_t`, it is enough.
`mrb_int` is overkill, especially if `MRB_32BIT` and `MRB_INT64` are defined.

Refactor the `mrb_get_args()` function

---

include/mruby.h
src/class.c

It is `o`, `C`, `S`, `A` and `H` specifiers that are integrated.
As a side effect, the `C!` Specifier can now be used.

Integrate the processing of similar specifiers of `mrb_get_args()`

---

src/vm.c

This is for the purpose of supporting `Regexp`.
- configuration and build
```console
% cat regexp_config.rb
MRuby::Lockfile.disable
MRuby::Build.new do
toolchain "clang"
enable_debug
gem core: "mruby-bin-mruby"
gem core: "mruby-print"
gem mgem: "mruby-onig-regexp"
#gem mgem: "mruby-regexp-pcre"
end
% rake MRUBY_CONFIG=regexp_config.rb
```
- mruby HEAD (bec074e)
```console
% build/host/bin/mruby -e 'p "abcdefg"[/.(?=...$)/]'
-e:1: can't convert OnigRegexp into Integer (TypeError)
```
- with this patch
```console
% build/host/bin/mruby -e 'p "abcdefg"[/.(?=...$)/]'
"d"
```

Partially allow overriding of `String#[]` methods

---

build_config/default.rb

By uncommenting the line changed by this commit, `ruby -c build_config/default.rb` complains of a syntax error due to the illegally nested double quotes.

Fix a syntax error in commented-out code

---

include/mruby.h

ref: #5564
```console
% cc -pedantic -S -Iinclude -DMRB_NO_PRESYM -o- src/array.c > /dev/null
In file included from src/array.c:7:
In file included from include/mruby.h:115:
In file included from include/mruby/value.h:204:
include/mruby/boxing_word.h:133:1: warning: must specify at least one argument for '...' parameter of variadic macro [-Wgnu-zero-variadic-macro-arguments]
mrb_static_assert(sizeof(mrb_value) == sizeof(union mrb_value_));
^
include/mruby.h:109:108: note: expanded from macro 'mrb_static_assert'
mrb_static_assert_expand(mrb_static_assert_selector(__VA_ARGS__, mrb_static_assert2, mrb_static_assert1)(__VA_ARGS__))
^
include/mruby.h:100:10: note: macro 'mrb_static_assert_selector' defined here
^
1 warning generated.
```

Avoid violations of the `mrb_static_assert()` standard

---

include/mruby/boxing_word.h

Adding `MRB_WORDBOX_NO_FLOAT_TRUNCATE` to the build configuration in 32-bit CPU mode had a double definition.
```console
% cat myconf.rb
MRuby::Build.new do
toolchain "clang"
defines << "MRB_WORDBOX_NO_FLOAT_TRUNCATE"
cc.flags << "-m32"
linker.flags << "-m32"
enable_debug
end
% rake CONFIG=myconf.rb
CPP   src/array.c -> build/host/src/array.pi
In file included from /var/tmp/mruby/src/array.c:7:
In file included from /var/tmp/mruby/include/mruby.h:115:
In file included from /var/tmp/mruby/include/mruby/value.h:203:
/var/tmp/mruby/include/mruby/boxing_word.h:11:10: warning:
'MRB_WORDBOX_NO_FLOAT_TRUNCATE' macro redefined [-Wmacro-redefined]
^
<command line>:3:9: note: previous definition is here
#define MRB_WORDBOX_NO_FLOAT_TRUNCATE 1
^
1 warning generated.
...SNIP...
```

Avoid redefining `MRB_WORDBOX_NO_FLOAT_TRUNCATE`

---

include/mruby/boxing_nan.h

```console
% c++ -xc++ -std=c++03 -S -Iinclude -DMRB_NAN_BOXING -DMRB_NO_PRESYM -o- src/array.c > /dev/null
In file included from src/array.c:7:
In file included from include/mruby.h:115:
In file included from include/mruby/value.h:201:
include/mruby/boxing_nan.h:95:12: error: cannot initialize return object of type 'enum mrb_vtype' with an rvalue of type 'int'
return (enum mrb_vtype)(o.u >> 8) & 0x1f;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Fix failed build with `MRB_NAN_BOXING` and `enable_cxx_abi`

---

src/class.c

The number of registers used is reduced.
Also, previously `R6` and` R7` were used, which exceeded the limit of `new_irep.nregs = 6`.
This could cause the VM stack to overrun.

Improved `Class#new` method

---

mrbgems/mruby-compiler/mrbgem.rake

Previously, the task was executed as many times as there were targets, including `mruby-compiler`.
```console
% rm mrbgems/mruby-compiler/core/y.tab.c
% rake `pwd`/mrbgems/mruby-compiler/core/y.tab.c
YACC  mrbgems/mruby-compiler/core/parse.y -> mrbgems/mruby-compiler/core/y.tab.c
YACC  mrbgems/mruby-compiler/core/parse.y -> mrbgems/mruby-compiler/core/y.tab.c
```

Run the task only once when `parse.y` is updated

---

src/vm.c

If a splat argument was passed, it could write out of range on the VM stack.
```console
% bin/mruby -e 'def m(*args, **opts, &blk) p [args, opts, blk] end; m(*%w(X Y Z), r: 1, g: 2, b: 3) {}'
[["X", "Y", "Z"], {}, #<Proc:0x80077d7d0>]
```

Fixes keywords are lost with the `OP_SENDB`

---

mrbgems/mruby-method/src/method.c
mrbgems/mruby-proc-ext/src/proc.c

Calling the `Method#{parameters,source_location}` method on a static `Proc` object resulted in `SIGSEGV`.
The trigger is https://github.com/mruby/mruby/pull/5402.
The original implementation of the `Method#{parameters,source_location}` method was to temporarily rewrite the object and then call the method of the same name in `Proc`.
Rewriting of objects placed in the ROM section by #5402 above is prohibited by hardware such as the CPU.
This caused a `SIGSEGV`.

Fixed occurs `SIGSEGV` with `mrbgems/mruby-method`

---

mrbgems/mruby-method/src/method.c

Both keyword arguments and block arguments were being destroyed when there were no arguments.
The cause of this is #5585. I' m sorry.

Fix `args_unshift()` in `mrbgems/mruby-method`

---

mrbgems/mruby-cmath/src/cmath.c

If the preprocessor check part is only `__clang__`, CI's such as `Ubuntu-2004-clang` will fail to compile.
This is why we limited the addition to FreeBSD and OpenBSD, which have `clang++` in their base systems.
DragonFly BSD and NetBSD have GCC built into their base systems, so nothing is changed.

Fixed compile error for `mrbgems/mruby-cmath` with `clang++`

---

mrbgems/mruby-array-ext/mrblib/array.rb
mrbgems/mruby-proc-ext/mrblib/proc.rb
mrbgems/mruby-string-ext/mrblib/string.rb
mrblib/string.rb
src/vm.c

Make "N for M" into the form "given N, expected M".
As I worked, I noticed that the `argnum_error()` function had a part to include the method name in the message.
I think this part is no longer needed by https://github.com/mruby/mruby/pull/5394.
- Before this patch
```console
% bin/mruby -e '[1, 2, 3].each 0'
[1] -e:1
-e:1:in each: 'each': wrong number of arguments (1 for 0) (ArgumentError)
```
- After this patch
```console
% bin/mruby -e '[1, 2, 3].each 0'
[1] -e:1
-e:1:in each: wrong number of arguments (given 1, expected 0) (ArgumentError)
```

Align "wrong number of arguments" messages

---

doc/mruby3.1.md
mrbgems/mruby-array-ext/mrblib/array.rb
mrbgems/mruby-array-ext/test/array.rb

Ruby 1.9.2 feature.
ref: https://docs.ruby-lang.org/ja/3.1.0/method/Array/i/repeated_combination.html
ref: https://docs.ruby-lang.org/ja/3.1.0/method/Array/i/repeated_permutation.html

Add `Array#{repeated_combination,repeated_permutation}` methods

---

src/dump.c
src/load.c

- `rlen` keeps 16 bits.
- `ilen` keeps 32 bits.
Note that this change will break mruby binary format compatibility.

Avoid losing the upper digits for mruby binary

---

mrbgems/mruby-compiler/core/codegen.c

Previously, it always pointed to the highest scope as the location of the error.
- example code `code.rb`
```ruby
huge_num = "1" + "0" * 300; eval <<CODE, nil, "test.rb", 1
class Object
module A
#{huge_num}
end
end
CODE
```
- Before this patch
```console
% bin/mruby code.rb
test.rb:1: integer too big
[1] code.rb:1
code.rb:1:in eval: codegen error (ScriptError)
```
- After this patch
```console
% bin/mruby code.rb
test.rb:3: integer too big
[1] code.rb:1
code.rb:1:in eval: codegen error (ScriptError)
```

Print error before cleanup in `codegen_error()`

---

include/mruby/compile.h
mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.c
mrbgems/mruby-compiler/core/codegen.c
mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c

Print an error if `OP_EXT[123]` is needed when generating mruby binary.
This may be useful for mruby/c.
Inspired by #5590.

Add `bin/mrbc --no-ext-ops` switch

---

mrbgems/mruby-array-ext/src/array.c
src/string.c

ref. #5613
I checked with Valgrind, and the methods that can cause use-after-free are `Array#rotate`, `Array#rotate!`, and `String#byteslice`.
Since `String#rindex` uses `RSTRING_LEN()` indirectly inside the function, no reference to the out-of-bounds range is generated.
- - -
memo: `git grep -EnC16 'mrb_get_args.*".*[fi].*"'`

Get object properties after `mrb_get_args()`

---

.github/workflows/build.yml

The main reason for failure is to exceed the time limit, and even when it succeeds, there is less than a minute left.
The 10-minute time limit seems to be too short.

Extend the Cygwin CI time limit to 15 minutes.

---

src/class.c

ref. #5613.
I mentioned in #5540 that there was no reentrant to the virtual machine, but in fact it was still a possibility at that point.
Also, the variable `ci` needs to be recalculated at the same time.

Adjusting the stack for after it enters the virtual machine

---

mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.c
mrbgems/mruby-complex/src/complex.c
mrbgems/mruby-rational/src/rational.c
src/object.c

ref. commit 7f40b645d2773c8f50c48ae4adf90488e164da55
Currently, the build configurations `MRB_USE_COMPLEX` and `MRB_USE_RATIONAL` are not listed in the documentation.
In other words, they are hidden settings.
They are defined in `mrbgems/mruby-{complex,rational}/mrbgem.rake`.
So this patch assumes that it is safe to refer to these functions in core-gems directly from core functions.
However, applications that link with `libmruby_core.a` will have compatibility issues.
In fact, `mrbgems/mruby-bin-mrbc` links with `libmruby_core.a`, so I had to prepare a dummy function.
- - -
If this patch is merged, we can close #5620, which is no longer needed.

Call functions directly from `mrb_ensure_float_type()`

---

src/proc.c

ref. 28ccc664e5dcd3f9d55173e9afde77c4705a9ab6

Assign after `mrb_irep_incref()` in `mrb_proc_new()`

---

include/mruby.h

The `mrb_static_assert_powerof2()` macro has been introduced for this purpose.

Assert that `MRB_METHOD_CACHE_SIZE` is a power of 2

---

src/cdump.c
src/dump.c

The file headers were pointing to each other's files.

Fixes file header in src/{cdump,dump}.c [ci skip]

---

doc/guides/mrbgems.md

```
+- tools/
|
+- example/
|
+- example.c
```
```
+- tools/
|
+- example/
|
+- example.c
```

Fix tree of mruby-bin-example

---

src/vm.c

If a non-hash object is passed in `OP_SEND` and `OP_SUPER`, an error should occur.
```ruby
kwd = "string"
p(**kwd)  #  => expect raised TypeError
```
This PR also integrates the code that was copied and pasted in #5628.

Check the type of the keyword rest argument

---

.github/workflows/build.yml

Until now, `windows-latest` meant `windows-2019`, but now it seems that it is being replaced by `windows-2022` in stages.
At the same time, Visual Studio 2019 will be replaced by Visual Studio 2022.
Since mruby's CI is configured to assume Visual Studio 2019, we'll update this and explicitly specify `windows-2022`.
ref. https://github.com/actions/virtual-environments/issues/4856

Pinning the Visual Studio version in GitHub Actions

---

src/array.c
test/t/array.rb

This following is a behavior from CRuby 1.8.7 to 3.1.0.
```console
% ruby -ve "p ['a', 'b', 'c']*''"
ruby 1.8.7 (2013-12-22 patchlevel 375) [i686-darwin13.0.2]
"abc"
% ruby -ve "p ['a', 'b', 'c']*''"
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin19]
"abc"
```
mruby unexpectedly gives the TypeError.
```ruby
['a', 'b', 'c']*'' #=> String cannot be converted to Integer (TypeError)
```
This PR makes mruby behave compatible with CRuby.
```ruby
['a', 'b', 'c']*'' #=> 'abc'
```
As far as I checked, the behavior is unspecified when `Array#*`'s argument
is not an instance of Integer class in X 3017 : 2013 (ISO/IEC 30170 : 2012).
I noticed this difference by the following idiom when writing ASCII art code using Ruby.
```ruby
%w(foo bar baz)*''
```
e.g. TRICK (https://github.com/tric)

Make `Array#*` the CRuby compatible behavior when giving a string argument

---

include/mruby/error.h
mrbgems/mruby-errno/src/errno.c
src/error.c

ref. #2485
The `SystemCallError#to_s` method also needed to be modified, but since it has no functional difference from the `Exception#to_s` method, it will be removed.

Avoid direct access to error messages as instance variables

---

mrbgems/mruby-compiler/core/codegen.c

I expect this will fix the two problems that "#5640" didn't address.
- It is expected to raise an exception `TypeError`, but it didn't before.
```console
% bin/mruby -e 'p [**1]'
[1]
```
- The variable `h` is expected to keep an empty hash, but it didn't before.
```console
% bin/mruby -e 'h = {}; p(**h, a: 1, b: 2); p h'
{:a=>1, :b=>2}
{:a=>1, :b=>2}
```

Insert an empty hash before the first `NODE_KW_REST_ARGS`

---

include/mruby.h

- Changed the description to match the order of the changed members.
- Replaced "array of symbols" instead of "array of strings that mean symbols".
- The `mrb_kwargs::optional` member has not been present since the first merge. It is a remnant from development time.
- Removed `const` modifier used in variable declarations in examples. This is not always necessary from a user perspective.
- Added note on the use of `MRB_SYM()`.
resolved #5649

Improved documentation for `struct mrb_kwargs` [ci skip]

---

lib/mruby/build/load_gems.rb

It appears that some execution paths no longer load YAML before it is
needed so we explicitly `require` it here.
Note that this change does **not** dynamically load the dependency the way some other code does.  I assumed that this was legacy behaviour but I can certainly change this if you would like.

Added a dependency on 'yaml' to load_gems.rb.

---

mrblib/00class.rb

Array objects obtained as splat arguments are generated within the method.
Therefore, it is safe to perform destructive operations.

Small improvements to `Module#{include,prepend}`

---

src/class.c

This is because it is not limited to the `BasicObject#initialize` method.

Change function name `mrb_bob_init` to `mrb_do_nothing`

---

mrblib/10error.rb
src/error.c

Suppresses the possibility of `mrb_vm_exec()` being called recursively.

Reimplement `Exception#message` in Ruby

---

src/gc.c

The object in `GC_RED` does not need to be marked, and the objects connected to this object should also not need to be marked.
- - -
Please reject this PR if there are future plans that require marking objects linked from objects in `GC_RED`.

No need to protect red objects

---

mrbgems/mruby-socket/src/socket.c

The `mrb_voidp()` related macros have been removed in mruby-1.1.0.

Remove old compatibility code

---

include/mruby/error.h
src/error.c

Normal return of control from the `mrb_sys_fail()` function has unexpected results.
Example: double free, malloc with huge size used as error integer
The following is an example of an actual crash:
```console
% cat crash.rb
def SystemCallError._sys_fail(*a)
nil
end
File.readlink("/404")
% bin/mruby crash.rb
zsh: segmentation fault (core dumped)  bin/mruby crash.rb
```

Must the `mrb_sys_fail()` function raise an exception

---

src/class.c

Previously defined as `BasicObject#method_added`.

Move `method_added` method into the `Module`

---

lib/mruby/build.rb

This was the cause of the command line flag being affected by changes in the parent build.
So, for example, if `mruby-rational` was included, even the automatically added `mrbc` builds included `MRB_USE_RATIONAL`.

Setting `Command#build` correctly in automatic "mrbc" build for presym

---

src/gc.c

Prevents retrieval with the `ObjectSpace.each_object` method.

Hides the class of string objects allocated by `mrb_alloca()`

---

include/mruby/bigint.h
mrbgems/mruby-bigint/README.md
mrbgems/mruby-bigint/core/bigint.c
mrbgems/mruby-bigint/core/bigint.h
mrbgems/mruby-bigint/mrbgem.rake
mrbgems/mruby-numeric-ext/src/numeric_ext.c

Users can now switch to their own implementation of GEM.
However, we do not guarantee that this will not be a problem in the current situation.
This may need to be improved in the future.
And, a part of `bigint.h` has been removed because it duplicates `include/mruby/internal.h`.
- - -
- `mrbgems/mruby-bigint/core/bigint.h` ⬅ `include/mruby/bigint.h`
- `mrbgems/mruby-bigint/core/bigint.c` ⬅ `src/bigint.c`
The files are placed in ***the `core/` directory***. Note that it is ***not the `src/` directory***.
I also plan to add tips for creating custom GEMs to `mrbgems/mruby-bigint/README.md`, using the GNU Multi-Precision Library as an example.

Move bigint implementation files to `mruby-bigint`

---

.github/workflows/codeql-analysis.yml

Avoid triggering CodeQL on the "push" event for Dependabot branches

---

.pre-commit-config.yaml

Conda, Homebrew and PyPI all have `2.18.1`
https://github.com/pre-commit/pre-commit/releases
https://pypi.org/project/pre-commit/#history
https://formulae.brew.sh/formula/pre-commit
https://anaconda.org/conda-forge/pre-commit
Also run `pre-commit autoupdate`
https://pre-commit.com/#pre-commit-autoupdate

Update minimum `pre-commit` version to latest `2.18.1`

---

include/mruby/error.h
src/backtrace.c
src/error.c
src/gc.c

With this change, the lower 16 bits of `struct RBasic::flags` are unused.
If this PR is accepted, a patch will be prepared to store `errno` of `SystemCallError` in the lower 10 bits of `struct RBasic::flags` if possible (I'm currently working on it, though).

Reorganize the `struct RException`

---

mrbgems/mruby-random/src/random.c

This is to prevent data corruption of the substituted `Random` instance.
If the `Object::Random` constants are redefined to a different `MRB_TT_ISTRUCT` object class, they can pass `mrb_get_args()` validation.
The following is an example of how the `Array#shuffle` method rewrites the data of a non `Random` instance.
```c
// code.c
#include <mruby/class.h>
#include <mruby/compile.h>
#include <mruby/istruct.h>
#define EVAL_LIT(MRB, ...) mrb_load_string((MRB), #__VA_ARGS__)
static mrb_value
fake_initialize(mrb_state *mrb, mrb_value self)
{
char *p = ISTRUCT_PTR(self);
for (int i = 0; i < ISTRUCT_DATA_SIZE; i++) {
p[i] = 'A' + i;
}
return self;
}
static mrb_value
fake_to_bytes(mrb_state *mrb, mrb_value self)
{
const char *p = ISTRUCT_PTR(self);
return mrb_str_new(mrb, p, …
```

Strict acquisition of the `Random` class given by `mrb_get_args()`

---

include/mruby/object.h
mrbgems/mruby-bigint/core/bigint.h
mrbgems/mruby-complex/src/complex.c
mrbgems/mruby-rational/src/rational.c
src/gc.c

Asserts the size of the object structure is less than or equal to 6 words.

Introduced `mrb_static_assert_object_size()`

---

mrbgems/mruby-kernel-ext/src/kernel.c

Check `NULL` for `proc` and `env` in `Kernel#__method__`

---

src/class.c
src/variable.c

If GC occurs in `mrb_calloc()` called by `iv_rehash()` or `mt_rehash()`, the object as table data may be destroyed.

Asigns table properties after `mrb_calloc()`

---

src/gc.c

If `mrb_realloc()` raises an out-of-memory exception, `arena_capa` will hold the wrong value.

Fixed possible inconsistency in `gc_protect()`

---

benchmark/bm_ao_render.rb

The original function name in ao.c was orthoBasis.
I guess the function is generating orthonormal basis (https://en.wikipedia.org/wiki/Orthonormal_basis).

fix typo otherBasis -> orthoBasis

---

src/variable.c

Fix #5725
---
If necessary, I think it is preferable to add a `MRB_PROC_OR_CI_TARGET_CLASS()` to get the `target_class` from `ci` instead, for example.

Use `mrb->object_class` instead if `MRB_PROC_TARGET_CLASS()` is `NULL`

---

include/mruby/proc.h

If `ci->u.target_class` was `NULL`, the value of the argument was always ignored.
This problem is caused by #5272.
ref. #5725

Fixes `mrb_vm_ci_target_class_set()`

---

src/proc.c

If `target_class->tt` is `MRB_TT_ICLASS`, it may cause loss of class inheritance relationships.
This problem is caused by #5402.
ref. #5725

Do not expand "included class" in `mrb_proc_new()`.

---

src/string.c

If compiled with MRB_UTF8_STRING and using clang-asan config, one of the tests fails due to a read out of bounds. A simple test case for this can be found by creating a string long enough to force it to be non-embedded which also ends in a three-byte UTF-8 character followed by a single ASCII character, then search for index of the UTF-8 character:
`./bin/mruby -e '"XXXXXXXXXXXXXXXXXXXXXXXX香X".rindex("香")'`
This results in a crash due to reading out of bounds:
> ==48442==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000001cad at pc 0x0001093104b6 bp 0x7ffee759ce50 sp 0x7ffee759c5f8
READ of size 3 at 0x603000001cad thread T0
#0 0x1093104b5 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long)+0x155 …

Fix out of bounds access by memcmp in String#rindex

---

mrbgems/mruby-errno/mrblib/errno.rb
mrbgems/mruby-errno/src/errno.c

If the `Errno::EXXX` class is defined minimally when needed, it will save about 17 KiB of RAM in a 32-bit environment.
Define the singular methods `.const_defined?`, `.const_missing` and `.constants` in the `Errno` module and act as if there are classes that have not yet been defined.
However, if real classes are enumerated, for example by the following code, the effect is lost.
```ruby
Errno.constants.map { |id| Errno.const_get(id) }
```
But I believe that such codes are rarely written with the intention of being written.
In this patch, the `Errno::EXXX#initialize` method is no longer defined for further memory reduction.
Instead, it has been merged into the `SystemCallError#initialize` method.
---
Initially, one of the candidates was to move `mruby-errno` from `stdlib.gembox` to another …

Define `Errno::EXXX` when needed

---

lib/mruby/build/load_gems.rb

If there is no `.lock` file and no commit hash specified, avoid `git checkout --detach`.
This behavior will be the same as up to mruby-3.1.
ref. #5638

Ignore git checkout if nil commit-hash

---

mrbgems/mruby-errno/src/errno.c

As of #5667, I had planned to store integer values in `struct RException::flags`.
But on second thought, I don't think there is much need for that, so I'm cancelling the plan.
Just a reminder. This PR is for compatibility with CRuby.

Allow negative `errno` to be handled as well

---

src/class.c

`OP_SEND R4 :allocate 0` requires an an invisible `nil` block to `R5`.
If `R5` is not allocated, this can lead to unexpected results due to buffer overflow.
This problem is caused by #5565.
ref. commit 33792c2a029130bf38d676ae3cf0b51d5d54ffd5
I'm sorry.

Corrected the number of registers in the `Class#new` method

---

include/mruby/irep.h

Because there is `W` type, at least 24 bits must be represented.
---
I was not sure whether to make it a bit field or not, but decided not to worry about padding since it is limited to function arguments and return values.

Fix the first operand of `struct mrb_insn_data` to 32 bits

---

src/variable.c

`mrb_class_find_path` resolves a `char*` pointer to a class name string
by calling `mrb_class_name`. It then allocates a new string with
capacity 40 to copy that `char*` into.
https://github.com/mruby/mruby/blob/e04184185ab43b94980550e850d8813a415fa438/src/variable.c#L1111-L1112
`mrb_class_name` resolves the class name via `class_name_str`, which
returns an `mrb_value` with type tag `MRB_TT_STRING` and backed by an
`RString*`. Then `mrb_class_name` extracts the `RSTRING_PTR`:
https://github.com/mruby/mruby/blob/e04184185ab43b94980550e850d8813a415fa438/src/class.c#L2133-L2134
That `RString*`-backed `mrb_value` ultimately comes from `mrb_class_path`
which resolves the string from the symbol table:
https://github.com/mruby/mruby/blob/e04184185ab43b94980550e850d8813a415fa438/src/class.c#L2111 …

Fix possible use after free in `mrb_class_find_path`

---

src/kernel.c

The `Kernel.puts` method is defined in the `mrbgems/mruby-print/mrblib/print.rb` file.

Removed unnecessary ISO section numbers for `Kernel.puts` [ci skip]

---

src/gc.c

GC may occur in the `c->stbase = mrb_malloc()` part of the `fiber_init()` function.
The `SIGSEGV` happens because it references the `c->ci->stack` field without checking `c->ci`.
This is caused by #5272.

Fix `SIGSEGV` caused by GC during fiber initialization

---

src/hash.c

If GC occurs in `mrb_realloc()` in `ht_init()` called from `ar_set()`, the following inconsistency occurs:
- If `h_ht_on()` is called before `mrb_realloc()`, `hash->hsh.ht` is referenced instead of `hash->hsh.ea` during GC.
- If the pointer is changed by `ea_adjust()` in `ar_set()`, `hash->hsh.ea` (`hash->hsh.ht`) is referenced in GC before the change.
These modifications can be resolved by changing the order of processing.
However, if a `NoMemoryError` exception is raised, it is presumed that the size of the "AR" will be exceeded and the unintended state will continue.
To prevent this, elements should be added after they have been converted to "HT".

Fix property between `ar_set()` and `ht_init()`.

---

mrbgems/mruby-compiler/core/codegen.c

If a GC occurs in `mrb_calloc()` called by `mt_rehash()` inside `mrb_define_method_raw(), the `proc` may be destroyed.

Protected `proc` objects given by `OP_DEF` on registers

---

build_config/android_arm64_v8a.rb
build_config/android_armeabi.rb
build_config/android_armeabi_v7a_neon_hard.rb
tasks/toolchains/android.rake

I found that current android.rake does not comply to Build System Maintainers Guide for NDK (Android's Native Development Kit), and mruby cannot be compiled by recent versions of NDK.
https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Sysroot
I updated android.rake and the corresponding build config files.  With this update, I checked NDK r19 and NDK r25(latest) can build mruby on macOS 12.5 (intel).

Reenabling building for Android NDK

---

mrbgems/mruby-compiler/core/codegen.c
src/vm.c

It should be compared to the `irep->nregs` value as is.
At the same time, discovered problems have been fixed.

Fixed assertion in `ARGUMENT_NORMALIZE()` for `bidx`.

---

include/mruby/proc.h
lib/mruby/gem.rb
mrbgems/mruby-bin-mirb/tools/mirb/mirb.c
mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
src/gc.c
src/vm.c

Exception raising can now be controlled by the caller.
The main purpose on this patch is:
- Suppress exceptions from `obj_free()` in `src/gc.c` with `mrb_env_unshare()`.
- Consider the possibility that calls to `mrb_malloc()` may cause `e` objects to be subject to GC.
When control is returned to `mrb_env_unshare()`, `struct free_obj::next` in the same offset as `struct REnv::stack` is rewritten.
Unexpected results then occur when the object is reused.
Also, if `mrb_heap_page` containing an `e` object is freed, it may cause `SIGSEGV` at that point.
- Protects the value of the stack on `callinfo` that just exits if GC occurs inside `mrb_env_unshare()`.
```ruby
def m
b = -> { b }
end
p m.call
```
This patch does not raise a `NoMemoryError` exception in `mrb_env_unshare()` and can detect that …

Improve out-of-memory tolerance of `mrb_env_unshare()`

---

doc/guides/mrbconf.md
src/gc.c

It also fills the GC'ed object area with `0xff` for debugging purposes.
---
This PR substitutes for #5720.
Also, with only this PR, CI will report an error.
Overcoming the problem will be sent in another PR.

Perform Full-GC from `mrb_realloc_simple()` by `MRB_GC_STRESS + MRB_DEBUG`

---

src/gc.c

When `gc_protect()` is called from `mrb_obj_alloc()`, unnecessary overhead is eliminated.

Check `MRB_GC_RED` with `mrb_gc_protect()`

---

include/mruby/value.h

:black_cat: I wish I could be more consistent, but this is my limitation.

Match the `mrb_value` documentation to the current implementation

---

include/mruby.h
include/mruby/irep.h

Eliminated invisible dependencies from `mruby/debug.h` to `mruby/irep.h`.

Make definition of `mrb_irep` by `typedef` in `mruby.h`

---

mrbgems/mruby-fiber/src/fiber.c

When call `Fiber#resume` from C function like `mrb_funcall()` and fiber raise a exception, mruby's stack is broken.
Add `fiber_check_cfunc` in fiber_resume() to make this problem as safe error.
Because fiber can't cross C function boundary.
This change has a breaking change, when fiber raises no exception.
Before this change, mrb_funcall() make fiber run normally.
After this change, mrb_funcall() sets mrb->exc.
Reproduction code:
```c
#include "mruby.h"
#include "mruby/compile.h"
int main(int argc, char **argv)
{
struct mrb_state *mrb = mrb_open();
mrb_value fiber = mrb_load_string(mrb, "Fiber.new { raise 'err' }"); // raise in fiber
mrb_funcall(mrb, fiber, "resume", 0); // corrupse ruby's stack.
mrb_load_string(mrb, "1"); // # SEGV in mrb_vm_ci_target_class() 
mrb_close(mrb);
return 0;
} …
```

Protect when call Fiber#resume from C function.

---

include/mruby.h
include/mruby/gc.h
src/class.c
src/gc.c

This pull request adds a new function, `mrb_get_args_a()`, which works exactly like `mrb_get_args()` except that it takes
the pointer arguments as an array instead of varargs.
I needed to add this for my mruby binder library that I want to release publicly. It allows you to write code like:
(from my test cases)
```cpp
auto* ruby = mrb_open();
auto* person_class = mrb::make_class<Person>(ruby, "Person");
mrb::add_method<Person>(
ruby, "age=", [](Person* p, int age) { p->age = age; });
mrb::add_method<Person>(
ruby, "age", [](Person const* p) { return p->age; });
mrb::add_method<Person>(ruby, "copy_from", [](Person* p, Person* src) {
p->name = src->name;
p->age = src->age;
});
mrb::add_method<Person>(
ruby, "dup", [](Person const* p) { return new Person(*p); });
auto other_age = …
```

Add mrb_get_args_a()

---

mrbgems/mruby-objectspace/src/mruby_objectspace.c

- Support for `MRB_TT_STRUCT`, `MRB_TT_BREAK` and `MRB_TT_BIGINT`.
- Performs symbol value embedding with `MRB_SYM()`.

Improves `ObjectSpace.count_objects`

---

doc/limitations.md

`binding` has been supported since 3.1.0.

Fix doc for limitation

---

mrbgems/mruby-bigint/README.md

- Add a period at the end of the line because markdown will combine lines if there are no blank lines.
- Enable link to `README-fgmp.md`.

Small improves for `mrbgems/mruby-bigint/README.md` [ci skip]

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/lint.yml
.github/workflows/oss-fuzz.yml
.github/workflows/super-linter.yml

This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using [secure-workflows](https://github.com/step-security/secure-workflows).
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes. Here is an example of the permissions in one of the workflow runs:
https://github.com/mruby/mruby/actions/runs/3163459384/jobs/5151028463#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflows:
- build.yml
- codeql-analysis.yml
- lint.yml
- oss-fuzz.yml
- super-linter.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- [GitHub recommends](https://docs.github.com/en/actions/security-guides/autom …

ci: add minimum GitHub token permissions for workflows

---

mrbgems/mruby-proc-binding/mrbgem.rake

The `mruby-proc_source_location()` function used in `src/proc-binding.c` of `mruby-proc-binding` is defined in `mruby-proc-ext`.

Needs `mruby-proc-ext` by `mruby-proc-binding`

---

README.md

The building on travis-ci.org is ceased.

docs: remove unused Travis CI button from README

---

lib/mruby/gem.rb
test/bintest.rb

Using `tr` is faster than `gsub` when replacing a single character in a string with another single character

Replace `gsub` with `tr`

---

build_config/cross-mingw-winetest.rb
doc/internal/boxing.md
doc/mruby3.0.md
doc/mruby3.1.md
src/fmt_fp.c
src/numeric.c

https://en.wikipedia.org/wiki/Floating-point_arithmetic

Fix spelling: `floating point` -> `floating-point`

---

mrbgems/mruby-pack/test/pack.rb
mrbgems/mruby-string-ext/test/numeric.rb
mrbgems/mruby-string-ext/test/string.rb
mrbgems/mruby-symbol-ext/test/symbol.rb
mrblib/array.rb
mruby-source.gemspec
test/t/string.rb

The default script encoding is Encoding::UTF-8 after v2.0.
https://ruby-doc.org/core-2.1.2/Encoding.html#class-Encoding-label-Script+encoding

Remove `# coding: utf-8` from Ruby files

---

src/class.c

MRB_TT_FALSE is equal to 0, so we have to explicitly check if the class is either NilClass or FalseClass.

class.c (mrb_instance_alloc): raise error if NilClass/FalseClass

---

mrbgems/mruby-compiler/core/codegen.c

Without this, the following program would hang:
```rb
case
when true, false
puts :success
end
```
Old VM instructions: (Notice the infinite loop created by `JMP 000`)
```
2 000 JMP		000
2 003 JMP		016
3 006 LOADSYM	R2	:success	
3 009 SSEND		R1	:puts	n=1
3 013 JMP		018
3 016 LOADNIL	R1		
3 018 RETURN	R1		
3 020 STOP
```
New VM instructions:
```
3 000 LOADSYM	R2	:success	
3 003 SSEND		R1	:puts	n=1
3 007 RETURN	R1		
3 009 STOP
```

codegen.c: exit headless `case` early if a condition is always true

---

mrbgems/mruby-io/src/io.c

The error of select(2) on Windows should be given from WSAGetLastError().
https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-select#return-value

use WSAGetLastError() for errno on Windows

---

src/kernel.c

`Kernel#<=>` should also call `#==` to check if the objects are equal.
```rb
class Foo
def ==(_)
true
end
end
p Foo.new <=> Object.new # => 0
```
~~Admittedly, I'm not sure if this is worth the performance hit. Perhaps it would be better to simply revert c1697a9.~~

kernel.c (mrb_cmp_m): use mrb_equal instead of mrb_obj_equal.

---

mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c

```rb
def method_with_arg_and_block(arg, &blk)
[arg, blk]
end
def test_method
return method_with_arg_and_block :foo do end
end
test_lambda1 = lambda do
break method_with_arg_and_block :foo do end
end
test_lambda2 = lambda do
next method_with_arg_and_block :foo do end
end
```
Before:
```rb
p test_method # => [:foo, nil]
p test_lambda1.call # => [:foo, nil]
p test_lambda2.call # => [:foo, nil]
```
After:
```rb
p test_method # => [:foo, #<Proc...>]
p test_lambda1.call # => [:foo, #<Proc...>]
p test_lambda2.call # => [:foo, #<Proc...>]
```

parse.y: fix return/break/next with method call with args and block

---

README.md
doc/guides/gc-arena-howto.md
doc/guides/link.md
doc/guides/mrbgems.md
doc/guides/symbol.md
doc/mruby3.0.md

Most of the Markdown has a single space between sentences.
This pr changes `2 spaces` to `1 space`.

docs: standardize whitespace in Markdown files

---

doc/internal/opcode.md
include/mruby/ops.h
mrbgems/mruby-compiler/core/codegen.c
src/codedump.c
src/vm.c

Transforms the value of a splat inside an array or a return statement. For example, `return *nil` should return `nil.to_a`, while `return *1` should return `[1]`

ops.h: update `OP_ARYDUP` instruction and rename  to `OP_ARYSPLAT`

---

.editorconfig
.pre-commit-config.yaml

Add `indent_style = space` to the `.editorconfig` file for batch files.

pre-commit(tabs): use blacklist to exclude files

---

.editorconfig

The top `.editorconfig` rule `charset = utf-8` now applies to batch files
```
mruby % file -I mrbgems/mruby-bin-config/mruby-config.bat
mrbgems/mruby-bin-config/mruby-config.bat: text/x-msdos-batch; charset=us-ascii
```
US-ASCII (basic English) is a 7-bit, 128 characters code page, originally designed for telegraphy.
UTF-8 encoding uses the same encoding as 7-bit ASCII for its first 128 characters. So a text file that only contains characters from that range of the first 128 characters will be identical at a byte level whether encoded with UTF-8 or 7-bit ASCII.
https://stackoverflow.com/questions/11303405/force-encode-from-us-ascii-to-utf-8-iconv

Remove `charset = latin1` from `.editorconfig` for batch files

---

src/vm.c

Introduce the macro functions `RAISE_EXC()`, `RAISE_FORMAT()` and `RAISE_LIT()`.
---
This patch has a merge conflict with #5750.
Once one is merged, I will fix the other.

Use macro in `mrb_vm_exec()` exception raising

---

src/vm.c

The current flow of the `L_RAISE` block is as follows:
```mermaid
flowchart LR
raise((raise))
raise --> citop{"top of call info?"}
citop -- YES --> chftop{"no catch handler?"}
citop -- NO --> chf{"no catch handler?"}
chftop -- YES --> fiber{"root of fiber?"}
chftop -- NO --> vmexec((vmexec))
fiber -- YES --> vmstop((vmstop))
fiber -- NO --> fswitch["switch fiber"]
fswitch --> citop
chf -- YES --> cipop["cipop"]
chf -- NO --> vmexec((vmexec))
cipop --> citop
```
This patch makes the catch handler search first:
```mermaid
flowchart LR
raise((raise))
raise --> chf{"no catch handler?"}
chf -- NO --> vmexec((vmexec))
chf -- YES --> citop{"top of call info?"}
citop -- YES --> fiber{"root of fiber?"}
citop -- NO --> cipop["cipop"]
cipop --> chf
fiber -- YES --> vmstop((vmstop))
fiber -- NO --> …
```

Simplify the `L_RAISE` block

---

.pre-commit-config.yaml

```
mruby % file -I mrbgems/mruby-bin-config/mruby-config
mrbgems/mruby-bin-config/mruby-config: text/x-shellscript; charset=us-ascii
```
The Google shell style guide states:
Executables should have no extension (strongly preferred)
This hook checks for conformance.
https://github.com/jumanjihouse/pre-commit-hooks#script-must-not-have-extension
We are already using hooks from "jumanjihouse" in the `mgem-list` repo.
https://github.com/mruby/mgem-list/blob/f5904922d5fbc87f45c582b8ef759e2ebf16df79/.pre-commit-config.yaml#L39

pre-commit(shell): add hook `script-must-not-have-extension`

---

src/string.c

:scream_cat: When I compiled optimally with gcc, I got a warning.
However, I could not understand why this warning was printed.
```console
% gcc12 -Iinclude -DMRB_NO_PRESYM -DMRB_UTF8_STRING -Wall -O3 -c src/string.c
src/string.c: In function 'str_escape':
src/string.c:1225:18: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
1225 |           buf[i] = p[i];
|           ~~~~~~~^~~~~~
src/string.c:1209:8: note: at offset 4 into destination object 'buf' of size 4
1209 |   char buf[4];  /* `\x??` or UTF-8 character */
|        ^~~
src/string.c:1225:18: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
1225 |           buf[i] = p[i];
|           ~~~~~~~^~~~~~
src/string.c:1209:8: note: at offset 5 into destination object 'buf' of size 4
1209 |   char …
```

Reduce memory copy in `mrb_str_inspect()` with UTF-8

---

src/vm.c

Raising a `SystemStackError` exception in an out-of-memory situation will generate backtrace information. This can eventually lead to a `NoMemoryError` exception, and this process flow is completely undesirable.
In effect, this change means that it will include a revert of commit 0dbb9e6e411572b0c37e7be723d6dc3895387f96.

Using `mrb_realloc()` with `stack_extend_alloc()`

---

.github/workflows/build.yml

https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/

gha: replace `Ubuntu 18.04` with `Ubuntu 22.04` in `build` workflow

---

include/mruby.h
mrbgems/mruby-fiber/src/fiber.c

- Added note on `mrb_fiber_resume()` and `mrb_fiber_yield()`. Removed comments from C files that were not documented by yard and doxygen instead.
- Leads to use of `mrb_fiber_resume()` instead of `Fiber#resume` in C.
- Leads to use of `mrb_fiber_yield()` instead of `Fiber.yield` in C.

Updates documentation for `mrb_fiber_resume()` and `mrb_fiber_yield()`

---

src/backtrace.c
src/error.c

- In case of `NoMemoryError` exceptions, the error message is now printed directly.
- Replaced `mrb_p()` used by #4250 with `mrb_print_error()`.
ref. squashed commit f1523d24042ca3416dc5b9be7b3fc220ddaed896
ref. subcommit da7d7f881bbbad9988a3a2b7bad8f2b72ff06bc6
ref. subcommit d9c7b6be6eb54630b64eea5c35be241e551676e5
---
I don't remember for sure, but I think I used `mrb_p()` in #4250 because it sometimes didn't output and that was also the case before the change in commit da7d7f881bbbad9988a3a2b7bad8f2b72ff06bc6.

Print errors by calling `mrb_print_backtrace()` without backtrace

---

doc/internal/opcode.md
lib/mruby/doc.rb
tasks/doc.rake

Allow to update `doc/internal/opcode.md` file mechanically from `include/mruby/ops.h` file.
At the same time, the `doc/internal/opcode.md` file has been updated. Consecutive hyphens at the end of the table were removed as they would have created noise as markdown flavours.

Add task `rake doc:update-opcode.md`

---

mrbgems/stdlib-io.gembox
mrbgems/stdlib.gembox

This is because GEMs that use errno are currently limited to `mruby-io` and `mruby-socket`.

Move `mruby-errno` to `stdlib-io.gembox`

---

doc/internal/opcode.md
lib/mruby/doc.rb

ref. https://github.github.com/gfm/#example-200
- - -
The "yard" called by "mrbdoc" has several libraries available to parse Markdown.
Note: The preferred library can be changed with `mrbdoc -M <gem-name>`.
<https://github.com/lsegal/yard/blob/v0.9.28/lib/yard/templates/helpers/markup_helper.rb#L24-L34>
<https://github.com/lsegal/yard/blob/v0.9.28/lib/yard/templates/helpers/markup_helper.rb#L87-L116>
Ruby gem name   | Support table?  | Can pipes in codes inside tables be escapable?  | Note
:-------------: | :-------------: | :---------------------------------------------: | ---
redcarpet       | yes             | no
rdiscount       | yes             | yes
kramdown        | yes             | yes, but escaped characters remain
bluecloth       | no
maruku          | yes             | no …

Escaping pipes in the code of table elements

---

.github/workflows/build.yml

The reason I limited myself to just `matrix.include` is that there are several environments that need to be specialized, and the whole description is easy to understand.
For example, the following description is not immediately comprehensible to me even when I write it myself. It is even more so if there are a lot of them.
```yaml
matrix:
os: ubuntu-2022.04, ubuntu-2020.04
cc: gcc, clang
include:
- { cc: gcc, cxx: g++ }
- { cc: clang, cxx: clang }
- { os: ubuntu-latest, cc: gcc-4.8, cxx: g++-4.8, container: ubuntu:18.04 }
```
This is the same as:
```yaml
matrix:
include:
- { os: ubuntu-2022.04, cc: gcc, cxx: g++ }
- { os: ubuntu-2022.04, cc: clang, cxx: clang++ }
- { os: ubuntu-2020.04, cc: gcc, cxx: g++ }
- { os: ubuntu-2020.04, cc: clang, cxx: clang++ }
- { os: ubuntu-latest, cc: …
```

Combine gcc/clang jobs with matrix

---

lib/mruby/build/command.rb

This was how the clone command was previously being generated, for example:
```
git clone  --recursive --branch "master" --depth 1 https://github.com/mattn/mruby-onig-regexp.git /path/to mruby with spaces/mruby-3.1.0/build/repos/wasm/mruby-onig-regexp
```
Now it's changed so the path is quoted and will work when containing spaces:
```
git clone  --recursive --branch "master" --depth 1 https://github.com/mattn/mruby-onig-regexp.git "/path/to mruby with spaces/mruby-3.1.0/build/repos/wasm/mruby-onig-regexp"
```
Similar for the other commands.
Thank you!

Fix cloning gem when destination path contains spaces

---

doc/limitations.md

Since redefinition of "nil?" is possible in ruby, ruby's output should be "truthy".
And since redefinition of "nil?" is not possible in mruby, mruby's output should be "falsy".
It was the reversed.

Fix typo in doc/limitations.md

---

mrbgems/mruby-dir/src/dir.c

Since `IOError` is a standard exception class in Ruby, there is no need to assume different superclasses. The Ruby specification allows repeated class definitions as long as the superclass is the same.
This also avoids using the `mruby/ext/io.h` file to reference `E_IO_ERROR`.

Define also the exception class `IOError` in `mruby-dir`

---

mrbgems/mruby-string-ext/test/string.rb

The default script encoding is Encoding::UTF-8 after v2.0.
https://ruby-doc.org/core-2.1.2/Encoding.html#class-Encoding-label-Script+encoding

Remove `# coding: utf-8` from Ruby file

---

include/mruby/value.h

Starting with macOS Ventura, `get_etext` and `get_edata` are now deprecated:
```
mruby/include/mruby/value.h:441:17: warning: 'get_etext' is deprecated: first deprecated in macOS 13.0 - No longer supported [-Wdeprecated-declarations]
return (char*)get_etext() < p && p < (char*)get_edata();
^
mruby/include/mruby/value.h:441:47: warning: 'get_edata' is deprecated: first deprecated in macOS 13.0 - No longer supported [-Wdeprecated-declarations]
return (char*)get_etext() < p && p < (char*)get_edata();
^
```

Use `getsegmentdata` instead of deprecated `get_etext`/`get_edata`

---

CONTRIBUTING.md
tasks/doc.rake

The RubyGems website gives a much better overview of both Gems
A lot more quick links and statistics.
https://rubygems.org/gems/yard-mruby
https://rubygems.org/gems/yard-coderay

Use rubygems.org links for yard-mruby and yard-coderay

---

mrbgems/mruby-dir/mrblib/dir.rb

Ignore `IOError` if `Dir#close` was done in the block.

Avoid `IOError` when returning from `Dir.open`

---

doc/guides/mrbconf.md

The actual size that `malloc()` allocates depends on the environment, so I believe it will be helpful.
For reference:
- In glibc-2.36 it is allocated on a 2-word boundary  
ref. <https://sourceware.org/git/?p=glibc.git;a=blob;f=malloc/malloc.c;hb=glibc-2.36#l1162>
- In FreeBSD userspace, jemalloc is used, so the granularity is a bit larger  
ref. <https://jemalloc.net/jemalloc.3.html#size_classes>
- In FreeBSD kernel space, it is rounded up to the power of 2  
ref. <https://www.freebsd.org/cgi/man.cgi?malloc(9)#IMPLEMENTATION_NOTES>

Added more description of the `MRB_HEAP_PAGE_SIZE` configuration

---

mrbgems/mruby-compiler/core/parse.y
mrbgems/mruby-compiler/core/y.tab.c
src/vm.c

This is to keep the local variables of the previously created blocks consistent in case the `mrbc_context` passed to `mrb_load_exec()` is `NULL` or different. Switching between `mrbc_context` pointers that are non `NULL` can be done safely by calling `mrbc_cleanup_local_variables()`.
Before this patch, the result of the following code is not as expected.
```console
% cat loadstr.c
#include <mruby/compile.h>
int
main(int argc, char *argv[])
{
mrb_state *mrb = mrb_open();
mrb_load_string(
mrb,
"(a, b, c, d, e, f, g) = [1, 2, 3, 4, 5, 6, 7] \n"
"$lambda = -> { p [a, b, c, d, e, f, g] }");
mrb_load_string(mrb, "$lambda.call");
mrb_close(mrb);
return 0;
}
% $(bin/mruby-config --cc --cflags --ldflags) loadstr.c $(bin/mruby-config --libs) && ./a.out
[main, nil, nil, main, nil, …
```

Call `mrb_env_unshare()` in `mrb_top_run()` if necessary

---

src/codedump.c

Hi there,
I'd like to propose a non-functional change that adds an ability to dump bytecode into an arbitrary file instead of relying on stdout unconditionally.
For the context, I'm working on an AOT compiler and use this method for debugging.
As the complexity grows, it helps a lot to dump the code into a file instead of the stdout for further debugging.
The new method is hidden behind `MRB_NO_STDIO` macro as it uses `FILE` which might be not present when there is no stdio.
I'm very happy to iterate on the patch and discuss the PR further if anything needs changes.
Thank you!

Add ability to dump bytecode into an arbitrary file

---

src/vm.c

Move the detachment of the "env" object, now done by `mrb_top_run()` by #5904, to `mrb_vm_run()`. This is because `mrb_vm_run()` can remove `mrb_env_unshare()` which is called from `bin/mirb`.
Also, even if the mruby VM is already running, either of the following conditions should be used to detach "env":
- If the `stack_keep` variable is 0.
- If the stack length of "env" is longer than `irep->nlocals`.
The reason for the change is that the stack beyond `irep->nlocals` is used inside the called method, and previously it was possible to reference and manipulate the state inside the method via "env".
env stack       |                           |
main stack      | top |  m1  |    m2    |
|<--------------->|
operable via env stack (including self)
If the problematic block is called from the …

Make `mrb_env_unshare()` call in `mrb_vm_run()`

---

mrbgems/mruby-eval/src/eval.c

```console
% bin/mruby -e 'class Binding; end; eval "1", Binding.new'
zsh: segmentation fault (core dumped)  bin/mruby -e 'class Binding; end; eval "1", Binding.new'
```
orz
After the fix it does not crash, but it is difficult to understand the error.
Not so soon, but may improve eventually with another PR.
```console
% bin/mruby -e 'class Binding; end; eval "1", Binding.new'
[1] -e:1
-e:1:in eval: wrong argument type nil (expected Proc) (TypeError)
```

Fixed `Kernel#.eval` crash when given a custom defined `Binding` instance

---

include/mruby/error.h
include/mruby/internal.h

This function is the entity of the `Kernel.#raise` or `Kernel#fail` method. I don't think users can use it whenever they want, and I don't think there is any need to expose it as an entity of a user-defined method.

Demotion `mrb_f_raise()` from `MRB_API`

---

AUTHORS

The AUTHORS file was last published on January 8th 2023

AUTHORS: update "as of" info for `year`

---

benchmark/bm_ao_render.rb

DuplicateMethodCall: Scene#render calls 'nsf * nsf' 3 times

benchmark: remove duplicate method calls

---

.editorconfig

We already have `trailing-whitespace` set globally in the `pre-commit` config and we are also using `spaces` instead of `tabs` except for "Makefiles" which have `tab_width = 8`
Perhaps in future we can enforce line lengths.
https://github.com/mruby/mruby/blob/92ca93c885a6e6d2facd8e9ca3dbf85ac3dce8c9/.pre-commit-config.yaml#L29
https://github.com/mruby/mruby/blob/92ca93c885a6e6d2facd8e9ca3dbf85ac3dce8c9/.pre-commit-config.yaml#L33

Simplify the `.editorconfig` file

---

.github/workflows/lint.yml
CONTRIBUTING.md

It looks like `misspell` is no longer maintained and the last commit was on `Mar 9, 2018`.
We already run `codespell` and it is an active project with the last commit 5 days ago.
Also updated the CONTRIBUTING guide with more
information on `pre-commit` as well as listed `codespell` as the spell checker.
https://github.com/codespell-project/codespell
https://github.com/client9/misspell
https://github.com/client9/misspell/issues/197

Remove `misspell` and update `CONTRIBUTING.md`

---

appveyor.yml

Visual Studio 2022 on Windows is now a 64-bit application.
https://www.appveyor.com/docs/build-environment/#build-worker-images
https://learn.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-2022?view=vs-2022#visual-studio-2022-is-64-bit

appveyor: add job for Visual Studio 2022

---

src/variable.c
test/t/syntax.rb

Previously, for example, it was possible to retrieve the `String` class as follows:
```console
% bin/mruby -e 'p Comparable::Enumerable::Errno::GC::Kernel::Math::ObjectSpace::String'
String
```
Note that this patch affects the API function `mrb_const_get()`.

Don't switch constant search path from modules to Object

---

lib/mruby/gem.rb
tasks/mrbgems.rake

The point is:
- Don't call `exit()` when an exception occurs in `mrblib/*.rb`.
- Ignore exceptions raised by gems finalizer.

Reorganize gem init final

---

mrbgems/mruby-binding-core/src/binding-core.c
mrbgems/mruby-binding-core/test/binding-core.rb

This is because I forgot to implement the `Binding#initialize_copy` method.

Fixed local variables not separated between copied binding objects

---

include/mruby/internal.h
src/proc.c
src/vm.c

Safely retrieve `self` from proc in `mrb_yield()`
Passing a proc generated by the following method to `mrb_yield()` or `mrb_yield_argv()` no longer causes `SIGSEGV`:
- C functions made into proc objects with `mrb_proc_new_cfunc()`.
- A proc object which is the top level of a program generated by `mrb_load_string_cxt()` etc. with `mrbc_context::no_exec` enabled.
See also: #5932

Safely retrieve `self` from proc in `mrb_yield()`

---

mrbgems/mruby-bin-strip/mrbgem.rake

It uses `mrb_irep_remove_lv()` defined in `mrbgems/mruby-compiler/core/codegen.c`.

Need a dependency to `mruby-compiler` for `mruby-bin-strip`

---

.github/linters/.markdown-lint.yml
README.md

Center logo, mruby title and linter badge
Fix for YARD and Doxygen output

Add `mruby` logo to the README

---

src/vm.c

The previous `while` loop ends if the catch handler pointer `ch` is not `NULL`.
Supplement to #5843.

Remove unnecessary branches in `L_RAISE` block

---

src/vm.c

- Calculate the difference between `oldbase` and `newbase` only once outside the loop.
- To make sure they are within range, the comparison is done only once instead of twice.

Small improvements to `envadjust()`

---

lib/mruby/build.rb
lib/mruby/build/command.rb
tasks/toolchains/gcc.rake

Previously, compiler flags were only added for GCC or similar. The situation has not changed, but it has become easier to improve.
I expect `MRuby::Command::Compiler#setup_debug` to be defined as a singleton method inside the block given to `MRuby::Toolchain.new`.

Make `MRuby::Build#enable_debug` compiler flag setting abstract

---

mrbgems/mruby-binding/src/binding.c
mrbgems/mruby-complex/src/complex.c
mrbgems/mruby-data/src/data.c
mrbgems/mruby-method/src/method.c
mrbgems/mruby-rational/src/rational.c
src/class.c
src/gc.c
src/numeric.c

Calling `Class#allocate` with `UnboundMethod#bind_call` usually succeeds without problems.
If this behavior does not make us happy, we can now prohibit it with `MRB_SET_INSTANCE_TT(klass, MRB_TT_UNDEF)`.
At the same time, it applies to the `Binding`, `Complex`, `Data`, `Float`, `Integer`, `Method`, `Rational` and `UnboundMethod` classes.

Allow `Class#allocate` to be prohibited

---

mrbgems/mruby-binding/src/binding.c

`Binding#eval` should not be defined in `mruby-binding`.

Remove noise in new `mruby-binding`

---

mrbgems/mruby-binding-eval/test/binding.rb
mrbgems/mruby-binding/src/binding.c
mrbgems/mruby-binding/test/binding.c
mrbgems/mruby-binding/test/binding.rb

This follows the behavior changed in CRuby 3.2.

`Kernel#binding` responds only to calls from Ruby

---

mrbgems/mruby-compiler/core/codegen.c

Previously, the following code did not give the expected result.
```
% bin/mruby -e 'p "%08X" % ~(-1 << 16)'
"..F0000FFFF"
% ruby32 -e 'p "%08X" % ~(-1 << 24)'
"00FFFFFF"
```
For information: this problem arises in the process of folding numbers through optimisation.

Sign extension with `OP_LOADI32` in `get_int_operand()`

---

.github/labeler.yml
.github/workflows/labeler.yml

https://github.com/actions/labeler
https://github.com/marketplace/actions/labeler
Verified Action
We need to add the labels to this repo from `.github/labeler.yml` before this PR will work.
https://github.com/mruby/mruby/labels
The are now 14 labels to add and since the repository default labels are colored you might choose to make all of these 14 new labels the same color.   
We need to merge this pr before the labelling works.
Ready for review @matz

Add the pull request labeler Action

---

README.md
Rakefile
doc/guides/compile.md
doc/guides/mrbgems.md

Also, use "x/y/z directory" instead of "directory x/y/z" if there is no problem.
- - -
I see "directory" notation as more common than "folder" in mruby.
```console
% git grep -iE 'directory|directories' 68d67aee0 -- :^Doxyfile | wc
91     790    9042
% git grep -iE 'folder' 68d67aee0 -- :^Doxyfile | wc
8      78     711
```

Replace "folder" with "directory" for consistency

---

mrbgems/mruby-io/src/io.c

MRB_NO_IO_POEPN -> MRB_NO_IO_POPEN

fix typo in mrbgems/mruby-io/src/io.c

---

.dockerignore
.gitignore
CONTRIBUTING.md
Dockerfile
Gemfile
Gemfile.lock
Makefile
Rakefile
docker-compose.yml

This is a first pass at adding Docker for `mruby`. 
So far just installing and running `pre-commit` but in future both Make and/or Rake tasks could be added for further testing.  I can add more Docker docs in future too.
For ease of use there is Docker Desktop:
https://www.docker.com/products/docker-desktop/
Some images here:

Add `Docker` to build and run all `mruby` tests. Run `pre-commit` and generate `YARD` docs with Docker

---

lib/mruby/build.rb

The `<MRUBY_ROOT>/bintest` directory does not exist in current mruby.

Avoid adding `<MRUBY_ROOT>/bintest` which does not exist

---

lib/mruby/build.rb

Previously, "bintest" would fail to run unless `MRUBY_ROOT` and `Dir.pwd` were the same.

Make "bintest" independent of directory

---

mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.c

The current `mrb_final_mrbgems()` function is only referenced in the `mrbgem/gem_init.c` file.
Also, the definition in that file makes it a static function.

Remove `mrb_final_mrbgems()` in `mrbc.c`

---

.pre-commit-config.yaml
doc/mruby3.2.md

Fix links in Markdown
https://github.com/tcort/markdown-link-check#run-as-a-pre-commit-hook

pre-commit: add hook `markdown-link-check`

---

lib/mruby/presym.rb

The purpose is to deal with `$"`, which has been treated as three characters including the escape character.

Encode and decode escape characters for presym

---

doc/guides/mrbgems.md
lib/mruby/gem.rb
mrbgems/mruby-test/mrbgem.rake

**Purpose**
While it is preferable to leave all tests enabled, I had a need to disable tests for specific mgems while leaving all others enabled. For example, some mgems which my project requires contain unit tests that depend on remote servers, and the tests will always fail if those servers are not accessible (e.g. due to firewall restrictions or temporary internet outage). Thus, this PR makes it possible to disable some tests while leaving the rest of the test suite enabled.
**Syntax**
```ruby
conf.gem 'mruby-noisygem' do |g|
g.skip_test = true
end
```
I think the assignment-style syntax, `g.skip_test = true|false`, might allow for more flexibility within a complex build script, but if a more declarative style (`g.skip_test`) is preferred, this is an easy change that I can make. …

Allow tests to be disabled for specific gems; warn about disabled tests

---

lib/mruby/build/command.rb

In #5977 it was incorrectly set to `private`.
I'm sorry.

Fixed visibility of `MRuby::Command::Compiler#setup_debug`

---

.github/linters/.markdown-lint.yml
doc/guides/gc-arena-howto.md

https://github.com/DavidAnson/markdownlint/blob/main/doc/md052.md
Fix Markdown reference link.
Previous to this fix the Markdown markup was broken as seen here:
https://github.com/mruby/mruby/blob/master/doc/guides/gc-arena-howto.md
But now looks better here:
https://github.com/jbampton/mruby/blob/fix-markdown-link/doc/guides/gc-arena-howto.md

Enable markdownlint rule MD052

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems
In future this will keep the Gemfile.lock up to date

Configure Dependabot updates for Bundler/Ruby

---

build_config/i586-pc-msdosdjgpp.rb
mrbgems/mruby-dir/src/dir.c
mrbgems/mruby-io/src/file.c
mrbgems/mruby-io/src/file_test.c
mrbgems/mruby-io/src/io.c

This provides a build configuration for MS-DOS, cross-compiled on Linux using DJGPP.
* Most gems compile unmodified, with a few flags set in the build configuration.
* mruby-dir compiles only if chroot is disabled.
* mruby-io requires a few changes to avoid the libgen.h file, which DJGPP does not have, and to define fsuseconds_t.
* mruby-socket does not compile.
* mruby-cmath does not compile, because DJGPP does not provide complex.h. I am working on an alternative implementation that does not require complex.h.

Build configuration for MS-DOS and DJGPP

---

tasks/libmruby.rake

If there are multiple build targets, it should be preferable to have the task processed at each of them.

"expose_header_files" task split per build

---

README.md

Updated the button to the latest format seen here:
https://github.com/marketplace/actions/super-linter#add-super-linter-badge-in-your-repository-readme
And the fixed button is seen here:
https://github.com/jbampton/mruby/tree/fix-super-linter-button

Fix Super-Linter button in README

---

.pre-commit-config.yaml

https://github.com/pre-commit/pre-commit-hooks#forbid-submodules
If you want to ban them entirely use forbid-submodules.
Really this is just one extra check or test we can have.

pre-commit: add hook `forbid-submodules`

---

Rakefile

Revert "Rake: update task clean to remove `bin` and `build` folders"

---

mrbgems/mruby-print/mrblib/print.rb

For example, evaluating `puts nil` raised `NoMethodError` before.

Convert to string before output in `puts`

---

lib/mruby/presym.rb

In #6011, a hexadecimal escape sequence followed by a hexadecimal character would cause a compile error. Also, avoid using "Numbered Parameter" which older Ruby does not have (e.g. AppVeyor).
ref. #6044
---
In the verification with `conf.enable_debug` in the build by MSVC:
- Before this patch, I can see a compile error in the escape sequence part.
https://github.com/dearblue/mruby/actions/runs/6122499107/job/16618399040#step:4:499
- After this patch, there are no compile errors, but `mrbtest` fails.
https://github.com/dearblue/mruby/actions/runs/6122499387/job/16618399785#step:4:2540
Fixed #6044

Fixes escape sequence bug and enhancements in Presym scanning

---

.gitattributes

References:
- [Git] リポジトリで改行コードを正規化する
https://zenn.dev/murnana/articles/eol-and-gitattributes
- 行終端を処理するようGitを設定する - GitHub Docs
https://docs.github.com/ja/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
---
The newline code of the batch file will be output as "CRLF".
The data retained in the repository will remain "LF", so there will be no difference in `mrbgems/mruby-bin-config/mruby-config.bat`.
If necessary, `rm mrbgems/mruby-bin-config/mruby-config.bat && git checkout -- mrbgems/mruby-bin-config/mruby-config.bat` will update the working file.
Also, if binary files such as JPEG are added in the future, they will not be treated as text, so it is expected that the data will not be automatically converted even if this is done.
This was confirmed just to be …

Add `.gitattributes` for newline code normalization

---

src/kernel.c

The prototype declaration of `mrb_f_raise()` has arleady demoted from `MRB_API` in a below commit.
https://github.com/mruby/mruby/commit/0898ce982eea706c9a7b814280cdda09e82abe17
However, the entity of `mrb_f_raise()` in kernel.c is set `MRB_API` yet.
Therefore, mruby occures build error with MSVC(in Visual Studio 2022) as below.
https://github.com/groonga/groonga/actions/runs/6310140553/job/17131485675#step:11:2067
The cause of the above error that we define both `mrb_f_raise()` with `MRB_API` and `mrb_f_raise()` without `MRB_API`.
---
The results of `rake test` of this PR.
```
>>> Test host <<<
mrbtest - Embeddable Ruby Test
.........................................................................................?............................................................................ …
```

Demotion mrb_f_raise() in kernel.c from MRB_API too

---

src/vm.c

Switching back from a fiber with an exception could point to an invalid PC.
The investigation was inspired by #6060.
---
I could not create code to reproduce the problem.
But before this patch, I got the following results on [my experimental branch of ngx_mruby](https://github.com/dearblue/ngx_mruby/commits/EXPLOSION).
mruby is built with `conf.enable_debug`.
```
Process 63755 stopped
* thread #1, name = 'nginx', stop reason = signal SIGABRT
frame #0: 0x0000000826985c5a libc.so.7`__sys_thr_kill + 10
libc.so.7`__sys_thr_kill:
->  0x826985c5a <+10>: jb     0x826983db8
0x826985c60 <+16>: retq
0x826985c61:       int3
0x826985c62:       int3
(lldb) bt
* thread #1, name = 'nginx', stop reason = signal SIGABRT
* frame #0: 0x0000000826985c5a libc.so.7`__sys_thr_kill + 10
frame #1: …
```

Fixed unwinding block that could point to invalid PC

---

mrbgems/mruby-io/src/io.c
mrbgems/mruby-io/test/file.rb

From CRuby 2.6 feature.
This is the "x" mode (`O_EXCL`; exclusive create) of `fopen(3)` introduced in C11.
ref. https://bugs.ruby-lang.org/issues/11258

Add "x" mode option for `IO.open`

---

lib/mruby/build.rb

Symbolic links were created with absolute paths, but to cope with path fluctuations between build and reference, they are now relative paths.
ref. #6084

Fixed `MRuby::Build#define_installer`

---

build_config/nintendo_wii.rb

This adds build config for Nintendo Wii, primarily based on the Gameboy Advance build config.
I used this to build mruby on Wii for https://github.com/yujiyokoo/mrbtris-wii which you can see the demo of at https://vimeo.com/876291806

Add build config for Nintendo Wii

---

build_config/host-shared.rb

Summary:
- VisualC++ does not supported.
- `cc.flags` must maintain array objects.
- Enable C++ exceptions for C++ friendly.

Brush up `build_config/host-shared.rb` file

---

mrbgems/mruby-eval/test/binding.rb
src/proc.c

Fixed acquisition of wrong target class in `Kernel#binding`

---

lib/mruby/build/load_gems.rb

The branch name of the cloned repository should be determined by the build configuration file.
fixes #6087
---
Previously, even when `gem "GEM-NAME", branch: "TAG-NAME"` was specified in the build configuration file, the `.lock` file would record `branch: HEAD`.
I don't think it would be necessary to get the branch name from local.

Get from local only if there is no default branch name

---

src/vm.c

The unwinding process that has been done at each point in time is now done in a merged block after looking for the last ci to `break` / `return`.
fix #6099
---
In my working branch, I am changing the parts related to `unwinding` and `RBreak`. This PR is a part of it. I will send PRs for other parts in stages.
https://github.com/mruby/mruby/compare/master...dearblue:mruby:wip/unwinding
The following benchmarks may be helpful to understand the impact on performance.
Please check `` host@(2) 2e881d329 Reorganization of unwinding at `break` / `return` `` for this PR.

Reorganization of unwinding at `break` / `return`.

---

src/vm.c

fix #6108
---
The cause was that control was being transferred from the `break` CI to the caller of `Class.new` without `cipop()`.
https://github.com/mruby/mruby/commit/2e881d3297246cde89b2f9134c3495d985e57f6d?diff=split#diff-b7d97be9c98fd50d49b9f2d6ee9bd3e4da589e223eeb0a06824d7af57d23efe6L2378-L2383
I thought I had moved the ↑ block to the ↓ block, but something important was lost.
https://github.com/mruby/mruby/commit/2e881d3297246cde89b2f9134c3495d985e57f6d?diff=split#diff-b7d97be9c98fd50d49b9f2d6ee9bd3e4da589e223eeb0a06824d7af57d23efe6R2378-R2386

Needs `cipop()` before crossing the C boundary

---

include/mruby/error.h
mrbgems/mruby-catch/src/catch.c
src/gc.c
src/vm.c

It is now possible to specify return destination directly. This allows callinfo to distinguish between calls to the same proc object.
At the same time, the `Kernel#catch` method is adjusted. By removing the previously required double lambda object, the REnv object is no longer created as well.

RBreak remembers the CI location

---

src/vm.c

Termination of fiber by `break` results in a `LocalJumpError`, so the indicated code will not be executed.
---
I wrote this in a definitive way in my commit message, but please confirm.
In current mruby, `break` requires an `env` in the running `proc`.
Also, `break` that jumps over the fiber is prevented by comparing `e->cxt` and `mrb->c`.
I can't think of a condition to reach that part.
A quick check with `git blame` shows that the commit where this block was introduced is https://github.com/mruby/mruby/commit/6bd3d88eddb8932bd02fadfbf2235c3cba2ad624.
I tried the code in the linked https://github.com/mruby/mruby/issues/1766 and the code block was never reached.
I don't think there is any problem with deleting it. How about it?

Remove unreachable code in `OP_R_BREAK`

---

include/mruby.h
mrbgems/mruby-fiber/src/fiber.c
mrbgems/mruby-fiber/test/fiber.rb
mrbgems/mruby-fiber/test/fiber2.rb
mrbgems/mruby-fiber/test/fibertest.c
src/vm.c

Neutralizes restriction #5782 introduced by `Fiber#resume` issue #5781.
ref. #6063

Ease fiber limitations

---

mrbgems/mruby-fiber/src/fiber.c

When fiber is terminated, the pointer indicated by `f->cxt->cibase->proc` is not protected from GC.
I should have done this patch way as of commit ca9e8d91e4651ccf62ebdd9a5bc5855a754af38a (#6105).
---
When this patch is not applied, the GC'd object will be touched.
```console
% lldb16 -- bin/mruby -e 'a = Fiber.new { Fiber.current }.resume; GC.start; p a'
(lldb) target create "bin/mruby"
Current executable set to '/usr/home/dearblue/candybox/ruby/mruby.git/bin/mruby' (x86_64).
(lldb) settings set -- target.run-args  "-e" "a = Fiber.new { Fiber.current }.resume; GC.start; p a"
(lldb) b mrbgems/mruby-fiber/src/fiber.c:385
Breakpoint 1: where = mruby`fiber_to_s + 343 at fiber.c:385:28, address = 0x00000000002e16a7
(lldb) r
Process 23679 launched: …
```

Consider proc to be GC'ed if fiber is terminated

---

src/vm.c

I think it will make the eyes less tired for a process flow.

Replace `for` and `CHECKPOINT` block comprehensions

---

src/vm.c

The `MRB_METHOD_CFUNC_P()` macro contains several branches, which will be replaced by simple branches.

Improve branching in the execution part of the `OP_SEND` block

---

mrbgems/mruby-io/src/io.c
mrbgems/mruby-io/test/io.rb

I hit the following two problems.
- `io.read(0, buf)` always returned a new empty string object.
- `io.read(num, buf)` was appending data to the given `buf`. This also meant that `buf` was never empty if EOF was reached.

Fixed `IO#read` with `buf`.

---

include/mruby/class.h
mrbgems/mruby-binding/src/binding.c
mrbgems/mruby-complex/src/complex.c
mrbgems/mruby-data/src/data.c
mrbgems/mruby-method/src/method.c
mrbgems/mruby-rational/src/rational.c
mrbgems/mruby-struct/src/struct.c
src/class.c
src/gc.c
src/numeric.c
src/proc.c

The method introduced by #5979 causes a fault by swapping classes.
```console
% bin/mruby -e 'Method = Proc; p Object.method(:inspect)'
zsh: segmentation fault (core dumped)  bin/mruby -e 'Method = Proc; p Object.method(:inspect)'
```
After applying this patch, a `TypeError` exception will be raised.
```console
% bin/mruby -e 'Method = Proc; p Object.method(:inspect)'
[1] -e:1
-e:1:in method: allocation failure of Proc (TypeError)
```
However, if the `mrb_vtype` is the same object, the same care must still be taken as before.
```console
% bin/mruby -e 'Method = Binding; p method(:puts).eval("12345")'
[1] -e:1
-e:1:in eval: wrong argument type nil (expected Proc) (TypeError)
```
---
I'm sorry.
And #5979 not doing it for `Proc` …

Prohibit `Class#allocate` in a different way

---

mrbgems/mruby-time/src/time.c

This update avoids the following error: `operator '&&' has no right operand` (related to `_POSIX_TIMERS`):
```
rake
CPP   mrbgems/mruby-time/src/time.c -> build/dreamcast/mrbgems/mruby-time/src/time.pi
/opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/mrbgems/mruby-time/src/time.c:88:47: error: operator '&&' has no right operand
88 | # if (defined(_POSIX_TIMERS) && _POSIX_TIMERS > 0) && defined(CLOCK_REALTIME)
|                                               ^
rake aborted!
Command failed with status (1): [C:\DreamSDK/msys/1.0/opt/toolchains/dc/sh-...]
/opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/lib/mruby/build/command.rb:33:in `_run'
/opt/toolchains/dc/kos-ports/mruby/build/mruby-3.2.0/lib/mruby/build/command.rb:95:in `run' …
```

`mruby-time`: protect against incorrectly defined `_POSIX_TIMERS`

---

build_config/dreamcast_shelf.rb

This configuration is used to support the **Sega Dreamcast** system.
mruby is now officially supported as a KallistiOS Port in kos-ports. 
See: https://dreamcast.wiki/Using_Ruby_for_Sega_Dreamcast_development
This PR replaces: https://github.com/mruby/mruby/pull/6129

`dreamcast_shelf build config`: complete overhaul

---

include/mruby/class.h
mrbgems/mruby-data/src/data.c
mrbgems/mruby-struct/src/struct.c
src/class.c

If `Class#allocate` is prohibited, subclasses should also be implicitly prohibited.
```ruby
p Class.new(Struct).allocate.class
```
Added `MRB_DEFINE_ALLOCATOR()` to allow subclasses to use `Class#allocate`.
Supplement to #6122.

Inherit `MRB_FL_UNDEF_ALLOCATE` in subclasses

---

src/vm.c

The restriction was introduced in commit b563bcb7ff87b859ccdfa30f5d7c3f06cb26a239 to resolve https://github.com/mruby/mruby/issues/3462. Subsequently, the `RBreak` object, introduced by mruby 1.3.0, allowed crossing the C boundary.
```ruby
def cross; Class.new { proc { return }.call }; end; cross
```

Allow `OP_RETURN_BLK` to cross C boundaries

---

src/vm.c

```ruby
def cross; Class.new { return 1 }; end; p cross'
```

Fixed return value of `OP_RETURN_BLK` called directly under C function

---

src/vm.c

In the `ensure` block while executing `fiber.transfer`, keep `fiber->cxt->prev` to be `NULL`.

Integrates the sequence when a fiber is terminated by `OP_RETURN`

---

src/vm.c

For example, the following code was crashing.
```c
#include <mruby/compile.h>
#include <mruby/proc.h>
int
main(int argc, char *argv[])
{
mrb_state *mrb = mrb_open();
mrb_value fiber = mrb_load_string(mrb, "Fiber.new { Fiber.new { 12345.6789 }.transfer }");
mrb_value res = mrb_fiber_resume(mrb, fiber, 0, NULL);
mrb_p(mrb, res);
mrb_close(mrb);
return 0;
}
```
---
This PR contains a commit to integrate the code for `return` from `mrb_vm_exec()`.
If this is a problem, please let me know.

Fixed when combined `mrb_fiber_resume()` and `Fiber#transfer`

---

mrbgems/mruby-rational/src/rational.c

At this point, I would guess that it is definition only and probably not used from anywhere else.
```console
% git grep -wn _new
mrbgems/mruby-rational/src/rational.c:774:  mrb_define_class_method(mrb, rat, "_new", rational_s_new, MRB_ARGS_REQ(2));
```

Remove unnecessary `Rational._new` method

---

.pre-commit-config.yaml

https://github.com/pre-commit/pre-commit-hooks#detect-aws-credentials
Another check or test we can have.
"--allow-missing-credentials - Allow hook to pass when no credentials are detected."

pre-commit: add hook `detect-aws-credentials`

---

lib/mruby/gem.rb

Returning internal objects is undesirable.

Make `MRuby::Gems::List#{each,<<}` method return `self`

---

include/mruby/internal.h
include/mruby/value.h
mrbgems/mruby-os-memsize/src/memsize.c
src/backtrace.c
src/gc.c

The `MRB_TT_BACKTRACE` object has been added for the purpose.
Previously, "use-after-free" could occur because the reference count in `backtrace_location::irep` was not incremented.
fixed #6160

Fixed use-after-free by backtrace object

---

src/state.c

Write invalid value to `irep` if `MRB_DEBUG` is defined by `MRuby::Build#enable_debug`.

Allow to detect use-after-free after `mrb_irep_free()` for debugging

---

src/gc.c

For reference, the flexible array was introduced by commit 3ab2f9371e60039936356afaee9f509d782259fd (#2997).
Subsequently changed for compatibility with C++ by commit 24939723d77291152298acc2fb6415b3d1fe2c24 (#5596).

Stop pseudo flexible array in `mrb_heap_page`

---

NEWS
doc/mruby3.3.md

- Remove items changed by mruby 3.2.
- The commit hash or pull request number will be written along with the changes.
- Add some items.

Update the `mruby3.3.md` file

---

mrbgems/mruby-enum-lazy/mrblib/lazy.rb
mrbgems/mruby-enum-lazy/test/lazy.rb

This pull request introduces the grep_v method to the Enumerable::Lazy class within the mruby-enum-lazy gem. The implementation aims to mirror the functionality of CRuby's [Enumerator::Lazy#grep_v](https://docs.ruby-lang.org/ja/latest/method/Enumerator=3a=3aLazy/i/grep_v.html), providing a lazy way to filter out elements from an enumerable that do not match a given pattern.

Add Enumerable::Lazy#grep_v to mruby-enum-lazy

---

mrbgems/mruby-bin-config/mruby-config.bat

Previously, the correct directory could not be obtained in some environments.
Therefore, changed the method to leave an element indicating the parent directory.
fix #6156

Fix `MRUBY_PACKAGE_DIR` in `mruby-config.bat`

---

src/vm.c

This was introduced in commit 365c151df0a8bd495328e012e0a27a8585b10355.
I should have checked env first.

Corrected strange conditional in `mrb_vm_run()`

---

src/vm.c

Resolving alias proc should be done by the caller of `CI_PROC_SET()`.
The same applies to `mrb_vm_ci_proc_set()`.

Stop assuming alias proc in `CI_PROC_SET()`

---

.github/workflows/super-linter.yml

Flag to enable the linting process of the secrets.
Just another check or test we can have.
Set VALIDATE_ALL_CODEBASE: true
https://github.com/super-linter/super-linter?tab=readme-ov-file#configure-super-linter

super-linter: set `VALIDATE_GITLEAKS` to `true`

---

.github/linters/mlc_config.json
.pre-commit-config.yaml

https://github.com/tcort/markdown-link-check?tab=readme-ov-file#config-file-format
pre-commit has been failing sometimes on the `markdown-link-check`.
The failure is intermittent and distracting.
This pr aims to ignore the offending links

pre-commit: add `markdown-link-check` config and ignore links

---

include/mruby/throw.h
src/vm.c

Use stack variable addresses as identifiers instead of global variable values. Since the stack variable address is uniquely determined within the call, there is no need to maintain a global variable.

Removed `mrb_jmpbuf_id` for C++ exceptions

---

src/vm.c

Since `mrb->c` is never `NULL`, there is no need to check it beforehand.

Omit NULL check of `e->cxt` in `OP_RETURN_BLK`

---

src/vm.c

The post-processing of the jump source is decided, and it is more natural to deploy it on the spot.

Remove the `L_STOP` label

---

src/vm.c

When `mrb->c->prev` is non `NULL` and `mrb->c->noexec` is false, switching source fiber should suspend with `Fiber#resume`.
In this case, the condition `mrb->c->ci == mrb->c->cibase` is not satisfied.
---
I wrote definitively in the commit message, but please check again.
I think the part I removed this time is a remnant for the fiber behavior up to Ruby 2.7.

Remove unreachable blocks in `OP_RETURN`

---

src/vm.c

Assertions were failing on exit if started with `mrb_fiber_resume()`.
The bug that caused it was introduced by commit 42308c42b548c30e54663e70902fc3eca7b22ea8 (#6106). The bug was moved by commit 990e18ad59e8428bd644559d852a3842994b7e94.

Fix wrong assertion in `OP_SENDB`.

---

src/numeric.c

This PR fixes the problem that `flo_xor` is not  called from `int_xor`.
Code like the following  works as expected:
```ruby
10^2.0
=> 10 #expected 8
````

Fix int_xor to call flo_xor.

---

.pre-commit-config.yaml

https://github.com/igorshubovych/markdownlint-cli?tab=readme-ov-file#use-with-pre-commit
https://yamllint.readthedocs.io/en/stable/integration.html#integration-with-pre-commit

pre-commit: fix the arguments syntax

---

.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/super-linter.yml

Flag to enable the linting process of the GitHub Actions.
Another check or test we can have.
https://github.com/super-linter/super-linter?tab=readme-ov-file#configure-super-linter
Lint shell script. Tested with ShellCheck
https://www.shellcheck.net/

super-linter: set `VALIDATE_GITHUB_ACTIONS` to `true`

---

.github/labeler.yml

These are some of the config files for the linters/tests that run

GitHub labeler: label more files

---

include/mruby/istruct.h

In C, `void` is required if there are no parameters.

Strict declaration for `mrb_istruct_size()`

---

mrbgems/mruby-metaprog/test/metaprog.rb
src/class.c
src/variable.c
test/t/module.rb

This will be a partial merge of #5317 with the following changes.
- Remove `iclass->iv_c` since `iclass->iv_c` is equivalent to `iclass->c`.
- `class_iv_ptr()` returns a single pointer instead of a double pointer.

Shared empty `iv_tbl` of module

---

doc/guides/mrbconf.md
include/mrbconf.h
include/mruby.h
include/mruby/proc.h
src/class.c

The purpose is to remove the `mid` field from the `mrb_cache_entry` structure. The resulting RAM requirement for the method cache is reduced from 5 words per entry to 4 words per entry for 32-bit CPUs.
The relevant changes are as follows:
- Removed `MRB_USE_METHOD_T_STRUCT`.
The `mrb_method_t` type is now always defined as a structure.
- Include method IDs in `mrb_method_t`
Change the `flags` member to `uint32_t`. The bitstring structure should be the same as the keys of the `mt` table in `class.c`.
I believe the impact on API compatibility with previous versions is minimal.
---
Attached is a benchmark comparison for your reference.
The targets are (1) the [current master](https://github.com/mruby/mruby/tree/61b1a4db8efecea4a09f7c4ce9449cd6f52f4bc6), (2) this PR, (3) [another …

Reorganize `mrb_cache_entry` and `mrb_method_t` types

---

mrbgems/mruby-bin-debugger/tools/mrdb/mrdb.c

VM inrush could invalidate addresses stored in `dbg->regs` by `stack_extend()`.
---
To confirm the problem, apply the following patch to the current master and try `rake test`.
```patch
diff --git a/src/vm.c b/src/vm.c
index 1e7623478..2261acdf3 100644
--- a/src/vm.c
+++ b/src/vm.c
@@ -204,6 +204,16 @@ stack_extend(mrb_state *mrb, mrb_int room)
if (!mrb->c->ci->stack || mrb->c->ci->stack + room >= mrb->c->stend) {
stack_extend_alloc(mrb, room);
}
+  else {
+    ptrdiff_t stsize = mrb->c->stend - mrb->c->stbase;
+    mrb_value *newstack = (mrb_value*)mrb_malloc(mrb, stsize * sizeof(mrb_value));
+    memcpy(newstack, mrb->c->stbase, stsize * sizeof(mrb_value));
+    memset(mrb->c->stbase, -1, stsize * sizeof(mrb_value));
+    mrb_free(mrb, mrb->c->stbase);
+    envadjust(mrb, …
```

Need to synchronize `dbg->regs` after VM call in `mrdb`

---

src/backtrace.c

Highlights are:
- Integrate the blocks `if (!ci->proc || MRB_PROC_CFUNC_P(ci->proc))` and `if (loc.irep == NULL)`.
- Folding some other conditionals.
- Assertions ensure that procs are not aliases.

Arranging `each_backtrace()`

---

src/vm.c

Currently `e->cxt` is used exclusively to check for `break` / `return` availability.
In other words, there is no need to maintain a reference to a fiber that has reached its end.

`mrb_env_unshare()` to break the link to fiber

---

src/vm.c

This reverts commit 26e436e24797f0c3228bc9900615afe7d2e29ddf.
After investigation, it is possible to revert by commit e89cc9b9fabd4277804fd43666b198a29c25bc34.
The build configuration file used in the investigation is shown below.
```ruby
MRuby::Build.new do |conf|
toolchain :clang
enable_debug
enable_bintest
enable_test
cc.command = "clang18"
linker.command = "clang18"
[cc, cxx].each { |c| c.defines << "MRB_GC_STRESS" }
[cc, cxx, linker].each { |cmd| cmd.flags << %w(-fsanitize=address) }
gem github: "iij/mruby-dir"       # rev: "89dceefa1250fb1ae868d4cb52498e9e24293cd1"
gem github: "iij/mruby-env"       # rev: "056ae324451ef16a50c7887e117f0ea30921b71b"
gem github: "iij/mruby-errno"     # rev: "b4415207ff6ea62360619c89a1cff83259dc4db0"
gem github: "iij/mruby-require"   # rev: …
```

Revert "Adjust environment when `mrb_exec_irep` happened."

---

mrbgems/mruby-random/src/random.c

previously the shuffle algorithm would leave the first element untouched about 1/3rd of the time

fix: `Array#shuffle(!)` result distribution

---

src/vm.c

This reverts commit 72581696d35e8da79a3a9d606294602c83abdf9f.
The #4012 that may have been the trigger for issue #4019 was later reverted by #4039 due to issue #4021.

Revert "`env` referred from top-level callinfo should not be unshared; fix #4019"

---

src/gc.c

Also, `e->stack = NULL` is not needed.
This is because "use-after-free" can be detected with `MRB_DEBUG` + `MRB_GC_STRESS`.

Fold the code for freeing `env`

---

mrbgems/mruby-io/include/mruby/ext/io.h
mrbgems/mruby-io/src/io.c

I'm currently writing a gem which wants to integrate with mruby-io and mruby-socket.
At the moment mruby-io closes fds it didn't create itself and thus can cause problems when other gems except the fd to still be available.
This only changes how ```fptr_finalize``` handles the closing of fds and nothing else.
I've tried handling that in my gem by stopping a created mruby-io object from being garbage collected until it's not needed anymore, but that wasn't enough.

Add a way to let other gems handle closing of fds in mruby-io

---

mrbgems/mruby-fiber/src/fiber.c
src/vm.c

Immediately frees the call stack and data stack at the end of a non-root fiber.
If the env object needs to be detached, the data stack is reused through `mrb_realloc()`.
Previously, it was not necessary to take into account that `c->cibase` could be `NULL`.
Note that this is no longer the case due to this patch.
In fact, changes to "mruby-fiber" are now required.

Free stack memory at end of fiber

---

mrbgems/mruby-array-ext/mrblib/array.rb

the worst case for `Array#reject!` (i.e. a proc always returning `true`) is at least 5x worse than the worst case for `Array#select!` (proc always returning `false`)
this commit unifies these implementations and inlines the (effective) call of `#select!` in `#keep_if` and `#reject!` in `#delete_if`

unify the code for filter methods (and speed up `#reject!`)

---

include/mruby/proc.h
src/vm.c

- Don't create multiple envs on one ci.
- Don't share a env to different ci.
- Don't attach a closed env to any ci.
Changes in `envadjust()` can be simplified with those guarantees.

Stricter env objects to attach to ci

---

mrblib/array.rb
src/array.c

reimplement `Array#delete` in c, fixing `ary.delete(nil, &blk)` firing the block regardless of removal
minimal reproduction:
```rb
ary = [nil]
ret = ary.delete(nil) { "not deleted?" }
```
result on `master`:
```rb
ret
ary
```
result after this patch:
```rb
ret 
ary
```

fix `Array#delete` always firing the block when deleting `nil`

---

mrbgems/mruby-pack/src/pack.c

Previously `\x80` was incorrectly mapped to `0`.
```ruby
"\x80\x80\x80\x80".unpack("m*")
```
The reason is that the C string terminator is placed in `base64_dec_tab[128]` and the array length is obtained by `sizeof`. Therefore, the length of `base64_dec_tab[]` is strictly specified and replaced with element-by-element initialization.
Also, similar changes are made to `base64chars[]`.

Fixed base64 decoding in `mruby-pack`

---

src/vm.c

Saying 'catched' instead of 'caught' is a grammatical error

Fix grammar in `src/vm.c`; `catched` -> `caught`

---

src/vm.c

`mrb_vm_run()` is,
- It does not change the fiber context.
- When control is returned, only one ci prepared by the caller is popped. If the ci equals cibase when called, the ci position does not change.
related commits:
- commit 4e84bdb507885bd37b4b0fa6b6359ac8c8b7b886
- commit 34dd258c638bfc9e8ffac6621f3918faff3d797f
- commit ebd6636a1e90dd12cb0ef112e7f1e0ca511f5d3b
- commit c6736357a72049a0eb2a31ccabcc3cd2baba7c9e
- commit 23a4e7149dc4253caf5ed0a528ffe5c21c4afb80
- commit 31a961acf16b7a9454ccb0f0ece91b79e95f7078
---
I have traced from the related commits to check the issues and they can no longer be reproduced.

Revise scope of role of `mrb_vm_run()`

---

src/gc.c
src/vm.c

The patch assumes that `struct REnv::cxt` only performs checks with the `OP_BREAK` and `OP_RETURN_BLK` instructions, and does not reference the entity.
Therefore, by changing to a weak reference, it is possible to collect fibers that are no longer directly referenced while in the suspended state.
However, we need to detach the living env objects that remain in the call stack of the fiber.
So, in effect, it involves a revert of following commits.
- commit a3365d8b3fc957b1d1fd89526440358aa9402fc3
- commit 57ffa1c1508f01434806b1b7301f4ae982eb9ae0
Examples of the effects of change are shown below.
Note that it was built with `rake MRUBY_CONFIG=host-debug`.
```ruby
f = Fiber.new { (x, y, z) = "X", "Y", "Z"; Fiber.yield -> { [x, y, z] } }
g = f.resume
GC.start
p ObjectSpace.memsize_of_all …
```

Allow recycling fibers by GC if not referenced directly

---

include/mruby.h
include/mruby/compile.h
include/mruby/irep.h

Also, add explanations for the `mrb_load_irep()` and `mrb_load_string()` families, which are indirect calls to `mrb_top_run()`.
---
I added a new feature to my mruby-gemcut and it took me a while to figure out the cause crash.
I need to call `mrb_top_run()` indirectly from inside the method, so using `mrb_proc_new_cfunc()` and `mrb_yield_with_class()` as workarounds.
[`Gemcut.facet` method](https://github.com/dearblue/mruby-gemcut/blob/67eb29bc650f436167226a177309009a8e69ebef/src/mruby-gemcut.c#L435-L456)
I was concerned about compatibility if I changed the behavior from within the mruby VM, so I added a note to the documentation first.
I can't think of a better way at this time.

Update documentation for `mrb_top_run()`

---

src/vm.c

Only go to exception handling if `mrb->exc` is non-null.
This may cause some compatibility problems, but I doubt that it is necessary to maintain that compatibility.
Here is how I see the incompatibility with the change at this time:
- If `mrb->exc` is non-null and `mrb_vm_exec()` is called, an exception will be thrown immediately.
- If `MRB_THROW()` is used while `mrb->exc` is `NULL`, it will not go to exception handling.

Remove `exc_caught` from `mrb_vm_exec()`

---

src/range.c

example of failure:
```rb
(-1..-4).to_a
```
expected result (by cruby):
```rb
(-1..-4).to_a
```

fix: `to_a` integer ranges with `begin > end` failing

---

mrbgems/mruby-dir/mrblib/dir.rb

The two methods exclude "." and "..".

Fixes `Dir.children` and `Dir.each_child`

---

mrblib/array.rb
test/t/array.rb

```ruby
a = %w(R G B A)
p a.delete("Y") { _1 }
```
Also, the test code was not present, so I added it.

Passes the nonexistent key as a block argument in `Array#delete`

---

src/error.c

- Initialize the GC arena each time `atexit` is called.
- To reduce the overhead of `MRB_TRY()`, an internal loop is also performed.

Improvements to `mrb_protect_atexit()`

---

mrbgems/mruby-eval/src/eval.c

In `Binding#eval`, two times parsing is executed.
The problem found in this case was caused by not passing an upper block to hold variables of the binding object during the first parsing.
The problem was uncovered by <https://github.com/mruby/mruby/discussions/6274>.
---
Upon further review, mruby-3.3.0 had the problem, but 3.1.0 and 3.2.0 did not.
It appears that the bug was introduced before the 3.3.0 release.

Fixed `Binding#eval` that failed to assign to the same variable

---

src/error.c

In the following example, the fiber context and call stack may be in an incomplete state.
- In case another thread running mruby is terminated abnormally
- In case of a global jump that is out of management by mruby

Always run `atexit` on the top-level call frame

---

src/string.c

We need to include stdlib.h and malloc.h to use malloc()/free() but they aren't included in src/string.c with WIN32_LEAN_AND_MEAN. It generates build time warnings.
We can solve this by including stdlib.h and malloc.h explicitly.

Include headers for malloc() explicitly; fix #6277

---

include/mruby/proc.h
mrbgems/mruby-binding/src/binding.c
src/vm.c

Set `env->cxt` to `NULL` when it is detached from the call frame. In other words, we can determine if `env->cxt` is `NULL` or not.
Also, `mruby-binding` had been setting `env->cxt` unnecessarily, so this has been fixed.

Remove `MRB_ENV_CLOSED` flag

---

mrbgems/mruby-binding/src/binding.c
src/proc.c

There are two issues to be fixed:
- `mrb_irep` could leak if `mrb_calloc()` encountered an out-of-memory exception
- `mrb_proc_merge_lvar()` allocated one extra variable name.
`irep->lv` can always refer to only one less range than `irep->nlocals`. Also, when `mrb_proc_merge_lvar()` extends `irep->lv`, `mrb_realloc()` with `NULL` has the same behavior as `mrb_malloc()`.

Fixes local variables in `mruby-binding`.

---

src/vm.c

The part removed in this patch was introduced by commit c7c9543bed57db12fd8aa57391e0b652ee27cb23.
The current mechanism should be able to trace from block objects created by `eval` to higher level blocks without any problems.

Simplify `uvenv()`

---

include/mruby.h
include/mruby/internal.h
src/vm.c

Outlines:
- Removed `mrb_callinfo::blk`
- Added `mrb_callinfo::flags`
- Added `MRB_CI_COMPANION_BLOCK` flag
---
Evaluation of `benchmark/` by `valgrind --tool=cachegrind`.
| ref | commit hash
| --- | ---
| 3.2.0 | 87260e7bb1a9edfb2ce9b41549c4142129061ca5
| 3.3.0 | 32279e4128527bab4c961854b9cce727a060abea
| master | 0a11af74f46f3dadf7a63c18350582f56967897f
| This PR | ad2e626e7a937fb4de9a1647aa58ea45aa3936ec
The first half is the result of building with `gcc13 -O3` and the second half with `gcc13 -Os`.
```
52,089,700,230 (100.0%)  PROGRAM TOTALS  /var/tmp/mruby/-O3/87260e7bb1a9edfb2ce9b41549c4142129061ca5
51,181,880,488 (100.0%)  PROGRAM TOTALS  /var/tmp/mruby/-O3/32279e4128527bab4c961854b9cce727a060abea
49,868,402,004 (100.0%)  PROGRAM TOTALS …
```

Delegate the care of a directly given block from `cipop()` to `cipush()`

---

src/vm.c

- There was some unnecessary complexity in `OP_BREAK` introduced in commit ad2e626 (#6282).
- Since `mrb->c` is never NULL, there is no need to check it with `MRB_ENV_ONSTACK_P()` beforehand.

Simplify `OP_RETURN_BLK` and `OP_BREAK

---

src/error.c

Supplement to commit 177debacc589d85614e7b5d12f012193702dfd48 (#6276).
If the ci is incomplete, the previous method may cause the application to crash because `env->stack` points to an invalid address when expanding the data stack. Since the ci is in an abnormal state, control it by putting `NULL` in `env->stack`.
If the ci is fine and top-level, detach `env` as usual with `mrb_env_unshare()`.

Detach `env` of ci explicitly on atexit

---

build_config/default.rb
doc/guides/compile.md
lib/mruby/build.rb
mrbgems/mruby-bin-config/mrbgem.rake
tasks/install.rake
tasks/libmruby.rake

Add the `MRuby::Build#libdir_name` accessor and the `MRUBY_SYSTEM_LIBDIR_NAME` environment variable.
Resolved #6240
---
I was thinking too hard when I commented on #6240.
This PR limits the modification of `lib/` to the build task (as described in the documentation).

Allow to change the output directory name of the `libmruby` file

---

doc/internal/opcode.md
lib/mruby/doc.rb

- Added the index number corresponding to the instruction code.
- Omitted trailing `|` from table elements.
The table elements in GitHub Flavored Markdown can't wrap wherever wanted.
And trying to align the end of it tends to make the whole thing longer.

Changed the instruction table in `opcode.md`

---

include/mruby/boxing_nan.h
include/mruby/boxing_no.h
include/mruby/boxing_word.h
include/mruby/value.h
src/variable.c

After Baltic Ruby and getting to talk to people about mruby there I decided to put some work in and started looking at how I could contribute to the project!
I started running optcarrot to find easy to fix perfomance issues in the profiler, and managed to make `mrb_iv_get` about 20% faster which in total speeds up that particular benchmark by about 2% on my M2 Mac Mini with only minor code changes. But since that code path should be hot in most cases it is probably worth it?
The two core changes are as follows
1. Rearrange `MRB_VTYPE_FOREACH` so that the compiler can convert `obj_iv_p` into a range check, this seems to be the only place where this makes a big difference to performance so it felt worth it.
2. Make a special variant of `mrb_type` for use in `obj_iv_p` that ignores boxed …

Optimise `mrb_iv_get`

---

include/mruby.h
include/mruby/internal.h
src/vm.c

This reverts commit ad2e626e7a937fb4de9a1647aa58ea45aa3936ec.
Because of the changes made by #6282, the following code caused a problem.
```ruby
b = proc { break "BAD!" }
p self.tap { b.call }
```
I revived the `mrb_callinfo::blk` field to fix this, but it did not overcome the following problem.
```ruby
def m(&b); b = b.clone; GC.start; b.call; end
p m { break "OK!" }
```
---
<details>
<summary>Patch to revive the `blk` field</summary>
```patch
diff --git a/include/mruby.h b/include/mruby.h
index 490f344ac..552b92e96 100644
--- a/include/mruby.h
+++ b/include/mruby.h
@@ -176,9 +176,9 @@ typedef struct {
uint8_t n:4;                  /* (15=*) c=n|nk<<4 */
uint8_t nk:4;                 /* (15=*) */
uint8_t cci;                  /* called from C function */
-  uint8_t flags; …
```

Revert "Delegate the care of a directly given block from `cipop()` to `cipush()`"

---

src/string.c

This doesn't change any logic, mrb_str_new was manually inlined here and I think it is a bit easier to follow if we just call the function instead.
Feel free to close this if you disagree.

Minor cleanup in mrb_str_init

---

src/string.c
test/t/string.rb

`string[]=(idx, replace)` should return `replace`.
```
string.[]=(idx, replace) → string
string.[]=(idx, len, replace) → string
```
```
string.[]=(idx, replace) → replace
string.[]=(idx, len, replace) → replace
```
As of the current mruby-compiler, `(string[idx] = 'X')` creates not only "CALL_NODE" but also "ASGN_NODE" and "OP_MOVE", overriding the wrong return value. On the other hand, `string.[]=(idx, 'X')` creates only "CALL_NODE", exposing the wrong return value.
If my new mruby-compiler2, leveraging Prism, took the place of official compiler, `(string[idx] = 'X')` and `string.[]=(idx, 'X')` would be going to generate the same VM code without "OP_MOVE". So I paranoidly added tests.
FYI: You can find how the new mruby-compiler2's AST and VM code look like in mruby/c's issue (mruby/c …

mrb_str_aset_m() should return replace instead of str

---

mrbgems/mruby-method/test/method.rb
src/vm.c

Previously, keyword arguments were lost if no positional arguments were passed.
Fixed #6304

Protect keyword arguments in `prepare_missing()`

---

src/vm.c

The caller of `MRB_EXC_THROW()` must be preconfigured.

Assume that `MRB_CATCH()` has `mrb->exc` set

---

mrbgems/mruby-numeric-ext/src/numeric_ext.c
mrbgems/mruby-numeric-ext/test/numeric.rb

Using mod for big integers leads to poor performance, so I replaced it with bitwise AND.

Optimize even?/odd? for big integers

---

doc/internal/opcode.md

It seems like a new column was added to the beginning of the table, but the text was not updated accordingly.

Fix wrong column number in opcode.md

---

src/vm.c

Clearing errors at the beginning of `mrb_vm_exec()` essentially keeps the mruby VM in a non-error state.
For consistency, functions such as `mrb_funcall()` check for errors when control returns from a C function as a method. In the case of a tail call, it should return to `mrb_vm_exec()` afterwards, so error checking is performed there.
Instructions issued while `mrb->exc` is non-null should be limited to `OP_EXCEPT`, the jump target of the catch handler table.

Omit error checking at `OP_RETURN`, `OP_RETURN_BLK` and `OP_BREAK`

---

src/vm.c

Previously it was "approximately double".
---
Simulating the current behavior and this patch's behavior, the following is shown:
- before this patch
```console
% ruby -e 'size = 32; limit = 512; loop { size = (size - 1) * 2; p size; break if size >= limit }'
62
122
242
482
962
```
- after this patch
```console
% ruby -e 'size = 32; limit = 512; loop { size = size * 2; p size; break if size >= limit }'
64
128
256
512
```

Doubling the call stack when extending it

---

src/vm.c

This PR is commit b055fa5 and 4e7c100 in #6307.
<details>
<summary>Result of `gcc -fstack-usage` for some targets (only `mrb_vm_exec()`)</summary>
```
vm-aarch64-unknown-freebsd14.0-gcc-12.3.0~-O3-1.a668e6d81.su:<stdin>:1407:1:mrb_vm_exec 864     static
vm-aarch64-unknown-freebsd14.0-gcc-12.3.0~-O3-2.822e3fdfd.su:<stdin>:1409:1:mrb_vm_exec 816     static
vm-aarch64-unknown-freebsd14.0-gcc-12.3.0~-Os-1.a668e6d81.su:<stdin>:1407:1:mrb_vm_exec 400     static
vm-aarch64-unknown-freebsd14.0-gcc-12.3.0~-Os-2.822e3fdfd.su:<stdin>:1409:1:mrb_vm_exec 384     static
vm-arm-none-eabi-gcc-11.3.0~-O3-1.a668e6d81.su:<stdin>:1407:1:mrb_vm_exec       296     static
vm-arm-none-eabi-gcc-11.3.0~-O3-2.822e3fdfd.su:<stdin>:1409:1:mrb_vm_exec       248     static …
```

Shrink variables in `mrb_vm_exec()`

---

lib/mruby/build/command.rb
lib/mruby/gem.rb

```console
% find -s lib -type f -name '*.rb' -exec ruby -cw {} \;
lib/mruby/build/command.rb:320: warning: `+' after local variable or literal is interpreted as binary operator
lib/mruby/build/command.rb:320: warning: even though it seems like unary operator
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
lib/mruby/gem.rb:469: warning: `&' interpreted as argument prefix
Syntax OK
Syntax OK
Syntax OK
Syntax OK
```

Avoid warnings in `lib/**/*.rb`

---

include/mruby/value.h

It seems that `mrbc` sometimes generates a broken bytecode file on Intel Mac.
After some debugging, I found that the problem is caused by the `mrb_ro_data_p` function.
It sometimes returns false-positive results, which leads to using a released memory area for symbols.
For this reason, some strings in the bytecode file are sometimes broken.
After some investigation, I found that constant strings in macOS are stored in the `__TEXT` segment, so it is probably enough to check that the pointer is in this segment (for some reason, it currently checks if the pointer is after the `_TEXT` segment).
Example:
```ruby
puts "Hello, World!"
```
The debug section of the bytecode is broken (there is no file name):
```
00000000: 5249 5445 3033 3030 0000 007f 4d41 545a  RITE0300....MATZ
00000010: 3030 …
```

Fix mrb_ro_data_p on Intel Mac

---

src/vm.c

- Can refer directly to `proc->e.env` after `MRB_PROC_ENV_P()`.
- Can omit `MRB_ENV_ONSTACK_P()` since `mrb->c` is never NULL and can be directly compared to `env->cxt`.
- Can avoid `goto` by putting the code block that raises the `LocalJumpError` at the end.

Shrinking the code in `OP_BREAK` and `OP_RETURN_BLK`

---

mrbgems/mruby-bin-mirb/mrbgem.rake

The build configuration for `mruby` assumes only the `ncurses` library needs to be linked because `tinfo` is implicitly pulled in.
In environments where ncurses is available only as a static library, `tinfo` needs to be linked explicitly (needed for functions like `tputs`.
This patch fixes that by linking `tinfo` if available.
It also fixes the build for environments where only the `ncursesw` version of the library (including wide character support) is present, while still giving preference to the `ncurses` version (without wide character support).

fix ncurses linking issues

---

src/vm.c

The following assertions can be added to omit the `if` block
- env object must be non-null
- env object must be in a shared state with the stack
The current caller is believed to satisfy the condition.

Add a precondition to call `mrb_env_unshare()`.

---

src/gc.c

When GC occurs during the expansion of the GC arena by `gc_protect()` in `mrb_obj_alloc()`, the object page just allocated by `add_heap()` is released.
Therefore, as soon as control returns from `gc_protect()`, there is a possibility of illegal writing or reading to the address just released.
This issue was discovered during the investigation of #6326.
---
I think this problem can be seen in the following build configuration file.
The key is to define `MRB_HEAP_PAGE_SIZE=1`.
```ruby
MRuby::Build.new do
toolchain
enable_test
enable_debug
defines << %w(MRB_HEAP_PAGE_SIZE=1)
defines << %w(MRB_GC_STRESS)
enable_sanitizer "address,undefined"
gem core: "mruby-proc-ext"
end
```
```
...SNIP...
Proc [15.2.17] : .
Proc.new [15.2.17.3.1] : .
Proc#[] [15.2.17.4.1] : .
Proc#arity [15.2.17.4.2] : . …
```

Fix use-after-free in `mrb_obj_alloc()`

---

src/gc.c

As far as `gcc -S` for several CPU architectures has confirmed, it reduces the number of branch instructions by one.

Reduce the number of branch instructions in the `heap_p()`

---

src/gc.c

A reference to an invalid address might occur in `is_dead()` of `obj_free()` called from `incremental_sweep_phase()`.
This would happen if the heap page was freed ahead of time in the same `incremental_sweep_phase()`.
fixed #6326

Fix use-after-free in `obj_free()` for env objects

---

mrbgems/mruby-compiler/mrbgem.rake

“mruby-compiler” should be able to generate `y.tab.c` files through a separate build configuration if it is not added to the ‘host’ build. In the example above, the “host/mrbc” build should generate the `y.tab.c` file.

Must not depend on the “host” build to generate `mruby-compiler/core/y.tab.c`

---

mrbgems/mruby-data/src/data.c
mrbgems/mruby-metaprog/src/metaprog.c
mrbgems/mruby-sprintf/src/sprintf.c
mrbgems/mruby-struct/src/struct.c
src/array.c

When calling `mrb_equal()` or `mrb_funcall()` family functions, the GC arena should be restored if the loop is repeated by a non-immediate return value.
In my opinion, restoring the GC arena is unnecessary when a non-immediate (true) value causes the function to return (e.g. the `mrb_ary_index_m()` function).
The patch does not take into account the case of recursive calls and may be incomplete.

Need to restore the GC arena after some function calls

---

src/array.c

since a block argument is guaranteed to be a `Proc` this shouldn't cause any problems and brings a moderate speed boost for methods like `Array#sort!`

prefer using `mrb_yield` to call block arguments

---

mrbgems/mruby-dir/test/dir.rb

In some environments, the test will fail because the directory in use cannot be deleted.
This problem was encountered when building 32-bit binary with mingw32 on FreeBSD and running on wine.

Perform GC before deleting directories

---

mrbgems/mruby-compiler/core/codegen.c
mrbgems/mruby-compiler/core/parse.y

this commit changes the parse tree of the `yield` node, allowing for proper keyword argument generation

codegen.c,parse.y: remove flattening of `yield` arguments; fix #6346

---

include/mruby/common.h
mrbgems/mruby-catch/src/catch.c
src/class.c
src/proc.c

Static proc objects defined as methods may be placed in 4-byte alignments in 32-bit environments.
This may be misinterpreted as an immediate value depending on the address.
Since C11 and C++11 have additional language features for byte alignment, corresponding compilers use them to define the `mrb_alignas()` macro.
For earlier compilers, they use their own extensions to define the `mrb_alignas()` macro.
GCC supports `__attribute__((aligned(alignment)))` since at least version 2.95.3 (1999).
https://gcc.gnu.org/onlinedocs/gcc-2.95.3/gcc_4.html#IDX305
According to GPT-4, support was added in version 2.7 (1995).
It is not known which version of Visual C++ added support for `__declspec(align(n))`.
According to GPT-4, at least Visual C++ 6.0 (1998) seems to support it.
Also, the documentation …

Need to place static proc objects into 8-byte alignments

---

src/array.c

The `mrb_ary_cmp()` function calls `mrb_cmp()` for comparison, but `mrb_cmp()` may call the `obj.<=>` method internally.
If a user-defined `<=>` method is called and the array object under comparison is expanded or reduced, a reference to an invalid address may subsequently be made.
---
```console
% bin/mruby -e 'class C; def <=>(other); $array.clear; 0; end; end; $array = Array.new(5) { C.new };  $array <=> $array.dup'
zsh: segmentation fault (core dumped)  ../bin/mruby -e
```

Fix use-after-free for `Array#<=>`

---

src/class.c

The `mrb_get_argv()` function and the `*` specifier of `mrb_get_args()` get the address of the argument. At this time, if it is passed in the form of a splat argument, it will be an address to an element of an array object.
After getting the pointer to the array object, the caller may call `mrb_vm_exec()` directly or indirectly. At this time, a splat argument with the class set can be retrieved as an array object by searching with `ObjectSpace.each_object`. If changes are made as array objects, addresses on the heap as arrays may become invalid, or objects in the array may be recycled by the GC. When the caller references the changed address in a subsequent operation, use-after-free is established.
This patch assigns `NULL` as the class of the array object so that it cannot be detected by …

Making splat argument objects invisible from Ruby side

---

.github/workflows/super-linter.yml
.pre-commit-config.yaml

Validate GitHub Actions with pre-commit.
Remove the Super-Linter GitHub Actions check.
It is more useful to run "actionlint" with pre-commit since the hooks run on our local machines on git commit.
We also run pre-commit on GitHub.
Whereas the Super-Linter tests only run on GitHub.
https://github.com/rhysd/actionlint/blob/main/docs/usage.md#pre-commit

Add `pre-commit` hook `actionlint`

---

include/mruby/boxing_word.h

This reverts commit e76bebe8360e240a2e4885202d270ba2d36fe5b3 (#6309).
Because it crashes limited to gcc13 -O3.
ref. #6358.
Also, benchmark tests have shown that revert tends to be preferable in this time.

Revert "Perform pseudo binary search with `mrb_type()`"

---

build_config/milkv_duo.rb

This RISC-V board comes in variants as low as 64MB RAM, and runs a stripped down version of Linux, so I thought mruby would be a good idea. 
Confirmed the following run on the board (Milk-V Duo 256MB / SG2002 SoC):
- C program using mruby as a library, also cross-compiled on host
- The `mrbc` `mruby` and `mirb` binaries produced
All the standard gems compile, except for the test gem. I get this error:
```
NoMethodError: undefined method `source_exts' for nil:NilClass
```
If there's a way to fix, so I can run the tests on the board too, please let me know.

Add build config for Milk-V Duo (RISC-V Linux) board

---

.pre-commit-config.yaml

https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#pretty-format-json
From the official pre-commit team a minor feature to add.
We have one JSON file at `.github/linters/mlc_config.json`.

Add `pre-commit` hook `pretty-format-json`

---

include/mruby/value.h

[#6380](https://github.com/mruby/mruby/issues/6380)

#6380: Fix indentation to include break after function return type

---

.github/workflows/build.yml

The macOS 12 runner image will be removed by December 3rd, 2024.
refs https://github.com/mruby/mruby/pull/6005

Remove macOS 12 from the build

---

src/gc.c

Once the class is set, objects can be referenced and manipulated from the Ruby side by using `ObjectSpace.each_object`.
Also, currently `mrb_gc_unregister()` assumes that the element is a non-immediate object.
However, `mrb_gc_unregister()` does not read or write to the address, so there was no problem.

Make array objects invisible in `mrb_gc_register()`

---

src/gc.c

The `mrb_nil_p()` used in conditional expressions is semantically included in `!mrb_array_p()`.

Small improvements for `mrb_gc_register()`

---

src/gc.c

Should simply be ignored for the possibility of being called from `RData::dfree`.
---
Currently, use-after-free still occurs when called during `mrb_close()`.
I will send a patch to fix it after checking more.

Avoid calling `mrb_gv_set()` from `mrb_gc_unregister()`

---

src/gc.c

`ARY_PTR()` and `ARY_LEN()` avoid using them in a loop if the array is not changed, since they involve branching.

Small improvements for `mrb_gc_unregister()`

---

include/mruby/internal.h
mrbgems/mruby-class-ext/src/class.c
mrbgems/mruby-class-ext/test/class.rb
mrbgems/mruby-object-ext/src/object.c
mrbgems/mruby-object-ext/test/object-ext.c
mrbgems/mruby-object-ext/test/object.rb
src/vm.c

However, on C, there is no easy way to pass keyword arguments. Therefore, when called `Kernel#instance_exec` on C, keyword arguments are converted to positional arguments. This is a limitation of current mruby.
fixed #6389
---
During our work we found two problems.
One had to do with commit messages, and calling `mrb_exec_irep()` from C did not pass arguments.
The other was that calls like `instance_exec(1, 2, 3, &:puts)` would result in a `__send__: main is not a symbol nor a string (TypeError)` exception.
I will put these together a bit more and add each as a separate issue.

Fixed argument forwarding in `instance_exec`

---

src/vm.c

C to Ruby calls using `mrb_exec_irep()` were not forwarding arguments.
There was also a problem in setting the target class and method ID, which is also fixed.
This issue was discovered during the work to fix #6389.
---
This patch was tested by customizing #6391.

Fix argument forwarding in `mrb_exec_irep()`

---

src/vm.c

The #6392 has been merged, so the call to `mrb_yield_with_class()` is no longer needed.

Follow-up to #6391

---

mrblib/symbol.rb

When called in combination with a method like `*_eval` or `*_exec` that switches self, `__send__` was passed an object that was not necessarily a symbol as the method name.
This problem was discovered during the #6389 correction process.

Storing method-id inside Symbol#to_proc

---

build_config/milkv_duo.rb

Sorry for such a trivial change. When I started writing the GPIO gem for this board, I thought its `WiringX` C library could do everything, so I named the gem after it. It didn't have all the features I needed, so I'm changing the gem name to be more generic.

Milk-V Build Config: update GPIO gem URL

---

.github/workflows/build.yml

macOS 15 (Sequoia) is now available as a public beta in GitHub Actions
https://github.com/actions/runner-images/issues/10686
https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md

Add macOS 15 to the build

---

mrbgems/mruby-io/src/io.c

`length` is `mrb_int`, not `int`.

`io_read`: use `%i` instead of `%d` in call to `mrb_raisef`

---

doc/guides/compile.md
lib/mruby/build.rb
tasks/install.rake

Introduce the `MRuby::Build#install_excludes` attribute. This attribute is an array to which you add strings, regular expressions, and proc objects that will serve as filters to exclude.
This feature was inspired by @hoshiumiarata's comment. https://github.com/mruby/mruby/issues/6352#issuecomment-2426721517

Allow to exclude specific files in `rake install`

---

mrbgems/mruby-io/src/file.c
src/dump.c

- Avoid "Designated initializer"
C++20 is required for C++.
- Avoid "Compound literals"
Not available for C++.

Improve compliance with C++ standards

---

src/vm.c
test/t/bs_block.rb

When multiple identical proc objects are placed on the call stack, it is not possible to distinguish where to `return`.
Therefore, use env object comparisons to do this.
fixed #6411

Distinguish the call frame of the generator with `OP_RETURN_BLK`

---

src/class.c

This pull request optimizes the "new" method's iseq by replacing LOADSELF + SEND with SSEND.

Optimize the "new" method's iseq

---

.github/linters/mlc_config.json

It seems like pull requests are failing in linting because some email addresses in markdown files are not accessible anymore.
Mostly, they are in the license section of the files, so they probably should not be removed. It's possible to whitelist them in the linter, but there are not too many email addresses in the markdown files in the first place, so it's easier to just disable linting of email addresses in markdown files (it's hard to imagine that this linting will help in any way).

Disable linting of email addresses in markdown files

---

mrbgems/mruby-compiler/core/parse.y
test/t/syntax.rb

It seems that using a numbered parameter as a singleton is generating an incorrect AST, so code like this is not working:
```ruby
o = Object.new
o.tap { def _1.a(b) = "a#{b}" }
=> undefined method '_1' (NoMethodError)
```
It generates the following AST:
```
00002               NODE_SDEF:
00002                 NODE_FCALL:
00002                   method='_1' (31195136)
00002                 :a
00002                   mandatory args:
00002                     NODE_ARG b
```
I tried to fix it, so it generates the following AST now:
```
00002               NODE_SDEF:
00002                 NODE_NVAR 1
00002                 :a
00002                   mandatory args:
00002                     NODE_ARG b
```
I'm not sure if this is the best way to fix it, so it's okay to fix it in another way if …

Fix numbered parameters when used as a singleton

---

mrbgems/mruby-compiler/core/parse.y
test/t/syntax.rb

Numbered parameters were not allowed in -> {}, but Ruby allows them, so I changed the behavior to follow Ruby.
Also, I adjusted the lambda node offset in mrb_parser_dump (it printed the lambda body at the same indent as NODE_LAMBDA).

Follow Ruby's behavior for numbered parameters in -> {}

---

.github/labeler.yml

PR #6384 was not auto labeled by the actions bot.
So the `tools` directory needs a label.
We should be consistent and have a label for all files and folders.
After this PR is merged we need to add a new label for `tools` here:
https://github.com/mruby/mruby/labels

Update `labeler.yml`: add label for the `tools` directory

---

.github/workflows/build.yml
.travis.yml
appveyor.yml
docker-compose.yml
tasks/test.rake

Under normal circumstances, `rake -m test` will parallelize not only the build task, but also the test task. With this patch, `rake -m test:run:serial` will parallelize the build tasks, but the test tasks will be done one by one in sequence.
The name of the task to be added is as follows:
| tasks to be added     | corresponding exist tasks
| --------------------- | ----------------
| `test:run:serial`     | `test:run`
| `test:run:serial:bin` | `test:run:bin`
| `test:run:serial:lib` | `test:run:lib`

Adding a serialized test task

---

.github/workflows/coverage.yml

I experimented with adding a GitHub Actions workflow to report coverage.
The workflow is triggered on every push to the repository, generates a HTML coverage report and uploads it as an artifact.
Additionally, it shows the coverage percentage in the summary.
The decisions I made (not necessarily the best ones):
- It runs only on one OS (Ubuntu). It's possible to run on multiple configurations and then merge the results, but that seems like overkill to me.
- It uses Clang. At first, I tried to use GCC, but it seems that GCC generates invisible branches in the code in some cases. This leads to false positives in the coverage report. Clang takes a different "source code-first" approach, so it is more accurate.
- It uses gcovr. I also experimented with lcov, but it generated errors (it's …

Add GitHub Actions workflow for coverage reporting

---

mrbgems/mruby-compiler/core/codegen.c

It looks like OP_ADDI and OP_SUBI use unsigned 8-bit values, so they can handle values in the range of 0-255.
If I am wrong, it's okay to ignore/decline this pull request.

Change the limits of OP_ADDI and OP_SUBI from 0-127 to 0-255.

---

src/vm.c

Some functions called by `mrb_vm_exec()` involve re-entry into the mruby VM. If the `ci` variable is not updated after re-entry, use-after-free is caused.
This patch makes the following after-call fixes.
| called                  | might call methods
| ----------------------- | ----------------
| `mrb_ary_splat()`       | `#to_a`
| `hash_new_from_regs()`  | `#eql?` `#hash`
| `mrb_hash_delete_key()` | `#eql?` `#hash`
| `mrb_hash_get()`        | `#eql?` `#hash` `#default`
| `mrb_hash_key_p()`      | `#eql?` `#hash`
| `mrb_hash_merge()`      | `#eql?` `#hash`
| `mrb_hash_set()`        | `#eql?` `#hash`
| `mrb_range_new()`       | `#<=>`

Need to update `ci` variable after re-entry to VM

---

mrbgems/mruby-bigint/core/bigint.c

Defining `MRB_NAN_BOXING` caused compilation to fail.

Fixed typo

---

mrbgems/mruby-compiler/core/parse.y
test/t/syntax.rb

It seems that `_1` ~ `_9` are not correctly handled when used as hash keys.
They are added to the mandatory arguments of the parent block.
This leads to a "numbered parameter used in outer block" error in the example below.
```ruby
def f(&); end
f do
h = {_1: 3}
-> { _1 }.call(7)
end
```
I tried to fix this by moving the part of numbered parameters handling from the lexer to the parser.
Also, I replaced warnings with errors (it seems that Ruby throws errors).

Fix numbered parameters when used as hash keys

---

.pre-commit-config.yaml
.prettierignore
.prettierrc
README.md

Add `.prettierignore` and the `.prettierrc` config file. Prettier is currently targeting the `JSON`, `Markdown` and `YAML` files in the mruby repo.
Additional file types can be targetted with prettier via additional community plugins.
https://prettier.io/docs/en/
You can see all the languages that are supported on the homepage:
https://prettier.io/
This PR references a few other issues and PRs
We did have prettier running with pre-commit before that method was removed from prettier.
https://github.com/mruby/mruby/pull/6292
https://github.com/mruby/mruby/issues/6291
https://github.com/mruby/mruby/issues/6138
https://github.com/mruby/mruby/pull/5490
Perhaps we could add more npm software to pre-commit in future using new the `local` repo approach. …

[CI] Add `prettier` to `pre-commit`

---

src/hash.c

In `src/hash.c`, there are code blocks that are passed as macro arguments. These code blocks are interpreted as part of the macro function, so breakpoints cannot be set in the debugger. Also, the gcov command will aggregate them to the caller, and the code in the block will not be counted.
This patch will prevent them from being interpreted as part of a macro, and thus the aforementioned problems will no longer occur.
---
This patch has a performance impact.
Checked with `valgrind --tool=cachegrind`, `bin/mrbtest` increases the number of instruction cycles by 0.4 %, and the microbenchmark shown at https://github.com/mruby/mruby/pull/6414#issuecomment- 2478972123 increases the number of instruction cycles by about 10 %.

Moving code in macro arguments out of macros

---

lib/mruby/build.rb

This method was added by commit 0ac755dbc888020781e8ed19e417a5799217c7b3 (#6407). It was added during the initial conception, but was ultimately no longer needed.

Remove unused `MRuby::Build#list_install_excludes` method

---

README.md
doc/guides/hier.md

This text was translated from Japanese to English by https://www.deepl.com/ .
---
- The text at the beginning of the file is an OpenBSD imitation (https://man.openbsd.org/OpenBSD-7.6/hier), but further tracing led to 4.3BSD NET/2 (https://man.freebsd.org/cgi/man.cgi?query=hier&manpath=4.3BSD+NET%2F2).
- I ran `rake doc:update-index` and it removed one blank line in the `README.md` file.
It seems that some mistake was made last time and they got mixed up.

Added document "Layout of the mruby filesystem"

---

mrbgems/mruby-compiler/core/codegen.c

The pool lookup logic for bigints was broken in the code generation for NODE_NEGATE.
It searched for positive bigints instead of negative ones, leading to two problems.
1. It reused the same pool entry for negative bigints if the positive one was already present.
For example:
```ruby
def f
puts(36893488147419102235)
puts(-36893488147419102235)
end
f
```
Will print:
```
36893488147419102235
36893488147419102235
```
After the fix, it will print:
```
36893488147419102235
-36893488147419102235
```
Codegen before fix:
```
irep 0x7f954ff49cd0 nregs=5 nlocals=2 pools=1 syms=1 reps=0 ilen=20
file: (mirb)
4 000 ENTER         0:0:0:0:0:0:0 (0x0)
5 004 LOADL         R3      L[0]                        <--------- SAME
5 007 SSEND         R2      :puts   n=1
6 011 LOADL         R3      L[0] …
```

Fix NODE_NEGATE for bigints

---

mrbgems/mruby-compiler/core/codegen.c
test/t/syntax.rb

The main purpose is to fix #6439, but includes additional testing and a fix to allow `redo` from nested loopinfo.
The additional test code should be correct as it was also confirmed by “ruby 3.4.0preview2 (2024-10-07 master 32c733f57b) +PRISM [amd64-freebsd14]”.

Fix `redo` keyword

---

src/vm.c
test/t/syntax.rb

fixed #6441
---
Even if merged with #6440, each added test will pass.

Fixed wrong range condition in `OP_JMPUW`

---

mrbgems/mruby-bin-mruby/tools/mruby/mruby.c
mrbgems/mruby-dir/src/dir.c
mrbgems/mruby-dir/test/dirtest.c
mrbgems/mruby-io/src/file.c
mrbgems/mruby-io/src/file_test.c
mrbgems/mruby-io/src/io.c
mrbgems/mruby-io/test/mruby_io_test.c
mrbgems/mruby-socket/test/sockettest.c

Checking the official MSVC documentation, if `_WIN64` is defined, then `_WIN32` is also defined.
https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros
I could not find any documentation on MinGW, but I assume it is not a problem.

Omit the `_WIN64` definition check

---

mrbgems/mruby-io/mrblib/file.rb
mrbgems/mruby-io/src/file.c
mrbgems/mruby-io/test/file.rb
mrbgems/mruby-io/test/mruby_io_test.c

- Improved `File.expand_path` test in `mruby-io
Since `mruby-io` does not depend on `mruby-env` even for test builds, it is impossible that `ENV` constants are defined.
Therefore, define `MRubyIOTestUtil::ENV_HOME` for alternative use.
- Fix `File.expand_path` for Windows
- The inner method `File._gethome` could be read as intending to use the `USERPROFILE` environment variable instead on Windows when the `HOME` environment variable is not available.
In reality, however, this was not the case.
- The result of `File.expand_path` should unify path separators with `/`, but it did not.

Fixed `File.expand_path`

---

mrbgems/mruby-io/include/mruby/ext/io.h

When defining macro constants for error classes in public header files, it is preferable to use `MRB_ERROR_SYM()`.

Suppress presym in `mruby/ext/io.h` file

---

src/numeric.c

Handle the case where the rhs of an int_mod or int_divmod operation is a bigint.
Partially fixes https://github.com/mruby/mruby/issues/6452 (except for the bug in bigint division).

mruby-bigint: handle rhs bigint in int_mod and int_divmod functions

---

mrbgems/mruby-bigint/core/bigint.c

Fixes https://github.com/mruby/mruby/issues/6451

mruby-bigint: fix rounding behavior in mpz_mdiv and mpz_mdivmod functions

---

build_config/i586-pc-msdosdjgpp.rb
mrbgems/mruby-io/include/mruby/ext/io.h
mrbgems/mruby-io/src/io.c
mrbgems/mruby-io/test/io.rb
mrbgems/mruby-io/test/mruby_io_test.c

Change to `MRB_USE_IO_PREAD_PWRITE` for consistency with mruby configuration macros.
Similarly, `MRB_WITHOUT_IO_PREAD_PWRITE` is changed to `MRB_NO_IO_PREAD_PWRITE`.
The previous names are available for compatibility but are deprecated.

Change `MRB_WITH_IO_PREAD_PWRITE` configuration name

---

mrbgems/mruby-io/src/file_test.c

It has been incorrectly defined as a class.

`FileTest` is a module

---

mrbgems/mruby-io/src/file.c
mrbgems/mruby-io/test/file.rb

Please also check the commit message.

Add `level` argument to `File.dirname`

---

.github/workflows/release.yml

This is to allow final confirmation of the created release file. Release files in draft form cannot be downloaded by the general public.
---
This is related to #6133.
While #6133 makes a release announcement as soon as the tag is pushed, this patch creates the release announcement in a stubbed state, giving the administrator room for final review.
Since it will be invisible to everyone except the project manager, the release status must be changed if the file is to be made available to the public.
The release message can also be changed at this time.

To create a release package file in draft

---

build_config/playstationportable.rb

It's compilable on GNU/Linux but untested, just really adding this because I'm hoping for those who want to use and improve, every flags/configs are based in build scripts from https://github.com/pspdev/pspsdk and also this crossbuild are based from gameboyadvance, thanks.

Add initial playstation portable crossbuild support

---

src/hash.c

Fixed missing changes to `IB_FIND_BY_KEY()` parameter names

---

mrbgems/mruby-rational/test/rational.rb
test/t/integer.rb

The `Rational` class is never defined during core testing.

Moved tests for `Integer#quo`

---

include/mruby/internal.h
src/class.c
src/hash.c
src/vm.c

It is sufficient to return the first element.

Avoid array object creation with “unknown keyword” error

---

src/string.c

If `off` was greater than zero, the address pointed to by `e` exceeded the valid range of the buffer.

Fixed buffer overrun in function `chars2bytes()`

---

build_config/emscripten-cxx.rb
build_config/emscripten.rb
mrbgems/mruby-cmath/src/cmath.c
tasks/toolchains/emscripten.rake

Adds support for Emscripten. Also related: #5453
Because Emscripten includes a lot options that should be used for both Compile & Link, I have a `compile_and_link_flags` var for convenience. This was really useful for me when testing and/or adding flags to improve code optimization, etc. I also provided doc links.
Just linking `libmruby.a` gave me a bunch of issues. See [emscripten/issues/23858](https://github.com/emscripten-core/emscripten/issues/23858). Using the `mruby-config` flags fixed my issue. Therefore, I added a comment about this in both of these files to ensure people use these flags when linking mruby to their Emscripten app.
This wouldn't compile in C++. I figured out it's because of this if-statement. I'm wondering why it isn't just `#if defined(__cplusplus)`? Maybe some …

Add Emscripten toolchain & build_config

---

doc/guides/memory.md

No `alloc.c` exists in the source tree. It'd be `allocf.c`

Fix TYPO in memory.md

---

.pre-commit-config.yaml

Node.js `v22.14.0` is the LTS version we should be now using.
https://nodejs.org/en
And seen on the pre-commit site we can set the node version as default.
For node they use nodeenv. 
https://pre-commit.com/#overriding-language-version
And here shows how nodeenv uses and lists its version numbers without the `v` prefix:
`nodeenv --list`
https://github.com/ekalinin/nodeenv?tab=readme-ov-file#advanced

Update pre-commit Node.js version to `v22.14.0 LTS`

---

src/class.c
test/t/module.rb

The following code should work
```ruby
module M
def me
p self
end
module_function :me
end
M.me
```

Fixed class method visibility via `module_function`

---

.pre-commit-config.yaml

@jbampton,
I don't think it should be maintained or controlled by the mruby project.
If you have any concerns or objections to this configuration change, I would appreciate your comments.

Exclude the external project "lrama" from pre-commit

---

mrbgems/mruby-bin-mrbc/tools/mrbc/mrbc.c

mrbc command's --remove-lv option is not work now.
Because define the MRB_DUMP_NO_LVAR value is 4, but mrbc_args.flags bit field width is 2 bit.
This pull request fixes this.

Change mrbc_args.flags bit width from 2 to 3.

---

.prettierignore

Prettier uses an ignore file to exclude files from formatting when running with pre-commit and also when running standalone from the command line.
This is detailed on the CLI docs page:
https://prettier.io/docs/cli

Add `tools/lrama` to `.prettierignore`

---

include/mruby.h
include/mruby/internal.h
include/mruby/proc.h
include/mruby/value.h
mrbgems/mruby-eval/src/eval.c
mrbgems/mruby-eval/test/eval.rb
mrbgems/mruby-method/src/method.c
mrbgems/mruby-struct/test/struct.rb
src/class.c
src/proc.c
src/vm.c
test/t/module.rb

There was a problem with visibility state from proc that straddles a fiber or is independent.
Therefore, it has been changed to give priority to env objects, if any. Also, added "separate module" flag to block traversal to a higher level env object.
Note that the "separate module" flag is now set when calling blocks with the `mrb_yield_with_class()` function.
fixed https://github.com/mruby/mruby/issues/6494

Fixed visibility at method definition

---

.github/labeler.yml

All pull requests should be auto labeled.
PR #6519 was not labeled.

gha: label more files

---

src/kernel.c
test/t/kernel.rb

```ruby
p
=> nil
```
```ruby
p
=> []
```

Fix Kernel#p when no argument

---

mrbgems/mruby-bin-mirb/tools/mirb/mirb.c

In CRuby’s irb, executing an empty input does not add it to the history. However, in mruby’s mirb, even empty inputs are recorded in the history. This behavior can be inconvenient when trying to reuse previous inputs.
While using mirb, I found it frustrating to press the up arrow key and have to skip over empty inputs in the history. To improve the usability, I modified mirb so that empty inputs are no longer added to the history.

Skip adding empty input to mirb history

---

build_config/luckfox_pico.rb

Build config for another tiny SBC (same form factor as Raspberry Pi Pico), with limited RAM and running Buildroot Linux.
I'd like to do a GPIO mrbgem for it in future, like the Milk-V Duo, but no plans for that yet. From the docs, all hardware looks accessible via the filesystem, so should be usable in mruby, even without a C extension.

Add build config for Luckfox Pico embedded SBC

---

src/class.c
test/t/module.rb

This reverts commit 3879b95a6223846bc6763d84cb8c0282a6792d31.
This is because the code first reported in #6494 no longer works.
And added more test.

Revert "class.c (find_visibility_scope): when callinfo returns, *ep == NULL; #6512"

---

src/class.c
test/t/class.rb

It seems that between 3.4.0 and current HEAD the behaviour of `extend` has changed. I noticed it, because the test for `mruby-class-attribute` [failed when ran against head](https://github.com/katafrakt/mruby-class-attribute/actions/runs/15242364473/job/42981521865?pr=1). `git bisect` pointed me to 6c72f8b378fc8743ec1775b3e2d7dd507ec2b394 and indeed I noticed that the handling of `extended` callback seems to be looking for it in the singleton class of the object which is being extended instead of the extension module.
With this change, tests for `mruby-class-attribute` pass. I also added a test with the PR. Hope it does not break other things.

Fix calling `extended` callback

---

src/readfloat.c

This commit adds a descriptive comment at the beginning of the `mrb_read_float` function in `src/readfloat.c`.
The comment explains the function's purpose, its parameters (`str`, `endp`, `fp`), and its return value (`TRUE` or `FALSE`). This improves code readability and understanding.

Add descriptive comment to mrb_read_float function

---

src/debug.c

This change adds Doxygen-style comments to the public API functions in `src/debug.c`, including mrb_packed_int_len, mrb_packed_int_encode, and mrb_packed_int_decode. The comments explain the purpose of each function, its parameters, and its return value. This improves the readability and maintainability of the code.

Add descriptive comments to public functions in src/debug.c

---

src/string.c

Add descriptive comments for MRB_API functions in src/string.c
This commit adds descriptive comments to various MRB_API functions within the src/string.c file. These comments aim to improve code readability and maintainability by explaining the purpose, parameters, and return values of these functions.

Here's the rewritten message:

---

src/array.c

This change adds C-style multiline comments to all functions marked with MRB_API in the src/array.c file.
The comments explain each function's purpose, its parameters, and what it returns, where applicable. This improves the readability and maintainability of the C API for mruby arrays.
The `@brief` markup was intentionally avoided as per your requirements.

Add descriptive comments for MRB_API functions in src/array.c

---

src/symbol.c

This commit adds descriptive comments to all functions marked with MRB_API in the `src/symbol.c` file. The comments explain the purpose, parameters, and return values of these functions, improving code readability and maintainability.
The following functions were commented:
- mrb_intern
- mrb_intern_static
- mrb_intern_cstr
- mrb_intern_str
- mrb_intern_check
- mrb_check_intern
- mrb_intern_check_cstr
- mrb_check_intern_cstr
- mrb_intern_check_str
- mrb_check_intern_str
- mrb_sym_name_len
- mrb_sym_str
- mrb_sym_name
- mrb_sym_dump

Add descriptive comments to MRB_API functions in src/symbol.c

---

src/class.c

This commit adds C-style block comments to all MRB_API functions defined in the src/class.c file. The comments explain the purpose of each function, its parameters, and its return value, aiming to improve code readability and maintainability.

Add descriptive comments for MRB_API functions in src/class.c

---

src/kernel.c

This commit adds descriptive C-style comments to the following functions in `src/kernel.c`:
- `mrb_func_basic_p`: Explains that the function checks if an object's method is implemented by a specific C function.
- `mrb_obj_freeze`: Explains that the function freezes an object, preventing further modifications.
- `mrb_obj_is_instance_of`: Explains that the function checks if an object is an instance of a given class.

Add descriptive comments to kernel functions

---

src/proc.c

This commit adds Doxygen-style comments to the following MRB_API functions in src/proc.c:
- mrb_proc_new_cfunc
- mrb_proc_new_cfunc_with_env
- mrb_closure_new_cfunc
- mrb_proc_cfunc_env_get
The comments describe the purpose, parameters, and return value of each function.

Add descriptive comments for MRB_API functions in src/proc.c

---

src/state.c

This commit adds descriptive comments to the following MRB_API functions in src/state.c, clarifying their purpose and functionality:
- mrb_open_core
- mrb_open
- mrb_free_context
- mrb_close
- mrb_add_irep
- mrb_top_self
- mrb_state_atexit

Add descriptive comments for MRB_API functions in src/state.c

---

src/variable.c

When calling a user function, a pointer retrieved outside of a loop may be invalidated.
---
I have code that actually crashes mruby.
The revision of mruby is 2edfd96cbef5f5768168188254398478f72c5459.
<details>
```console
% cat iv_foreach.rb
$o = Object.new
$o.instance_variable_set :@a, Object.new
$o.instance_variable_set :@var0, 0
class << $o.instance_variable_get(:@a)
def inspect
10.times { $o.instance_variable_set :"@var#{_1}", _1 }
super
end
end
p $o
% valgrind bin/mruby iv_foreach.rb
==6786== Memcheck, a memory error detector
==6786== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==6786== Using Valgrind-3.25.1 and LibVEX; rerun with -h for copyright info
==6786== Command: bin/mruby iv_foreach.rb
==6786==
==6786== Invalid read of size 4
==6786==    at 0x28C763: …
```

`iv_foreach()` needs to update the pointer at each loop

---

src/class.c

When calling a user function, a pointer retrieved outside of a loop may be invalidated.

`mrb_mt_foreach()` needs to update the pointer at each loop

---

.pre-commit-config.yaml

https://github.com/jumanjihouse/pre-commit-hooks
It has been 3 years since the last update and in #6563 when originally using the jumanjihouse rubocop hook google gemini mentioned it could be a security risk using these unmaintained hooks.

Remove jumanjihouse pre-commit hooks no longer maintained

---

lib/mruby/build.rb

`emulator` variables are never used after they are assigned.

Removed unreferenced variables in `CrossBuild#run_bintest`

---

test/bintest.rb

Simply reverse the calling direction of `cmd_bin` method and `cmd_list` method.

Avoid array object creation in `cmd_bin` method in bintest

---

src/class.c
src/gc.c

Instances cannot be created with `MRB_TT_FALSE`.
_**Compatibility Note**_
This change may cause runtime errors.
However, that is probably because it is not set correctly by `MRB_SET_INSTANCE_TT()`.
---
I have shown previously in https://github.com/mruby/mruby/pull/6097#discussion_r1383453371 about the stricter `mrb_obj_alloc()` and compatibility issues.
The cause of the problem is that mruby-lz4 tried to create an instance of its own class with `mrb_data_object_alloc()` while `MRB_SET_INSTANCE_TT()` was missing.
I think it is preferable to have a consistent instance type tag in a custom class.

Stricter type tag in `mrb_obj_alloc()`

---

lib/mruby/build.rb

This change allows loading a local `build_config.rb` file when it exists in the current directory, instead of always using the default configuration.
**Use Case:**
I frequently work with multiple mruby projects and consolidate mruby source code. Currently, I need to specify `MRUBY_CONFIG=./build_config.rb` when running rake, which is cumbersome. This change eliminates that manual step.
**Implementation:**
- Checks for `./build_config.rb` before using `build_config/default.rb`

Add fallback to local build_config.rb before using default configuration

---

lib/mruby/build.rb

ref: https://github.com/mruby/mruby/pull/6583#issuecomment-3136009214
Only use local build_config.rb when current directory != MRUBY_ROOT.

fix: skip local build_config.rb when working in MRUBY_ROOT

---

build_config/dreamcast_shelf.rb

This update simplifies and stabilizes the compilation of mruby for the Sega Dreamcast, using KallistiOS wrappers rather than embedding settings directly in the `dreamcast_shelf.rb` configuration file.
This build config is used by the `mruby` port available in [kos-ports](https://github.com/KallistiOS/kos-ports).
Fixes issue: https://github.com/KallistiOS/kos-ports/issues/113
Related PR: https://github.com/mruby/mruby/pull/6130

`dreamcast_shelf build config`: update to use KallistiOS wrappers

---

src/vm.c

this fixes an issue where base can be out of range on a raspberry pi.

fix bigint on raspberry pi

---

mrbgems/mruby-set/src/set.c

This removes the magic number that also gets repeated in the code. Adding a constant adds extra context without having to add comments.

Extract golden ration prime into constant

---

mrbgems/mruby-string-ext/src/string.c

This issue was originally discovered by OSS-Fuzz:
https://issues.oss-fuzz.com/issues/428404023
The root cause was that str_strip_bang modified the string content and length in-place but failed to null-terminate the string at its new length.
When this modified, non-null-terminated string was duplicated, the buffer may be resized, dropping the old null terminator (via str_uminus -> mrb_str_dup -> str_replace -> str_share). When this is later passed to mrb_raisef using the %!s format specifier, mrb_vformat called strlen on the underlying non-null terminated buffer pointer.
The fix adds explicit null-termination in str_strip_bang, str_lstrip_bang, and str_rstrip_bang after the string length is updated.

Fix a heap-buffer-overflow in in str strip! methods.
